use cob_interfase
go

delete from in_numlet

insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',0,'CERO','ZERO')	 	 
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',1,'UN','ONE')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',2,'DOS','TWO')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',3,'TRES','THREE')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',4,'CUATRO','FOUR')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',5,'CINCO','FIVE')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',6,'SEIS','SIX')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',7,'SIETE','SEVEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',8,'OCHO','EIGHT')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',9,'NUEVE','NINE')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',10,'DIEZ','TEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',11,'ONCE','ELEVEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',12,'DOCE','TWELVE')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',13,'TRECE','THIRTEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',14,'CATORCE','FOURTEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',15,'QUINCE','FIFTEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',16,'DIEZ Y SEIS','SIXTEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',17,'DIEZ Y SIETE','SEVENTEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',18,'DIEZ Y OCHO','EIGHTEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('U',19,'DIEZ Y NUEVE','NINETEEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',1,'DIEZ','TEN')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',2,'VEINTE','TWENTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',3,'TREINTA','THIRTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',4,'CUARENTA','FORTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',5,'CINCUENTA','FIFTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',6,'SESENTA','SIXTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',7,'SETENTA','SEVENTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',8,'OCHENTA','EIGHTY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('D',9,'NOVENTA','NINETY')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',1,'CIENTO','ONE HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',2,'DOSCIENTOS','TWO HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',3,'TRESCIENTOS','THREE HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',4,'CUATROCIENTOS','FOUR HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',5,'QUINIENTOS','FIVE HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',6,'SEISCIENTOS','SIX HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',7,'SETECIENTOS','SEVEN HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',8,'OCHOCIENTOS','EIGHT HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('C',9,'NOVECIENTOS','NINE HUNDRED')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('M',1,'MIL','THOUSAND')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('L',1,'MILLON','MILLION')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('L',2,'MILLONES','MILLIONS')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('B',1,'BILLON','BILLION')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('B',2,'BILLONES','BILLIONS')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('O',0,'PESOS','COLOMBIAN PESO')
insert into in_numlet(nl_tipo,nl_numero,nl_letras_esp,nl_letras_otro) values ('O',1,'DOLARES','DOLLARS')
go