/************************************************************/
/*******************Service Operations Script*********************/
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

use cobis
GO

DECLARE @rol int, @w_producto int
SELECT @rol = ro_rol from cobis..ad_rol where ro_descripcion = 'MENU POR PROCESOS'
SELECT @w_producto = 7 -- select @w_producto = pd_producto from cl_producto where pd_descripcion = 'CARTERA'

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Loan.RejectedDispersions.SearchRejectedDispersions')
  DELETE FROM cts_serv_catalog WHERE csc_service_id = 'Loan.RejectedDispersions.SearchRejectedDispersions' AND csc_method_name = 'searchRejectedDispersions' AND csc_trn = 77502
  
IF EXISTS (SELECT 1 FROM dbo.ad_servicio_autorizado WHERE ts_servicio = 'Loan.RejectedDispersions.SearchRejectedDispersions' AND ts_rol = @rol)
    DELETE FROM dbo.ad_servicio_autorizado WHERE ts_servicio = 'Loan.RejectedDispersions.SearchRejectedDispersions' AND ts_rol = @rol
		
IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Loan.RejectedDispersions.DispersionActions')
   DELETE FROM cts_serv_catalog WHERE csc_service_id = 'Loan.RejectedDispersions.DispersionActions' AND csc_method_name = 'dispersionActions' AND csc_trn = 77503

IF EXISTS (SELECT 1 FROM dbo.ad_servicio_autorizado WHERE ts_servicio = 'Loan.RejectedDispersions.DispersionActions' AND ts_rol = @rol)
   DELETE FROM dbo.ad_servicio_autorizado WHERE ts_servicio = 'Loan.RejectedDispersions.DispersionActions' AND ts_rol = @rol
   
GO
