--Tablas CONTA - Parametros 
--------------------------- 
 
use cob_conta
go
set nocount on
go
print 'Eliminacion de registros'
go
delete cobis..cl_parametro where pa_producto = 'CON'
go
delete cobis..cl_errores where numero >= 600000 and numero <= 699999
go

print 'Insercion cl_parametro'
go
insert into cobis..cl_parametro values ('AREA CALCULO UTILIDAD', 'ARCU  ', 'I', null, '31', null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('CONCEPTO PARA ICA CDT', 'CICDT ', 'C', '4010', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('CIUDAD PARA INICIO DE CORTE CONTABILIDAD', 'CIUDAD', 'I', null, null, null, '11001', null, null, null, 'CON')
insert into cobis..cl_parametro values ('CODIGO CIUDAD FERIADOS NACIONALES PARA CONTABILIDAD', 'CIUN  ', 'I', null, null, null, '11111', null, null, null, 'CON')
insert into cobis..cl_parametro values ('PORCENTAJE DE COMISIONES', 'COMI  ', 'C', '0315', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('BANCAMIA', 'CORVUS', 'I', null, null, '59', null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('CONCEPTO PARA RETEFUENTE CDT', 'CRCDT ', 'C', '0215', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('DOCUMENTO', 'DCTO  ', 'C', '999', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA ESTAMPILLAS', 'DEST  ', 'F', null, null, null, null, null, null, '100', 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA ICA', 'DICA  ', 'F', null, null, null, null, null, null, '100', 'CON')
insert into cobis..cl_parametro values ('DIRECCION SERVIDOR HISTORICO', 'DISH  ', 'C', '172.16.14.173', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA IVA', 'DIVA  ', 'F', null, null, null, null, null, null, '100', 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA IVA PAGADO', 'DIVAP ', 'F', null, null, null, null, null, null, '100', 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA RENTA', 'DREN  ', 'F', null, null, null, null, null, null, '100', 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA TIMBRE', 'DTIM  ', 'F', null, null, null, null, null, null, '100', 'CON')
insert into cobis..cl_parametro values ('ENTE DEFAULT', 'ENTD  ', 'I', null, null, null, '2', null, null, null, 'CON')
insert into cobis..cl_parametro values ('ENTE DEFAULT', 'ENTE  ', 'I', null, null, null, '1', null, null, null, 'CON')
insert into cobis..cl_parametro values ('BBVA MICROSEGUROS', 'EPMS  ', 'I', null, null, null, '804221', null, null, null, 'CON')
insert into cobis..cl_parametro values ('FACTOR GLOBAL DE GASTOS COMPENSADOS', 'FGC   ', 'F', null, null, null, null, null, null, '0.003016', 'CON')
insert into cobis..cl_parametro values ('IVA STANDARD', 'IVA   ', 'I', null, null, null, '11001', null, null, null, 'CON')
insert into cobis..cl_parametro values ('PARAMETRO MESES A CONSERVAR EN DEPURACION', 'MACD  ', 'C', null, '5', null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('DIFERENCIA MONEDA EXTRANJERA', 'MEXT  ', 'S', null, null, '350', null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('MONEDA BASE 1', 'MON1  ', 'I', null, null, null, '1', null, null, null, 'CON')
insert into cobis..cl_parametro values ('MONEDA BASE 2', 'MON2  ', 'I', null, null, null, '2', null, null, null, 'CON')
insert into cobis..cl_parametro values ('NUMERO DE PROCESO BATCH MAYORIZACION COMPROBANTES', 'NBMC  ', 'I', null, null, null, '6058', null, null, null, 'CON')
insert into cobis..cl_parametro values ('NUMERO MAXIMO DE ASIENTOS PERMITIDOS POR COMPROBANTE', 'NMAC  ', 'I', null, null, null, '5000000', null, null, null, 'CON')
insert into cobis..cl_parametro values ('NUMERO MAXIMO DE REGISTROS POR COMPROBANTE', 'NMRC  ', 'I', null, null, null, '60000', null, null, null, 'CON')
insert into cobis..cl_parametro values ('OFICINA CENTRALIZADORA', 'OFC   ', 'I', null, null, null, '9000', null, null, null, 'CON')
insert into cobis..cl_parametro values ('PORCENTAJE DE AJUSTE DEL ANIO GRAVABLE', 'PAAG  ', 'F', null, null, null, null, null, null, '0', 'CON')
insert into cobis..cl_parametro values ('PARTICIONES TOTALES PARA PROCESOS PARALELOS', 'PART  ', 'I', null, null, null, '10', null, null, null, 'CON')
insert into cobis..cl_parametro values ('PASSWORD CONEXION', 'PCXR  ', 'C', '', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('DIRECCION SERVIDOR HISTORICO', 'PLANC ', 'C', '192.168.243.5', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('RUTA CONEXION ', 'PLANR ', 'C', 'bcps_historicos', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('RUTA CONEXION DESTINO', 'PPL   ', 'C', '\\200.31.82.70\CONSULTAS\', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('PORCENTAJE PARA TIEMPO MAYOR', 'PPTM  ', 'T', null, '4', null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('NUMERO DE PROCESOS SUMULTANEOS', 'PROC  ', 'I', null, null, null, '10', null, null, null, 'CON')
insert into cobis..cl_parametro values ('RUTA CONEXION', 'RCXR  ', 'C', 'listados_cer4', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('TIEMPO PARA COBRO DE RETEFUENTE', 'TPCR  ', 'I', null, null, null, '5', null, null, null, 'CON')
insert into cobis..cl_parametro values ('USUARIO CONEXION', 'UCXR  ', 'C', '', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro values ('RUTA EJECUCION ZIP', 'ZIP   ', 'C', 'C:\WINDOWS\SYSTEM32\', null, null, null, null, null, null, 'CON')
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_tinyint, pa_producto)
values ('MAXIMO DE MESES PARA SOLICITAR REPORTES (PMSREP)', 'PMSREP', 'T', 3, 'CON')
go

print  '--> Insercion tabla cl_errores'
go
insert into cobis..cl_errores values (601001,0,'Campos NOT NULL con valores nulos')
insert into cobis..cl_errores values (601002,0,'Codigo de empresa ya existe')
insert into cobis..cl_errores values (601003,0,'NIT ya definido en otra empresa')
insert into cobis..cl_errores values (601004,0,'Codigo de categoria ya existe')
insert into cobis..cl_errores values (601005,0,'Codigo de periodo ya existe')
insert into cobis..cl_errores values (601007,0,'Fin de consulta de empresas')
insert into cobis..cl_errores values (601008,0,'Categoria consultada no existe')
insert into cobis..cl_errores values (601009,0,'Fin de consulta de categorias')
insert into cobis..cl_errores values (601010,1,'Mayorizacion en ejecucion - No se permite autorizar comprobantes')
insert into cobis..cl_errores values (601011,1,'Mayorizacion en ejecucion - No se permite desautorizar comprobantes')
insert into cobis..cl_errores values (601012,1,'Mayorizacion en ejecucion - No se permite reversar comprobantes')
insert into cobis..cl_errores values (601013,1,'Autoriz,Desautoriz o Rever Comprob - No se permite Ejecutar Mayorizacion')
insert into cobis..cl_errores values (601014,0,'Codigo de seccion ya existe')
insert into cobis..cl_errores values (601015,0,'Seccion consultada no existe')
insert into cobis..cl_errores values (601016,0,'Fin de consulta de secciones')
insert into cobis..cl_errores values (601018,0,'No existe codigo de empresa especificada')
insert into cobis..cl_errores values (601019,1,'Error en ingreso del registro control ejecucion de mayorizacion')
insert into cobis..cl_errores values (601020,1,'Error en actualizacion parametro control ejecucion mayorizacion')
insert into cobis..cl_errores values (601021,1,'Error en ingreso registro control Aurotiz/Desautoriz/Rev Compro')
insert into cobis..cl_errores values (601022,1,'Error en emilinacion registro control Aurotiz/Desaut/Rev Compro')
insert into cobis..cl_errores values (601023,0,'No existe nivel superior de cuenta especificada')
insert into cobis..cl_errores values (601024,0,'Cuenta no esta asociada como de Presupuesto o no existe')
insert into cobis..cl_errores values (601025,0,'No existe categoria especificada')
insert into cobis..cl_errores values (601026,0,'No existe seccion especificada')
insert into cobis..cl_errores values (601027,0,'Codigo de cuenta ya existe')
insert into cobis..cl_errores values (601028,0,'Cuenta consultada no existe o no se encuentra vigente')
insert into cobis..cl_errores values (601029,0,'No existen cuentas relacionadas a oficina')
insert into cobis..cl_errores values (601030,0,'Periodo consultado no existe')
insert into cobis..cl_errores values (601032,0,'Codigo de comprobante tipo ya existe')
insert into cobis..cl_errores values (601033,0,'Nivel de cuenta ya existe')
insert into cobis..cl_errores values (601034,0,'No existe nivel de cuenta especificado')
insert into cobis..cl_errores values (601035,0,'Fin de consulta de niveles de cuentas')
insert into cobis..cl_errores values (601037,0,'Cuenta no tiene niveles dependientes')
insert into cobis..cl_errores values (601038,0,'Codigo de organizacion ya existe')
insert into cobis..cl_errores values (601039,0,'No existe codigo superior de organizacion especificado')
insert into cobis..cl_errores values (601040,0,'Nivel de organizacion consultado no existe')
insert into cobis..cl_errores values (601041,0,'Fin de consulta de niveles de organizacion')
insert into cobis..cl_errores values (601042,0,'No existen registros de modificaciones al plan de cuentas')
insert into cobis..cl_errores values (601043,0,'Fin de la consulta de modificaciones al plan de cuentas')
insert into cobis..cl_errores values (601044,1,'Error en emilinacion registro control Ejec Proceso Mayorizacion')
insert into cobis..cl_errores values (601045,0,'Comprobante tipo consultado no existe')
insert into cobis..cl_errores values (601046,0,'Fin de consulta de comprobantes tipo')
insert into cobis..cl_errores values (601047,0,'Codigo de documento por empresa ya existe')
insert into cobis..cl_errores values (601048,0,'Documento de empresa consultado no existe')
insert into cobis..cl_errores values (601049,0,'No existen documentos de empresa')
insert into cobis..cl_errores values (601050,0,'Oficina consultada no es de movimiento')
insert into cobis..cl_errores values (601051,0,'Fin de consulta de dinamicas de cuentas')
insert into cobis..cl_errores values (601052,0,'Nivel superior de cuenta es de movimiento')
insert into cobis..cl_errores values (601053,0,'Cuenta de movimiento ya existe')
insert into cobis..cl_errores values (601054,0,'Error en la insercion de la relacion cuenta - oficina - seccion')
insert into cobis..cl_errores values (601055,0,'Cuenta de movimiento no existe')
insert into cobis..cl_errores values (601056,0,'Total debitos y creditos en tabla temporal descuadrados')
insert into cobis..cl_errores values (601057,0,'Numero de detalles del comprobante diferente al total registrado en la tabla')
insert into cobis..cl_errores values (601058,0,'Total de debitos diferente al registrado en la tabla temporal')
insert into cobis..cl_errores values (601059,0,'Total de creditos diferente al registrado en la tabla temporal')
insert into cobis..cl_errores values (601060,0,'Fin de consulta de comprobantes')
insert into cobis..cl_errores values (601061,0,'Comprobante consultado no existe para fecha indicada')
insert into cobis..cl_errores values (601062,0,'Comprobante no existe o esta duplicado en tabla temporal')
insert into cobis..cl_errores values (601063,0,'Codigo de cotizacion ya existe')
insert into cobis..cl_errores values (601064,0,'Cotizacion consultada no existe')
insert into cobis..cl_errores values (601065,0,'No existen saldos, cuenta no autorizada o fecha de consulta no vigentes')
insert into cobis..cl_errores values (601066,0,'Cuenta no es de movimiento')
insert into cobis..cl_errores values (601067,0,'Cuenta no es de movimiento')
insert into cobis..cl_errores values (601068,0,'Cuenta no asociada a oficina y area')
insert into cobis..cl_errores values (601069,0,'No existen saldos, cuenta no autorizada, fecha de consulta no vigentes o cuenta no posee terceros')
insert into cobis..cl_errores values (601070,1,'Oficina(s) no corresponde al nivel indicado')
insert into cobis..cl_errores values (601071,1,'Error en la insercion de saldo temporal de cuenta sobregirada')
insert into cobis..cl_errores values (601072,0,'No existen niveles de cuentas asociados a la empresa especificada')
insert into cobis..cl_errores values (601073,1,'Error en la insercion de saldo de cuenta sobregirada')
insert into cobis..cl_errores values (601074,0,'No existen transacciones para la cuenta especificada o fechas no vigentes')
insert into cobis..cl_errores values (601075,0,'Comprobante no puede ser desmayorizado, estado del corte no es vigente ni actual')
insert into cobis..cl_errores values (601076,0,'No existen detalles para el plan Especifico')
insert into cobis..cl_errores values (601077,0,'Tipo de transaccion no corresponde')
insert into cobis..cl_errores values (601078,0,'Corte especificado no existe')
insert into cobis..cl_errores values (601079,0,'No existe Corte Actual especificado')
insert into cobis..cl_errores values (601080,0,'No existe nivel superior de oficina especificada')
insert into cobis..cl_errores values (601081,0,'Codigo de oficina ya existe')
insert into cobis..cl_errores values (601082,0,'Oficina consultada no existe')
insert into cobis..cl_errores values (601083,0,'Seccion ya esta relacionada con oficina')
insert into cobis..cl_errores values (601084,0,'Codigo de oficina-seccion consultada no existe')
insert into cobis..cl_errores values (601085,0,'No existen secciones asignadas a oficinas')
insert into cobis..cl_errores values (601086,0,'No existe codigo de seccion especificada')
insert into cobis..cl_errores values (601087,0,'Codigo de seccion ya esta relacionada con empresa')
insert into cobis..cl_errores values (601088,0,'No existen secciones relacionadas a la empresa')
insert into cobis..cl_errores values (601089,0,'Seccion de empresa consultada no existe')
insert into cobis..cl_errores values (601090,0,'Nivel de departamento ya existe')
insert into cobis..cl_errores values (601091,0,'Nivel de departamento consultado no existe')
insert into cobis..cl_errores values (601093,0,'Departamento consultado no existe')
insert into cobis..cl_errores values (601094,0,'Codigo de moneda consultado no existe')
insert into cobis..cl_errores values (601095,0,'Departamento especificado no existe')
insert into cobis..cl_errores values (601096,0,'Departamento especificado ya existe')
insert into cobis..cl_errores values (601097,0,'Proceso consultado no existe')
insert into cobis..cl_errores values (601099,0,'Proceso ya existe')
insert into cobis..cl_errores values (601100,0,'Cuenta ya esta relacionada a proceso')
insert into cobis..cl_errores values (601101,0,'Cuenta no esta relacionada a proceso')
insert into cobis..cl_errores values (601102,0,'No existen cuentas relacionadas a procesos')
insert into cobis..cl_errores values (601104,0,'No existen cuentas asociadas')
insert into cobis..cl_errores values (601106,0,'Departamento ya esta relacionado con oficina')
insert into cobis..cl_errores values (601107,0,'No existen departamentos relacionados con oficinas')
insert into cobis..cl_errores values (601108,0,'Departamento no esta relacionado con oficina')
insert into cobis..cl_errores values (601109,0,'Cuenta no existe o no es de movimiento o no se encuentra asociada a oficinas y/o areas')
insert into cobis..cl_errores values (601110,0,'Departamento ya esta relacionado con cuenta')
insert into cobis..cl_errores values (601112,0,'No existen mas departamentos relacionados a la cuenta ingresada')
insert into cobis..cl_errores values (601113,0,'Departamento no autorizado a usar esta cuenta')
insert into cobis..cl_errores values (601114,0,'No existen asientos asociados al comprobante')
insert into cobis..cl_errores values (601115,0,'No existen transacciones autorizadas para el rol especificado')
insert into cobis..cl_errores values (601116,0,'Comprobante no esta mayorizado, no puede ser desmayorizado')
insert into cobis..cl_errores values (601117,0,'Codigo de interfase ya existe')
insert into cobis..cl_errores values (601118,0,'Codigo de interfase no existe')
insert into cobis..cl_errores values (601119,0,'Interfase consultada no existe')
insert into cobis..cl_errores values (601120,0,'No existen interfases')
insert into cobis..cl_errores values (601121,0,'No existen mas interfases')
insert into cobis..cl_errores values (601122,0,'Codigo de nivel de area ya existe')
insert into cobis..cl_errores values (601123,0,'Codigo de nivel de area consultado no existe')
insert into cobis..cl_errores values (601124,0,'No existen niveles de area')
insert into cobis..cl_errores values (601125,0,'No existen mas niveles de areas')
insert into cobis..cl_errores values (601126,0,'No existe nivel superior de area especificada')
insert into cobis..cl_errores values (601127,0,'Codigo de area ya existe')
insert into cobis..cl_errores values (601128,0,'Codigo de area consultado no existe')
insert into cobis..cl_errores values (601129,0,'No existen Areas')
insert into cobis..cl_errores values (601130,0,'No existen mas Areas')
insert into cobis..cl_errores values (601131,0,'Oficina consultada no existe o no es de movimiento')
insert into cobis..cl_errores values (601132,0,'Area consultada no existe o no es de movimiento')
insert into cobis..cl_errores values (601133,0,'Nivel de cuenta de presupuesto ya existe')
insert into cobis..cl_errores values (601134,0,'Nivel de cuenta de presupuesto no existe')
insert into cobis..cl_errores values (601135,0,'No existen niveles de cuenta de presupuesto')
insert into cobis..cl_errores values (601136,0,'No existen mas niveles de cuenta de presupuesto')
insert into cobis..cl_errores values (601137,0,'Codigo de tipo de operacion ya existe')
insert into cobis..cl_errores values (601138,0,'Tipo de operacion consultado no existe')
insert into cobis..cl_errores values (601139,0,'No existen Tipos de operacion')
insert into cobis..cl_errores values (601140,0,'No existen mas Tipos de operacion')
insert into cobis..cl_errores values (601141,0,'Cuenta de presupuesto ya existe')
insert into cobis..cl_errores values (601143,0,'No existen registros relacionados a la cuenta de presupuesto')
insert into cobis..cl_errores values (601144,0,'No existen Mas registros relacionados a la cuenta de presupuesto')
insert into cobis..cl_errores values (601145,0,'Registro de presupuesto ya existe')
insert into cobis..cl_errores values (601146,0,'No existen registros de presupuesto')
insert into cobis..cl_errores values (601147,0,'Cuenta de correspondencia no existe en el plan general')
insert into cobis..cl_errores values (601148,0,'Cuenta de correspondencia ya existe')
insert into cobis..cl_errores values (601149,0,'Correspondencia consultada no existe')
insert into cobis..cl_errores values (601150,0,'No existen mas registros')
insert into cobis..cl_errores values (601151,0,'Cuenta COBIS ya esta relacionada con cuenta ITX')
insert into cobis..cl_errores values (601152,0,'Ya existe control de ingreso de comprobantes para el usuario dado')
insert into cobis..cl_errores values (601153,0,'No existen registros para la consulta dada')
insert into cobis..cl_errores values (601154,0,'Usuario no tiene acceso en la oficina o area dada')
insert into cobis..cl_errores values (601155,0,'El Nivel de Organizacion debe ser jerarquicamente menor')
insert into cobis..cl_errores values (601156,0,'Cuenta superior tiene movimientos o saldos')
insert into cobis..cl_errores values (601157,0,'Error en Insercion de Secuencia')
insert into cobis..cl_errores values (601158,0,'Cuenta no esta relacionada con oficina')
insert into cobis..cl_errores values (601159,0,'Registro No Existe')
insert into cobis..cl_errores values (601160,0,'Registro ya Existe')
insert into cobis..cl_errores values (601161,1,'Error en Insercion de Registro')
insert into cobis..cl_errores values (601162,0,'Error en actualizacion de Registro')
insert into cobis..cl_errores values (601163,0,'Ya existe registro en tabla temporal de perfilies')
insert into cobis..cl_errores values (601164,0,'Error en delete de Registro')
insert into cobis..cl_errores values (601165,0,'Cuenta es Nivel Superior de Cuentas existentes')
insert into cobis..cl_errores values (601166,0,'Cuenta a actualizar tiene movimientos o saldos')
insert into cobis..cl_errores values (601167,0,'Ya existe el tercero')
insert into cobis..cl_errores values (601168,0,'No existe definido el producto para interfaz contable')
insert into cobis..cl_errores values (601169,0,'No existe el registro de Retencion para el Regimen Fiscal del Tercero')
insert into cobis..cl_errores values (601170,0,'Rango de periodo ya existe')
insert into cobis..cl_errores values (601171,0,'No existen mas niveles de oficinas')
insert into cobis..cl_errores values (601172,0,'Oficina no tiene dependientes')
insert into cobis..cl_errores values (601173,0,'Area no tiene dependientes')
insert into cobis..cl_errores values (601174,0,'No existe deshabilitacion a eliminar')
insert into cobis..cl_errores values (601175,0,'Existe deshabilitacion a eliminar')
insert into cobis..cl_errores values (601176,0,'No existe habilitacion a cortes para oficinas')
insert into cobis..cl_errores values (601177,0,'Existe operacion bancaria asociada al banco')
insert into cobis..cl_errores values (601178,0,'No existe operacion bancaria asociada al banco')
insert into cobis..cl_errores values (601179,0,'Tipo de Area ya existe')
insert into cobis..cl_errores values (601182,0,'No existen comprobantes para validar la interfaz contable en la fecha y producto dados')
insert into cobis..cl_errores values (601184,0,'Los datos del documento del Impuesto no existen')
insert into cobis..cl_errores values (601185,0,'Falta cotizaciòn de dìa anterior')
insert into cobis..cl_errores values (601250,0,'DEBE INGRESAR UN CRITERIO DE BUSQUEDA VALIDO')
insert into cobis..cl_errores values (601500,0,'Parametro MON1 no definido')
insert into cobis..cl_errores values (601501,0,'Parametro MON2 no definido')
insert into cobis..cl_errores values (601502,0,'No ha sido ingresada la cotizacion a la fecha dada para MON1')
insert into cobis..cl_errores values (601503,0,'Existen valores en cotizaciones que dependen de MON1 para la fecha dada')
insert into cobis..cl_errores values (601600,0,'No Existe Grupo Gastos Compensados')
insert into cobis..cl_errores values (601601,0,'No Existe Cuenta Contable')
insert into cobis..cl_errores values (601602,0,'NO SE PERMITE MAYORIZACIËN MIENTRAS SE EJECUTA PASO A DEFINITIVOS')
insert into cobis..cl_errores values (601603,0,'PRODUCTO CONTABILIDAD HABILITADO')
insert into cobis..cl_errores values (601604,0,'ERROR OPCION SP_MAYSI')
insert into cobis..cl_errores values (602028,0,'Cuenta no tiene niveles dependientes')
insert into cobis..cl_errores values (603001,1,'Error en insercion de empresa')
insert into cobis..cl_errores values (603002,1,'Error en insercion de categoria')
insert into cobis..cl_errores values (603003,1,'Error en insercion de Tipo_plan')
insert into cobis..cl_errores values (603004,1,'Error en insercion de Jerarquia')
insert into cobis..cl_errores values (603005,1,'Error en insercion de seccion')
insert into cobis..cl_errores values (603006,1,'Error en insercion de Centro de Costo')
insert into cobis..cl_errores values (603007,1,'Error en insercion de Cuenta')
insert into cobis..cl_errores values (603008,1,'Error en insercion de Periodo')
insert into cobis..cl_errores values (603009,1,'Error en insercion de comprobante Tipo')
insert into cobis..cl_errores values (603010,1,'Error en insercion de Nivel de Cuenta')
insert into cobis..cl_errores values (603011,1,'Contador de dinamica es Nulo')
insert into cobis..cl_errores values (603012,1,'Error en insercion de Dinamica de Cuenta')
insert into cobis..cl_errores values (603013,1,'Error en insercion de Organizacion')
insert into cobis..cl_errores values (603014,1,'Error en insercion de Plan Especifico')
insert into cobis..cl_errores values (603015,1,'Error en insercion de Detalle de Plan Especifico')
insert into cobis..cl_errores values (603016,1,'Error en insercion de Detalle de comprobante Tipo')
insert into cobis..cl_errores values (603017,1,'Error en insercion de Documento por Filial')
insert into cobis..cl_errores values (603018,1,'Error en insercion de Cortes')
insert into cobis..cl_errores values (603019,1,'Error en insercion de Comprobante en tabla temporal')
insert into cobis..cl_errores values (603020,1,'Error en insercion de Detalle de Comprobante en tabla temporal')
insert into cobis..cl_errores values (603021,1,'Error en la mayorizacion del comprobante')
insert into cobis..cl_errores values (603022,1,'Error en actualizacion de estado del comprobante')
insert into cobis..cl_errores values (603023,0,'Periodo o Corte no vigente o Cerrado')
insert into cobis..cl_errores values (603024,1,'Error en insercion de Saldos al mayorizar')
insert into cobis..cl_errores values (603025,1,'Error en insercion de Comprobante')
insert into cobis..cl_errores values (603026,1,'Error en insercion de Cotizacion')
insert into cobis..cl_errores values (603027,1,'Error en insercion de Nivel de Cuentas de una empresa')
insert into cobis..cl_errores values (603028,1,'Error en insercion automatica de Niveles de Cuentas por empresa')
insert into cobis..cl_errores values (603029,1,'Error en insercion automatica de Cuentas por empresa pertenecientes a un tipo de Plan dado')
insert into cobis..cl_errores values (603030,1,'Error en insercion automatica de tablas relacionadas al catalogo de empresas')
insert into cobis..cl_errores values (603031,1,'No se puede ingresar esta cuenta debido a que ya esta definida para alguna empresa')
insert into cobis..cl_errores values (603032,1,'Error en insercion de transaccion de servicio')
insert into cobis..cl_errores values (603033,1,'Error en insercion de Oficina')
insert into cobis..cl_errores values (603034,1,'Error en insercion de Oficina_seccion')
insert into cobis..cl_errores values (603035,1,'Error en insercion de secciones de una empresa')
insert into cobis..cl_errores values (603036,1,'Error en insercion de nivel de departamento')
insert into cobis..cl_errores values (603037,1,'Error en insercion de Departamento')
insert into cobis..cl_errores values (603038,1,'Error en insercion automatica de Oficina-seccion')
insert into cobis..cl_errores values (603039,1,'Error en insercion de Proceso')
insert into cobis..cl_errores values (603040,1,'Error en insercion de cuenta relacionda a Proceso')
insert into cobis..cl_errores values (603041,1,'Error en insercion de cuenta asociada')
insert into cobis..cl_errores values (603042,1,'Error en actualizacion de movimiento en cuenta superior')
insert into cobis..cl_errores values (603043,1,'Error en insercion de departamento-oficina')
insert into cobis..cl_errores values (603044,1,'Error en insercion de cuenta-departamento')
insert into cobis..cl_errores values (603045,1,'Error en insercion de comprobante Tipo a tabla temporal')
insert into cobis..cl_errores values (603046,1,'Error en insercion de detalle de comprobante Tipo a tabla temporal')
insert into cobis..cl_errores values (603047,1,'Error en la insercion de la interfase')
insert into cobis..cl_errores values (603048,1,'Error en la insercion de la interfase')
insert into cobis..cl_errores values (603049,1,'Error en la insercion de nivel de area')
insert into cobis..cl_errores values (603050,1,'Error en la insercion de area')
insert into cobis..cl_errores values (603051,1,'Error en la insercion de Nivel de cuenta de presupuesto')
insert into cobis..cl_errores values (603052,1,'Error en la insercion de tipo de operacion')
insert into cobis..cl_errores values (603053,1,'Error en la insercion de cuenta de presupuesto')
insert into cobis..cl_errores values (603054,1,'Error en la insercion de plan general de presupuesto')
insert into cobis..cl_errores values (603055,1,'Error en la insercion de presupuesto')
insert into cobis..cl_errores values (603056,1,'No existe definido condicion en cta asoc. para insercion asientos automaticos')
insert into cobis..cl_errores values (603057,1,'Error en insercion de correspondencia')
insert into cobis..cl_errores values (603058,1,'Error en insercion de control de ingreso de comprobantes')
insert into cobis..cl_errores values (603059,1,'Error en insercion de registro')
insert into cobis..cl_errores values (603060,1,'Error en insercion de datos de conciliacion')
insert into cobis..cl_errores values (603061,1,'Existe definida mas de una Condicion en Cuenta-Proceso')
insert into cobis..cl_errores values (603062,1,'Error en la insercion de Diferidos')
insert into cobis..cl_errores values (603063,1,'No existe corte definido para saldo tercero')
insert into cobis..cl_errores values (603064,1,'Ya existe un corte actual para periodo')
insert into cobis..cl_errores values (603065,0,'Error en inserci¢n de terceros')
insert into cobis..cl_errores values (603066,0,'Operaci¢n de Conciliaci¢n ya existe')
insert into cobis..cl_errores values (603067,0,'Operaci¢n de Conciliaci¢n a Eliminar no existe')
insert into cobis..cl_errores values (603068,0,'Extracto de Conciliación Bancaria No Existe')
insert into cobis..cl_errores values (603069,0,'Validacion de Cuentas Contrapartida de Movimientos Especiales no Cuadra')
insert into cobis..cl_errores values (603070,1,'Fecha final del corte superior a la fecha final del periodo')
insert into cobis..cl_errores values (603071,0,'LA CUENTA CONTABLE YA SE ENCUENTRA DEFINIDA PARA OTRA CUENTA CORRIENTE')
insert into cobis..cl_errores values (603072,0,'El banco no tiene definidas cuentas conciliadas')
insert into cobis..cl_errores values (603073,1,'Error en la insercion de la habilitacion de oficina a corte')
insert into cobis..cl_errores values (603074,0,'Error en Insercion de Asientos en Tabla Temporal de Transferencias')
insert into cobis..cl_errores values (603075,0,'Error en Actualizacion de Tabla Temporal de Transferencias')
insert into cobis..cl_errores values (603076,0,'Error en Borrado de Tabla Temporal de Transferencias')
insert into cobis..cl_errores values (603077,0,'Error en Insercion de Asientos en Tabla Temporal de Posicion')
insert into cobis..cl_errores values (603078,0,'Error en Actualizacion de Tabla Temporal de Posicion')
insert into cobis..cl_errores values (603079,0,'Error en la insercion de exenciones por producto')
insert into cobis..cl_errores values (603080,1,'Error en la insercion de Tipo de Area')
insert into cobis..cl_errores values (605001,0,'Codigo de empresa a actualizar no existe')
insert into cobis..cl_errores values (605002,1,'Error en actualizacion de empresa')
insert into cobis..cl_errores values (605003,0,'Codigo de categoria a actualizar no existe')
insert into cobis..cl_errores values (605004,1,'Error en actualizacion de categoria')
insert into cobis..cl_errores values (605005,0,'Codigo de Tipo_plan a actualizar no existe')
insert into cobis..cl_errores values (605006,1,'Error en actualizacion de Tipo_plan')
insert into cobis..cl_errores values (605007,0,'Codigo de Jerarquia a actualizar no existe')
insert into cobis..cl_errores values (605008,1,'Error en actualizacion de Jerarquia')
insert into cobis..cl_errores values (605009,0,'Codigo de seccion a actualizar no existe')
insert into cobis..cl_errores values (605010,1,'Error en actualizacion de seccion')
insert into cobis..cl_errores values (605011,0,'Codigo de Centro de Costo a actualizar no existe')
insert into cobis..cl_errores values (605012,1,'Error en actualizacion de centro de Costo')
insert into cobis..cl_errores values (605013,0,'Codigo de Cuenta a actualizar no existe')
insert into cobis..cl_errores values (605014,1,'Error en actualizacion de Cuenta')
insert into cobis..cl_errores values (605015,0,'Codigo de Comprobante Tipo a actualizar no existe')
insert into cobis..cl_errores values (605016,1,'Error en actualizacion de comprobante tipo')
insert into cobis..cl_errores values (605017,1,'Error en actualizacion de Nivel Cta en catalogo de filial')
insert into cobis..cl_errores values (605018,0,'Nivel de cuenta a actualizar no existe')
insert into cobis..cl_errores values (605019,1,'Error en actualizacion de Nivel de Cuenta')
insert into cobis..cl_errores values (605020,1,'Error en actualizacion de contador en Cuentas')
insert into cobis..cl_errores values (605021,0,'Dinamica de cuenta a actualizar no existe')
insert into cobis..cl_errores values (605022,1,'Error en actualizacion de Dinamica de Cuenta')
insert into cobis..cl_errores values (605023,0,'Codigo de Organizacion a actualizar no existe')
insert into cobis..cl_errores values (605024,1,'Error en actualizacion de Organizacion')
insert into cobis..cl_errores values (605025,0,'Plan Especifico a actualizar no existe')
insert into cobis..cl_errores values (605026,1,'Error en actualizacion de Plan Especifico')
insert into cobis..cl_errores values (605027,1,'Error en actualizacion de Detalle de Plan Especifico')
insert into cobis..cl_errores values (605028,1,'Error en actualizacion de Comprobante Tipo')
insert into cobis..cl_errores values (605029,1,'Documento de filial a actualizar no existe')
insert into cobis..cl_errores values (605030,1,'Error en actualizacion de Documento de Filial')
insert into cobis..cl_errores values (605031,0,'Nivel de Cuenta a actualizar esta relacionado con catalogo de Cuentas')
insert into cobis..cl_errores values (605032,0,'Codigo de Organizacion a actualizar esta relacionado con Oficinas')
insert into cobis..cl_errores values (605033,1,'Nivel Superior de Cuenta esta Cancelado')
insert into cobis..cl_errores values (605034,1,'Error en la actualizacion de estado en Niveles inferiores de la Cuenta')
insert into cobis..cl_errores values (605035,1,'Nivel Superior de Centro de Costo esta cancelado')
insert into cobis..cl_errores values (605036,1,'Error en la actualizacion de saldos al mayorizar')
insert into cobis..cl_errores values (605037,1,'Error en la actualizacion de Comprobante')
insert into cobis..cl_errores values (605038,1,'Cotizacion a actualizar no existe')
insert into cobis..cl_errores values (605039,1,'Error en la actualizacion de Cotizacion')
insert into cobis..cl_errores values (605040,1,'Error en la actualizacion de Corte')
insert into cobis..cl_errores values (605041,1,'Error en la desmayorizacion')
insert into cobis..cl_errores values (605042,1,'Nivel de Cuenta de una empresa a actualizar no existe')
insert into cobis..cl_errores values (605043,1,'Error en actualizacion del atributo <<movimiento>> al insertar un nuevo nivel de Centro Costo')
insert into cobis..cl_errores values (605044,1,'Existen cuentas con saldos, NO se puede modificar el tipo de plan de la empresa')
insert into cobis..cl_errores values (605045,1,'Error en actualizacion del estado de una cuenta en modificacion de cuentas de un Tipo de Plan')
insert into cobis..cl_errores values (605046,0,'Codigo de Oficina a actualizar No existe')
insert into cobis..cl_errores values (605047,1,'Error en actualizacion de Oficina')
insert into cobis..cl_errores values (605048,1,'Error en actualizacion de Oficina_seccion')
insert into cobis..cl_errores values (605049,0,'Codigo de Oficina_seccion a actualizar no existe')
insert into cobis..cl_errores values (605050,0,'Codigo de seccion por empresa a actualizar no existe')
insert into cobis..cl_errores values (605051,1,'Error en actualizacion de seccion por empresa')
insert into cobis..cl_errores values (605052,0,'Nivel de Departamento a actualizar no existe')
insert into cobis..cl_errores values (605053,1,'Error en actualizacion de nivel de departamento')
insert into cobis..cl_errores values (605054,0,'Codigo de Departamento a actualizar no existe')
insert into cobis..cl_errores values (605055,1,'Error en actualizacion de Departamento')
insert into cobis..cl_errores values (605056,1,'Codigo de proceso a actualizar no existe')
insert into cobis..cl_errores values (605057,1,'Error en actualizacion de Proceso')
insert into cobis..cl_errores values (605058,1,'Codigo de cuenta-proceso a actualizar no existe')
insert into cobis..cl_errores values (605059,1,'Error en actualizacion de Cuenta-Proceso')
insert into cobis..cl_errores values (605060,1,'Codigo de cuenta asociada a actualizar no existe')
insert into cobis..cl_errores values (605061,1,'Error en actualizacion de Cuenta aosciada')
insert into cobis..cl_errores values (605062,1,'Codigo de oficina_departamento a actualizar no existe')
insert into cobis..cl_errores values (605063,1,'Error en Actualizacion de Oficina_departamento')
insert into cobis..cl_errores values (605064,1,'Nivel de area a actualizar no existe')
insert into cobis..cl_errores values (605065,1,'Error en actualizacion de nivel de area')
insert into cobis..cl_errores values (605066,1,'Codigo de area a actualizar no existe')
insert into cobis..cl_errores values (605067,1,'Error en la actualizacion de area')
insert into cobis..cl_errores values (605068,1,'Nivel de cuenta de presupuesto a actualizar no existe')
insert into cobis..cl_errores values (605069,1,'Nivel de cuenta de presupuesto a actualizar relacionado con cuentas de presupuesto')
insert into cobis..cl_errores values (605070,1,'Error en actualizacion de nivel de cuenta de presupuesto')
insert into cobis..cl_errores values (605072,1,'Error en actualizacion de tipo de operacion')
insert into cobis..cl_errores values (605073,1,'Error en actualizacion de cuenta de presupuesto')
insert into cobis..cl_errores values (605074,1,'Codigo de plan general de presupuesto a actualizar no existe')
insert into cobis..cl_errores values (605075,1,'Error en actualizacion de plan general de presupuesto')
insert into cobis..cl_errores values (605076,1,'Registro de presupuesto a actualizar no existe')
insert into cobis..cl_errores values (605077,1,'Error en actualizacion de presupuesto')
insert into cobis..cl_errores values (605078,1,'Cuenta no puede ser de movimiento')
insert into cobis..cl_errores values (605079,1,'Cuenta de correspondencia a actualizar no existe')
insert into cobis..cl_errores values (605080,1,'Error en actualizacion de correspondencia')
insert into cobis..cl_errores values (605081,1,'Error en actualizacion de tipo de area')
insert into cobis..cl_errores values (605082,1,'No existe registro')
insert into cobis..cl_errores values (605083,1,'Error en Relacion de Conciliacion Bancaria')
insert into cobis..cl_errores values (605084,1,'Error en Actualizacion de Diferidos')
insert into cobis..cl_errores values (605085,1,'Fecha de Inicio de Diferido Menor que Fecha Batch')
insert into cobis..cl_errores values (605086,1,'Error en la Actualizacion Saldos Terceros')
insert into cobis..cl_errores values (605087,1,'Cuenta a ser cancelada con hijas vigentes')
insert into cobis..cl_errores values (605088,0,'Error en la actualizacion de Asiento')
insert into cobis..cl_errores values (607001,0,'Codigo de empresa a eliminar no existe')
insert into cobis..cl_errores values (607002,1,'Error en eliminacion de empresa')
insert into cobis..cl_errores values (607003,0,'Codigo de empresa relacionado con CUENTAS')
insert into cobis..cl_errores values (607004,0,'Codigo de empresa relacionado con ORGANIZACION')
insert into cobis..cl_errores values (607005,0,'Codigo de empresa relacionado con NIVEL DE CUENTA')
insert into cobis..cl_errores values (607006,0,'Codigo de categoria a eliminar no existe')
insert into cobis..cl_errores values (607007,1,'Codigo de categoria relacionado con CUENTAS')
insert into cobis..cl_errores values (607008,1,'Error en eliminacion de categoria')
insert into cobis..cl_errores values (607009,0,'Codigo de Tipo_plan a eliminar no existe')
insert into cobis..cl_errores values (607010,0,'Codigo de Tipo_plan relacionado con CUENTAS')
insert into cobis..cl_errores values (607011,1,'Error en eliminacion de Tipo_plan')
insert into cobis..cl_errores values (607012,0,'Codigo de Jerarquia a eliminar no existe')
insert into cobis..cl_errores values (607013,0,'Codigo de Jerarquia relacionado con ORGANIZACION')
insert into cobis..cl_errores values (607014,1,'Error en eliminacion de Jerarquia')
insert into cobis..cl_errores values (607015,0,'Codigo de seccion a eliminar no existe')
insert into cobis..cl_errores values (607016,0,'Codigo de seccion relacionado con Cuenta')
insert into cobis..cl_errores values (607017,1,'Error en eliminacion de seccion')
insert into cobis..cl_errores values (607018,0,'Codigo de Centro de Costo a eliminar no existe')
insert into cobis..cl_errores values (607019,0,'Codigo de Centro de Costo relacionado con Plan General')
insert into cobis..cl_errores values (607020,1,'Error en eliminacion de Centro de Costo')
insert into cobis..cl_errores values (607021,0,'Codigo de Cuenta a eliminar no existe')
insert into cobis..cl_errores values (607022,0,'Codigo de Cuenta relacionado con Plan General')
insert into cobis..cl_errores values (607023,1,'Error en eliminacion de Cuenta')
insert into cobis..cl_errores values (607024,0,'Codigo de Periodo relacionado con Saldos')
insert into cobis..cl_errores values (607025,1,'Error en eliminacion de Cortes')
insert into cobis..cl_errores values (607026,1,'Error en eliminacion de Periodos')
insert into cobis..cl_errores values (607027,0,'Codigo de Comprobante Tipo a eliminar no existe')
insert into cobis..cl_errores values (607028,0,'Nivel de Cuenta a eliminar no existe')
insert into cobis..cl_errores values (607029,0,'Nivel de Cuenta relacionado con catalogo de cuentas')
insert into cobis..cl_errores values (607030,1,'Error en eliminacion de Nivel de Cuenta')
insert into cobis..cl_errores values (607031,0,'Codigo de Organizacion a eliminar no existe')
insert into cobis..cl_errores values (607032,0,'Codigo de Organizacion relacionado en catalogo Organizacion')
insert into cobis..cl_errores values (607034,1,'Error en eliminacion de Organizacion')
insert into cobis..cl_errores values (607035,0,'Plan Especifico a eliminar no existe')
insert into cobis..cl_errores values (607036,1,'Error en eliminacion de detalle de Plan Especifico')
insert into cobis..cl_errores values (607037,1,'Error en eliminacion de Plan Especifico')
insert into cobis..cl_errores values (607038,1,'Error en eliminacion de Comprobante Tipo')
insert into cobis..cl_errores values (607039,1,'Error en eliminacion de detalle de Comprobante Tipo')
insert into cobis..cl_errores values (607040,1,'Documento de filial a eliminar no existe')
insert into cobis..cl_errores values (607041,1,'Documento de Filial relacionado con Comprobantes')
insert into cobis..cl_errores values (607042,1,'Error en eliminacion de Documento de Filial')
insert into cobis..cl_errores values (607043,1,'Error en eliminacion de Dinamica de una Cuenta')
insert into cobis..cl_errores values (607044,1,'Niveles Superiores de Cuentas, Relacionados con de Cuentas')
insert into cobis..cl_errores values (607045,0,'Cuenta a eliminar es Nivel Superior de Cuentas existentes')
insert into cobis..cl_errores values (607046,0,'Niveles Inferiores de Organizacion estan relacionados con Oficinas')
insert into cobis..cl_errores values (607047,0,'Centro de Costo a eliminar es Nivel Superior de Centros Existentes')
insert into cobis..cl_errores values (607048,0,'Cuenta de Movimiento relacionada con detalle de Plan Especifico')
insert into cobis..cl_errores values (607049,0,'Cuenta de Movimiento relacionada con  Saldos')
insert into cobis..cl_errores values (607050,0,'Cuenta de Movimiento relacionada con  Asientos')
insert into cobis..cl_errores values (607051,0,'Cuenta de Movimiento relacionada con  Detalle de Comprobantes Tipo')
insert into cobis..cl_errores values (607052,1,'Error en la Eliminacion de la relacion Cuenta - Centro de Costo')
insert into cobis..cl_errores values (607053,0,'Error, verifique el status del comprobante')
insert into cobis..cl_errores values (607054,1,'Error en la Eliminacion de asientos del comprobante')
insert into cobis..cl_errores values (607055,1,'Error en la Eliminacion del comprobante')
insert into cobis..cl_errores values (607056,1,'Comprobante/asiento esta mayorizado, No puede ser modificado')
insert into cobis..cl_errores values (607057,1,'Cotizacion a eliminar NO existe')
insert into cobis..cl_errores values (607058,1,'Error en la Eliminacion de Cotizacion')
insert into cobis..cl_errores values (607059,1,'Error en eliminacion de cuentas por empresa en proceso de modificacion de tipo Plan de una empresa')
insert into cobis..cl_errores values (607060,1,'Error en eliminacion de niveles de cuentas por empresa en proceso de modificacion de tipo Plan de una empresa')
insert into cobis..cl_errores values (607061,1,'No se puede eliminar el plan de cuentas de la empresa debido a que existen cuentas con saldos')
insert into cobis..cl_errores values (607062,1,'No se puede eliminar el plan de cuentas de la empresa debido a que existen asientos con cuentas de la empresa')
insert into cobis..cl_errores values (607064,1,'Oficina a eliminar esta relacionada con catalogo oficina-seccion')
insert into cobis..cl_errores values (607065,1,'Oficina a eliminar es nivel superior de oficinas existentes')
insert into cobis..cl_errores values (607066,1,'Error en eliminacion de Oficina')
insert into cobis..cl_errores values (607067,1,'Codigo de Oficina_seccion a eliminar no existe')
insert into cobis..cl_errores values (607068,1,'Codigo de Oficina_seccion relacionado con plan general')
insert into cobis..cl_errores values (607069,1,'Error en eliminacion de Oficina_seccion')
insert into cobis..cl_errores values (607070,0,'Codigo de seccion de una empresa a eliminar no existe')
insert into cobis..cl_errores values (607071,0,'Codigo de seccion de una empresa a eliminar relacionado con Oficina_seccion')
insert into cobis..cl_errores values (607072,1,'Error en eliminacion  de seccion de una empresa')
insert into cobis..cl_errores values (607073,0,'Nivel de Departamento a eliminar no existe')
insert into cobis..cl_errores values (607074,0,'Nivel de Departamento a eliminar tiene relacion con catalogo de departamentos')
insert into cobis..cl_errores values (607075,1,'Error en eliminacion de nivel de departamento')
insert into cobis..cl_errores values (607076,0,'Codigo de Departamento a eliminar no existe')
insert into cobis..cl_errores values (607077,0,'Codigo de Departamento a eliminar esta relacionado a oficinas')
insert into cobis..cl_errores values (607078,0,'Departamento a eliminar es nivel superior de otros departamentos')
insert into cobis..cl_errores values (607079,0,'Error en eliminacion de departamento')
insert into cobis..cl_errores values (607080,0,'Codigo de Proceso a eliminar no existe')
insert into cobis..cl_errores values (607081,0,'Codigo de Proceso a eliminar relacionado con tabla cuenta_proceso')
insert into cobis..cl_errores values (607082,0,'Error en eliminacion de Proceso')
insert into cobis..cl_errores values (607083,0,'Codigo de cuenta-proceso a eliminar no existe')
insert into cobis..cl_errores values (607084,0,'Codigo de cuenta-proceso a eliminar  relacionado co tabla cuenta_asociada')
insert into cobis..cl_errores values (607085,0,'Error en eliminacion de Cuenta-Proceso')
insert into cobis..cl_errores values (607086,0,'Codigo de cuenta asociada a eliminar no existe')
insert into cobis..cl_errores values (607087,0,'Error en eliminacion de cuenta asociada')
insert into cobis..cl_errores values (607088,0,'Error en eliminacion de oficina_departamento al eliminar empresa')
insert into cobis..cl_errores values (607089,0,'Error en eliminacion de organizacion al eliminar empresa')
insert into cobis..cl_errores values (607090,0,'Error en eliminacion de oficina_seccion al eliminar empresa')
insert into cobis..cl_errores values (607091,0,'Error en eliminacion de plan genera;l de cuentas al eliminar empresa')
insert into cobis..cl_errores values (607092,0,'Error en eliminacion de oficinas al  eliminar empresa')
insert into cobis..cl_errores values (607093,0,'Codigo de oficina_departamento a eliminar no existe')
insert into cobis..cl_errores values (607094,0,'Codigo de oficina_departamento a eliminar relacionado con Comprobantes')
insert into cobis..cl_errores values (607095,0,'Error en Eliminacion de Oficina-departamento')
insert into cobis..cl_errores values (607096,0,'Codigo de cuenta-departamento a eliminar no existe')
insert into cobis..cl_errores values (607097,0,'Error en eliminacion de Cuenta-departamento')
insert into cobis..cl_errores values (607098,0,'Cuenta a eliminar esta relacionada con departamentos')
insert into cobis..cl_errores values (607099,0,'Error en la eliminacion de la interfase')
insert into cobis..cl_errores values (607100,0,'Nivel de area a eliminar no existe')
insert into cobis..cl_errores values (607101,0,'Nivel de area a eliminar relacionado con catalogo de areas')
insert into cobis..cl_errores values (607102,0,'Niveles inferiores del nivel de area relacionados con catalogo de areas')
insert into cobis..cl_errores values (607103,0,'Error en eliminacion de nivele de area')
insert into cobis..cl_errores values (607104,0,'Codigo de area a eliminar no existe')
insert into cobis..cl_errores values (607105,0,'Codigo de area a eliminar es nivel superior de areas existentes')
insert into cobis..cl_errores values (607106,0,'Error en eliminacion de area')
insert into cobis..cl_errores values (607107,0,'Nivel de ctas de presup. a eliminar relacionado con cuentas de presup.')
insert into cobis..cl_errores values (607108,0,'Error en eliminacion de nivel de cuenta de presupuesto')
insert into cobis..cl_errores values (607109,0,'Tipo de operacion a eliminar no existe')
insert into cobis..cl_errores values (607110,0,'Tipo de operacion a eliminar relacionado con asientos')
insert into cobis..cl_errores values (607111,0,'Error en eliminacion de tipo de operacion')
insert into cobis..cl_errores values (607112,0,'Codigo de cuenta a eliminar relacionado con plan general de presupuesto')
insert into cobis..cl_errores values (607113,0,'Error en eliminacion de cuenta de presupuesto')
insert into cobis..cl_errores values (607114,0,'Codigo de plan general de presupuesto a eliminar no existe')
insert into cobis..cl_errores values (607115,0,'Error en eliminacion de plan general de presupuesto')
insert into cobis..cl_errores values (607116,0,'Registro de presupuesto a eliminar no existe')
insert into cobis..cl_errores values (607117,0,'Error en eliminacion de registro de presupuesto')
insert into cobis..cl_errores values (607118,0,'Control de ingreso de comprob. a eliminar no existe')
insert into cobis..cl_errores values (607119,0,'Relacion login-oficina-area existe en comprobantes, no puede ser eliminado')
insert into cobis..cl_errores values (607120,0,'Error en eliminacion de control de ingreso de comprobantes')
insert into cobis..cl_errores values (607121,0,'Error en Grabacion de datos Conciliacion')
insert into cobis..cl_errores values (607122,0,'Codigo de Moneda no Corresponde')
insert into cobis..cl_errores values (607123,0,'Tipo de transaccion no Corresponde')
insert into cobis..cl_errores values (607124,0,'Debitos y Creditos no Cuadran')
insert into cobis..cl_errores values (607125,0,'Opcion esta relacionada con Items')
insert into cobis..cl_errores values (607126,0,'Error al eliminar datos de conciliacion')
insert into cobis..cl_errores values (607127,0,'Tercero tiene asociado movimientos o saldos')
insert into cobis..cl_errores values (607128,0,'Concepto ya ha sido aplicado. Solo puede modificarlo')
insert into cobis..cl_errores values (607129,0,'Tercero tiene movimiento contable en el periodo')
insert into cobis..cl_errores values (607130,0,'Comprobante tipo no se puede eliminar ya que se encuentra relacionado con comprobante contable')
insert into cobis..cl_errores values (607131,0,'Oficina relacionada con plan de cuentas')
insert into cobis..cl_errores values (607132,0,'Oficina contabilidad no relacionada con oficina admin')
insert into cobis..cl_errores values (607133,0,'Error en eliminacion de tipo de area')
insert into cobis..cl_errores values (607134,0,'Error en Eliminacion de exencion por producto')
insert into cobis..cl_errores values (609100,0,'No existen Comprobantes Interfaz Contable Erroneos para Reprocesar')
insert into cobis..cl_errores values (609101,0,'Oficinas relacionadas Ya Existen')
insert into cobis..cl_errores values (609102,0,'Oficinas relacionadas para Eliminacion No Existe')
insert into cobis..cl_errores values (609103,0,'Error en Eliminacion de Equivalencia de Oficinas')
insert into cobis..cl_errores values (609104,0,'No Existen registros relacionados con Oficina Cobis')
insert into cobis..cl_errores values (609105,0,'No Existen Mas registros relacionados con Oficina Cobis')
insert into cobis..cl_errores values (609106,0,'No Existen registros relacionados con Oficina Unisys')
insert into cobis..cl_errores values (609107,0,'No Existen Mas registros relacionados con Oficina Unisys')
insert into cobis..cl_errores values (609108,0,'No Existen registros relacionados con la Empresa Activa')
insert into cobis..cl_errores values (609109,0,'No Existen Mas registros relacionados con la Empresa Activa')
insert into cobis..cl_errores values (609110,0,'Error en Insercion de Oficinas Equivalentes')
insert into cobis..cl_errores values (609111,0,'Cuenta Unisys ya esta relacionada con Cuenta Oficina Cobis')
insert into cobis..cl_errores values (609112,0,'Cuentas relacionadas Ya Existen')
insert into cobis..cl_errores values (609113,0,'Cuentas relacionadas para Eliminacion No Existe')
insert into cobis..cl_errores values (609114,0,'Error en Eliminacion de Equivalencia de Cuenta cobis, Cuenta Unisys')
insert into cobis..cl_errores values (609115,0,'No Existen registros relacionados con Cuenta Cobis')
insert into cobis..cl_errores values (609116,0,'No Existen Mas registros relacionados con Cuenta Cobis')
insert into cobis..cl_errores values (609117,0,'No Existen registros relacionados con Cuenta Unisys')
insert into cobis..cl_errores values (609118,0,'No Existen Mas registros relacionados con Cuenta Unisys')
insert into cobis..cl_errores values (609119,0,'No Existen registros relacionados con la Empresa Activa')
insert into cobis..cl_errores values (609120,0,'No Existen Mas registros relacionados con la Empresa Activa')
insert into cobis..cl_errores values (609121,0,'Error en Insercion de Cuentas Oficina Equivalentes')
insert into cobis..cl_errores values (609122,0,'No Existen registros relacionados con la Oficina Cobis')
insert into cobis..cl_errores values (609123,0,'No Existen Mas registros relacionados con la Oficina Cobis')
insert into cobis..cl_errores values (609124,0,'Cuenta Cobis no es de movimiento')
insert into cobis..cl_errores values (609125,0,'Comprobante no tiene asociado registro en retencion')
insert into cobis..cl_errores values (609126,0,'Cuenta Posee Saldo')
insert into cobis..cl_errores values (609127,0,'Cuenta de Tercero Posee Saldo')
insert into cobis..cl_errores values (609128,0,'Cuenta Posee Saldo o Movimiento')
insert into cobis..cl_errores values (609129,0,'Oficina no es de movimiento o Cuenta consultada no existe')
insert into cobis..cl_errores values (609130,0,'Oficina no es de movimiento o no existen saldos asociados')
insert into cobis..cl_errores values (609131,0,'No existen saldos para el Tercero consultado')
insert into cobis..cl_errores values (609132,0,'No existen transacciones para la oficina consultada')
insert into cobis..cl_errores values (609133,0,'No existen transacciones para la oficna consultada  o fechas no vigentes')
insert into cobis..cl_errores values (609134,0,'No existen terceros consultados o fechas no vigentes')
insert into cobis..cl_errores values (609135,0,'Fin de Consulta')
insert into cobis..cl_errores values (609136,0,'No existen saldos para la consulta dada o fechas no vigentes o cuenta sin niveles dependientes')
insert into cobis..cl_errores values (609137,0,'Cuenta a eliminar se encuentra asociada a proceso')
insert into cobis..cl_errores values (609138,0,'No existen transacciones para el tercero consultado o fechas no vigentes')
insert into cobis..cl_errores values (609139,0,'Existen cortes cerrados mayor a la fecha a mayorizar')
insert into cobis..cl_errores values (609140,0,'Cuenta no es de movimiento')
insert into cobis..cl_errores values (609141,0,'Cuenta a eliminar posee saldo')
insert into cobis..cl_errores values (609142,0,'Cuenta ya se encuentra asociada en oficina y area')
insert into cobis..cl_errores values (609143,0,'Cuenta no relacionada en plan general de presupuesto a oficina y area')
insert into cobis..cl_errores values (609144,0,'Oficina o Area no se puede eliminar se encuentra relacionada en el plan general')
insert into cobis..cl_errores values (609145,0,'No existen codigos de login')
insert into cobis..cl_errores values (609146,0,'Oficina no es consolidadora')
insert into cobis..cl_errores values (609147,0,'No existen procesos')
insert into cobis..cl_errores values (609148,0,'Descripcion ya existe')
insert into cobis..cl_errores values (609150,0,'La cuenta no posee Areas Autorizadas')
insert into cobis..cl_errores values (609227,1,'Error fecha comprobante corresponde a un dia feriado')
insert into cobis..cl_errores values (609301,0,'El regimen fiscal seleccionado no cumple las condiciones')
insert into cobis..cl_errores values (609303,0,'Error al insertar oficina pagadora')
insert into cobis..cl_errores values (609304,0,'Ya existe esta oficina ASOCIADA')
insert into cobis..cl_errores values (609305,0,'Error al insertar oficina asociada')
insert into cobis..cl_errores values (609306,0,'No hay oficinas asociadas para esta oficina pagadora')
insert into cobis..cl_errores values (609307,0,'Error al borrar oficina asociada')
insert into cobis..cl_errores values (609308,0,'Ya existe esta oficina PAGADORA')
insert into cobis..cl_errores values (609309,0,'Error al modificar informacion de la oficina pagadora')
insert into cobis..cl_errores values (609310,0,'Oficina superior es de nivel errado, o es de movimiento')
insert into cobis..cl_errores values (609311,0,'Area superior es de nivel errado, o es de movimiento')

delete from cobis..cl_errores where numero in (609312, 609313, 609314, 609315, 609316, 609317, 609318, 609319, 609320, 609321, 609322, 609323,601180)

insert into cobis..cl_errores (numero, severidad, mensaje) values (609312, 0, 'ERROR: EN LA CONSULTA DE SOLICITUD DE REPORTES')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609313, 0, 'ERROR: EN LA CONSULTA DE LISTADO DE REPORTES')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609314, 0, 'ERROR: YA SE PROCESO LA SOLICITUD PARA LA FECHA')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609315, 0, 'ERROR: EN INGRESO DE TRANSACCION DE SERVICIO')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609316, 0, 'ERROR: EN EL BORRADO DE SOLICITUD')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609317, 0, 'ERROR: EN EL INGRESO DE SOLICITUD')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609318, 0, 'ERROR: NO EXISTE PARAMETRO CFN')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609319, 0, 'ERROR: AL CALCULAR FECHA DE FIN DE MES')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609320, 0, 'ERROR: NO EXISTE PROCESO DE SOLICITUD DE REPORTE')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609321, 0, 'ERROR: NO EXISTE FECHA PROCESO')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609322, 0, 'ERROR: EN LA CONSULTA DE DIAS FERIADOS')
insert into cobis..cl_errores (numero, severidad, mensaje) values (609323, 0, 'ERROR: PETICION EXCEDE EL LIMITE DE TIEMPO MAXIMO DE GENERACION')
insert into  cobis..cl_errores (numero, severidad, mensaje) values(601180, 0, 'Existen comprobantes pendientes de Aprobación/Anulación para la fecha del corte')
go
