use cobis
go

delete from cl_ttransaccion
 where tn_trn_code in (78,2810,2811,2587,2589,2590,2591,2592,2593,2594,2595,2596,2700,80,90,2543,18,2502)

insert into cl_ttransaccion values (78,'CONSULTA PARAMETROS DE INICIO EN TERM FINANCIERA','COPA','CONSULTA LOS PARAMETROS DE INICIO PARA LA TERMINAL FINANCIERA')
insert into cl_ttransaccion values (2810,'MANTENIMIENTO CENTROS DE CANJE','MCDC','MANTENIMIENTO CENTROS DE CANJE')
insert into cl_ttransaccion values (2811,'RELACION OFICINA - CENTRO DE CANJE','ROCC','RELACION OFICINA - CENTRO DE CANJE')
insert into cl_ttransaccion values (2587,'CONSULTA DE RUTA Y TRANSITO','CRYT','CONSULTA DE RUTA Y TRANSITO')
insert into cl_ttransaccion values (2589,'CREACION DE OFICINAS DEL BANCO', 'CODB', 'CREACION DE OFICINAS DEL BANCO')
insert into cl_ttransaccion values (2590,'ACTUALIZACION DE OFICINAS DEL BANCO', 'AODB', 'ACTUALIZACION DE OFICINAS DEL BANCO')
insert into cl_ttransaccion values (2591,'CONSULTA DE OFICINAS DEL BANCO', 'CODB', 'CONSULTA DE OFICINAS DEL BANCO')
insert into cl_ttransaccion values (2592,'ELIMINACION DE OFICINAS DEL BANCO', 'EODB', 'ELIMINACION DE OFICINAS DEL BANCO')
insert into cl_ttransaccion values (2593,'CREACION DE BANCOS','CBAN','CREACION DE BANCOS')
insert into cl_ttransaccion values (2594,'ACTUALIZACION DE BANCOS','ABAN','ACTUALIZACION DE BANCOS')
insert into cl_ttransaccion values (2595,'CONSULTA DE BANCOS','CBAN','CONSULTA DE BANCOS')
insert into cl_ttransaccion values (2596,'ELIMINACION DE BANCOS','EBAN','ELIMINACION DE BANCOS')
insert into cl_ttransaccion values (2700,'CONSULTA DE TOTALES NACIONALES', 'CTCA', 'CONSULTA LOS TOTALES NACIONALES DE CAJA')
insert into cl_ttransaccion values (80, 'CONSULTA DE TOTALES POR OFICINA', 'CTOF', 'CONSULTA DE TOTALES POR OFICINA')
insert into cl_ttransaccion values (90, 'CONSULTA DE TOTALES POR CAJERO ADM', 'CTCA', 'CONSULTA LOS TOTALES DE CAJERO (ADMINISTRATIVA)')
insert into cl_ttransaccion values (2543, 'CONSULTA DE NOMBRE DE CLIENTE', 'CCLN', 'CONSULTA DE NOMBRE DE CLIENTE')
insert into cl_ttransaccion values (18, 'CONSULTA DE BANCO', 'COBA', 'CONSULTA DE BANCO VIA F5')
insert into cl_ttransaccion values (2502,'ND POR CHQ DEVUELTO CAMARA','NDCD','ND POR CHEQUE DEVUELTO CAMARA')
go

