osql -U%1 -P%2 -S%3 -iadprorol.sp   >sp.out
osql -U%1 -P%2 -S%3 -iadtrnrol.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iaycntxt.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iayfunc.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iayherram.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ib_qryfun.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ibdd.sp        >>sp.out
osql -U%1 -P%2 -S%3 -ibusqnodo.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ic_anveef.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ic_efanve.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icaldias.sp    >>sp.out
osql -U%1 -P%2 -S%3 -icat_ico.sp    >>sp.out
osql -U%1 -P%2 -S%3 -icatalogo.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icatpro.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iccactofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icccalofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iccconofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icccreofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icccupofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icceliofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iccofialt.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icerror.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iciudad.sp     >>sp.out
osql -U%1 -P%2 -S%3 -icodef.sp      >>sp.out
osql -U%1 -P%2 -S%3 -icomphora.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iconstabl.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icontext.sp    >>sp.out
osql -U%1 -P%2 -S%3 -icoparam.sp    >>sp.out
osql -U%1 -P%2 -S%3 -icopjeofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -icoprol.sp     >>sp.out
osql -U%1 -P%2 -S%3 -icotrans.sp    >>sp.out
osql -U%1 -P%2 -S%3 -icseqnos.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ictfunc.sp     >>sp.out
osql -U%1 -P%2 -S%3 -idefault.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ideftr.sp      >>sp.out
osql -U%1 -P%2 -S%3 -idepar.sp      >>sp.out
osql -U%1 -P%2 -S%3 -idepar2.sp     >>sp.out
osql -U%1 -P%2 -S%3 -idirecta.sp    >>sp.out
osql -U%1 -P%2 -S%3 -idirecta2.sp   >>sp.out
osql -U%1 -P%2 -S%3 -idistr.sp      >>sp.out
osql -U%1 -P%2 -S%3 -idomingos.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ieqfunc.sp     >>sp.out
osql -U%1 -P%2 -S%3 -ierrores.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ifechapro.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iferiados.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ifiliadml.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ifilial.sp     >>sp.out
osql -U%1 -P%2 -S%3 -ifunc.sp       >>sp.out
osql -U%1 -P%2 -S%3 -ifuncbusq.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ifuncio.sp     >>sp.out
osql -U%1 -P%2 -S%3 -ifuncio2.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ifuncrol.sp    >>sp.out
osql -U%1 -P%2 -S%3 -igenncs.sp     >>sp.out
osql -U%1 -P%2 -S%3 -igetsrv.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iherram.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iherramrol.sp  >>sp.out
osql -U%1 -P%2 -S%3 -ihora_tmp.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ihpagen.sp     >>sp.out
osql -U%1 -P%2 -S%3 -ihpsucur.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iindirec2.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iindirect.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iintfunc.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ilink.sp       >>sp.out
osql -U%1 -P%2 -S%3 -imapa.sp       >>sp.out
osql -U%1 -P%2 -S%3 -imedfunci.sp   >>sp.out
osql -U%1 -P%2 -S%3 -imedofi.sp     >>sp.out
osql -U%1 -P%2 -S%3 -imoneda.sp     >>sp.out
osql -U%1 -P%2 -S%3 -imoneddml.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iniv_map.sp    >>sp.out
osql -U%1 -P%2 -S%3 -inivel.sp      >>sp.out
osql -U%1 -P%2 -S%3 -inmcntxt.sp    >>sp.out
osql -U%1 -P%2 -S%3 -inmherram.sp   >>sp.out
osql -U%1 -P%2 -S%3 -inodo.sp       >>sp.out
osql -U%1 -P%2 -S%3 -inodo_lo2.sp   >>sp.out
osql -U%1 -P%2 -S%3 -inodo_loc.sp   >>sp.out
osql -U%1 -P%2 -S%3 -inodo_ni2.sp   >>sp.out
osql -U%1 -P%2 -S%3 -inodo_niv.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ioficidml.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ioficina.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iopbatch.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ioperador.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ipais.sp       >>sp.out
osql -U%1 -P%2 -S%3 -iparamet.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iparroq.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iprfunc.sp     >>sp.out
osql -U%1 -P%2 -S%3 -ipro_inst.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ipro_rol.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ipro_tra2.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ipro_tran.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iproaso.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iprocedu.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iproducto.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iproloc.sp     >>sp.out
osql -U%1 -P%2 -S%3 -ipromon.sp     >>sp.out
osql -U%1 -P%2 -S%3 -iprotoco.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iprovinc.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iqr2_usu.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iqr_pro_r.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iqr_r_tr.sp    >>sp.out
osql -U%1 -P%2 -S%3 -irol.sp        >>sp.out
osql -U%1 -P%2 -S%3 -irolbusq.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iruteo.sp      >>sp.out
osql -U%1 -P%2 -S%3 -isedehijo.sp   >>sp.out
osql -U%1 -P%2 -S%3 -isefuhijo.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iseq_dist.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iserver_d.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iserver_l.sp   >>sp.out
osql -U%1 -P%2 -S%3 -isexo.sp       >>sp.out
osql -U%1 -P%2 -S%3 -isis_ope.sp    >>sp.out
osql -U%1 -P%2 -S%3 -isp_fn_hijas.sp>>sp.out
osql -U%1 -P%2 -S%3 -isp_llave.sp   >>sp.out
osql -U%1 -P%2 -S%3 -isuc_corr.sp   >>sp.out
osql -U%1 -P%2 -S%3 -isupromon.sp   >>sp.out
osql -U%1 -P%2 -S%3 -isuproofi.sp   >>sp.out
osql -U%1 -P%2 -S%3 -it_ho_tmp.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ita_carta.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ita_coap.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ita_divd.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ita_divf.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ita_otref.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ita_parin.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ita_reldo.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ita_tasas.sp   >>sp.out
osql -U%1 -P%2 -S%3 -itablas.sp     >>sp.out
osql -U%1 -P%2 -S%3 -itcp.sp        >>sp.out
osql -U%1 -P%2 -S%3 -itello.sp      >>sp.out
osql -U%1 -P%2 -S%3 -iterminal.sp   >>sp.out
osql -U%1 -P%2 -S%3 -itipohora.sp   >>sp.out
osql -U%1 -P%2 -S%3 -itlink.sp      >>sp.out
osql -U%1 -P%2 -S%3 -itr_autor.sp   >>sp.out
osql -U%1 -P%2 -S%3 -itranbusq.sp   >>sp.out
osql -U%1 -P%2 -S%3 -itransac.sp    >>sp.out
osql -U%1 -P%2 -S%3 -itrfunc.sp     >>sp.out
osql -U%1 -P%2 -S%3 -itrnrol.sp     >>sp.out
osql -U%1 -P%2 -S%3 -itrnrol2.sp    >>sp.out
osql -U%1 -P%2 -S%3 -iusua_rol.sp   >>sp.out
osql -U%1 -P%2 -S%3 -iusuario.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ival_para.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ival_rol.sp    >>sp.out
osql -U%1 -P%2 -S%3 -ivalidpwd.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ivigencia.sp   >>sp.out
osql -U%1 -P%2 -S%3 -ix25.sp        >>sp.out
osql -U%1 -P%2 -S%3 -ix25_conf.sp   >>sp.out