use cobis
go
-- ----------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------COB_REMESAS---------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------------
delete from cl_ttransaccion
 where tn_trn_code in (475,494,720,721,698,712,713,715,716,718,723,722,727,447,606,607, 150017)
go

insert into cl_ttransaccion values (475, 'CONSULTA DE PRODUCTOS COBIS', 'COPC', 'CONSULTA DE PRODUCTOS COBIS')
insert into cl_ttransaccion values (494, 'CONSULTA DE TRANSACCIONES A CONTABILIZAR', 'CCON', 'CONSULTA DE TRANSACCIONES A CONTABILIZAR')
insert into cl_ttransaccion values (720, 'MANTENIMIENTO OPCIONES DML PARA PARAMETRIZACION DE PERFIL', 'MPPER', 'REALIZA EL MANTENIMIENTO DE LOS DATOS PARA LA PARAMETRIZACION DE LAS TRANSACCIONES AL PERFIL CONTABLE')
insert into cl_ttransaccion values (721, 'OPCIONES DE CONSULTA PARA PARAMETRIZACION DE PERFIL', 'CPPER', 'EJECUTA LAS CONSULTAS DE LOS DATOS PARA LA PARAMETRIZACION DE LAS TRANSACCIONES AL PERFIL CONTABLE')
insert into cl_ttransaccion values (712, 'AUTORIZACION DE TRANSFERENCIAS AUTOMATICAS', 'ATAU', 'AUTORIZACION DE TRANSFERENCIAS AUTOMATICAS')
insert into cl_ttransaccion values (713, 'BUSQUEDA DE DETALLE TRANSFERENCIAS AUTOMATICAS', 'BETA', 'BUSQUEDA DE DETALLE TRANSFERENCIAS AUTOMATICAS')
insert into cl_ttransaccion values (715, 'ACTUALIZACION DE DEFINICION TRANSFERENCIAS AUTOMATICAS', 'BETA', 'ACTUALIZACION DE DEFINICION TRANSFERENCIAS AUTOMATICAS')
insert into cl_ttransaccion values (716, 'ELIMINACION DE DEFINICION TRANSFERENCIAS AUTOMATICAS', 'BETA', 'ELIMINACION DE DEFINICION TRANSFERENCIAS AUTOMATICAS')
insert into cl_ttransaccion values (718, 'ELIMINACION DE DETALLE TRANSFERENCIAS AUTOMATICAS', 'BETA', 'ELIMINACION DE DETALLE TRANSFERENCIAS AUTOMATICAS')
insert into cl_ttransaccion values (723, 'AUMENTAR DIAS DE RETENCION PARA CANJE', 'ADRC', 'AUMENTAR DIAS DE RETENCION PARA CANJE')
insert into cl_ttransaccion values (698, 'CREACION DE ACCION NOTAS DEBITO', 'CAND', 'CREACION DE ACCION NOTAS DEBITO')
insert into cl_ttransaccion values (722, 'MARCACION DE SERVICIOS A CUENTAS', 'MASE', 'MARCACION DE SERVICIOS A CUENTAS')
insert into cl_ttransaccion values (727, 'TRANSMITIR MARCACION DE SERVICIOS A CUENTAS', 'TRMS', 'TRANSMITIR MARCACION DE SERVICIOS A CUENTAS')
insert into cl_ttransaccion values (447, 'CONSULTA CARTAS Y BANCOS CORRESPONSALES', 'CCBC', 'CONSULTA CARTAS Y BANCOS CORRESPONSALES')
insert into cl_ttransaccion values (606, 'CONSULTA CHEQUES REMESAS VIA BANCOS X OFICINA', 'CCBO', 'CONSULTA CHEQUES REMESAS VIA BANCOS X OFICINA')
insert into cl_ttransaccion values (607, 'CONSULTA TOTAL DE CHEQUES REMESAS VIA BANCOS X OFICINAS', 'CTCR', 'CONSULTA TOTAL DE CHEQUES REMESAS VIA BANCOS X OFICINAS')
insert into cl_ttransaccion values (150017, 'APROBACION CHEQ RECHAZADOS', 'ACHRE', 'APROBACION CHEQUES RECHAZADOS')

go

