
--BUEN DIA FAVOR DE APOYARNOS EN LA REASIGNACION DE LOS SIGUIENTES PROSPECTOS 
--ACTUALEMENTE SE ENCUENTRAN ASIGNADOS A CARLOS YOVANI HUERTA RETAMA Y SE 
--SOLICITA EL CAMBIO AL ASESOR EFREN GONZALEZ ORNELAS :
  --MARTINEZ ANTONIO CARITINA ID 16276
  --GONZALEZ MARTINEZ BERENICE ID 16181
--FAVOR DE REALIZAR CAMBIO DE ASESOR, ACTUALMENTE EL CLIENTE LO TRAE LA ASESORA 
--LILIANA LIBERTAD FIGUEROA MEDINA Y SE REASIGNARA AL ASESOR MARIO QUINTERO CASARRUBIAS.
  --MARIA DE JESUS BAHENA ID 10046

USE cobis
go

UPDATE cobis..cl_ente 
SET en_oficial    = 96,
    c_funcionario = 'egonzalezor',
    en_oficina    = 3354
WHERE en_ente in (16276,16181)

UPDATE cobis..cl_ente 
SET en_oficial    = 187,
    c_funcionario = 'mquintero',
    en_oficina    = 1032
WHERE en_ente in (10046)

go
