use cob_cartera
go
if exists (select 1 from sysobjects where name = 'ca_seguros_coka') 
   drop table ca_seguros_coka
go

create table  ca_seguros_coka(
sc_nro_poliza          varchar (30) null,
sc_anio_poliza         int          null,
sc_producto            varchar (30) null,
sc_buc                 varchar (20) null, 
sc_sucursal            varchar (70) null,
sc_nro_prestamo        varchar (24) null,
sc_nro_certificado     varchar (36) null,
sc_mes_emision         varchar (2)  null,
sc_fecha_endoso        varchar (10) null,
sc_fecha_efectiva      varchar (10) null,
sc_fecha_expiracion    varchar (10) null,
sc_long_cobertura      int          null,
sc_pais                varchar (10) null,
sc_moneda              varchar (10) null,
sc_vendedor            varchar (10) null,
sc_nombre_asegurado    varchar (40) null,
sc_apellido_paterno    varchar (16) null,
sc_apellido_materno    varchar (16) null,
sc_direccion1          varchar (100)null,
sc_direccion2          varchar (50) null,
sc_ciudad              varchar (64) null,
sc_estado              varchar (64) null,
sc_cod_postal          varchar (30) null,
sc_telefono            varchar (16) null,
sc_email               varchar (254)null,
sc_genero              CHAR (1)     null,
sc_rfc                 varchar (30) null,
sc_edad                int          null,
sc_fecha_nac           varchar (10) null,
sc_nombre_1            varchar (64) null,
sc_rfc_1               varchar (30) null,
sc_fecha_nac_1         varchar (10) null,
sc_sexo_1              varchar (1) null,
sc_porcentaje_1        varchar (45) null,
sc_nombre_2            varchar (64) null,
sc_rfc_2               varchar (30) null,
sc_fecha_nac_2         varchar (10) null,
sc_sexo_2              varchar (1) null,
sc_porcentaje_2        varchar (45) null,
sc_nombre_3            varchar (64) null,
sc_rfc_3               varchar (30) null,
sc_fecha_nac_3         varchar (10) null,
sc_sexo_3              varchar (1) null,
sc_porcentaje_3        varchar (45) null,
sc_cta_banco           varchar (45) null,
sc_seguro_vida         numeric(20,2) null,
sc_seguro_infarto_cer  numeric(20,2) null,
sc_seguro_infarto_mioc numeric(20,2) null,
sc_seguro_cancer       numeric(20,2) null,
sc_monto_prima         numeric(20,2) null,
sc_comision            numeric(20,2) null,
sc_tipo_seguro         varchar(16)   null
)
GO