/************************************************************************/
/*                 Descripcion                                          */
/*  Script para creacion de Codigos de Errores                          */
/************************************************************************/
/*                                                                      */
/*  Fecha         Autor               Comentario                        */
/*  07/07/2016    Oscar Saavedra      Instalador Version Davivienda     */
/************************************************************************/
use cobis
go

SET NOCOUNT ON
go

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

print '*****************************************'
print '*****  CREACION ERRORES PLAZO FIJO ******'
print '*****************************************'
print ''
print 'Inicio Ejecucion Creacion de Codigos de Errores Plazo Fijo : ' + convert(varchar(60),getdate(),109)
print ''

print '-->Errores Cobis: Insercion'
if exists (select 1 from cobis..cl_errores where numero between 140000 and 149999) begin
   delete
   from  cobis..cl_errores
   where numero between 140000 and 149999
end
go

insert into cobis..cl_errores values (141000, 0, 'ERROR EN ESTADO DE TRANSACCION')
insert into cobis..cl_errores values (141001, 0, 'NO SE AUTORIZA EL PAGO')
insert into cobis..cl_errores values (141002, 0, 'TRANSACCION NO CORRESPONDE A ESTE SERVIDOR')
insert into cobis..cl_errores values (141003, 0, 'NO EXISTE CUENTA PARA OFICINA')
insert into cobis..cl_errores values (141004, 0, 'OPERACION NO EXISTE O NO SE HA REVERSADO EN LA CAJA')
insert into cobis..cl_errores values (141005, 0, 'OPERACION NO ESTA VIGENTE')
insert into cobis..cl_errores values (141006, 0, 'CODIGO DE OFICINA EN OPERACION NO EXISTE')
insert into cobis..cl_errores values (141007, 0, 'OPERACION BLOQUEADA')
insert into cobis..cl_errores values (141008, 0, 'NO EXISTE TIPO DE OPERACION')
insert into cobis..cl_errores values (141009, 1, 'NO EXISTE INFORMACION EN CB_PARAMETRO')
insert into cobis..cl_errores values (141010, 0, 'OPERACION NO BLOQUEADA CONTRA EL TIPO DE BLOQUEO INGRESADO')
insert into cobis..cl_errores values (141011, 0, 'VALOR DEL MONTO NO PUEDE SER CERO O MENOR QUE CERO')
insert into cobis..cl_errores values (141012, 0, 'DATOS INCONSISTENTES')
insert into cobis..cl_errores values (141013, 0, 'MONEDA NO EXISTE')
insert into cobis..cl_errores values (141014, 0, 'OPERACION CON FONDOS EN RETENCION')
insert into cobis..cl_errores values (141015, 0, 'NO EXISTE TIPO DE BLOQUEO')
insert into cobis..cl_errores values (141016, 0, 'VCMTO DEBE SER MAYOR A FECHA ACTUAL')
insert into cobis..cl_errores values (141017, 0, 'ERROR EN EL SISTEMA DE ADMINISTRACION:  NO EXISTEN SERVIDORES')
insert into cobis..cl_errores values (141018, 0, 'ERROR EN CODIGO DE TRANSACCION')
insert into cobis..cl_errores values (141019, 0, 'TIPO DE BLOQUEO NO HA SIDO LEVANTADO PREVIAMENTE')
insert into cobis..cl_errores values (141020, 0, 'NO EXISTE TIPO DE DEFAULT')
insert into cobis..cl_errores values (141021, 0, 'ERROR EN TABLA DE FECHAS PROMEDIO')
insert into cobis..cl_errores values (141022, 0, 'NO EXISTE SERVICIO')
insert into cobis..cl_errores values (141023, 0, 'ERROR EN TABLA DE PERSONALIZACION DEFAULT')
insert into cobis..cl_errores values (141024, 0, 'ERROR EN TABLA DE PERSONALIZACION CONTRATADA')
insert into cobis..cl_errores values (141025, 0, 'ERROR EN LONGITUD DE OFICINA')
insert into cobis..cl_errores values (141026, 0, 'ERROR EN LONGITUD DE SECUENCIAL')
insert into cobis..cl_errores values (141027, 0, 'ERROR EN CALCULO DEL MODULO DEL DIGITO VERIFICADOR')
insert into cobis..cl_errores values (141028, 0, 'EL TITULAR ES MENOR DE EDAD')
insert into cobis..cl_errores values (141029, 0, 'OPERACION DE GERENCIA, EMISOR DEBE SER EL BANCO')
insert into cobis..cl_errores values (141030, 0, 'NO HAY MAS REGISTROS')
insert into cobis..cl_errores values (141031, 0, 'OPERACION NO ACTIVA O CANCELADA')
insert into cobis..cl_errores values (141032, 0, 'NO EXISTE DEPARTAMENTO')
insert into cobis..cl_errores values (141033, 0, 'NO EXISTE BANCO')
insert into cobis..cl_errores values (141034, 0, 'ERROR EN EL MODO DE LA TRANSACCION')
insert into cobis..cl_errores values (141035, 0, 'NO EXISTE OFICINA')
insert into cobis..cl_errores values (141036, 0, 'NO EXISTEN MAS REGISTROS')
insert into cobis..cl_errores values (141037, 0, 'VALOR DEBE SER MAYOR A CERO')
insert into cobis..cl_errores values (141038, 0, 'NO EXISTE CASILLA')
insert into cobis..cl_errores values (141039, 0, 'CODIGO DE TRANSACCION PARA DELETE NO VALIDO')
insert into cobis..cl_errores values (141040, 0, 'CODIGO DE TRANSACCION NO VALIDO')
insert into cobis..cl_errores values (141041, 0, 'TIPO DE PLAZO A CREAR YA EXISTE')
insert into cobis..cl_errores values (141042, 0, 'CODIGO DE PAGO A CREAR YA EXISTE')
insert into cobis..cl_errores values (141043, 0, 'TIPO DE MONTO A CREAR YA EXISTE')
insert into cobis..cl_errores values (141044, 0, 'NO EXISTE BENEFICIARIO')
insert into cobis..cl_errores values (141045, 0, 'BENEFICIARIO YA EXISTE')
insert into cobis..cl_errores values (141046, 0, 'NO EXISTE CASILLA')
insert into cobis..cl_errores values (141047, 0, 'NO EXISTE CUENTA CORRIENTE')
insert into cobis..cl_errores values (141048, 0, 'NO EXISTE CUENTA DE AHORROS')
insert into cobis..cl_errores values (141049, 0, 'NO EXISTE DIRECCION')
insert into cobis..cl_errores values (141050, 0, 'NO EXISTE ENTE')
insert into cobis..cl_errores values (141051, 0, 'NO EXISTE OPERACION DE PLAZO FIJO')
insert into cobis..cl_errores values (141052, 0, 'PRODUCTO NO EXISTE O NO VALIDO')
insert into cobis..cl_errores values (141053, 0, 'NO EXISTE TIPO DE MONTO. MONTO NO VALIDO')
insert into cobis..cl_errores values (141054, 0, 'NO EXISTE TIPO DE PLAZO')
insert into cobis..cl_errores values (141055, 0, 'NO EXISTE LA TASA')
insert into cobis..cl_errores values (141056, 0, 'NO EXISTE LA RENOVACION')
insert into cobis..cl_errores values (141057, 0, 'NO EXISTE EL CHEQUE')
insert into cobis..cl_errores values (141058, 0, 'FUNCIONARIO NO RELACIONADO')
insert into cobis..cl_errores values (141059, 0, 'NO EXISTE CL_CAPITALIZACION')
insert into cobis..cl_errores values (141060, 0, 'BENEFICIARIO NO SE PUEDE ELIMINAR PORQUE ES TITULAR')
insert into cobis..cl_errores values (141061, 0, 'RENOVACION YA EXISTE')
insert into cobis..cl_errores values (141062, 0, 'NO EXISTE FORMA DE PAGO/RECEPCION O ESTA ELIMINADO')
insert into cobis..cl_errores values (141063, 0, 'OPERACION DE PLAZO FIJO NO POSEE CHEQUES ASOCIADOS')
insert into cobis..cl_errores values (141064, 0, 'NO EXISTE RETENCION')
insert into cobis..cl_errores values (141065, 0, 'NO EXISTE LA PIGNORACION')
insert into cobis..cl_errores values (141066, 0, 'NO EXISTE EL PRESTAMO')
insert into cobis..cl_errores values (141067, 0, 'TOTAL A PIGNORAR EXCEDE EL MONTO DE LA OPERACION')
insert into cobis..cl_errores values (141068, 0, 'DEPOSITO SE ENCUENTRA PIGNORADO')
insert into cobis..cl_errores values (141069, 0, 'MONTO A BLOQUEAR MAYOR QUE MONTO DEL PLAZO FIJO')
insert into cobis..cl_errores values (141070, 0, 'NO EXISTE CATEGORIA DE DEPOSITOS')
insert into cobis..cl_errores values (141071, 0, 'NO EXISTE PERIODICIDAD DE PAGOS')
insert into cobis..cl_errores values (141072, 0, 'PERIODICIDAD DE PAGOS NO PUEDE SER NULA EN PAGOS PERIODICOS')
insert into cobis..cl_errores values (141073, 0, 'RANGO NO ES VALIDO')
insert into cobis..cl_errores values (141074, 0, 'YA EXISTE LA TASA')
insert into cobis..cl_errores values (141075, 0, 'NO EXISTE MOVIMIENTO MONETARIO')
insert into cobis..cl_errores values (141076, 0, 'NO EXISTE CONDICION')
insert into cobis..cl_errores values (141077, 0, 'NO EXISTE DETALLE DE CONDICION')
insert into cobis..cl_errores values (141078, 0, 'CONDICION YA EXISTE')
insert into cobis..cl_errores values (141079, 0, 'DETALLE DE CONDICION YA EXISTE')
insert into cobis..cl_errores values (141080, 1, 'NO SE PUDO INSERTAR CABECERA')
insert into cobis..cl_errores values (141081, 1, 'DEBITOS Y CREDITOS NO CONCUERDAN')
insert into cobis..cl_errores values (141082, 1, 'ERROR AL OBTENER CLAVE DE CONTA')
insert into cobis..cl_errores values (141083, 0, 'TRANSACCION NO ACEPTA MONTOS MENORES QUE CERO')
insert into cobis..cl_errores values (141084, 0, 'MOVIMIENTO MONETARIO YA FUE APLICADO')
insert into cobis..cl_errores values (141085, 0, 'MOVIMIENTO MONETARIO INCOMPLETO')
insert into cobis..cl_errores values (141086, 1, 'NO SE PUDO INSERTA ASIENTO CONTABLE')
insert into cobis..cl_errores values (141087, 0, 'MOVIMIENTO MONETARIO YA HA SIDO REVERSADO')
insert into cobis..cl_errores values (141088, 0, 'MONTO A DEBITAR EXCEDE LOS INTERESES')
insert into cobis..cl_errores values (141089, 0, 'DEPOSITO TIENE INTERESES PAGADOS')
insert into cobis..cl_errores values (141090, 0, 'NO EXISTE DEPOSITO O NO TIENE ESTADO DE INGRESADO')
insert into cobis..cl_errores values (141091, 0, 'CODIGO DE TRANSACCION PARA HELP NO VALIDO')
insert into cobis..cl_errores values (141092, 0, 'NO EXISTE TRAN_PRODUCTO')
insert into cobis..cl_errores values (141093, 0, 'OPERACION NO TIENE ESTADO POR CANCELAR')
insert into cobis..cl_errores values (141094, 0, 'EXISTEN MOVIMIENTOS DE CANCELACION APLICADOS')
insert into cobis..cl_errores values (141095, 0, 'NO EXISTE EMISION DE CHEQUE')
insert into cobis..cl_errores values (141096, 0, 'CHEQUE HA SIDO EMITIDO')
insert into cobis..cl_errores values (141097, 0, 'DEPOSITO NO ACEPTA MODIF. DE CAPITALIZACION')
insert into cobis..cl_errores values (141098, 0, 'DEPOSITO NO ACEPTA NUEVA FORMA DE PAGO')
insert into cobis..cl_errores values (141099, 0, 'DEPOSITO NO ACEPTA NUEVA PERIOCIDAD')
insert into cobis..cl_errores values (141100, 0, 'DEPOSITO NO ACEPTA NUEVA FECHA DE PAGODE INT.')
insert into cobis..cl_errores values (141101, 0, 'CAPITALIZACIONES PERIODICAS SE ACEPTAN SOLO EN APERTURA Y RENOVACION')
insert into cobis..cl_errores values (141102, 0, 'DEPOSITO NO ACEPTA CAMBIO DE DIA DE PAGO')
insert into cobis..cl_errores values (141103, 0, 'NO EXISTE COTIZACION PARA MONEDA')
insert into cobis..cl_errores values (141104, 0, 'NO EXISTE TRAN_CONTABLE')
insert into cobis..cl_errores values (141105, 0, 'EXISTEN TIPOS/DEPOSITOS RELACIONADOS CON EL PLAZO A ELIMINAR')
insert into cobis..cl_errores values (141106, 0, 'EXISTEN TIPOS/DEPOSITOS RELACIONADOS CON EL MONTO A ELIMINAR')
insert into cobis..cl_errores values (141107, 0, 'MONTO A DEBITAR EXCEDE PROVISION DE INTERESES')
insert into cobis..cl_errores values (141108, 0, 'SUMA DE LOS MONTOS DIFIERE DE INCREMENTO')
insert into cobis..cl_errores values (141109, 0, 'DEPOSITO CON CAPITALIZACION NO ACEPTA PAGO DE INTERESES ANTICIPADOS')
insert into cobis..cl_errores values (141110, 0, 'FORMA DE PAGO/RECEPCION A CREAR YA EXISTE')
insert into cobis..cl_errores values (141111, 0, 'NO EXISTE FORMA DE PAGO/RECEPCION O ESTA ELIMINADA')
insert into cobis..cl_errores values (141112, 0, 'OPERACION O TRANSACCION NO PERMITIDA')
insert into cobis..cl_errores values (141113, 0, 'AUTORIZACION PARA EL FUNCIONARIO A CREAR YA EXISTE')
insert into cobis..cl_errores values (141114, 0, 'AUTORIZACION PARA EL FUNCIONARIO NO EXISTE O ESTA ELIMINADO')
insert into cobis..cl_errores values (141115, 0, 'TIPO DE DEPOSITO NO EXISTE O ESTA DESHABILITADO')
insert into cobis..cl_errores values (141116, 0, 'TIPO DE DEPOSITO A CREAR YA EXISTE')
insert into cobis..cl_errores values (141117, 0, 'TIPO DE DEPOSITO SE ENCUENTRA EN TABLAS RELACIONADAS')
insert into cobis..cl_errores values (141118, 0, 'LIMITE DE NEGOCIACION A CREAR YA EXISTE')
insert into cobis..cl_errores values (141119, 0, 'LIMITE DE NEGOCIACION NO EXISTE')
insert into cobis..cl_errores values (141120, 0, 'AUXILIAR DE TIPO DE DEPOSITO A CREAR YA EXISTE')
insert into cobis..cl_errores values (141121, 0, 'AUXLIAR DE TIPO DE DEPOSITO NO EXISTE')
insert into cobis..cl_errores values (141122, 0, 'LIMITE NO AUTORIZADO PARA FUNCIONARIO U OFICINA')
insert into cobis..cl_errores values (141123, 0, 'NO EXISTE ESA MONEDA PARA TIPO DE DEPOSITO INGRESADO')
insert into cobis..cl_errores values (141124, 0, 'MONTO NO ESTA DENTRO DE UNO DEFINIDO PARA EL TIPO DE DEPOSITO')
insert into cobis..cl_errores values (141125, 0, 'PLAZO NO ESTA DENTRO DE UNO DEFINIDO PARA EL TIPO DE DEPOSITO')
insert into cobis..cl_errores values (141126, 0, 'NO HAY TASA DEFINIDA PARA TIPO DE DEPOSITO, PLAZO Y MONTO INGRESADOS')
insert into cobis..cl_errores values (141127, 0, 'NO EXISTE FUNCIONARIO INGRESADO')
insert into cobis..cl_errores values (141128, 0, 'NO EXISTE EL REGISTRO MONETARIO ASOCIADO')
insert into cobis..cl_errores values (141129, 0, 'EL VALOR DEL DETALLE DE LOS CHEQUES EXCEDE EL VALOR DEL MOV. MONETARIO ASOCIADO')
insert into cobis..cl_errores values (141130, 0, 'EL BENEFICIARIO NO EXISTE ASOCIADO AL DEPOSITO')
insert into cobis..cl_errores values (141131, 0, 'DEPOSITO YA TIENE UNA ACCION A SEGUIR')
insert into cobis..cl_errores values (141132, 0, 'NO EXISTE CANCELACION')
insert into cobis..cl_errores values (141133, 0, 'ESTADO NO VALIDO PARA REVERSO')
insert into cobis..cl_errores values (141134, 0, 'FUNCIONARIO NO TIENE AUTORIZACION')
insert into cobis..cl_errores values (141135, 0, 'YA EXISTE CANCELACION ASOCIADA AL DEPOSITO')
insert into cobis..cl_errores values (141136, 0, 'MONEDA NO ESTA REGISTRADA')
insert into cobis..cl_errores values (141137, 0, 'DEBE INGRESAR AUTORIZACION')
insert into cobis..cl_errores values (141138, 0, 'RENOVACION NO EXISTE')
insert into cobis..cl_errores values (141139, 1, 'RENOVACION YA EXISTE')
insert into cobis..cl_errores values (141140, 0, 'NO EXISTE DATO EN PARAMETRO')
insert into cobis..cl_errores values (141141, 0, 'TIEMPO DE REVERSO HA PASADO EL LIMITE')
insert into cobis..cl_errores values (141142, 0, 'NO EXISTE CUENTA RELACIONADA')
insert into cobis..cl_errores values (141143, 0, 'NO EXISTE OFICINA RELACIONADA')
insert into cobis..cl_errores values (141144, 0, 'NO HAY DISPONIBLE EN LA CUENTA')
insert into cobis..cl_errores values (141145, 1, 'NO EXISTE PARAMETRO EN CB_RELPARAM')
insert into cobis..cl_errores values (141146, 1, 'COMPROBANTE EN COMPRA/VENTA AFECTA ME')
insert into cobis..cl_errores values (141147, 1, 'NUMERO DE DETALLES NO COINCIDE')
insert into cobis..cl_errores values (141148, 0, 'NO SE PUEDE ELIMINAR PORQUE EXISTE STOCK')
insert into cobis..cl_errores values (141149, 0, 'NO SE PUEDE REALIZAR LA OPERACION PORQUE MANTIENE INVENTARIO')
insert into cobis..cl_errores values (141150, 0, 'NO SE PUEDE REALIZAR ESTA TRANSACCION SOBRE LA OPERACION')
insert into cobis..cl_errores values (141151, 0, 'NUMERO DE PREIMPRESO YA EXISTE')
insert into cobis..cl_errores values (141152, 0, 'TRANSACCION NO PERMITIDA. SE HAN INGRESADO VALORES EN CAJA, DEBEN REVERSARSE')
insert into cobis..cl_errores values (141153, 0, 'RECUERDE DEPOSITAR LOS FONDOS EN CAJA')
insert into cobis..cl_errores values (141154, 0, 'TRANSACCION NO PERMITIDA. LA FECHA DE ACTIVACION SOBREPASA UN DIA')
insert into cobis..cl_errores values (141155, 0, 'ERROR EN EJECUCION DE SP_RETIENE_CAPITAL: CLIENTE U OPERACION NO EXISTEN')
insert into cobis..cl_errores values (141156, 0, 'ERROR EN CODIGO DE CUENTA CONTABLE')
insert into cobis..cl_errores values (141157, 0, 'TRANSACCION NO PERMITIDA. OPERACION FUE REVERSADA')
insert into cobis..cl_errores values (141158, 0, 'TRANSACCION NO PERMITIDA. NO SE ENCUENTRA REGISTRO DE OPERACION ANTERIOR CANCELADA')
insert into cobis..cl_errores values (141159, 0, 'NO EXISTE VALOR DE TASA VARIABLE. COMUNICAR AL MODULO RESPONSABLE')
insert into cobis..cl_errores values (141160, 0, 'TRANSACCION NO PERMITIDA PARA ESTE TIPO DE DEPOSITO')
insert into cobis..cl_errores values (141161, 0, 'NO EXISTE INFORMACION DE CUPON')
insert into cobis..cl_errores values (141162, 0, 'NO SE PUEDE REVERSAR ESTA OPERACION, VALORES FUERON APLICADOS EN CAJA O CUENTAS CORRIENTES/AHORROS')
insert into cobis..cl_errores values (141163, 0, 'NO SE PUEDE CANCELAR CUPON, SE ENCUENTRA RETENIDO')
insert into cobis..cl_errores values (141164, 1, 'ERROR EN ESTADO DE CUPON')
insert into cobis..cl_errores values (141165, 1, 'ERROR EN BUSQUEDA DE TASA DE RETENCION DE IMPUESTOS')
insert into cobis..cl_errores values (141166, 1, 'ERROR EN REVERSO DE CHEQUES DE GERENCIA')
insert into cobis..cl_errores values (141167, 1, 'CONSUTA DE TASAS INVALIDA, TIPO TRANSACCION NO EXISTE')
insert into cobis..cl_errores values (141168, 1, 'ERROR AL ENVIAR LA INFORMACION A SERVICIOS BANCARIOS')
insert into cobis..cl_errores values (141169, 1, 'FORMA DE PAGO NO VALIDA PARA BRANCH')
insert into cobis..cl_errores values (141170, 1, 'NO SE ENCUENTRA COMPROBANTE CONTABLE')
insert into cobis..cl_errores values (141171, 1, 'NO SE PUEDE REGISTRAR GARANTIA YA QUE EL DEPOSITO SE ENCUENTRA RETENIDO')
insert into cobis..cl_errores values (141172, 1, 'EL DEP=SITO YA FUE APROBADO POR EL GERENTE')
insert into cobis..cl_errores values (141173, 1, 'EL USUARIO QUE QUIERE ANULAR EL DPF NO ES EL MISMO QUE REALIZ= LA APERTURA')
insert into cobis..cl_errores values (141174, 1, 'ERROR AL OBTENER EL SECUENCIAL DEL NÚMERO PREIMPRESO')
insert into cobis..cl_errores values (141175, 1, 'FECHA VALOR NO SE ENCUENTRA DENTRO PERIODO ANIO FISCAL')
insert into cobis..cl_errores values (141176, 1, 'BLOQUEO LEGAL NO EXISTE')
insert into cobis..cl_errores values (141177, 0, 'TRANSACCION NO PERMITIDA. CLIENTE CIFRADO ENTRE PROPIETARIOS.')
insert into cobis..cl_errores values (141178, 0, 'TRANSACCION NO PERMITIDA. MENOR DE EDAD ENTRE PROPIETARIOS.')
insert into cobis..cl_errores values (141179, 0, 'OPERACION ESTA PIGNORADA. NO SE PUEDE INGRESAR UN PROPIETARIO, MENOR DE EDAD.')
insert into cobis..cl_errores values (141180, 0, 'TRANSACCION NO PERMITIDA.  NO SE HA APROBADO EL DEPOSITO')
insert into cobis..cl_errores values (141181, 1, 'EL ESTADO DE LA OPERACION HA CAMBIADO FUERA DE LA PANTALLA ACTUAL')
insert into cobis..cl_errores values (141182, 0, 'NO EXISTEN AUTORIZACIONES PENDIENTES')
insert into cobis..cl_errores values (141183, 0, 'NO EXISTE LA OPERACIÓN DE CARTERA')
insert into cobis..cl_errores values (141184, 0, 'NO EXISTE LA TARJETA DE CREDITO')
insert into cobis..cl_errores values (141185, 0, 'LA AUTORIZACIÓN YA FUE UTILIZADA')
insert into cobis..cl_errores values (141186, 0, 'YA EXISTE UNA AUTORIZACIÓN PARA ESTA OPERACIÓN EN ESTA FECHA')
insert into cobis..cl_errores values (141187, 1, 'ERROR EN LA ACTUALIZACION DE LA AUTORIZACION DE SPREAD')
insert into cobis..cl_errores values (141188, 0, 'NO SE ENCUENTRA AREA CONTABLE PARA TIPO DE DEPOSITO')
insert into cobis..cl_errores values (141189, 0, 'LA CUENTA SE ENCUENTRA BLOQUEADA')
insert into cobis..cl_errores values (141190, 0, 'NO PUEDE REALIZAR INC/DIS CON FECHA MENOR A LA FECHA DE ULTIMO PAGO DE INTERESES O APERTURA')
insert into cobis..cl_errores values (141191, 0, 'NO ESTA PERMITIDA LA TRANSACCION PORQUE EL DEPOSITO POSEE UNA INSTRUCCION DE CANCELACION/RENOVACION.')
insert into cobis..cl_errores values (141194, 0, 'MONTO A INCREMENTAR NO CORRESPONDE A RECIBIDO EN CAJA')
insert into cobis..cl_errores values (141195, 1, 'NO EXISTEN REGISTROS QUE CUMPLAN LAS CONDICIONES DADAS')
insert into cobis..cl_errores values (141196, 0, 'SE HAN APLICADO MOVIMIENTOS MONETARIOS ANTES DE FECHA VALOR')
insert into cobis..cl_errores values (141197, 0, 'NO EXISTEN CHEQUES DEVUELTOS')
insert into cobis..cl_errores values (141198, 0, 'LA OPERACION TUVO UN INCREMENTO/DISMINUCION PREVIO')
insert into cobis..cl_errores values (141199, 0, 'NO EXISTE LA FRECUENCIA DE PAGO INGRESADA')
insert into cobis..cl_errores values (141200, 0, 'TRANSACCION NO PERMITIDA. LA OPERACION TIENE BLOQUEO LEGAL')
insert into cobis..cl_errores values (141201, 0, 'NO PUEDE CAMBIAR LA FECHA VALOR PORQUE REALIZO PAGO DE INTERESES')
insert into cobis..cl_errores values (141202, 0, 'NO PUEDE CAMBIAR LA FECHA VALOR EL DEPOSITO ESTA VENCIDO')
insert into cobis..cl_errores values (141203, 1, 'NO EXISTE INFORMACION DE LA OPERACION EN LA TABLA TEMPORAL')
insert into cobis..cl_errores values (141204, 0, 'TRANSACCION NO PERMITIDA. REVERSO SOLO SE PERMITE EL MISMO DIA DE TRANSACCION')
insert into cobis..cl_errores values (141205, 0, 'NO PUEDE CAMBIAR LA FECHA VALOR PORQUE REALIZO PAGO DE INTERESES ANTICIPADOS')
insert into cobis..cl_errores values (141206, 0, 'NO PUEDE CAMBIAR LA FECHA VALOR, EL DEPOSITO TIENE INTERESES PAGADOS')
insert into cobis..cl_errores values (141207, 1, 'NO SE HAN DEFINIDO DIAS DE INACTIVACION')
insert into cobis..cl_errores values (141208, 0, 'NO EXISTEN ORDENES DE PAGO A REVERSAR')
insert into cobis..cl_errores values (141209, 0, 'TRANSACCION NO PERMITIDA. RENOVACIÓN EJECUTADA POR EL BATCH')
insert into cobis..cl_errores values (141210, 0, 'TRANSACCION NO PERMITIDA. EL DPF NO TIENE RENOVACIONES PARA REVERSAR')
insert into cobis..cl_errores values (141211, 0, 'TRANSACCIO NO PERMITIDA. EL DPF NO TIENE INSTRUCCIONES DE RENOVACION PARA ELIMINAR')
insert into cobis..cl_errores values (141212, 0, 'TIPO DE DEPOSITO DESCONTINUADO')
insert into cobis..cl_errores values (141213, 0, 'LA FECHA DE PROCESO ES MENOR A LA FECHA VALOR DEL DPF')
insert into cobis..cl_errores values (141214, 0, 'NO EXISTE LA OPERACION DE COMERCIO EXTERIOR')
insert into cobis..cl_errores values (141215, 0, 'NO EXISTE LA OPERACION DE GARANTIA')
insert into cobis..cl_errores values (141216, 1, 'DEPOSITOS CON VUELTO NO PUEDEN VOLVER A ACTIVARSE')
insert into cobis..cl_errores values (141217, 0, 'VALORES DE INCREMENTO EN SUSPENSO INGRESADO EN INSTRUCCION NO HAN PASADO POR CAJA')
insert into cobis..cl_errores values (141218, 0, 'NO EXISTEN PAGOS PARA ESTA OPERACION')
insert into cobis..cl_errores values (141219, 0, 'NO SE PERMITE BLOQUEO LEGAL PORQUE EL DPF PERTENE A UN FIDEICOMISO')
insert into cobis..cl_errores values (141220, 0, 'NO SE HA INGRESADO EL VALOR ENVIADO POR EL JUZGADO')
insert into cobis..cl_errores values (141221, 0, 'NO SE HA INGRESADO EL VALOR QUE EL BANCO EMBARGARA')
insert into cobis..cl_errores values (141222, 0, 'NO SE HA INGRESADO UN TIPO DE BLOQUEO VALIDO')
insert into cobis..cl_errores values (141223, 0, 'NO SE HA INGRESADO LA FECHA DEL OFICIO')
insert into cobis..cl_errores values (141224, 0, 'NO SE HA INGRESADO EL NUMERO DEL OFICIO')
insert into cobis..cl_errores values (141225, 0, 'NO SE HA INGRESADO LA AUTORIDAD DEL OFICIO')
insert into cobis..cl_errores values (141226, 0, 'NO SE HA INGRESADO EL FUNCIONARIO QUE INGRESA EL OFICIO')
insert into cobis..cl_errores values (141227, 0, 'NO SE HA INGRESADO NO SE HA INGRESADO UN MOTIVO DE EMBARGO VALIDO')
insert into cobis..cl_errores values (141228, 0, 'LOS TITULOS CAPITALIZABLES NO PERMITEN CAMBIAR EL DETALLE DE PAGO INTERESES')
insert into cobis..cl_errores values (141229, 0, 'EL MONTO REAL A BLOQUEAR DEBE SER MENOR O IGUAL QUE EL MONTO DISPONIBLE')
insert into cobis..cl_errores values (141230, 0, 'DEPOSITO TIENE INSTRUCCION DE CANCELACION O RENOVACION. POR FAVOR LEVANTARLA')
insert into cobis..cl_errores values (141231, 0, 'DEPOSITO NO SE ENCUENTRA NI ACTIVO NI VENCIDO. POR FAVOR REVICE SU ESTADO')
insert into cobis..cl_errores values (141232, 0, 'EL PROPIETARIO DEL TIUTLO ES UNA FUNDACION')
insert into cobis..cl_errores values (141233, 0, 'DEBE INGRESAR UNA FORMA DE PAGO DE INTERESES AL TITULO')
insert into cobis..cl_errores values (141234, 0, 'ESA FORMA DE PAGO DE INTRESES NO ES VALIDA')
insert into cobis..cl_errores values (141235, 0, 'NO SE HA INGRESADO UNA DESCRIPCION DEL LEVANTAMIENTO LEGAL DEL EMBARGO')
insert into cobis..cl_errores values (141236, 0, 'NO SE HA INGRESADO EL NUMERO DE BLOQUEO DE EMBARGO A LEVANTAR')
insert into cobis..cl_errores values (141237, 0, 'ERROR EN LA CREACION DE DETALLE DEL PAGO DE INTERESES')
insert into cobis..cl_errores values (141238, 0, 'ERROR EN LA CREACION DEL EMBARGO LEGAL')
insert into cobis..cl_errores values (141239, 0, 'ERROR EN EL LEVANTAMINETO DEL EMBARGO LEGAL')
insert into cobis..cl_errores values (141240, 0, 'LA IDENTIFICACION DEL BENEFICIARIO NO ES VALIDA')
insert into cobis..cl_errores values (141241, 0, 'EL MONTO A EMBARGAR DEBE SER MENOR QUE EL DISPONIBLE A SER EMBARGADO')
insert into cobis..cl_errores values (141242, 0, 'EL MONTO A EMBARGAR DEBE SER IGUAL AL DISPONIBLE A SER EMBARGADO')
insert into cobis..cl_errores values (141243, 0, 'NO EXISTE PARAMETRO DE FORMA DE PAGO DE INTERESES DESPUES DE LEVANTAR EMBARGO')
insert into cobis..cl_errores values (141244, 0, 'NO EXISTE PARAMETRO DE FORMA DE PAGO DE INTERESES PARA EL EMBARGO LEGAL')
insert into cobis..cl_errores values (141245, 0, 'NO EXISTE PARAMETRO DE COMPONENTE INFLACCIONARIO ANIO GRAVABLE')
insert into cobis..cl_errores values (141246, 1, 'SE EMITIO LA ORDEN DE CANCELACION CON UNA FORMA DE PAGO DIFERENTE A EFECTIVO')
insert into cobis..cl_errores values (141247, 0, 'MONTO ESTA DENTRO DE UNO DEFINIDO PARA EL TIPO DE DEPOSITO')
insert into cobis..cl_errores values (141248, 0, 'PLAZO ESTA DENTRO DE UNO DEFINIDO PARA EL TIPO DE DEPOSITO')
insert into cobis..cl_errores values (141249, 0, 'NO SE HA INGRESADO EL NUMERO DEL TITULO')
insert into cobis..cl_errores values (141250, 0, 'NO SE HA INGRESADO EL CODIGO DEL BANCO DEL CHEQUE')
insert into cobis..cl_errores values (141251, 0, 'NO SE HA INGRESADO EL NUMERO DEL CHEQUE')
insert into cobis..cl_errores values (141252, 0, 'NO SE HA INGRESADO EL VALOR DEL CHEQUE')
insert into cobis..cl_errores values (141253, 0, 'NO EXISTE EMISION DE CHEQUE, NUMERO DE BANCO O NUMERO DE CHEQUE INVALIDO')
insert into cobis..cl_errores values (141254, 0, 'PAGOS EN EFECTIVO PENDIENTES DE REVERSAR EN BRANCH')
insert into cobis..cl_errores values (141255, 0, 'CLIENTE NO OBJETIVO')
insert into cobis..cl_errores values (141256, 0, 'SUCURSAL NO SE ENCUENTRA ACTIVA')
insert into cobis..cl_errores values (141257, 0, 'MODULO PLAZO FIJO NO SE ENCUENTRA EN ESTADO ACTIVO PARA ESTA OFICINA')
insert into cobis..cl_errores values (143000, 1, 'ERROR EN INSERCION DE TRANSACCION MONETARIA')
insert into cobis..cl_errores values (143001, 1, 'ERROR EN INSERCION DE OPERACION')
insert into cobis..cl_errores values (143002, 1, 'ERROR EN INSERCION DE ANULACION')
insert into cobis..cl_errores values (143003, 1, 'ERROR EN INSERCION DE REPORTE')
insert into cobis..cl_errores values (143004, 1, 'ERROR EN INSERCION DE RENOVACION')
insert into cobis..cl_errores values (143005, 1, 'ERROR EN INSERCION DE TRANSACCION DE SERVICIO')
insert into cobis..cl_errores values (143006, 1, 'ERROR EN INSERCION DE HISTORIAL')
insert into cobis..cl_errores values (143007, 1, 'ERROR EN INSERCION DE PIGNORACION')
insert into cobis..cl_errores values (143008, 1, 'ERROR EN INSERCION DE RETENCION')
insert into cobis..cl_errores values (143009, 1, 'ERROR EN INSERCION DE BENEFICIARIO')
insert into cobis..cl_errores values (143010, 1, 'ERROR EN INSERCION DE TASA')
insert into cobis..cl_errores values (143012, 1, 'ERROR EN INSERCION DE MONTO')
insert into cobis..cl_errores values (143013, 1, 'ERROR EN INSERCION DE RETENCION')
insert into cobis..cl_errores values (143014, 1, 'ERROR EN INSERCION DE PLAZO')
insert into cobis..cl_errores values (143016, 1, 'ERROR EN INSERCION DE CONDICION')
insert into cobis..cl_errores values (143017, 1, 'ERROR EN INSERCION DE DETALLE DE CONDICION')
insert into cobis..cl_errores values (143018, 1, 'ERROR EN INSERCION DE FORMA DE PAGO/RECEPCION')
insert into cobis..cl_errores values (143019, 1, 'ERROR EN INSERCION DE MOV_CONT')
insert into cobis..cl_errores values (143020, 1, 'ERROR EN INSERCION DE TRANSACCION MONETARIA')
insert into cobis..cl_errores values (143021, 1, 'ERROR EN INSERCION DE PPAGO')
insert into cobis..cl_errores values (143022, 1, 'ERROR EN INSERCION DE MOVIMIENTO MONETARIO')
insert into cobis..cl_errores values (143023, 1, 'ERROR EN INSERCION DE TRAN_PROD')
insert into cobis..cl_errores values (143024, 1, 'ERROR EN INSERCION DE TABLA PREIMPRESOS')
insert into cobis..cl_errores values (143028, 1, 'ERROR EN INSERCION DE CONDICIONTMP')
insert into cobis..cl_errores values (143029, 1, 'ERROR EN INSERCION DE DETALLE DE CONDICIONTMP')
insert into cobis..cl_errores values (143031, 1, 'ERROR EN INSERCION DE EMISION DE CHEQUE')
insert into cobis..cl_errores values (143032, 1, 'ERROR EN INSERCION DE MOVIMIENTO PENDIENTE')
insert into cobis..cl_errores values (143033, 1, 'ERROR EN INSERCION DE AUTORIZACIONES POR FUNCIONARIO')
insert into cobis..cl_errores values (143034, 1, 'ERROR EN INSERCION DE TIPOS DE DEPOSITOS')
insert into cobis..cl_errores values (143035, 1, 'ERROR EN INSERCION DE LIMITES DE NEGOCIACION')
insert into cobis..cl_errores values (143036, 1, 'ERROR EN INSERCION DE AUXILIARES DE TIPOS DE DEPOSITOS')
insert into cobis..cl_errores values (143037, 1, 'ERROR EN INSERCION DE DETALLE DE PAGO TEMPORAL')
insert into cobis..cl_errores values (143038, 1, 'ERROR EN INSERCION DE DETALLE DE PAGO')
insert into cobis..cl_errores values (143039, 1, 'ERROR EN INSERCION DE CANCELACION')
insert into cobis..cl_errores values (143040, 1, 'ERROR EN INSERCION DE AUTORIZACION')
insert into cobis..cl_errores values (143041, 1, 'ERROR EN INSERCION DE MOVIMIENTO CONTABLE')
insert into cobis..cl_errores values (143042, 1, 'ERROR EN INSERCION DE MOVIMIENTO MONETARIO CON PROBLEMA')
insert into cobis..cl_errores values (143043, 1, 'ERROR EN INSERCION DE DETALLE DE LOTE')
insert into cobis..cl_errores values (143044, 0, 'ERROR AL INSERTAR LA COTIZACION')
insert into cobis..cl_errores values (143045, 1, 'ERROR EN INSERCION DE TABLA DE TICKET MONETARIO')
insert into cobis..cl_errores values (143046, 1, 'ERROR EN INSERCION DE TABLA CONVERSION TICKET')
insert into cobis..cl_errores values (143047, 1, 'ERROR EN INSERCION DE TASA VARIABLE')
insert into cobis..cl_errores values (143048, 1, 'ERROR EN INSERCION DE ENDOSOS')
insert into cobis..cl_errores values (143049, 1, 'ERROR EN INSERCION DE CUPONES')
insert into cobis..cl_errores values (143050, 1, 'ERROR AL INGRESAR AL TEMPORAL DE CUSTODIA')
insert into cobis..cl_errores values (143051, 1, 'ERROR AL INGRESAR GARANTIA')
insert into cobis..cl_errores values (143052, 1, 'ERROR EN INSERCION DE TEMPORAL CLIENTE EXTERNO')
insert into cobis..cl_errores values (143053, 1, 'ERROR EN INSERCION DE LA INSTRUCCION ESPECIAL')
insert into cobis..cl_errores values (143054, 1, 'ERROR EN INSERCION DE RELACION DE COMPROBANTE')
insert into cobis..cl_errores values (143055, 1, 'ERROR EN INSERCION DE BLOQUEO LEGAL')
insert into cobis..cl_errores values (143056, 1, 'ERROR EN INSERCION DE CLIENTE EXTERNO DEFINITIVA')
insert into cobis..cl_errores values (143057, 1, 'ERROR EN INSERCI=N DE HIST=RICO DE TASAS')
insert into cobis..cl_errores values (143058, 1, 'ERROR EN INSERCI=N DE HIST=RICO DE TASAS VARIABLES')
insert into cobis..cl_errores values (143059, 1, 'ERROR EN INSERCION DE FIRMAS AUTORIZADAS')
insert into cobis..cl_errores values (143060, 1, 'NO EXISTE ORDEN EMITIDA PARA ESTA OPERACION')
insert into cobis..cl_errores values (143061, 0, 'ERROR INGRESO ENAJENACION')
insert into cobis..cl_errores values (143062, 1, 'ERROR COMPROBANTE CONTABLE ESTA DESCUADRADO')
insert into cobis..cl_errores values (143063, 0, 'ERROR EN GENERACION DE CUOTAS')
insert into cobis..cl_errores values (143064, 0, 'ERROR: TOTAL VALORES ENAJENADOS MAYOR A IMPUESTO RETENIDO')
insert into cobis..cl_errores values (143066, 1, 'ERROR INSERCCION PF_FERIADOS_OFICINA')
insert into cobis..cl_errores values (145000, 1, 'ERROR EN ACTUALIZACION DE TRANSACCION MONETARIA')
insert into cobis..cl_errores values (145001, 1, 'ERROR EN ACTUALIZACION DE OPERACION')
insert into cobis..cl_errores values (145002, 1, 'ERROR EN ACTUALIZACION DE ANULACION')
insert into cobis..cl_errores values (145003, 1, 'ERROR EN ACTUALIZACION DE REPORTE')
insert into cobis..cl_errores values (145004, 1, 'ERROR EN ACTUALIZACION DE RENOVACION')
insert into cobis..cl_errores values (145005, 1, 'ERROR EN ACTUALIZACION DE TRANSACCION DE SERVICIO')
insert into cobis..cl_errores values (145006, 1, 'ERROR EN ACTUALIZACION DE HISTORIAL')
insert into cobis..cl_errores values (145007, 1, 'ERROR EN ACTUALIZACION DE PIGNORACION')
insert into cobis..cl_errores values (145008, 1, 'ERROR EN ACTUALIZACION DE RETENCION')
insert into cobis..cl_errores values (145009, 1, 'ERROR EN ACTUALIZACION DE BENEFICIARIO')
insert into cobis..cl_errores values (145010, 1, 'ERROR EN ACTUALIZACION DE TASA')
insert into cobis..cl_errores values (145012, 1, 'ERROR EN ACTUALIZACION DE MONTO')
insert into cobis..cl_errores values (145014, 1, 'ERROR EN ACTUALIZACION DE PLAZO')
insert into cobis..cl_errores values (145015, 1, 'ERROR EN ACTUALIZACION DE CONVERSION')
insert into cobis..cl_errores values (145016, 1, 'ERROR EN ACTUALIZACION DE CONDICION')
insert into cobis..cl_errores values (145018, 1, 'ERROR EN ACTUALIZACION DE FORMA DE PAGO/RECEPCION')
insert into cobis..cl_errores values (145019, 1, 'ERROR EN ACTUALIZACION DE MOV_CONT')
insert into cobis..cl_errores values (145020, 1, 'ERROR EN ACTUALIZACION DE MOV_MONET')
insert into cobis..cl_errores values (145021, 1, 'ERROR EN ACTUALIZACION DE PPAGO')
insert into cobis..cl_errores values (145023, 1, 'ERROR EN ACTUALIZACION DE TRAN PROD')
insert into cobis..cl_errores values (145031, 1, 'ERROR EN ACTUALIZACION DE ORDEN DE PAGO')
insert into cobis..cl_errores values (145034, 1, 'ERROR EN ACTUALIZACION DE TIPO DE DEPOSITO')
insert into cobis..cl_errores values (145035, 1, 'ERROR EN ACTUALIZACION DE LIMITE DE NEGOCIACION')
insert into cobis..cl_errores values (145036, 1, 'ERROR EN ACTUALIZACION DE CANCELACION')
insert into cobis..cl_errores values (145037, 1, 'ERROR EN ACTUALIZACION DE DETALLE DE PAGO')
insert into cobis..cl_errores values (145038, 1, 'ERROR EN ACTUALIZACION DE DETALLE DE RCONDICION')
insert into cobis..cl_errores values (145039, 1, 'ERROR EN ACTUALIZACION DE PF_MOV_CONT')
insert into cobis..cl_errores values (145040, 1, 'ERROR EN ACTUALIZACION DE DETALLE DEL LOTE')
insert into cobis..cl_errores values (145041, 1, 'ERROR EN ACTUALIZACION DE CONVERSION TICKET')
insert into cobis..cl_errores values (145042, 1, 'ERROR EN ACTUALIZACION DE SECUENCIAL TICKET')
insert into cobis..cl_errores values (145043, 1, 'ERROR EN ACTUALIZACION DE CUPONES')
insert into cobis..cl_errores values (145044, 0, 'ERROR AL ACTUALIZAR LA COTIZACION')
insert into cobis..cl_errores values (145045, 1, 'ERROR EN ACTUALIZACION DE INSTRUCCIONES')
insert into cobis..cl_errores values (145046, 1, 'ERROR EN ACTUALIZACION DE EMISION CHEQUE')
insert into cobis..cl_errores values (145047, 1, 'ERROR EN ACTUALIZACION DE RELACION DE COMPROBANTES')
insert into cobis..cl_errores values (145048, 1, 'ERROR EN ACTUALIZACION DE COMPROBANTE CONTABLE')
insert into cobis..cl_errores values (145049, 1, 'ERROR EN ACTUALIZACION DE ESTADO DE FUSION-FRACCIONAMIENTO')
insert into cobis..cl_errores values (145050, 1, 'ERROR EN ACTUALIZACION DE HISTORICO DE TASAS')
insert into cobis..cl_errores values (145051, 1, 'ERROR EN ACTUALIZACION DE HISTORICO DE TASAS VARIABLES')
insert into cobis..cl_errores values (145052, 1, 'ERROR EN RECALCULO DE CUOTAS')
insert into cobis..cl_errores values (145053, 1, 'ERROR EN ACTUALIZACION DE PRIMERA CUOTA')
insert into cobis..cl_errores values (145054, 1, 'ERROR EN ACTUALIZACION DE ULTIMA CUOTA')
insert into cobis..cl_errores values (145055, 1, 'ERROR EN ACTUALIZACION DE MOVIMIENTO MONETARIO')
insert into cobis..cl_errores values (145056, 1, 'ERROR EN ACTUALIZACION DE LA INSTRUCCION ESPECIAL')
insert into cobis..cl_errores values (145057, 1, 'ERROR EN ACTUALIZACION DE DETALLE DE PAGO INCREMENTO RENOVACION')
insert into cobis..cl_errores values (145058, 1, 'ERROR EN ACTUALIZACION SECUENCIAL TICKET INCREMENTO RENOVACION')
insert into cobis..cl_errores values (145115, 1, 'NO EXISTE INFORMACION EN CONVERSION')
insert into cobis..cl_errores values (147000, 1, 'ERROR EN ELIMINACION DE TRANSACCION MONETARIA')
insert into cobis..cl_errores values (147001, 1, 'ERROR EN ELIMINACION DE OPERACION')
insert into cobis..cl_errores values (147002, 1, 'ERROR EN ELIMINACION DE ANULACION')
insert into cobis..cl_errores values (147003, 1, 'ERROR EN ELIMINACION DE REPORTE')
insert into cobis..cl_errores values (147004, 1, 'ERROR EN ELIMINACION DE RENOVACION')
insert into cobis..cl_errores values (147005, 1, 'ERROR EN ELIMINACION DE TRANSACCION DE SERVICIO')
insert into cobis..cl_errores values (147006, 1, 'ERROR EN ELIMINACION DE HISTORIAL')
insert into cobis..cl_errores values (147007, 1, 'ERROR EN ELIMINACION DE PIGNORACION')
insert into cobis..cl_errores values (147008, 1, 'ERROR EN ELIMINACION DE RETENCION')
insert into cobis..cl_errores values (147009, 1, 'ERROR EN ELIMINACION DE BENEFICIARIO')
insert into cobis..cl_errores values (147010, 1, 'ERROR EN ELIMINACION DE TASA')
insert into cobis..cl_errores values (147012, 1, 'ERROR EN ELIMINACION DE MONTO')
insert into cobis..cl_errores values (147013, 1, 'ERROR EN ELIMINACION DE RETENCION')
insert into cobis..cl_errores values (147014, 1, 'ERROR EN ELIMINACION DE PLAZO')
insert into cobis..cl_errores values (147016, 1, 'ERROR EN ELIMINACION DE CONDICION')
insert into cobis..cl_errores values (147017, 1, 'ERROR EN ELIMINACION DE DETALLE DE CONDICION')
insert into cobis..cl_errores values (147018, 1, 'ERROR EN ELIMINACION DE FORMAS DE PAGO/RECEPCION')
insert into cobis..cl_errores values (147020, 1, 'ERROR EN ELIMINACION DE MOVIMIENTO MONETARIO')
insert into cobis..cl_errores values (147021, 1, 'ERROR EN ELIMINACION DE PPAGO')
insert into cobis..cl_errores values (147023, 1, 'ERROR EN ELIMINACION DE TRAN_PROD')
insert into cobis..cl_errores values (147032, 1, 'ERROR EN ELIMINACION DE MOVIMIENTO PENDIENTE')
insert into cobis..cl_errores values (147033, 1, 'ERROR EN ELIMINACION DE AUTORIZACION POR FUNCIONARIO')
insert into cobis..cl_errores values (147034, 1, 'ERROR EN ELIMINACION DE TIPO DE DEPOSITO')
insert into cobis..cl_errores values (147035, 1, 'ERROR EN ELIMINACION DE LIMITE DE NEGOCIACION')
insert into cobis..cl_errores values (147036, 1, 'ERROR EN ELIMINACION DE AUXILIARES DE TIPOS DE DEPOSITOS')
insert into cobis..cl_errores values (147038, 1, 'ERROR EN ELIMINACION DE DETALLE DE PAGOS')
insert into cobis..cl_errores values (147039, 1, 'ERROR EN ELIMINACION DE MOVIMIENTOS MONETARIOS CON PROBLEMAS')
insert into cobis..cl_errores values (147040, 1, 'ERROR AL ELIMINAR LA COTIZACION')
insert into cobis..cl_errores values (147041, 1, 'ERROR AL ELIMINAR ORDEN DE PAGO')
insert into cobis..cl_errores values (147042, 1, 'ERROR AL ELIMINAR CUPONES')
insert into cobis..cl_errores values (147043, 1, 'ERROR AL ELIMINAR DEL TEMPORAL DE CUSTODIA')
insert into cobis..cl_errores values (147044, 1, 'ERROR AL ELIMINAR INSTRUCCION ESPECIAL')
insert into cobis..cl_errores values (148001, 0, 'RANGO DE PRORROGA A CREAR, YA EXISTE')
insert into cobis..cl_errores values (148002, 0, 'ERROR EN LA INSERCION DE RANGO DE PRORROGA')
insert into cobis..cl_errores values (148003, 0, 'NO EXISTE RANGO DE PRORROGA')
insert into cobis..cl_errores values (148004, 0, 'ERROR EN ACTUALIZACION DE RANGO DE PRORROGA')
insert into cobis..cl_errores values (148005, 0, 'EXISTEN TIPOS/DEPOSITOS RELACIONADOS CON LA PRORROGA A ELIMINAR')
insert into cobis..cl_errores values (148006, 0, 'ERROR EN ELIMINACION DE PLAZO')
insert into cobis..cl_errores values (148007, 0, 'YA EXISTE UN RANGO DE PRORROGA QUE CONTIENE A UNO DE LOS VALORES A INGRESAR')
insert into cobis..cl_errores values (148008, 0, 'YA EXISTE UN RANGO DE PLAZOS QUE SE ENCUENTRA DENTRO DEL RANGO INGRESADO')
insert into cobis..cl_errores values (148009, 0, 'RANGO MINIMO NO DEBE SER MAYOR AL RANGO MAXIMO')
insert into cobis..cl_errores values (148010, 0, 'PRORROGA ESTA ASOCIADA A UN TIPO DE AUXILIAR, ES NECESARIO DESASOCIAR ESTA ANTES DE LA ELIMINACION')
insert into cobis..cl_errores values (148011, 0, 'PRORROGA ESTA ASOCIADA A UN TASA, ES NECESARIO DESASOCIAR ESTA ANTES DE LA ELIMINACION')
insert into cobis..cl_errores values (148012, 0, 'PRORROGA ESTA ASOCIADA A UN TASA VARIABLE, ES NECESARIO DESASOCIAR ESTA ANTES DE LA ELIMINACION')
insert into cobis..cl_errores values (148013, 0, 'NO EXISTEN REGISTROS DE CARGA MASIVA DE TASAS')
insert into cobis..cl_errores values (148014, 0, 'ERROR EN LA INSERCION DE CABECERA DE CARGA MASIVA DE TASAS')
insert into cobis..cl_errores values (148015, 0, 'ERROR EN LA INSERCION DE DETALLE TEMPORAL DE CARGA MASIVA DE TASAS')
insert into cobis..cl_errores values (148016, 0, 'ERROR EN LA INSERCION DE DETALLE DE CARGA MASIVA DE TASAS')
insert into cobis..cl_errores values (148017, 0, 'FECHA DE VIGENCIA DE LA CARGA DE TASAS DEBE SER SUPERIOR A LA FECHA DE PROCESO')
insert into cobis..cl_errores values (148018, 0, 'ERROR EN EL TRUNCADO DE DETALLE TEMPORAL DE CARGA MASIVA DE TASAS')
insert into cobis..cl_errores values (148019, 0, 'ERROR EN EL TRUNCADO DE DETALLE DE CARGA MASIVA DE TASAS')
insert into cobis..cl_errores values (148020, 0, 'YA EXISTE UN ARCHIVO INGRESADO CON EL MISMO NOMBRE')
insert into cobis..cl_errores values (148021, 0, 'ERROR EN LA ACTUALIZACION DE ARCHIVOS CANCELADOS')
insert into cobis..cl_errores values (148022, 0, 'ERROR EN EL TRUNCADO DE LOG DE ERRORES DEL ARCHIVO')
insert into cobis..cl_errores values (148023, 0, 'TIPO DE MOMENTO NO EXISTE')
insert into cobis..cl_errores values (148024, 0, 'TIPO DE SEGMENTO NO EXISTE')
insert into cobis..cl_errores values (148025, 0, 'TIPO DE IVC NO EXISTE')
insert into cobis..cl_errores values (148026, 0, 'TASA MINIMA SUPERIOR A TASA MAXIMA')
insert into cobis..cl_errores values (148027, 0, 'TASA VIGENTE NO SE ENCUENTRA DENTRO DE LA TASA MINIMA Y MAXIMA')
insert into cobis..cl_errores values (148028, 0, 'ERROR EN LA ESTRUCTURA DEL ARCHIVO')
insert into cobis..cl_errores values (148029, 0, 'OPERADOR NO VALIDO')
insert into cobis..cl_errores values (148030, 0, 'ERROR EN LA ACTUALIZACION DE ESTADO DE REGISTROS')
insert into cobis..cl_errores values (148031, 0, 'NO COINCIDE RANGO INGRESADO CON EL TIPO DE MONTO')
insert into cobis..cl_errores values (148032, 0, 'NO COINCIDE RANGO INGRESADO CON EL TIPO DE PLAZO')
insert into cobis..cl_errores values (148033, 0, 'NO COINCIDE RANGO INGRESADO CON EL TIPO DE PRORROGA')
insert into cobis..cl_errores values (148034, 0, 'ERROR EN LA CAPTURA DE CADENA DE REGISTROS')
insert into cobis..cl_errores values (148035, 0, 'TASAS MINIMA O MAXIMA NULAS')
insert into cobis..cl_errores values (148036, 0, 'NO EXISTE ARCHIVO DE TASAS A CARGAR PARA LA ACTUAL FECHA')
insert into cobis..cl_errores values (148037, 0, 'LA ACTUAL TASA SE ENCUENTRA CONTENIDA DENTRO UN CARGUE DE TASA MASIVAS INGRESADO, POR FAVOR VALIDAR')
insert into cobis..cl_errores values (148038, 0, 'LA ACTUAL TASA SE ENCUENTRA CONTENIDA DENTRO UN CARGUE DE TASA MASIVAS APROBADO, POR FAVOR VALIDAR')
insert into cobis..cl_errores values (148039, 0, 'YA EXISTE UN ARCHIVO EN ESTADO APROBADO POR FAVOR RECHAZAR O APROBAR ESTE')
insert into cobis..cl_errores values (148040, 0, 'REGISTRO DE TASAS DUPLICADO')
insert into cobis..cl_errores values (149001, 1, 'LA SUMA DE LOS MONTOS RETENIDOS DIFIERE DEL MONTO BLOQ.')
insert into cobis..cl_errores values (149002, 1, 'ERROR AL EMITIR CAPITALIZACION')
insert into cobis..cl_errores values (149003, 1, 'ERROR AL EMITIR PAGO A CUENTA DE INTERESES')
insert into cobis..cl_errores values (149004, 1, 'ERROR AL EMITIR PAGO INT. A CUENTA DE BENEF.')
insert into cobis..cl_errores values (149005, 1, 'LA SUMA DE PORCENTAJES DE BENEF. DIFIERE DEL 100%')
insert into cobis..cl_errores values (149006, 1, 'OPERACION PIGNORADA NO SE PUEDE CANCELAR')
insert into cobis..cl_errores values (149007, 1, 'OPERACION BLOQUEADA NO SE PUEDE CANCELAR')
insert into cobis..cl_errores values (149008, 1, 'ERROR AL EMITIR PAGO DE CANCELACION')
insert into cobis..cl_errores values (149009, 1, 'LA SUMA DE LOS MONTOS A CANCELAR DIFIERE DEL TOTAL')
insert into cobis..cl_errores values (149010, 1, 'ERROR AL EMITIR NOTA DEB. CRED. EN RENOVACION')
insert into cobis..cl_errores values (149011, 1, 'LA SUMA DE LOS MONTOS EN RENOVACION DIFIERE DEL TOTAL')
insert into cobis..cl_errores values (149012, 1, 'ERROR EN NOTA C/D HACIA CUENTAS DE INVERSION.')
insert into cobis..cl_errores values (149013, 1, 'ERROR EN NOTA C/D HACIA CUENTAS CORRIENTES.')
insert into cobis..cl_errores values (149014, 1, 'ERROR EN NOTA C/D HACIA PLAZO FIJO')
insert into cobis..cl_errores values (149015, 0, 'ERROR PROCESO PAGO DE INTERESES')
insert into cobis..cl_errores values (149016, 1, 'ERROR PROCESO DE CANCELACION')
insert into cobis..cl_errores values (149017, 0, 'ERROR PROCESO RENOVACION')
insert into cobis..cl_errores values (149018, 1, 'ERROR AL EMITIR NOTA DEB. CRED. EN APERTURA')
insert into cobis..cl_errores values (149019, 1, 'LA SUMA DE LOS MONTOS EN APERTURA DIFIERE DEL TOTAL')
insert into cobis..cl_errores values (149020, 1, 'LA SUMA DE LOS PORCENTAJES EN APERTURA DIFIERE DE 100')
insert into cobis..cl_errores values (149021, 1, 'TRANSACCION-PRODUCTO NO DEFINIDA')
insert into cobis..cl_errores values (149022, 1, 'ERROR EN PROCESO DE APLICACION DE MOVIMIENTO')
insert into cobis..cl_errores values (149023, 1, 'ERROR EN PROCESO DE CALCULO DE INTERESES DIARIOS')
insert into cobis..cl_errores values (149024, 0, 'P I D: FECHA DE FIN DE DIA DIFERENTE DE INICIO')
insert into cobis..cl_errores values (149025, 0, 'P I D: FECHA DE INICIO MAYOR QUE FECHA ACTUAL')
insert into cobis..cl_errores values (149026, 0, 'P I D: FECHA DE FIN DIA MAYOR QUE FECHA ACTUAL')
insert into cobis..cl_errores values (149027, 0, 'P F D: FECHA DE INICIO DIFERENTE DE FECHA PROCESO')
insert into cobis..cl_errores values (149028, 0, 'P F D: FECHA FINAL MAYOR O IGUAL AL PROCESO')
insert into cobis..cl_errores values (149029, 0, 'P F D: PROCESO INICIO DE DIA NO SE HA EJECUTADO')
insert into cobis..cl_errores values (149030, 1, 'ERROR EN EMISION DE CHEQUE DE GERENCIA')
insert into cobis..cl_errores values (149031, 1, 'ERROR EN APLICACION DE MOV. PENDIENTE')
insert into cobis..cl_errores values (149032, 0, 'P CONT: ERROR AL APLICAR CONTABILIDAD')
insert into cobis..cl_errores values (149033, 0, 'P CONT: ERROR AL CREAR CABECERA CONTABLE')
insert into cobis..cl_errores values (149034, 0, 'P CONT: ERROR AL CREAR ASIENTO CONTABLE')
insert into cobis..cl_errores values (149035, 0, 'P CONT: DIFERENCIAS EN LOS TOTALES')
insert into cobis..cl_errores values (149036, 0, 'P CONT: DIFERENCIAS EN EL NUMERO DE ASIENTOS')
insert into cobis..cl_errores values (149037, 0, 'P CONT: ERROR AL CREAR COMPROBANTE CONTABLE')
insert into cobis..cl_errores values (149038, 0, 'P CONT: FECHA DE FINAL DE DIA DIFERENTE DE FECHA PROCESO')
insert into cobis..cl_errores values (149039, 0, 'P CONT: PROCESO YA FUE REALIZADO')
insert into cobis..cl_errores values (149040, 0, 'P CONT: ERROR EN PROCESO CONTABLE')
insert into cobis..cl_errores values (149041, 0, 'P REN AUT: ERROR AL APLICAR RENOVACION NEGOCIADA, ESTA HA DE SER ANULADA')
insert into cobis..cl_errores values (149042, 1, 'P INC: SUMA DE MONTOS MONETARIOS DIFIERE DE INCREMENTO')
insert into cobis..cl_errores values (149043, 1, 'P INC: FECHA PROXIMA ESTIMADA DIFIERE DE LA EXISTENTE')
insert into cobis..cl_errores values (149044, 1, 'P I D: ERROR AL APLICAR INCREMENTO DE CAPITAL')
insert into cobis..cl_errores values (149045, 1, 'P I P: FECHA NO ES FIN DE MES')
insert into cobis..cl_errores values (149046, 1, 'P I P: PROCESO DE FIN DE DIA YA FUE EJECUTADO')
insert into cobis..cl_errores values (149047, 1, 'P I P: PROCESO DE INICIO DE DIA YA FUE EJECUTADO')
insert into cobis..cl_errores values (149048, 1, 'P I P: PROCESO CONTABLE YA FUE EJECUTADO')
insert into cobis..cl_errores values (149049, 0, 'P I P: ERROR AL REALIZAR FIN DIA')
insert into cobis..cl_errores values (149050, 0, 'NO EXISTE PERFIL CONTABLE DEFINIDO PARA LA TRANSACCION')
insert into cobis..cl_errores values (149051, 0, 'NO EXISTE LA COTIZACION ESPECIFICA DESEADA')
insert into cobis..cl_errores values (149052, 1, 'PERIODO DE PAGO NO ES VALIDO')
insert into cobis..cl_errores values (149058, 1, 'RELACION DE TRANSACCION CON PERFIL CONTABLE YA EXISTE')
insert into cobis..cl_errores values (149064, 1, 'NO EXISTE INFORMACION EN CB_DET_PERFIL')
insert into cobis..cl_errores values (149065, 1, 'ERROR EN INSERCION DE AUTORIZACION DE SPREAD')
insert into cobis..cl_errores values (149066, 0, 'EL VALOR DE LA DISMINUCION ES MAYOR AL MONTO DISPONIBLE DEL DEPOSITO')
insert into cobis..cl_errores values (149078, 0, 'ERROR NO ENCONTRO CODIGO DE PERFIL DEFINIDO PARA LA TRANSACCION')
insert into cobis..cl_errores values (149079, 0, 'ERROR AL REALIZAR BATCH DE GENERACION DE CHEQUES DE GERENCIA')
insert into cobis..cl_errores values (149080, 0, 'ESTE TIPO DE DEPOSITO NO PERMITE CAMBIOS DE TASA.')
insert into cobis..cl_errores values (149081, 1, 'EL DOCUMENTO YA TIENE ESTE ESTADO DE CUSTODIA.')
insert into cobis..cl_errores values (149082, 1, 'EL ESTADO EN CUSTODIA NO PERMITE ESTA TRANSACCION.')
insert into cobis..cl_errores values (149083, 1, 'EL DEPOSITO NO TIENE SALDO DISPONIBLE PARA RETENCION.')
insert into cobis..cl_errores values (149084, 1, 'AUTORIZACION: USUARIO Y CLAVE INCORRECTO.')
insert into cobis..cl_errores values (149085, 1, 'AUTORIZACION: EL USUARIO NO TIENE ROL PARA ESTA TRANSACCION.')
insert into cobis..cl_errores values (149086, 1, 'NO SE LOGRA EJECUTAR DE MANERA CORRECTA EL PROCESO DE POSICION DE DIVISAS')
insert into cobis..cl_errores values (149087, 1, 'ERROR AL ACTUALIZAR MODULO DE GARANTIAS')
insert into cobis..cl_errores values (149088, 1, 'ERROR AL BORRAR TABLA MOVIMIENTOS DE COMPENSACION')
insert into cobis..cl_errores values (149089, 1, 'ERROR AL BORRAR TABLA ENCABEZADO DE COMPENSACION')
insert into cobis..cl_errores values (149090, 1, 'ERROR AL INSERTAR LOS DATOS A LA TABLA MOVIMIENTOS DE COMPENSACION')
insert into cobis..cl_errores values (149091, 1, 'ERROR AL INSERTAR LOS DATOS A LA TABLA ENCABEZADO MOVIMIENTOS DE COMPENSACION')
insert into cobis..cl_errores values (149092, 1, 'ERROR EN ELIMINACI¢N DE BLOQUEO LEGAL')
insert into cobis..cl_errores values (149093, 0, 'CORRESPONSAL NO ENCONTRADO')
insert into cobis..cl_errores values (149094, 0, 'NO EXISTEN DATOS')
insert into cobis..cl_errores values (149095, 1, 'ERROR EN CONSULTA DE SIGUIENTE SECUENCIAL DE LA TABLA DE FUNCIONARIOS')
insert into cobis..cl_errores values (149096, 0, 'ESTE TIPO DE DEPOSITO NO PERMITE AUMENTOS/DISMINUCIONES.')
insert into cobis..cl_errores values (149097, 1, 'NO SE PERMITE LA TRANSACCIÓN PORQUE EL DEPÓSITO ESTÁ INACTIVO')
insert into cobis..cl_errores values (149098, 0, 'ERROR EN APLICACION DE PAGO A PRESTAMO')
insert into cobis..cl_errores values (149099, 0, 'ERROR EN PROCESO DE FECHA VALOR PRESTAMO')
insert into cobis..cl_errores values (149100, 0, 'ERROR DESCUADRE DE INTERESES GANADOS CONTRA LOS INTERESES ESTIMADOS')
insert into cobis..cl_errores values (149101, 0, 'ERROR INGRESE EL PLAZO CORRECTO DE OVERNIGHT')
insert into cobis..cl_errores values (149102, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_OPERACION')
insert into cobis..cl_errores values (149103, 0, 'ERROR ACTUALIZANDO TS_OPERACION')
insert into cobis..cl_errores values (149104, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_MOV_MONET')
insert into cobis..cl_errores values (149105, 0, 'ERROR ACTUALIZANDO TS_MOV_MONET')
insert into cobis..cl_errores values (149106, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_DET_PAGO')
insert into cobis..cl_errores values (149107, 0, 'ERROR ACTUALIZANDO TS_DET_PAGO')
insert into cobis..cl_errores values (149108, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_RENOVACION')
insert into cobis..cl_errores values (149109, 0, 'ERROR ACTUALIZANDO TS_RENOVACION')
insert into cobis..cl_errores values (149110, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_CANCELACION')
insert into cobis..cl_errores values (149111, 0, 'ERROR ACTUALIZANDO TS_CANCELACION')
insert into cobis..cl_errores values (149112, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_CUOTAS')
insert into cobis..cl_errores values (149113, 0, 'ERROR ACTUALIZANDO TS_CUOTAS')
insert into cobis..cl_errores values (149114, 0, 'ERROR ACTUALIZANDO COB_PFIJO..PF_AUTORIZACION')
insert into cobis..cl_errores values (149115, 0, 'ERROR INSERTANDO COB_SBANCARIOS..TS_INVENTARIO_INS')
insert into cobis..cl_errores values (149116, 0, 'ERROR ACTUALIZANDO COB_SBANCARIOS..SB_INVENTARIO_INS')
insert into cobis..cl_errores values (149117, 0, 'ERROR ACTUALIZANDO COB_SBANCARIOS..TS_PUNTOS_REORDEN')
insert into cobis..cl_errores values (149118, 0, 'ERROR ACTUALIZANDO COB_SBANCARIOS..SB_PUNTOS_REORDEN')
insert into cobis..cl_errores values (149119, 0, 'ERROR ACTUALIZANDO COB_SBANCARIOS..SB_IMPRESION_LOTES')
insert into cobis..cl_errores values (149120, 0, 'ERROR ACTUALIZANDO COBIS..CL_TRASLADO_DETALLE')
insert into cobis..cl_errores values (149121, 0, 'CODIGO DE FRECUENCIA YA EXISTE')
insert into cobis..cl_errores values (149122, 0, 'NO SE PUEDE BORRAR FRECUENCIA, TIENE RELACION CON TIPO DE DEPOSITO EXISTENTE')
go

print ''
print 'Fin Ejecucion Creacion de Codigos de Errores Plazo Fijo : ' + convert(varchar(60),getdate(),109)
print ''
