/*************************************************** BusinessRules ***************************************************/
use cobis
go

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

declare @w_id_menu int,@w_moneda tinyint, @w_id_producto int,@w_tipo varchar(20)
select @w_id_menu 	= me_id from cobis..cew_menu where me_name = 'MNU_GROUP_ADMINISTRATION'
select @w_id_producto	= pd_producto from cobis..cl_producto where pd_abreviatura='CWF' --43
select @w_tipo		= 'R'
select @w_moneda   	= 0

print 'Sistemas y Subtipos'

insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcess',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcessByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryBynombreTablaPage',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryVariablePseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryUsersPseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                    
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                             
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.InsertSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.UpdateSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.InsertSystemRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.UpdateSystemRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByCode',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSystemRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryBySubtypeToDelete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.RemoveSystemRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.RemoveSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryBySystemToDelete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.QueryAllSubtypesRules',@w_id_producto,@w_tipo,@w_moneda)                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.QueryAllSystems',@w_id_producto,@w_tipo,@w_moneda)                                                                                                             
insert into cew_menu_service values(@w_id_menu,'CEW.Preferences.getUserPreferences',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'CEW.Official.GetOfficialInfo',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'CEW.Favorites.getUserFavorites',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.DeleteExceptionById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.FindAllExceptions',@w_id_producto,@w_tipo,@w_moneda)                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.GetExceptionById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.InsertException',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.UpdateException',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.FindResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.InsertResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.RemoveResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.UpdateResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionActiveByRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionByRulesVersion',@w_id_producto,@w_tipo,@w_moneda)                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.FindByIdAndATable',@w_id_producto,@w_tipo,@w_moneda)                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryOtherRuleByStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryTypesInRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRuleAndStatusList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatusList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryRuleVersionActive',@w_id_producto,@w_tipo,@w_moneda)                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.Count',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAllByPage',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryByCodigo',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                  
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryOtherVariables',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryByTypeAndSubtype',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryPoliciesInRules',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RulesVerionManager.QueryAllRules',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Menu.getMenuByRole',@w_id_producto,@w_tipo,@w_moneda)

go

use cobis
go

declare @w_id_menu int,@w_moneda tinyint, @w_id_producto int,@w_tipo varchar(20)
select @w_id_menu 	= me_id from cobis..cew_menu where me_name = 'MNU_VARIABLES_PROGRAMS'
select @w_id_producto	= pd_producto from cobis..cl_producto where pd_abreviatura='CWF' --43
select @w_tipo		= 'R'
select @w_moneda   	= 0

print 'Variables y Programas'

insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcess',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcessByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryBynombreTablaPage',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryVariablePseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryUsersPseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                    
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryByIdProgram',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryAllProgram',@w_id_producto,@w_tipo,@w_moneda)                                                                                                             
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryVariableTypes',@w_id_producto,@w_tipo,@w_moneda)                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryVariableSubTypes',@w_id_producto,@w_tipo,@w_moneda)                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryVariableByTypeAndSubType',@w_id_producto,@w_tipo,@w_moneda)                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSystemByAcronym',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSubTypeByAcronym',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.DeleteExceptionById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.FindAllExceptions',@w_id_producto,@w_tipo,@w_moneda)                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.GetExceptionById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.InsertException',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.UpdateException',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.FindResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.InsertResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.RemoveResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.UpdateResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionActiveByRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionByRulesVersion',@w_id_producto,@w_tipo,@w_moneda)                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.FindByIdAndATable',@w_id_producto,@w_tipo,@w_moneda)                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryOtherRuleByStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryTypesInRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRuleAndStatusList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatusList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryRuleVersionActive',@w_id_producto,@w_tipo,@w_moneda)                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.Count',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAllByPage',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryByCodigo',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                  
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryOtherVariables',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryByTypeAndSubtype',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryPoliciesInRules',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RulesVerionManager.QueryAllRules',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'CEW.Favorites.getUserFavorites',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Official.GetOfficialInfo',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Preferences.getUserPreferences',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Menu.getMenuByRole',@w_id_producto,@w_tipo,@w_moneda)


go

use cobis
go

declare @w_id_menu int,@w_moneda tinyint, @w_id_producto int,@w_tipo varchar(20)
select @w_id_menu 	= me_id from cobis..cew_menu where me_name = 'MNU_EDITOR_POLITICAS'
select @w_id_producto	= pd_producto from cobis..cl_producto where pd_abreviatura='CWF' --43
select @w_tipo		= 'R'
select @w_moneda   	= 0

print 'Editor de Politicas'

insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                    
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcess',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcessByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryBynombreTablaPage',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryVariablePseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryUsersPseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                    
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRuleAndStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryActiveRulesByType',@w_id_producto,@w_tipo,@w_moneda)                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.Simulate',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Rules.Admin.RulesAdmin.QueryRuleDependence',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.ConditionRuleQueryManager.QueryConditionRuleTree',@w_id_producto,@w_tipo,@w_moneda)                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySubTypeBySystem',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByCode',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySystems',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                    
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.CatalogAdmManager.FindSystemsByType',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.GetRuleRoleDetList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySubTypesInRuleBySystem',@w_id_producto,@w_tipo,@w_moneda)                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.DeleteExceptionById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.FindAllExceptions',@w_id_producto,@w_tipo,@w_moneda)                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.GetExceptionById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.InsertException',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.UpdateException',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.FindResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.InsertResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.RemoveResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.UpdateResultPolicies',@w_id_producto,@w_tipo,@w_moneda)                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                              
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionActiveByRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                     
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionByRulesVersion',@w_id_producto,@w_tipo,@w_moneda)                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.FindByIdAndATable',@w_id_producto,@w_tipo,@w_moneda)                                                                                                               
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryOtherRuleByStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryTypesInRule',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRuleAndStatusList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatus',@w_id_producto,@w_tipo,@w_moneda)                                                                                                            
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatusList',@w_id_producto,@w_tipo,@w_moneda)                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryRuleVersionActive',@w_id_producto,@w_tipo,@w_moneda)                                                                                                   
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.Count',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                          
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAllByPage',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryByCodigo',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                  
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryOtherVariables',@w_id_producto,@w_tipo,@w_moneda)                                                                                                         
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryByTypeAndSubtype',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryPoliciesInRules',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RulesVerionManager.QueryAllRules',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                       
insert into cew_menu_service values(@w_id_menu,'CEW.Preferences.getUserPreferences',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                      
insert into cew_menu_service values(@w_id_menu,'CEW.Official.GetOfficialInfo',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'CEW.Favorites.getUserFavorites',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Menu.getMenuByRole',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                    

go

use cobis
go

declare @w_id_menu int,@w_moneda tinyint, @w_id_producto int,@w_tipo varchar(20)
select @w_id_menu 	= me_id from cobis..cew_menu where me_name = 'MNU_BUSSINESS_RULES_ADMIN'
select @w_id_producto	= pd_producto from cobis..cl_producto where pd_abreviatura='CWF' --43
select @w_tipo		= 'R'
select @w_moneda   	= 0

print 'Seguridades de Reglas y Politicas'
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRole.DeleteRuleRole',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRole.FindAllRoles',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRole.InsertRuleRole',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRole.UpdateRuleRole',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRoleDet.DeleteRuleRoleDetail',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRoleDet.InsertRuleRoleDetail',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRoleDet.queryRuleRolDescription',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Commons.Security.RuleRoleDet.queryRuleRolDescription1',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.CatalogAdmManager.FindSystemsByType',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ConditionRuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.DeleteExceptionById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.FindAllExceptions',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.GetExceptionById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.InsertException',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Exceptions.Services.UpdateException',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindAllSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSystemRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.InsertSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.InsertSystemRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.QueryAllSubtypesRules',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.QueryAllSystems',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.RemoveSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.RemoveSystemRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.UpdateSubTypeRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.UpdateSystemRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.ProgramaAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.FindResultPolicies',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.InsertResultPolicies',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.RemoveResultPolicies',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Result.Policies.Services.UpdateResultPolicies',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.RuleVersionAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.Create',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.Delete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.DeleteList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.Save',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.VariableAdmManager.SaveList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionActiveByRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ConditionRuleManager.QueryAllConditionByRulesVersion',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.ConditionRuleQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.ConditionRuleQueryManager.QueryByRuleVersion',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.ConditionRuleQueryManager.QueryConditionRuleTree',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.GetRuleRoleDetList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.GetRuleRoleDetListRight',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryActiveRules',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryActiveRulesByType',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryByType',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryByTypeAndSubtype',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryByTypeAndSubtypeBySystem',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryOtherRuleByStatus',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryRulesByTypeAndSubType',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySubTypeBySystem',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySubTypesInRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySubTypesInRuleBySystem',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QuerySystems',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryTypesInRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.QueryTypesInRuleByRol',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.UpdateRuleRolDetail',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRule',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRuleAndStatus',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByRuleAndStatusList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatus',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryByStatusList',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleVersionQueryManager.QueryRuleVersionActive',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.Count',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryAllByPage',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryByCodigo',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryBynombreTabla',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.TablaQueryManager.QueryBynombreTablaPage',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryAll',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryAllProgram',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryByIdProgram',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryOtherVariables',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryVariableByTypeAndSubType',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryVariableSubTypes',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.VariableQueryManager.QueryVariableTypes',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.Generate',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.List<Rule> queryByType',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryAllRules',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryByTypeAndSubtype',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryByTypeAndSubtypeAndSystem',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.Simulate',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RulesVerionManager.QueryAllRules',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryPoliciesInRules',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryBySystemToDelete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.RuleManager.QueryBySubtypeToDelete',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.ProgramaAdmManager.FindById',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.FindByIdAndATable',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.FindByProductAndActive',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.FindRuleActiveByAcronym',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Rules.Admin.RulesAdmin.QueryRuleDependence',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.CountTotalCatalog',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.CountTotalCatalogWithParam',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalog',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByCode',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByCodeWithParam',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByDescription',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogByDescriptionWithParam',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Cobis.Commons.Services.QueryCatalogWithParam',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'AddressTxService.getAddressesbyCustomer',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSystemByAcronym',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Adm.Groupingrules.Services.FindSubTypeByAcronym',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'Bpl.Rules.Engine.Query.RuleQueryManager.updateRuleRoleDetailBySystemAndOrSubtype',@w_id_producto,@w_tipo,@w_moneda) 
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcess',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                        
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryCatalogProcessByDescription',@w_id_producto,@w_tipo,@w_moneda)                                                                                                           
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryVariablePseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                 
insert into cew_menu_service values(@w_id_menu,'Workflow.Admin.WorkflowAdmin.QueryUsersPseudoCatalog',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                    
insert into cew_menu_service values(@w_id_menu,'UCSP.Admin.Administration.GetAllRoleAssociatesVCC',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Preferences.getUserPreferences',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Official.GetOfficialInfo',@w_id_producto,@w_tipo,@w_moneda)                                                                                                                                            
insert into cew_menu_service values(@w_id_menu,'CEW.Favorites.getUserFavorites',@w_id_producto,@w_tipo,@w_moneda)
insert into cew_menu_service values(@w_id_menu,'CEW.Menu.getMenuByRole',@w_id_producto,@w_tipo,@w_moneda)

go
