//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 02:47:53 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/EstadoCuenta", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cobiscorp.cloud.xmlgenerator.dto.jaxb;
