use cobis    
go

print 'cl_errores'
/**************************/
/*   BATCH                */
/**************************/
delete cl_errores where numero between 800000 and 809999
go

delete cl_errores
 where numero between 108000 and 108002
    or numero between 151160 and 151164
    or numero in (153068, 155062, 157091, 103007)
go

/* * * * * *  NUEVOS ERRORES MODULO SEGURIDAD * * * * */
insert into cl_errores values (103007, 1, 'Error en creación de direccion')
insert into cl_errores values (108000, 1, 'ERROR EN INSERCION EN BA_LOG_OPERADOR')
insert into cl_errores values (108001, 0, 'NO EXISTE OPERADOR AUTORIZADO!')
insert into cl_errores values (108002, 0, 'OPERACION INEXISTENTE!')
insert into cl_errores values (151160, 0, 'No existe usuario o usuario no está vigente')
insert into cl_errores values (151161, 0, 'No existe parámetro de rol de operador de batch')
insert into cl_errores values (151162, 0, 'El usuario no posee rol de operador de batch')
insert into cl_errores values (151163, 0, 'Ya existe operador de batch')
insert into cl_errores values (151164, 0, 'No existe operador de batch')
insert into cl_errores values (153068, 0, 'Error en inserción de operador de batch')
insert into cl_errores values (155062, 0, 'Error en actualización de operador de batch')
insert into cl_errores values (157091, 0, 'Error en eliminación de operador de batch')
go 

/*  Errores de existencia  */
print 'Errores de existencia'
go
insert into cl_errores values (801001, 0, 'Campos NOT NULL con valores NULL')
insert into cl_errores values (801004, 0, 'código de batch ya existente')
insert into cl_errores values (801005, 0, 'El código del lote ya existe')
insert into cl_errores values (801007, 0, 'Código de parametro ya existe')
insert into cl_errores values (801008, 0, 'No existen parámetros')
insert into cl_errores values (801009, 0, 'No existen mas parámetros')
insert into cl_errores values (801029, 0, 'No existen procesos batch que cumplan la condición')
insert into cl_errores values (801030, 0, 'No existen lotes que cumplan la condición')
insert into cl_errores values (801031, 0, 'No existen procesos batch asociados a este lote')
insert into cl_errores values (801032, 0, 'No existen mas procesos asociados')
insert into cl_errores values (801041, 0, 'El código del lote_batch ya existe')
insert into cl_errores values (801042, 0, 'El código del batch no existe')
insert into cl_errores values (801043, 0, 'El código del lote no existe')
insert into cl_errores values (801044, 0, 'Secuencial ya existente en el lote')
insert into cl_errores values (801077, 0, 'No corresponde tipo de transacción')
insert into cl_errores values (801078, 0, 'Código de dependencia no existe o no es inferior')
insert into cl_errores values (801079, 0, 'Batch no existe en el LOG')
insert into cl_errores values (801080, 0, 'No existen registros de ejecucion que cumplan la condición')
insert into cl_errores values (801081, 0, 'No existe el log')
insert into cl_errores values (801082, 0, 'Ya existe el control de acceso para el código ingresado')                            
insert into cl_errores values (801083, 0, 'No existen mas roles')
insert into cl_errores values (801084, 0, 'No existen mas códigos de login')                            
insert into cl_errores values (801085, 0, 'No existe la fecha de proceso')                            
insert into cl_errores values (803002, 0, 'Error en actualización en la tabla temporal de sarta batch')
insert into cl_errores values (803003, 0, 'Error en la creación del lote')
insert into cl_errores values (803004, 0, 'Error en inserción de parametro')
insert into cl_errores values (803005, 0, 'Error en inserción de control de acceso')
insert into cl_errores values (803006, 0, 'Error en inserción temporal de sarta')
insert into cl_errores values (803007, 0, 'Error en inserción temporal de sarta-batch')
insert into cl_errores values (803008, 0, 'Error en inserción temporal de enlaces')
insert into cl_errores values (803009, 0, 'Error en inserción temporal de parámetros')
insert into cl_errores values (803010, 0, 'Error en inserción final de sarta')
insert into cl_errores values (803011, 0, 'Error en inserción final de sarta-batch')
insert into cl_errores values (803012, 0, 'Error en inserción final de enlaces')
insert into cl_errores values (803013, 0, 'Error en inserción final de parámetros')
insert into cl_errores values (803030, 0, 'Error en la inserción del lote_batch')
insert into cl_errores values (803032, 0, 'Error en la creación de la transacción de servicio')
insert into cl_errores values (805013, 0, 'Código del batch a actualizar no existe')
insert into cl_errores values (805014, 0, 'El lote a modificar no existe')
insert into cl_errores values (805015, 0, 'Parametro a actualizar no existe')
insert into cl_errores values (805016, 0, 'Error en actualización de parametro')
insert into cl_errores values (805033, 0, 'Error en la actualización del batch')
insert into cl_errores values (805034, 0, 'Error en la actualización del lote')
insert into cl_errores values (805035, 0, 'Error en la actualización del lote-batch')
insert into cl_errores values (805036, 0, 'Control de acceso para código ingresado no existe')
insert into cl_errores values (805037, 0, 'Error en la actualización de la fecha de proceso')
insert into cl_errores values (807021, 0, 'El batch a eliminar no existe')
insert into cl_errores values (807022, 0, 'El código del batch esta relacionado con ba_log')
insert into cl_errores values (807023, 0, 'El batch posee parámetros')
insert into cl_errores values (807024, 0, 'Error en la eliminación del batch')
insert into cl_errores values (807025, 0, 'Parametro a eliminar no existe')
insert into cl_errores values (807026, 0, 'Error en la eliminación de parámetro')
insert into cl_errores values (807027, 0, 'El batch esta relacionado a algún lote')
insert into cl_errores values (807030, 0, 'El lote a eliminar no existe')
insert into cl_errores values (807031, 0, 'El código del lote esta relacionado en lote_batch')
insert into cl_errores values (807032, 0, 'El lote posee procesos batch con parámetros')
insert into cl_errores values (807033, 0, 'Error en la eliminación del lote')
insert into cl_errores values (807040, 0, 'El código del lote_batch no existe')
insert into cl_errores values (807041, 0, 'Error en la eliminación del lote_batch')
insert into cl_errores values (807042, 0, 'Error en la actualización de la secuencialidad de los procesos')
insert into cl_errores values (807043, 0, 'Existen parámetros asociados a este lote batch')
insert into cl_errores values (807044, 0, 'Existen procesos batch que dependen del registro a eliminar')
insert into cl_errores values (807045, 0, 'Control de acceso a eliminar no existe')
insert into cl_errores values (807046, 0, 'Error en eliminación de control de acceso')
insert into cl_errores values (807047, 0, 'código de Producto no enviado')
insert into cl_errores values (807048, 0, 'Error en la actualización del path fuente')
insert into cl_errores values (807049, 0, 'Error en la actualización del path destino')
go

/*Errores nuevos para batch gráfico*/
insert into cl_errores values (803001, 0, 'Error en la eliminación de la sarta')
insert into cl_errores values (808000, 0, 'Lote  no autorizado para su Ejecución')
insert into cl_errores values (808001, 0, 'No existe proceso para iniciar la ejecución del lote')
insert into cl_errores values (808002, 0, 'Proceso del cual depende no ha finalizado correctamente')
insert into cl_errores values (808003, 0, 'No es posible determinar status de procesos previos')
insert into cl_errores values (808004, 0, 'Fecha de proceso no coincide con la fecha de cierre del producto')
insert into cl_errores values (808005, 0, 'Aprobación de parámetros para la fecha no esta realizada')
insert into cl_errores values (808006, 0, 'No se ha encontrado el servidor de base de datos')
insert into cl_errores values (808007, 0, 'No existe archivo de resultado adjunto al proceso')
insert into cl_errores values (808008, 0, 'Error, ya existe aprobación para esa fecha')
insert into cl_errores values (808009, 0, 'No existen procesos asociados al lote para elaborar el gráfico')
insert into cl_errores values (808010, 0, 'No existen enlaces asociados al lote para elaborar el gráfico')
insert into cl_errores values (808011, 0, 'No es posible mostrar las estad¡sticas del proceso')
insert into cl_errores values (808012, 1, 'Error en la copia a la tabla ba_sarta_batch_exec')
insert into cl_errores values (808013, 1, 'Error en la copia a la tabla ba_enlace_exec')
insert into cl_errores values (808014, 1, 'Error en la inserción del enlace en ba_enlace_exec')
insert into cl_errores values (808015, 1, 'Error en la actualización del enlace en ba_enlace_exec')
insert into cl_errores values (808016, 1, 'Error en la eliminación del enlace en ba_enlace_exec')
insert into cl_errores values (808017, 1, 'Error en la inserción del proceso en ba_sarta_batch_exec')
insert into cl_errores values (808018, 1, 'Error en la actualización del proceso en ba_sarta_batch_exec')
insert into cl_errores values (808019, 1, 'Error en la eliminación del proceso en ba_sarta_batch_exec')
insert into cl_errores values (808020, 1, 'Error en la copia a la tablas ba_sarta_batch_log y ba_enlace_log')
insert into cl_errores values (808021, 0, 'No existen condiciones necesarias para matar el proceso')
insert into cl_errores values (808022, 0, 'No fue posible ejecutar comando')
insert into cl_errores values (808023, 0, 'El programa ya ha sido ejecutado y solo se puede ejecutar una vez en el dia')
insert into cl_errores values (808024, 0, 'El programa ya ha sido ejecutado exitosamente y solo se puede ejecutar una vez en el dia')
insert into cl_errores values (808025, 1, 'Error, en la creación de corrida')
insert into cl_errores values (808026, 0, 'No es posible graficar este lote pues esta activo')
insert into cl_errores values (808027, 1, 'Error en liberación del lote')
insert into cl_errores values (808028, 0, 'No es posible liberar este lote pues esta activo. Refrescar la consulta administrativa')
insert into cl_errores values (808029, 1, 'Error en cambio de estado a Ejecución')
insert into cl_errores values (808030, 0, 'No existen condiciones para iniciar la ejecución, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808031, 1, 'Error en cambio de estado a Pendiete para cargar')
insert into cl_errores values (808032, 0, 'No es posible liberar la corrida para esta sarta, existen procesos activos en el Sistema Operativo')
insert into cl_errores values (808033, 0, 'No es posible liberar la corrida para esta sarta, no existe una corrida en Ejecución para esta fecha de proceso')
insert into cl_errores values (808034, 1, 'Error en cambio de estado a Finalizado')
insert into cl_errores values (808035, 0, 'No existen condiciones para Finalizar la corrida, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808036, 1, 'Error en cambio de estado a Pendiente Graficado')
insert into cl_errores values (808037, 0, 'No existen condiciones para cambio de estado a Pendiente Graficado, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808038, 1, 'Error en cambio de estado a Finalizado')
insert into cl_errores values (808039, 0, 'No existen condiciones para cambio de estado a Finalizado, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808040, 1, 'Error en cambio de estado a Pendiente Graficado')
insert into cl_errores values (808041, 0, 'No existen condiciones para cargar esta corrida, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808042, 1, 'Error en cambio de estado a Pendiente (para graficar)')
insert into cl_errores values (808043, 0, 'No existen condiciones para cambio de estado a Pendiente (para graficar), posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808044, 0, 'No existen condiciones para re-iniciar la Ejecución, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808045, 1, 'Error en cambio de estado a Finalizado Graficado')
insert into cl_errores values (808046, 0, 'No existe una corrida para esta sarta y fecha de proceso')
insert into cl_errores values (808047, 1, 'Error en cambio de estado a Finalizado Cerrado')
insert into cl_errores values (808048, 0, 'No existen condiciones para cambio de estado a (Z) Finalizado Cerrado, posiblemente el lote esta activo en otra estación')
insert into cl_errores values (808049, 0, 'Error, la ultima corrida no corresponde a la consultada')
insert into cl_errores values (808050, 0, 'La corrida no esta activa para su SSN. No puede ejecutar procesos de este lote.')
insert into cl_errores values (808051, 0, 'Existen lotes activos. Estado: "E", "G", "R", "F"')
insert into cl_errores values (808052, 0, 'NO existen definiciones de ejecución para actualizar en estructuras de log sarta_batch. LIMPIE LA VENTANA Y CARGUE LA ULTIMA CORRIDA')
insert into cl_errores values (808053, 0, 'NO existen definiciones de ejecución para actualizar en estructuras de log enlace. LIMPIE LA VENTANA Y CARGUE LA ULTIMA CORRIDA')
insert into cl_errores values (808054, 0, 'Error en inserción de impresora')
insert into cl_errores values (808055, 0, 'Secuencial de impresora NO existe')
insert into cl_errores values (808056, 0, 'Error en actualización de impresora')
insert into cl_errores values (808057, 0, 'Error en eliminación de impresora')
insert into cl_errores values (808058, 0, 'Usuario o rol no tiene acceso autorizado')
insert into cl_errores values (808059, 0, 'El login ya tiene autorizado el proceso')
insert into cl_errores values (808060, 0, 'Error al insertar autorización de los procesos del lote para el login')
insert into cl_errores values (808061, 0, 'Error al insertar autorización del proceso para el login')
insert into cl_errores values (808062, 0, 'Registro de autorización del programa batch para el login no existe')
insert into cl_errores values (808063, 0, 'Error al actualizar autorización del proceso para el login')
insert into cl_errores values (808064, 0, 'Error al eliminar autorización del proceso para el login')
insert into cl_errores values (808065, 0, 'Autorización del proceso para el login no esta vigente')
insert into cl_errores values (808066, 0, 'La fecha ingresada debe ser superior a la fecha del sistema')
insert into cl_errores values (808067, 0, 'Error, la fecha ingresada debe ser de Inicio de mes')
insert into cl_errores values (808068, 0, 'Error, la fecha ingresada no es la consecutiva a la fecha actual del sistema')
insert into cl_errores values (808069, 0, 'Error, la fecha ingresada es feriado')
insert into cl_errores values (808070, 0, 'Error, en la inserción de registro')
insert into cl_errores values (808071, 0, 'Error, en la lectura de la tabla ba_batch')
insert into cl_errores values (808072, 0, 'Error, no existen registros')
insert into cl_errores values (808073, 0, 'La fecha de cierre es menor a la fecha de proceso actual')

-----------------------------------------------------------------------------
-- PJA: 12 MAYO 2011
-- Errores para esquema de almacenamiento para el registro de errores que se 
-- presenten durante la ejecución de los procesos batch. 
-----------------------------------------------------------------------------

insert into cl_errores values (808074, 0, 'No existen registros de errores de procesamiento')
insert into cl_errores values (808075, 0, 'Error, en la eliminación de registros de errores de procesamiento históricos')
insert into cl_errores values (808076, 0, 'Error, en la inserción de registros diarios al histórico')
insert into cl_errores values (808077, 0, 'Error, en la eliminación de registros de errores de procesamiento diario')
--Caso 22337
insert into cl_errores values (808078, 0, 'Se presentó un error al obtener datos del producto')
go
