/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor y por las y por las convenciones              */
/*   internacionales de  propiedad intelectual. Su uso no   */
/*   autorizado dara  derecho a  COBISCORP para obtener     */
/*   ordenes de  secuestro o retencion y  para perseguir    */
/*   penalmente a los autores de cualquier infraccion.      */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.service.impl;

import javax.ws.rs.Consumes;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.apache.felix.scr.annotations.Component;
import org.apache.felix.scr.annotations.Reference;
import org.apache.felix.scr.annotations.ReferenceCardinality;
import org.apache.felix.scr.annotations.Service;

import cobiscorp.ecobis.cts.integration.services.ICTSServiceIntegration;
import cobiscorp.ecobis.ucsp.service.IMaxDebtService;

import com.cobiscorp.cobis.commons.log.ILogger;
import com.cobiscorp.cobis.commons.log.LogFactory;
import com.cobiscorp.cobis.web.services.commons.model.ServiceResponse;
import com.cobiscorp.cobis.web.services.commons.utils.ServiceBase;

//@Path("/cobiscorp/ecobis/ucsp/hsbc/service/impl/MaxDebtService")
@Path("/cobis/web/clientviewer/MaxDebtService")
@Component
@Service({ IMaxDebtService.class })
public class MaxDebtService extends ServiceBase implements IMaxDebtService {

	@Reference(bind = "setServiceIntegration", unbind = "unsetServiceIntegration", cardinality = ReferenceCardinality.MANDATORY_UNARY)
	private ICTSServiceIntegration serviceIntegration;

	private ILogger logger = LogFactory.getLogger(MaxDebtService.class);

	private static final String QUERYMAXDEBT_SERVICE_ID = "ClientViewer.MaxDebt.QueryMaxDebt"; //"UCSP.HSBC.MaxDebt.QueryMaxDebt";
	/*
	 * (non-Javadoc)
	 * @see cobiscorp.ecobis.ucsp.service.IMaxDebtService#queryMaxDebt(java.lang.Integer, java.lang.Integer)
	 */
	@Override
	@PUT	
	@Path("/queryMaxDebt/{customerCode}/{groupCode}")
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	public ServiceResponse queryMaxDebt(@PathParam("customerCode") Integer customerCode,
			@PathParam("groupCode") Integer groupCode) {
		try {
			if (logger.isDebugEnabled()) {
				logger.logDebug("queryMaxDebt start");
			}
			
			return this.execute(serviceIntegration, logger,
					QUERYMAXDEBT_SERVICE_ID, new Object[] { customerCode, groupCode });
		} catch (Exception ex) {
			return this.manageException(ex, logger);
		}
	}

	/**
	 * Method that set the instance of ICTSServiceIntegration
	 * 
	 * @param serviceIntegration
	 *            Instance of ICTSServiceIntegration
	 */
	public void setServiceIntegration(ICTSServiceIntegration serviceIntegration) {
		this.serviceIntegration = serviceIntegration;
	}

	/**
	 * Method that unset the instance of ICTSServiceIntegration
	 * 
	 * @param serviceIntegration
	 *            Instance of ICTSServiceIntegration
	 */
	public void unsetServiceIntegration(
			ICTSServiceIntegration serviceIntegration) {
		this.serviceIntegration = null;
	}

}