
    /************************************************************/
    /*******************Service Operations Script*********************/
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    use cobis
    GO
    
      IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Sales.Cloud.ConsultingReportZurich.ReportZurichInformation')
	     DELETE cts_serv_catalog WHERE csc_service_id = 'Sales.Cloud.ConsultingReportZurich.ReportZurichInformation'
      GO
    
      IF EXISTS (SELECT * FROM ad_servicio_autorizado WHERE ts_servicio = 'Sales.Cloud.ConsultingReportZurich.ReportZurichInformation')
      begin
        DELETE ad_servicio_autorizado WHERE ts_servicio = 'Sales.Cloud.ConsultingReportZurich.ReportZurichInformation'
      end
      GO