
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1444' where di_ente = 11 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1444' where di_ente = 11 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1449' where di_ente = 12 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1449' where di_ente = 12 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ 23' where di_ente = 13 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AVE CUAUHTEMOC ESQ NORTE 4' where di_ente = 13 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 75' where di_ente = 16 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 75' where di_ente = 16 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1447 ' where di_ente = 17 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1447 ' where di_ente = 17 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1447' where di_ente = 20 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1447' where di_ente = 20 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1444' where di_ente = 23 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1444' where di_ente = 23 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 75 LT 1 A' where di_ente = 24 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443' where di_ente = 24 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 27 MZ 628 LT 13' where di_ente = 28 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 27 MZ 628 LT 13' where di_ente = 28 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 27 MZ 628 LT 13 ' where di_ente = 31 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 27 MZ 628 LT 13 ' where di_ente = 31 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 30ESQ OTE 1 MZ 600 LT 1' where di_ente = 33 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 30ESQ OTE 1 MZ 600 LT 1' where di_ente = 33 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2A MZ 628 LT 14' where di_ente = 36 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2A MZ 628 LT 14' where di_ente = 36 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 30 ESQ OTE 1 MZ 600 LT 1' where di_ente = 43 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 30 ESQ OTE 1 MZ 600 LT 1' where di_ente = 43 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT1' where di_ente = 81 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT1' where di_ente = 81 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT1' where di_ente = 82 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT1' where di_ente = 82 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ1553 LT2' where di_ente = 85 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ1553 LT2' where di_ente = 85 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 513' where di_ente = 86 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 513' where di_ente = 86 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ74 LT6' where di_ente = 214 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ74 LT6' where di_ente = 214 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1119 LT 25' where di_ente = 231 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 348 LT 12' where di_ente = 281 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 348 LT 12' where di_ente = 281 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 LT 13 ' where di_ente = 289 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 LT 13 ' where di_ente = 289 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 ' where di_ente = 292 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 ' where di_ente = 292 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 38 MZ179 LT20' where di_ente = 299 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 38 MZ179 LT20' where di_ente = 299 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 LT 13' where di_ente = 301 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 LT 13' where di_ente = 301 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 235 L 2' where di_ente = 305 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 235 L 2' where di_ente = 305 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 38 MZ 179 LT 20' where di_ente = 310 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 38 MZ 179 LT 20' where di_ente = 310 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ40 LT28' where di_ente = 425 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ40 LT28' where di_ente = 425 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ19LT 7 1' where di_ente = 429 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ19LT 7 1' where di_ente = 429 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 39 LT21' where di_ente = 436 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 39 LT21' where di_ente = 436 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ 34 LT14' where di_ente = 481 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 17 PTE 7A' where di_ente = 481 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 59 LT02' where di_ente = 487 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV TEZOZOMOC' where di_ente = 487 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ59 LT02' where di_ente = 493 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ59 LT02' where di_ente = 493 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6A MZ 23 LT 1' where di_ente = 503 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6A MZ 23 LT 1' where di_ente = 503 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 8 M1100 LT1 ' where di_ente = 551 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 8 M1100 LT1 ' where di_ente = 551 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 490 LT 10' where di_ente = 552 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 490 LT 10' where di_ente = 552 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 490 LT 10' where di_ente = 553 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 490 LT 10' where di_ente = 553 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 231 LT 13 ' where di_ente = 554 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 231 LT 13 ' where di_ente = 554 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 189 LT 2' where di_ente = 555 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 189 LT 2' where di_ente = 555 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 480 LT 7' where di_ente = 694 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 480 LT 7' where di_ente = 694 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 28 MZ 460 LT 3' where di_ente = 702 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 28 MZ 460 LT 3' where di_ente = 702 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 480 LT 7' where di_ente = 703 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 480 LT 7' where di_ente = 703 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR ONCE' where di_ente = 727 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR ONCE' where di_ente = 727 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11' where di_ente = 731 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11' where di_ente = 731 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 ' where di_ente = 739 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 ' where di_ente = 739 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR ONCE' where di_ente = 752 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR ONCE' where di_ente = 752 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 A MZ 9 LT 13' where di_ente = 758 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 A MZ 9 LT 13' where di_ente = 758 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 7 MZ 261 LT 7 ' where di_ente = 792 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 7 MZ 261 LT 7 ' where di_ente = 792 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 49 LT 13' where di_ente = 795 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 49 LT 13' where di_ente = 795 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 1540 LT 12 ' where di_ente = 803 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 50 LT 1' where di_ente = 803 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 555 LT 2' where di_ente = 805 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 555 LT 2' where di_ente = 805 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 806 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 806 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 813 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 813 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 555 LT 2' where di_ente = 814 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 814 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 27 LT 15 ' where di_ente = 829 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 27 LT 15 ' where di_ente = 829 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 906 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 ' where di_ente = 906 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE  MZ93 LT18' where di_ente = 909 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE  MZ93 LT18' where di_ente = 909 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14MZ1418 LT5' where di_ente = 913 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV SOTO Y GAMA Y PTE 12' where di_ente = 913 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 34 MZ1396 LT4' where di_ente = 917 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 34 MZ1396 LT4' where di_ente = 917 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12MZ1452LT2' where di_ente = 932 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12MZ1452LT2' where di_ente = 932 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6' where di_ente = 942 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ I57 LT 23' where di_ente = 942 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 54 MZ 74 LT 26' where di_ente = 973 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 54 MZ 74 LT 26' where di_ente = 973 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 14 MZ 1097 LT 9' where di_ente = 997 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 14 MZ 1097 LT 9' where di_ente = 997 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 533 LT 4' where di_ente = 1000 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 533 LT 4' where di_ente = 1000 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 14 MZ 1097 LT 9' where di_ente = 1001 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 14 MZ 1097 LT 9' where di_ente = 1001 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1095 LT 25' where di_ente = 1002 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1095 LT 25' where di_ente = 1002 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1129' where di_ente = 1006 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1129' where di_ente = 1006 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ55 L20' where di_ente = 1010 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ55 L20' where di_ente = 1010 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE MZ 119 LT17 ' where di_ente = 1020 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE MZ 119 LT17 ' where di_ente = 1020 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ55 L20' where di_ente = 1021 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ55 L20' where di_ente = 1021 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE MZ 119 LT17' where di_ente = 1024 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE MZ 119 LT17' where di_ente = 1024 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LT3' where di_ente = 1056 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LT3' where di_ente = 1056 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LOTE 7' where di_ente = 1058 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LOTE 7' where di_ente = 1058 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LT 3' where di_ente = 1061 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LT 3' where di_ente = 1061 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ8 LT 32' where di_ente = 1071 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ8 LT 32' where di_ente = 1071 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6A MZ6 LT20' where di_ente = 1081 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6A MZ6 LT20' where di_ente = 1081 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 29 MZ 251 LT 15' where di_ente = 1084 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 29 MZ 251 LT 15' where di_ente = 1084 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 244 LT13' where di_ente = 1088 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 ESQ  OTE 30' where di_ente = 1088 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 29 MZ 251 LT 15' where di_ente = 1091 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 29 MZ 251 LT 15' where di_ente = 1091 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ244 LT12' where di_ente = 1094 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ244 LT12' where di_ente = 1094 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 244 LT 12' where di_ente = 1095 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 244 LT 12' where di_ente = 1095 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 1 MZ32 LT9' where di_ente = 1110 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 1 MZ32 LT9' where di_ente = 1110 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 1 MZ 32 LT 9' where di_ente = 1112 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV TLALOC' where di_ente = 1112 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1181 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1181 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1182 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1182 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NTE 17 MZ 181 LT 58' where di_ente = 1185 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NTE 17 MZ 181 LT 58' where di_ente = 1185 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1188 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1188 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 25 MZ 639 LT 4' where di_ente = 1190 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 ' where di_ente = 1190 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39' where di_ente = 1219 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39' where di_ente = 1219 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39' where di_ente = 1220 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39' where di_ente = 1220 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 149' where di_ente = 1240 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 149' where di_ente = 1240 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 194' where di_ente = 1242 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 194' where di_ente = 1242 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 148' where di_ente = 1247 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 148' where di_ente = 1247 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 42 MZ 102 LT 7' where di_ente = 1285 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ERMITA' where di_ente = 1285 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1132 LT 5' where di_ente = 1286 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1132 LT 5' where di_ente = 1286 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 42 MZ 102 LT 7' where di_ente = 1288 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ERMITA' where di_ente = 1288 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1082 LT 8' where di_ente = 1289 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1082 LT 8' where di_ente = 1289 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 105 LT 21' where di_ente = 1292 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 105 LT 21' where di_ente = 1292 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 146 LT 1 ' where di_ente = 1293 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 146 LT 1 ' where di_ente = 1293 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10MZ104 LT2' where di_ente = 1294 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV CUAUHTEMO MZ 105 LT 4' where di_ente = 1294 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT2' where di_ente = 1295 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT2' where di_ente = 1295 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 146 LT 1' where di_ente = 1297 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 146 LT 1' where di_ente = 1297 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 105 LT 21' where di_ente = 1304 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV CUAUHTEMOC ESQ CUITLAHUAC' where di_ente = 1304 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ1072 LT 1' where di_ente = 1320 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ1072 LT 1' where di_ente = 1320 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1132 LT 5' where di_ente = 1342 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1132 LT 5' where di_ente = 1342 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 5 MZ 331 LT 17 ' where di_ente = 1344 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 5 MZ 331 LT 17 ' where di_ente = 1344 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1104 LT 9' where di_ente = 1346 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1104 LT 9' where di_ente = 1346 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 179 LOTE 13' where di_ente = 1375 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 179 LOTE 13' where di_ente = 1375 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 35 MZ62 LT10 ' where di_ente = 1380 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 35 MZ62 LT10 ' where di_ente = 1380 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 1175 LT 03' where di_ente = 1383 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 1175 LT 03' where di_ente = 1383 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 22 MZ105 LT15' where di_ente = 1414 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT 13' where di_ente = 1414 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1418 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1418 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 209' where di_ente = 1426 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 209' where di_ente = 1426 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1431 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1431 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 5 L 13 M 646' where di_ente = 1483 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 NZ 1175 LT 2' where di_ente = 1483 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 93 LT 12' where di_ente = 1486 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 93 LT 12' where di_ente = 1486 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MANZANA 616 LOTE 14 ' where di_ente = 1490 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MANZANA 616 LOTE 14 ' where di_ente = 1490 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 105 LT 17' where di_ente = 1506 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 105 LT 17' where di_ente = 1506 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 83 LT 16' where di_ente = 1552 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 83 LT 86 ' where di_ente = 1552 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 929 LT 16' where di_ente = 1555 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 929 LT 16' where di_ente = 1555 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR TRECE MZ 61 LT 3' where di_ente = 1562 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR TRECE MZ 61 LT 3' where di_ente = 1562 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1280 LT 13' where di_ente = 1583 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1280 LT 13' where di_ente = 1583 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1422 LT 15' where di_ente = 1658 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV IGNACIO COMONFORT ESQ PT 20 LT 16 MZ1324' where di_ente = 1658 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ 1357 LT 5' where di_ente = 1669 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10 ESQ PT 15' where di_ente = 1669 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 37MANZANA1363 LOTE3' where di_ente = 1672 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 37MANZANA1363 LOTE3' where di_ente = 1672 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ148 ' where di_ente = 1718 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ148 ' where di_ente = 1718 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ70' where di_ente = 1721 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ70' where di_ente = 1721 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ1363 LT14' where di_ente = 1749 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ 1363 LT 14' where di_ente = 1749 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ1358 LT4' where di_ente = 1753 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ1358 LT4' where di_ente = 1753 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 1839' where di_ente = 1761 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 1839' where di_ente = 1761 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 11 121 9 ' where di_ente = 1763 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 11 121 9 ' where di_ente = 1763 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 1839' where di_ente = 1766 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 1839' where di_ente = 1766 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 225' where di_ente = 1793 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 225 ' where di_ente = 1793 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'MORELOS NO 8' where di_ente = 1808 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'COL MORELOS NO 8' where di_ente = 1808 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'COL MORELOS NO 8' where di_ente = 1808 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'FRANCISCO SARABIA' where di_ente = 1854 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'COL FRANCISCO SARABIA' where di_ente = 1854 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE37 MANZANA1363 LOTE 3' where di_ente = 1908 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE37 MANZANA1363 LOTE 3' where di_ente = 1908 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 209 ' where di_ente = 1920 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 209 ' where di_ente = 1920 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 149' where di_ente = 2016 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 149' where di_ente = 2016 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 24 LT8 ' where di_ente = 2061 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 24 LT8 ' where di_ente = 2061 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 148' where di_ente = 2104 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ 148' where di_ente = 2104 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 1 LT 28' where di_ente = 2156 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 1 LT 28' where di_ente = 2156 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 14 L28' where di_ente = 2162 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV MOCTEZUMA ' where di_ente = 2162 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 22' where di_ente = 2171 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 22' where di_ente = 2171 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 14 LT 28' where di_ente = 2175 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 14 LT 28' where di_ente = 2175 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ 99 LT22' where di_ente = 2252 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ 99 LT22' where di_ente = 2252 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 3 MZ 46 LT20' where di_ente = 2268 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 3 MZ 46 LT20' where di_ente = 2268 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 1189 LT 2' where di_ente = 2278 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 1189 LT 2' where di_ente = 2278 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 17 MZ 25LT1' where di_ente = 2281 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 17 MZ 25LT1' where di_ente = 2281 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 17 MZ 25 LT1' where di_ente = 2285 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'TLAHUAC' where di_ente = 2285 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 11 LT 17' where di_ente = 2412 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 11 LT 17' where di_ente = 2412 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 11 LT 17' where di_ente = 2414 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 11 LT 17' where di_ente = 2414 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 27 LT 20' where di_ente = 2418 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 27 LT 20' where di_ente = 2418 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32 MZ 32 LT' where di_ente = 2459 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32 MZ 32 LT' where di_ente = 2459 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 LT ' where di_ente = 2464 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 LT ' where di_ente = 2464 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P1 LT' where di_ente = 2471 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P1 LT' where di_ente = 2471 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 89 LT ' where di_ente = 2472 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 89 LT ' where di_ente = 2472 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 89 LT ' where di_ente = 2473 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 89 LT ' where di_ente = 2473 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P 1 LT ' where di_ente = 2475 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P 1 LT ' where di_ente = 2475 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1405 LT 5' where di_ente = 2489 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV COVARRUVIAS Y PTE 11 ' where di_ente = 2489 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P1 LT' where di_ente = 2493 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P1 LT' where di_ente = 2493 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11MZ984 LT 15' where di_ente = 2526 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11MZ984 LT 15' where di_ente = 2526 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 8 MZ1009 LT 22' where di_ente = 2549 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 8A ESQ SOTO Y GAMA' where di_ente = 2549 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 209' where di_ente = 2599 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 209' where di_ente = 2599 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT 15' where di_ente = 2615 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT 15' where di_ente = 2615 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12 MZ1416 LT10' where di_ente = 2626 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV SOTO Y GAMA ESQ CUAHUTEMOC' where di_ente = 2626 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 MZA1451 LOTE19' where di_ente = 2660 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 MZA1451 LOTE19' where di_ente = 2660 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 34 MZ1396 LT4' where di_ente = 2681 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV COMONFORT Y ZAPATA' where di_ente = 2681 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 7A MZ988 LT 11' where di_ente = 2686 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 7A MZ988 LT 11' where di_ente = 2686 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 7A MZ988 LT9' where di_ente = 2695 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 7A MZ988 LT9' where di_ente = 2695 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 5 MZ 14 LT 4 ' where di_ente = 2706 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 5 MZ 14 LT 4 ' where di_ente = 2706 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 5 MZ 271 LT 11' where di_ente = 2744 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 5 MZ 271 LT 11' where di_ente = 2744 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 9 MZ 90 LT 5' where di_ente = 2747 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 9 MZ 90 LT 5' where di_ente = 2747 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 7 AMZ 988 LT10' where di_ente = 2776 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 7 MZ 988 LT10' where di_ente = 2776 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 31 MZ 17 LT 3' where di_ente = 2799 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 31 MZ 17 LT 3' where di_ente = 2799 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 65 LT 9' where di_ente = 2811 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 65 LT 9' where di_ente = 2811 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 69 LT 9' where di_ente = 2813 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 69 LT 9' where di_ente = 2813 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 3 MZ 12 LT 7 ' where di_ente = 2816 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 3 MZ 12 LT 7 ' where di_ente = 2816 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT 12' where di_ente = 2825 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT 12' where di_ente = 2825 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 6A MZ 21 LT 2' where di_ente = 2856 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 6A MZ 21 LT 2' where di_ente = 2856 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 5 MZ 271 LT 11' where di_ente = 2864 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35  MZ 217 LT8' where di_ente = 2864 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2A MZ 17 LT 1' where di_ente = 2885 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2A MZ 17 LT 1' where di_ente = 2885 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 2964 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 2964 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1426 LT 13 3' where di_ente = 2971 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1426 LT 13 3' where di_ente = 2971 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1377LT 10' where di_ente = 3117 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1377 LT 10' where di_ente = 3117 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7A MANZANA1008LOTE2' where di_ente = 3210 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7A MANZANA1008LOTE2' where di_ente = 3210 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 8 MZ1021 LT21' where di_ente = 3278 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 8 MZ1021 LT21' where di_ente = 3278 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 22 MZ 456' where di_ente = 3288 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 22 MZ 456' where di_ente = 3288 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 1324 LT 20 7' where di_ente = 3330 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 1324 LT 20 7' where di_ente = 3330 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1401 LT 22' where di_ente = 3404 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1401 LT 22' where di_ente = 3404 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT  09' where di_ente = 3431 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT  09' where di_ente = 3431 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE ' where di_ente = 3442 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE ' where di_ente = 3442 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ LT' where di_ente = 3487 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ LT' where di_ente = 3487 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 47 MZ 98 LT ' where di_ente = 3517 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV RUIZ CORTINEZ NUM ' where di_ente = 3517 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 LT 2' where di_ente = 3530 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 LT 2' where di_ente = 3530 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1458 LT 29' where di_ente = 3531 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1458 LT 29' where di_ente = 3531 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3535 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3535 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 8A MZ986 LT11' where di_ente = 3611 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PIPILA' where di_ente = 3611 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 8A MZ986 LT11' where di_ente = 3614 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 8A MZ986 LT11' where di_ente = 3614 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 MZ1450 LT 16' where di_ente = 3636 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV SOTO Y GAMA' where di_ente = 3636 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3639 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3639 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ LT' where di_ente = 3674 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ LT' where di_ente = 3674 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE ' where di_ente = 3724 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE ' where di_ente = 3724 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3857 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3857 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NTE 18 MZ 1260 LT 7' where di_ente = 3896 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NTE 18 MZ 1260 LT 7' where di_ente = 3896 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 11 MZ983 LT 4' where di_ente = 3913 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 11 MZ983 LT 4' where di_ente = 3913 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 139 LT 3' where di_ente = 3923 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 139 LT 3' where di_ente = 3923 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 141 LT 70' where di_ente = 3929 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 141 LT 70' where di_ente = 3929 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE  38 MZ LT' where di_ente = 3934 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE  38 MZ LT' where di_ente = 3934 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 23 MZ 141 LT 1' where di_ente = 3990 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 23 MZ 141 LT 1' where di_ente = 3990 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1279 LT 8' where di_ente = 4011 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1279 LT 8' where di_ente = 4011 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 48 MZ 48 LT' where di_ente = 4196 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 48 MZ 48 LT' where di_ente = 4196 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 4224 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 4224 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ 64 LT8' where di_ente = 4325 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 14 MZ 64 LT7' where di_ente = 4325 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 19' where di_ente = 4427 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19' where di_ente = 4427 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ 64 LT 7' where di_ente = 4450 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV CUITLAHUAC' where di_ente = 4450 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443 LT 13' where di_ente = 4482 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443 LT 13' where di_ente = 4482 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 75 LT 1 A' where di_ente = 4485 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 75 LT 1 A' where di_ente = 4485 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1396 LT 8' where di_ente = 4486 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1396 LT 8' where di_ente = 4486 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1396 LT 8' where di_ente = 4487 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1396 LT 8' where di_ente = 4487 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 63 LT 55' where di_ente = 4503 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 63 LT 55' where di_ente = 4503 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 26 MZ 902 LT ' where di_ente = 4514 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 26 MZ 902 LT ' where di_ente = 4514 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 43 LT 41' where di_ente = 4515 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 43 LT 41' where di_ente = 4515 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 43 LT 41' where di_ente = 4522 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 43 LT 41' where di_ente = 4522 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 28 LT 5' where di_ente = 4640 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 28 LT 5' where di_ente = 4640 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 A MZ 131 LT 20' where di_ente = 4782 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 A MZ 131 LT 20' where di_ente = 4782 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 A MZ 130 L 9' where di_ente = 4784 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 A MZ 130 L 9' where di_ente = 4784 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE  MZ 119 LT 17 ' where di_ente = 4815 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE  MZ 119 LT 17 ' where di_ente = 4815 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 20' where di_ente = 4909 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20' where di_ente = 4909 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 MZ 28 LT 24' where di_ente = 4953 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 MZ 28 LT 24' where di_ente = 4953 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 20 MZ 129 LT 8' where di_ente = 4961 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 20 MZ 129 LT 8' where di_ente = 4961 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 8' where di_ente = 5108 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 8' where di_ente = 5108 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ56' where di_ente = 5507 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'VENUSTIANO CARRANZA' where di_ente = 5507 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 253 LT' where di_ente = 5762 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 253 LT' where di_ente = 5762 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 253 LT' where di_ente = 5768 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 253 LT' where di_ente = 5768 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 225' where di_ente = 5878 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 225' where di_ente = 5878 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 43 MZ 56 LT' where di_ente = 5895 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 43 MZ 56 LT' where di_ente = 5895 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT' where di_ente = 5898 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT' where di_ente = 5898 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 514 LT14' where di_ente = 5910 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 7 Y NORTE 26' where di_ente = 5910 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT' where di_ente = 5913 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT' where di_ente = 5913 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 51 LT 06' where di_ente = 5932 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 51 LT 06' where di_ente = 5932 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT ' where di_ente = 5939 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT ' where di_ente = 5939 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 172' where di_ente = 5940 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 172' where di_ente = 5940 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 MZ 12 LT' where di_ente = 6116 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AVILA CAMACHO MZ 8' where di_ente = 6116 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 16A MZ 226' where di_ente = 6120 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 16A MZ 226' where di_ente = 6120 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 27 LT 10' where di_ente = 6122 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 27 LT 10' where di_ente = 6122 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 18 MZ 1087 LT 1' where di_ente = 6139 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 18 MZ 1087 LT 1' where di_ente = 6139 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 1583 LT 13' where di_ente = 6251 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 1583 LT 13' where di_ente = 6251 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 192' where di_ente = 6359 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 192' where di_ente = 6359 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 129 LT 10' where di_ente = 6443 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 129 LT 10' where di_ente = 6443 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = ' NORTE MZ 129 LT 10' where di_ente = 6446 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = ' NORTE MZ 129 LT 10' where di_ente = 6446 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'B JUAREZ' where di_ente = 6456 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'COL B JUAREZ' where di_ente = 6456 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 LT 13' where di_ente = 6467 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 LT 13' where di_ente = 6467 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'EMILIANO ZAPATA' where di_ente = 6478 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'COL EMILIANO ZAPATA' where di_ente = 6478 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ60 LT 9' where di_ente = 6540 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PANTITLAN' where di_ente = 6540 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ60 LT 9' where di_ente = 6549 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ60 LT 9' where di_ente = 6549 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ60 LT 9' where di_ente = 6557 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ISABEL LA CATOLICA' where di_ente = 6557 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 356 LT 10 ' where di_ente = 6619 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 356 LT 10 ' where di_ente = 6619 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 372 LT 9 ' where di_ente = 6627 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 372 LT 9 ' where di_ente = 6627 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 349 LT 12' where di_ente = 6661 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'AV COVARRUBIAS MZ 371 LT7' where di_ente = 6661 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 112 LT 8' where di_ente = 6682 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 112 LT 8' where di_ente = 6682 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 145 LT 4' where di_ente = 6685 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 145 LT 4' where di_ente = 6685 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ492 LT 22' where di_ente = 6723 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 170 LT 22' where di_ente = 6759 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 170 LT 22' where di_ente = 6759 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 1583 LT 13' where di_ente = 6767 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 1583 LT 13' where di_ente = 6767 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 27 LT 10' where di_ente = 6821 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 7 LEONA VICARIO' where di_ente = 6821 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 50' where di_ente = 6824 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SOTO Y GAMA' where di_ente = 6824 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'C INDEPENDENCIA' where di_ente = 6827 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'C INFEPENDENCIA' where di_ente = 6827 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 15 MZ 161 LT 8 ' where di_ente = 6866 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 15 MZ 161 LT 8 ' where di_ente = 6866 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1090 LT 2' where di_ente = 6905 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 112 LT 8' where di_ente = 6951 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 112 LT 8' where di_ente = 6951 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1290 LT 5' where di_ente = 6969 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1290 LT 5' where di_ente = 6969 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ1449 LT 3' where di_ente = 6975 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ1449 LT 3' where di_ente = 6975 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ1449 LT 11' where di_ente = 6982 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SOTO Y GAMA' where di_ente = 6982 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ1449 LT3' where di_ente = 6988 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SOTO Y GAMA' where di_ente = 6988 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ1449 LT 3' where di_ente = 6991 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 14' where di_ente = 6991 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15MZ1290 LT 5' where di_ente = 6999 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ANAHUAC Y MAZO' where di_ente = 6999 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 50' where di_ente = 7019 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 50' where di_ente = 7019 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 14 MZ1450 LT 15' where di_ente = 7065 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 14 MZ1450 LT 15' where di_ente = 7065 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 ' where di_ente = 7172 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 ' where di_ente = 7172 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 2 MZ 100 LT 9' where di_ente = 7201 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 2 MZ 100 LT 9' where di_ente = 7201 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1119 LT 26' where di_ente = 7294 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 15 LT' where di_ente = 7335 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 15 LT' where di_ente = 7335 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ16' where di_ente = 7497 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ16' where di_ente = 7497 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 67' where di_ente = 7501 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 67' where di_ente = 7501 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 16' where di_ente = 7509 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 5' where di_ente = 7509 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 2A MZ67' where di_ente = 7548 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 2A MZ67' where di_ente = 7548 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 36 LT' where di_ente = 7561 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 36 LT' where di_ente = 7561 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 15 LT ' where di_ente = 7589 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PASCUAL ORTIZ RUBIO N ' where di_ente = 7589 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 135 ' where di_ente = 7629 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 135 ' where di_ente = 7629 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 16' where di_ente = 7640 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 4 MZ 10' where di_ente = 7640 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ16' where di_ente = 7818 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ16' where di_ente = 7818 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 348 LT 7' where di_ente = 7849 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 348 LT 7' where di_ente = 7849 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 16 ' where di_ente = 7857 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 16 ' where di_ente = 7857 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 366 LT 7' where di_ente = 7861 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 366 LT 7' where di_ente = 7861 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37 MZ 185 LT' where di_ente = 7883 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37 MZ 185 LT' where di_ente = 7883 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 2A MZ 67' where di_ente = 7909 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'TORRES Y LOPEZ MZ 254' where di_ente = 7909 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ1294 LT 5' where di_ente = 7953 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ1294 LT 5' where di_ente = 7953 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 ' where di_ente = 8022 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 69 LT' where di_ente = 8022 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 ' where di_ente = 8075 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 ' where di_ente = 8075 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'IGNACIO ZARAGOZA' where di_ente = 8606 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'IGANCIO ZARAGOZA' where di_ente = 8606 and di_tipo = 'AE'
