use cobis
go
delete from cl_errores where numero in (1901001,1901002,1901003,1901004,1901005,1901006,1901007,1901008,1901009,1901010,1901011,
										1901012,1901013,1901014,1901015,1901016,1901017,1901018,1901019,1901020,1901021,
										1901022,1901023,1901024,1901025,1901026,1901027,1901028,1901029,1901030,1901031,
										1901032,1901033,1901034,1901035,1901036,1901037,1901038,1901039,1901040,1903001,
										1903002,1903003,1903004,1903005,1903006,1903007,1903008,1903009,1903010,1903011,
										1903012,1903013,1903014,1903015,1903016,1903017,1903030,1905001,1905002,1905003,
										1905004,1905005,1905006,1905007,1905008,1905009,1905010,1905011,1905012,1905013,
										1905014,1905015,1905016,1905017,1905018,1905019,1905020,1905021,1905022,1907001,
										1907002,1907003,1907004,1907005,1907006,1907007,1907008,1907009,1907010,1907011,
										1907012,1907013,1907014,1907015,1907016,1907017,1907018,1909001,1909002,1909003,
										1909004,1909005,1909006,1910001,1910002,1910003,1910004,1910005,1912001,1912002,
										1912003,1912004,1912005,1912006,1912007,1912008,1912009,1912010,1912011,1912012,
										1912013,1912014,1912015,1912016,1912017,1912018,1912019,1912020,1912021,1912022,
										1912023,1912024,1912025,1912026,1912027,1912028,1912029,1912030,1912031,1912032,
										1912033,1912034,1912035,1912036,1912037,1912038,1912039,1912040,1912041,1912042,
										1912043,1912044,1912045,1912046,1912047,1912048,1912050,1912051,1912052,1912053,
										1912054,1912055,1912056,1912057,1912058,1912059,1912060,1912061,1912062,1912063,
										1912064,1912065,1912066,1912067,1912068,1912069,1912070,1912071,1912072,1912073,
										1912074,1912075,1912076,1912077,1912078,1912079,1912080,1912081,1912082,1912083,
										1912084,1912085,1912086,1912087,1912088,1912089,1912090,1912091,1912092,1912094,
										1912096,1912097,1912098,1912099,1912100,1912110,1912112,1912113,1912114,1912115,
										1912122,1912123,1912124,1912125)
go
insert into cl_errores values( 1901001     ,  0           , ' Campos not null con valores nulos                                                                                                    ')
insert into cl_errores values( 1901002     ,  0           , ' Codigo del registro ya existe                                                                                                        ')
insert into cl_errores values( 1901003     ,  0           , ' No existen registros                                                                                                                 ')
insert into cl_errores values( 1901004     ,  0           , ' No existen mas registros                                                                                                             ')
insert into cl_errores values( 1901005     ,  0           , ' Registro consultado no existe                                                                                                        ')
insert into cl_errores values( 1901006     ,  0           , ' Tipo de transaccion no corresponde                                                                                                   ')
insert into cl_errores values( 1901007     ,  0           , ' Nombre de la descripcion no existe                                                                                                   ')
insert into cl_errores values( 1901008     ,  0           , ' Numero de cuenta no corresponde                                                                                                      ')
insert into cl_errores values( 1901009     ,  0           , ' Cuenta Contable no existe                                                                                                            ')
insert into cl_errores values( 1901010     ,  1           , ' Error en creacion de nota de credito a ctas. corrientes                                                                              ')
insert into cl_errores values( 1901011     ,  1           , ' Error en creacion de nota de credito a ctas. ahorros                                                                                 ')
insert into cl_errores values( 1901012     ,  1           , ' Error en creacion de Detalle Contable                                                                                                ')
insert into cl_errores values( 1901013     ,  1           , ' Error en creacion de Transacciones de la garantia                                                                                    ')
insert into cl_errores values( 1901014     ,  1           , ' No existe Tipo Superior de Garantia                                                                                                  ')
insert into cl_errores values( 1901015     ,  1           , ' La Garantia esta ya Cancelada                                                                                                        ')
insert into cl_errores values( 1901016     ,  1           , ' El valor de la poliza es menor al permitido                                                                                          ')
insert into cl_errores values( 1901017     ,  1           , ' El valor actual de la garantia es Cero                                                                                               ')
insert into cl_errores values( 1901018     ,  1           , ' El valor del endoso no puede ser menor al valor de la poliza                                                                         ')
insert into cl_errores values( 1901019     ,  1           , ' No se permite este cambio de estado                                                                                                  ')
insert into cl_errores values( 1901020     ,  1           , ' No se encontro el sector para realizar la contabilizacion                                                                            ')
insert into cl_errores values( 1901021     ,  1           , ' No existen mas niveles de jerarquia para el Tipo de Garantia                                                                         ')
insert into cl_errores values( 1901022     ,  1           , ' No existen inspecciones para esta garantia                                                                                           ')
insert into cl_errores values( 1901023     ,  1           , ' No existen polizas para esta garantia                                                                                                ')
insert into cl_errores values( 1901024     ,  1           , ' No existen perfil contable para ese cambio de estado                                                                                 ')
insert into cl_errores values( 1901025     ,  1           , ' No existen  codigo valor para ese estado                                                                                             ')
insert into cl_errores values( 1901026     ,  1           , ' El valor del endoso no cubre el porcentaje requerido del valor de la poliza                                                          ')
insert into cl_errores values( 1901027     ,  1           , ' El valor total de las polizas de una garantia no cubre el porcentaje de cobertura                                                    ')
insert into cl_errores values( 1901028     ,  1           , ' La cuenta del cliente no esta definida                                                                                               ')
insert into cl_errores values( 1901029     ,  1           , ' El Pago al Avaluador/Abogado ya ha sido realizado                                                                                    ')
insert into cl_errores values( 1901030     ,  1           , ' No existe Registro de Control de Abogado                                                                                             ')
insert into cl_errores values( 1901031     ,  1           , ' No existe Registro de Control de Avaluador                                                                                           ')
insert into cl_errores values( 1901032     ,  1           , ' La garantia no ha sido distribuida                                                                                                   ')
insert into cl_errores values( 1901033     ,  1           , ' El cambio de estado se realiza a traves del proceso de distribucion del Consolidador                                                 ')
insert into cl_errores values( 1901034     ,  1           , ' No existe una distribucion anterior                                                                                                  ')
insert into cl_errores values( 1901035     ,  1           , ' Cuenta No Existe para Ningun Cliente de la Garantia                                                                                  ')
insert into cl_errores values( 1901036     ,  1           , ' No Existe la Garantia Indicada                                                                                                       ')
insert into cl_errores values( 1901037     ,  1           , ' El archivo ha sido aplicado anteriormente                                                                                            ')
insert into cl_errores values( 1901038     ,  1           , ' Existen errores en el archivo. No se puede aplicar                                                                                   ')
insert into cl_errores values( 1901039     ,  1           , ' No se puede hacer un cambio de valor sobre una garantia Agotada y Vigente con Obligacion                                             ')
insert into cl_errores values( 1901040     ,  1           , ' No existe tramite para esa garantia                                                                                                  ')
insert into cl_errores values( 1903001     ,  0           , ' Error en insercion del registro                                                                                                      ')
insert into cl_errores values( 1903002     ,  0           , ' Codigo de registro a insertar ya existe                                                                                              ')
insert into cl_errores values( 1903003     ,  0           , ' Error en insercion de transaccion de servicio                                                                                        ')
insert into cl_errores values( 1903004     ,  0           , ' Valor total de vencimientos mayor al valor de la garantia                                                                            ')
insert into cl_errores values( 1903005     ,  0           , ' No se ha registrado fecha de envio de carta al inspector                                                                             ')
insert into cl_errores values( 1903006     ,  0           , ' Recuperaciones anteriores no cubren el valor del Vencimiento                                                                         ')
insert into cl_errores values( 1903007     ,  0           , ' La fecha de vencimiento debe ser mayor o igual a la fecha actual                                                                     ')
insert into cl_errores values( 1903008     ,  0           , ' El valor del debito no puede ser mayor o igual al valor contable                                                                     ')
insert into cl_errores values( 1903009     ,  0           , ' No se puede recuperar una garantia propuesta                                                                                         ')
insert into cl_errores values( 1903010     ,  0           , ' La fecha de recuperacion debe ser mayor o igual a la fecha actual                                                                    ')
insert into cl_errores values( 1903011     ,  0           , ' No se puede ingresar una garantia cancelada                                                                                          ')
insert into cl_errores values( 1903012     ,  0           , ' No se puede ingresar una garantia anulada                                                                                            ')
insert into cl_errores values( 1903013     ,  0           , ' No se puede ingresar una garantia en estado diferente de Propuesto                                                                   ')
insert into cl_errores values( 1903014     ,  0           , ' El valor a recuperar excede el saldo de vencimientos                                                                                 ')
insert into cl_errores values( 1903015     ,  0           , ' El valor contable es menor que el valor distribuido                                                                                  ')
insert into cl_errores values( 1903016     ,  0           , ' El valor de la garantia es menor a la suma de los vencimientos                                                                       ')
insert into cl_errores values( 1903017     ,  0           , ' No se puede asociar documentos de negocios distintos al mismo tramite                                                                ')
insert into cl_errores values( 1903030     ,  0           , ' No Permite Contabilizar Garantias Especiales En Estado F                                                                             ')
insert into cl_errores values( 1905001     ,  0           , ' Error en actualizacion del registro                                                                                                  ')
insert into cl_errores values( 1905002     ,  0           , ' Codigo del registro a actualizar no existe                                                                                           ')
insert into cl_errores values( 1905003     ,  0           , ' Valor total de recuperaciones sobrepasa el valor del vencimiento                                                                     ')
insert into cl_errores values( 1905004     ,  0           , ' Valor del registro a actualizar ya existe                                                                                            ')
insert into cl_errores values( 1905005     ,  0           , ' Valor Inicial no puede ser cambiado                                                                                                  ')
insert into cl_errores values( 1905006     ,  0           , ' No se puede cancelar una garantia con Riesgos                                                                                        ')
insert into cl_errores values( 1905007     ,  0           , ' No se puede cancelar una garantia en estado de Propuesta                                                                             ')
insert into cl_errores values( 1905008     ,  0           , ' No se puede cancelar una garantia ya cancelada                                                                                       ')
insert into cl_errores values( 1905009     ,  0           , ' La Garantia debe estar Vigente                                                                                                       ')
insert into cl_errores values( 1905010     ,  0           , ' La Garantia debe estar Vigente o Propuesta                                                                                           ')
insert into cl_errores values( 1905011     ,  0           , ' No se puede modificar una inspeccion ya cobrada                                                                                      ')
insert into cl_errores values( 1905012     ,  0           , ' No se puede cambiar de estado una garantia Cancelada                                                                                 ')
insert into cl_errores values( 1905013     ,  0           , ' No se puede anular una garantia vigente o cancelada                                                                                  ')
insert into cl_errores values( 1905014     ,  0           , ' No se puede cambiar de estado una garantia Anulada                                                                                   ')
insert into cl_errores values( 1905015     ,  0           , ' No se puede actualizar de estado la poliza                                                                                           ')
insert into cl_errores values( 1905016     ,  0           , ' No se puede actualizar una garantia en estado cancelada                                                                              ')
insert into cl_errores values( 1905017     ,  0           , ' No se puede actualizar una garantia anulada                                                                                          ')
insert into cl_errores values( 1905018     ,  0           , ' La fecha de vigencia debe ser menor o igual a la de ingreso                                                                          ')
insert into cl_errores values( 1905019     ,  0           , ' La fecha de vigencia debe ser mayor a la fecha de registro                                                                           ')
insert into cl_errores values( 1905020     ,  0           , ' No se puede cancelar una garantia Castigada                                                                                          ')
insert into cl_errores values( 1905021     ,  0           , ' No se puede castigar una garantia Vigente por Cancelar                                                                               ')
insert into cl_errores values( 1905022     ,  0           , ' No se puede Quitar el Castigo a una garantia Vigente con Obligacion                                                                  ')
insert into cl_errores values( 1907001     ,  0           , ' Error en eliminacion del registro                                                                                                    ')
insert into cl_errores values( 1907002     ,  0           , ' Codigo del registro a eliminar no existe                                                                                             ')
insert into cl_errores values( 1907003     ,  0           , ' Tipo de garantia a eliminar posee subtipos                                                                                           ')
insert into cl_errores values( 1907004     ,  0           , ' Existen garantias con este tipo                                                                                                      ')
insert into cl_errores values( 1907005     ,  0           , ' Existen clientes relacionados con esta garantia                                                                                      ')
insert into cl_errores values( 1907006     ,  0           , ' Existen inspecciones relacionadas con esta garantia                                                                                  ')
insert into cl_errores values( 1907007     ,  0           , ' Existe descripcion para esta garantia                                                                                                ')
insert into cl_errores values( 1907008     ,  0           , ' Existen recuperaciones para esta garantia                                                                                            ')
insert into cl_errores values( 1907009     ,  0           , ' Existen transacciones para esta garantia                                                                                             ')
insert into cl_errores values( 1907010     ,  0           , ' Existen vencimientos para esta garantia                                                                                              ')
insert into cl_errores values( 1907011     ,  0           , ' Existen inspecciones pendientes para esta garantia                                                                                   ')
insert into cl_errores values( 1907012     ,  0           , ' Existen garantias que estan custodiadas por esta almacenera                                                                          ')
insert into cl_errores values( 1907013     ,  0           , ' Existen controles para este inspector                                                                                                ')
insert into cl_errores values( 1907014     ,  0           , ' Existen inspecciones registradas para este inspector                                                                                 ')
insert into cl_errores values( 1907015     ,  0           , ' Existen garantias registradas para este cliente                                                                                      ')
insert into cl_errores values( 1907016     ,  0           , ' Item del tipo de garantia tiene valores                                                                                              ')
insert into cl_errores values( 1907017     ,  0           , ' Existen garantias asociadas a esta tabla                                                                                             ')
insert into cl_errores values( 1907018     ,  0           , ' Ejecutivo de Cuenta no corresponde                                                                                                   ')
insert into cl_errores values( 1909001     ,  0           , ' Error en el Manejo del Cursor Asignado                                                                                               ')
insert into cl_errores values( 1909002     ,  0           , ' Error en el Retorno de Consultas                                                                                                     ')
insert into cl_errores values( 1909003     ,  0           , ' No se puede consultar garantias anuladas                                                                                             ')
go
insert into cl_errores values( 1909004     ,  0           , ' Tramite abierto, ya se envio carta a abogado                                                                                         ')
insert into cl_errores values( 1909005     ,  0           , ' Proceso terminado por una abogado                                                                                                    ')
insert into cl_errores values( 1909006     ,  0           , ' Garantia en tramite                                                                                                                  ')
insert into cl_errores values( 1910001     ,  0           , ' No se permite cambio de estado                                                                                                       ')
insert into cl_errores values( 1910002     ,  0           , ' No se realiz½ el cambio de estado automÿtico                                                                                         ')
insert into cl_errores values( 1910003     ,  0           , ' No se realiz½ el cambio de estado automÿtico por reversa                                                                             ')
insert into cl_errores values( 1910004     ,  0           , ' Esta bajando el valor de una garantia con marca de Agotamiento                                                                       ')
insert into cl_errores values( 1910005     ,  0           , ' Porcentaje de cubrimiento mayor al parametrizado                                                                                     ')
insert into cl_errores values( 1912001     ,  0           , ' Valor inicial errado cu_valor_inicial                                                                                                ')
insert into cl_errores values( 1912002     ,  0           , ' Inspeccion errada cu_inspeccionar                                                                                                    ')
insert into cl_errores values( 1912003     ,  0           , ' Cuantia diferente de I cu_cuantia                                                                                                    ')
insert into cl_errores values( 1912004     ,  0           , ' Error en castigo cu_castigo                                                                                                          ')
insert into cl_errores values( 1912005     ,  0           , ' Error en insercion de cliente garantia                                                                                               ')
insert into cl_errores values( 1912006     ,  0           , ' Abierta cerrada no valido cu_abierta_cerrada                                                                                         ')
insert into cl_errores values( 1912007     ,  0           , ' Clase de custodia no valido cu_clase_custodia                                                                                        ')
insert into cl_errores values( 1912008     ,  0           , ' Error en numero de acciones  cu_num_acciones                                                                                         ')
insert into cl_errores values( 1912009     ,  0           , ' Error en valor de la accion  cu_valor_accion                                                                                         ')
insert into cl_errores values( 1912010     ,  0           , ' Error en cobertura                                                                                                                   ')
insert into cl_errores values( 1912011     ,  0           , ' Error en siniestro cu_siniestro                                                                                                      ')
insert into cl_errores values( 1912012     ,  0           , ' Error en clase de custodia                                                                                                           ')
insert into cl_errores values( 1912013     ,  0           , ' Porcentaje valor errado cu_poecentaje_valor                                                                                          ')
insert into cl_errores values( 1912014     ,  0           , ' Fecha de constitucion errada cu_fecha_const                                                                                          ')
insert into cl_errores values( 1912015     ,  0           , ' Fecha de inspeccion errada                                                                                                           ')
insert into cl_errores values( 1912016     ,  0           , ' Fecha de modificacion errada cu_fecha_modif                                                                                          ')
insert into cl_errores values( 1912017     ,  0           , ' Provisiona errada cu_provisiona                                                                                                      ')
insert into cl_errores values( 1912018     ,  0           , ' Fecha de vencimiento errada  cu_fecha_vcto                                                                                           ')
insert into cl_errores values( 1912019     ,  0           , ' Cliente no existe en MIS                                                                                                             ')
insert into cl_errores values( 1912020     ,  0           , ' Valor actual errado cu_valor_actual                                                                                                  ')
insert into cl_errores values( 1912021     ,  0           , ' Compartida no valida  cu_compartida                                                                                                  ')
insert into cl_errores values( 1912022     ,  0           , ' Error en generacion de tabla de migracion                                                                                            ')
insert into cl_errores values( 1912023     ,  0           , ' Filiar errada cg_filial                                                                                                              ')
insert into cl_errores values( 1912024     ,  0           , ' Cliente no existe en MIS, cg_ente                                                                                                    ')
insert into cl_errores values( 1912025     ,  0           , ' Principal no valido, cg_principal                                                                                                    ')
insert into cl_errores values( 1912026     ,  0           , ' Clase de custodia errado cu_clase_custodia                                                                                           ')
insert into cl_errores values( 1912027     ,  0           , ' Garantia no existe en cu_custodia cg_cogigo_externo cg_ente                                                                          ')
insert into cl_errores values( 1912028     ,  0           , ' Cliente no existe en MIS gp_deudor                                                                                                   ')
insert into cl_errores values( 1912029     ,  0           , ' Garantia no existe en cu_custodia cg_cogigo_externo cg_ente                                                                          ')
insert into cl_errores values( 1912030     ,  0           , ' Error en insercion  de gar_propuesta                                                                                                 ')
insert into cl_errores values( 1912031     ,  0           , ' Cliente no existe en MIS, de gar propuesta                                                                                           ')
insert into cl_errores values( 1912032     ,  0           , ' Abierta tiene tipo errado en gar propuesta                                                                                           ')
insert into cl_errores values( 1912033     ,  0           , ' Estado diferente de V en gar propuesta                                                                                               ')
insert into cl_errores values( 1912034     ,  0           , ' Ente de emisora no existe o no coincide cu_entidad_emisora                                                                           ')
insert into cl_errores values( 1912035     ,  0           , ' Ente no coincide con MIS cu_garante                                                                                                  ')
insert into cl_errores values( 1912036     ,  0           , ' Ente no coincide en tabla de cliente_garantia  no existe en MIS cg_ente                                                              ')
insert into cl_errores values( 1912037     ,  0           , ' Cliente_garantia no existe en Garantias                                                                                              ')
insert into cl_errores values( 1912038     ,  0           , ' Error actualizando tabla de migracion por cliente_gar                                                                                ')
insert into cl_errores values( 1912039     ,  0           , ' No coincide ente com Mis en gar_propuesta                                                                                            ')
insert into cl_errores values( 1912040     ,  0           , ' Garantia sin migrar gp_garantia                                                                                                      ')
insert into cl_errores values( 1912041     ,  0           , ' Ente no coincide en tabla de gar_propuesta                                                                                           ')
insert into cl_errores values( 1912042     ,  0           , ' porcentaje errado en gar_propuesta                                                                                                   ')
insert into cl_errores values( 1912043     ,  0           , ' Valor disponible errado cu_disponible                                                                                                ')
insert into cl_errores values( 1912044     ,  0           , ' Codigo de abierta-cerra errado gp_abierta                                                                                            ')
insert into cl_errores values( 1912045     ,  0           , ' Estado de la garantia errado gp_est_garantia                                                                                         ')
insert into cl_errores values( 1912046     ,  0           , ' Porcentaje errado gp_porcentaje                                                                                                      ')
insert into cl_errores values( 1912047     ,  0           , ' Valor respaldo garantia errado gp_valor_resp_garantia                                                                                ')
insert into cl_errores values( 1912048     ,  0           , ' No existe almacenera en catalogo cu_almacenera                                                                                       ')
insert into cl_errores values( 1912050     ,  0           , ' Entidad especial errada cu_entidad_esp                                                                                               ')
insert into cl_errores values( 1912051     ,  0           , ' Garantia no existe en cu_custodia                                                                                                    ')
insert into cl_errores values( 1912052     ,  0           , ' Garantia ya fue migrada cu_codigo_externo                                                                                            ')
insert into cl_errores values( 1912053     ,  0           , ' Filial errada o diferente de 1 cu_filial                                                                                             ')
insert into cl_errores values( 1912054     ,  0           , ' Tipo de garantia errado cu_tipo                                                                                                      ')
insert into cl_errores values( 1912055     ,  0           , ' Oficina errada o no existe cu_oficina                                                                                                ')
insert into cl_errores values( 1912056     ,  0           , ' Ciudad  errada  cu_ciudad_prenda                                                                                                     ')
insert into cl_errores values( 1912057     ,  0           , ' Fecha de registro errada cu_fecha_reg                                                                                                ')
insert into cl_errores values( 1912058     ,  0           , ' Cliente garantia ya fue migrada cg_cogigo_externo cg_ente                                                                            ')
insert into cl_errores values( 1912059     ,  0           , ' Periodicidad errada cu_periodicidad                                                                                                  ')
insert into cl_errores values( 1912060     ,  0           , ' Tipo errado cg_tipo_cust                                                                                                             ')
insert into cl_errores values( 1912061     ,  0           , ' Oficina errada cg_sucursal                                                                                                           ')
insert into cl_errores values( 1912062     ,  0           , ' Tipo garante errado cg_tipo_garante                                                                                                  ')
insert into cl_errores values( 1912063     ,  0           , ' Gar_propuesta ya fue migrada gp_tramite gp_deudor                                                                                    ')
insert into cl_errores values( 1912064     ,  0           , ' Error actualizando tabla de migracion por gar_pruesta                                                                                ')
insert into cl_errores values( 1912065     ,  0           , ' Aseguradora no existe cu_aseguradora                                                                                                 ')
insert into cl_errores values( 1912066     ,  0           , ' Tipo no existe en tabla de homologaciones cu_tipo                                                                                    ')
insert into cl_errores values( 1912067     ,  0           , ' Tipo no existe cobis para cobertura cu_tipo                                                                                          ')
insert into cl_errores values( 1912068     ,  0           , ' Fuente de valor errada cu_fuente_valor                                                                                               ')
insert into cl_errores values( 1912069     ,  0           , ' Ubicacion no valida cu_ubicacion                                                                                                     ')
insert into cl_errores values( 1912070     ,  0           , ' Falta numeo de documento para garantia FAG cu_num_dcto                                                                               ')
insert into cl_errores values( 1912071     ,  0           , ' Valor coberura errado cm_valor_cobertura                                                                                             ')
insert into cl_errores values( 1912072     ,  0           , ' Clase de Vehiculo no Valida cu_clase_vehiculo                                                                                        ')
insert into cl_errores values( 1912073     ,  0           , ' Numero de identificacion no coincide con tabla cm_ced_ruc                                                                            ')
insert into cl_errores values( 1912074     ,  0           , ' Tipo de identificacion no coincide con tabla cm_tipo_ced                                                                             ')
insert into cl_errores values( 1912075     ,  0           , ' Numero de identificacion de entidad emisora no coincide con MIS                                                                      ')
insert into cl_errores values( 1912076     ,  0           , ' Tipo de identificacion de entidad emisora no coincide con Mis                                                                        ')
insert into cl_errores values( 1912077     ,  0           , ' Numero de identificacion de entidad emisora no coincide con MIS                                                                      ')
insert into cl_errores values( 1912078     ,  0           , ' Tipo de identificacion de entidad emisora no coincide con MIS                                                                        ')
insert into cl_errores values( 1912079     ,  0           , ' Numero de identificacion no coincide con tabla cu_custodia                                                                           ')
insert into cl_errores values( 1912080     ,  0           , ' Tipo de identificacion no coincide con tabla cu_custodia                                                                             ')
insert into cl_errores values( 1912081     ,  0           , ' Ente directo no coincide con tabla cu_custodia                                                                                       ')
insert into cl_errores values( 1912082     ,  0           , ' Tipo de garantia no coincide con cu_custodia                                                                                         ')
insert into cl_errores values( 1912083     ,  0           , ' No existe Ente cm_pdeudor                                                                                                            ')
insert into cl_errores values( 1912084     ,  0           , ' No existe registro en cu_cliente garantia cm_pgarantia cm_pdeudor                                                                    ')
insert into cl_errores values( 1912085     ,  0           , ' error en valor actual de la garantia cu_custodia                                                                                     ')
insert into cl_errores values( 1912086     ,  0           , ' No existe registro en cu_custodia  cm_codigo_externoi                                                                                ')
insert into cl_errores values( 1912087     ,  0           , ' Filial invalida cu_item_custodia   cm_filiali                                                                                        ')
insert into cl_errores values( 1912088     ,  0           , ' Registro ya fue migrado cu_item_custodia                                                                                             ')
insert into cl_errores values( 1912089     ,  0           , ' Oficina invalida cu_item_custodia cm_sucursali                                                                                       ')
insert into cl_errores values( 1912090     ,  0           , ' Tipo no exise cu_item_custodia cm_tipo_cusdi                                                                                         ')
insert into cl_errores values( 1912091     ,  0           , ' Item no corresponde  cm_tipo_custodi cm_itemi                                                                                        ')
insert into cl_errores values( 1912092     ,  0           , ' Error en grabacion de cu_item_custodia                                                                                               ')
insert into cl_errores values( 1912094     ,  0           , ' tipo no coincide con cu_custodia cm_tipo_custodia                                                                                    ')
insert into cl_errores values( 1912096     ,  0           , ' No existe obligacion en Cartera cr_gar_propuesta                                                                                     ')
insert into cl_errores values( 1912097     ,  0           , ' Tramite nulo cr_gar_propuesta                                                                                                        ')
insert into cl_errores values( 1912098     ,  0           , ' Par metro contable no programado                                                                                                     ')
insert into cl_errores values( 1912099     ,  0           , ' Par metro contable no pudo ser resuelto                                                                                              ')
insert into cl_errores values( 1912100     ,  0           , ' valor inicial menor al Valor actual cu_custodia                                                                                      ')
insert into cl_errores values( 1912110     ,  0           , ' valor disponible superior a valor actual cu_custodia                                                                                 ')
insert into cl_errores values( 1912112     ,  0           , ' Valor respaldado diferente a valor de la garantia                                                                                    ')
insert into cl_errores values( 1912113     ,  0           , ' Valor disponible mayor a cero                                                                                                        ')
insert into cl_errores values( 1912114     ,  0           , ' Valor Distribuido Menor o Igual a Cero                                                                                               ')
insert into cl_errores values( 1912115     ,  0           , ' No existe valor del Parametro                                                                                                        ')
insert into cl_errores values( 1912122     ,  0           , 'El cambio de estado no esta parametrizado')
insert into cl_errores values( 1912123     ,  0           , 'Cliente tiene créditos vigentes, deben cancelarse primero')
insert into cl_errores values( 1912124     ,  0           , 'Garantía no tiene asociada un cliente')
insert into cl_errores values( 1912125     ,  0           , 'No existe código valor')

go
