use cob_custodia
go

delete from cob_custodia..cu_tipo_custodia

insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('AVAL', null, 'AVALES', 'A', 'S', 100, 'A', 100, 'S', 'N', null, 'O', 'V', 'N', 'N', 'N', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('PAGARE', 'AVAL', 'PAGARE', 'A', 'S', 100, 'A', 100, 'S', 'N', null, 'O', 'V', 'N', 'N', 'N', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('HIP', null, 'GARANTIAS HIPOTECARIAS', 'A', 'S', null, 'A', 0, 'S', 'I', null,  'O', 'V', 'N', 'N', 'N', null, null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('VIVOTRAS', 'HIP', 'OTROS BIENES INMUEBLES', 'A', 'S', 100, 'A',100, 'S', 'I', null, 'O', 'V', 'N', 'N', 'S', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('VIVSOCIAL','HIP', 'VIVIENDA SOCIAL', 'A', 'S', 100,  'A', 100, 'S', 'I', null, 'O', 'V', 'N', 'N', 'S', null, null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('LIQ', null,'GARANTIAS LIQUIDAS', 'A', 'N', null, 'A', 0, 'N', 'E', null, 'I', 'V', 'N', 'N', 'N', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('AHORRO', 'LIQ', 'AHORROS', 'A', 'N', null, 'A', 0, 'N', 'E', null, 'O', 'V', 'N', 'N', 'N', null, null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('DPF','LIQ', 'DEPOSITOS A PLAZO FIJO','A', 'N', null, 'A', 0, 'N', 'E', null, 'O', 'V', 'N', 'N', 'N', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('PERS', null, 'GARANTIAS PERSONALES', 'A', 'N', null, 'C', 0, 'N', 'N', null,  'I', 'V', 'N', 'N', 'N', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('PERSONAL',  'PERS', 'PERSONALES', 'A', 'N', null,  'C', 0, 'N', 'N', null, 'O', 'V', 'N', 'N', 'N', 04,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('PREN', null, 'GARANTIAS PRENDARIAS', 'A', 'S', 70,  'C', 70, 'S', 'O', null, 'O', 'V', 'N', 'N', 'N', null,null)
insert into cob_custodia..cu_tipo_custodia(tc_tipo, tc_tipo_superior, tc_descripcion, tc_periodicidad, tc_contabilizar, tc_porcentaje, tc_clase, tc_porcen_cobertura, tc_monetaria, tc_tipo_bien, tc_garan_empleado, tc_adecuada, tc_estado, tc_multimoneda, tc_agotada, tc_ctr_vencimiento, tc_clase_garantia, tc_producto) values ('VEHICULO', 'PREN', 'VEHICULO', 'A', 'S', 70,  'C', 70,  'S', 'O', null, 'O' , 'V', 'N', 'N', 'S', null, null)
go

