package com.cobiscorp.ecobis.clientviewer.bl.utils;

public class Constants {

	public static final String LOAN_NOT_CURRENT = "NO VIGENTE", CURRENT_LOAN_CODE = "1", EXPIRED_LOAN_CODE = "2", LEGAL_LOAN_CODE = "10", NON_ACCURAL_LOAN_CODE = "11",
			LATES_STATUS_CODE = "21", CURRENT_FUTURE_CREDITS_GUARANTEE_CODE = "F", CURRENT_WITH_OBLIGATION_GUARANTEE_CODE = "V", CREDIT_LOAN_CODE = "99", COMEXT_LOAN_CODE = "98",
			NOT_CURRENT_LOAN_CODE = "0", PROPOSED_GUARANTEE_CODE = "P", CURRENT_TO_CANCEL = "X", GUARANTEE_CANCEL="C";

	public static final String[] LOANS_CURRENT_STATUS_ARRAY = { CURRENT_LOAN_CODE, EXPIRED_LOAN_CODE, LEGAL_LOAN_CODE, NON_ACCURAL_LOAN_CODE, LATES_STATUS_CODE };
	public static final String[] GUARANTEES_CURRENT_STATUS_ARRAY = { CURRENT_FUTURE_CREDITS_GUARANTEE_CODE, CURRENT_WITH_OBLIGATION_GUARANTEE_CODE };
	public static final String[] GUARANTEES_CURRENT_STATUS_ARRAY_HIS = { CURRENT_FUTURE_CREDITS_GUARANTEE_CODE, CURRENT_WITH_OBLIGATION_GUARANTEE_CODE, GUARANTEE_CANCEL };
	public static final String[] LOANS_PENDING_STATUS_ARRAY = { NOT_CURRENT_LOAN_CODE, COMEXT_LOAN_CODE, CREDIT_LOAN_CODE };
	public static final String[] GUARANTEES_PENDING_STATUS_ARRAY = { PROPOSED_GUARANTEE_CODE, CURRENT_TO_CANCEL };
	public static final String DEUDAS = "DEUD";

	// PARAMETRO GENERAL CÓNYUGE
	public static final String PRODUCT_PARAMETER_COUPLE = "CRE";
	public static final String MNEMONIC_COUPLE = "COU";
	public static final int DEFAULT_PARAMETER = 2;
}
