
use cob_credito
go
if exists(select 1 from sysobjects where name like 'cr_resultado_xml' and type = 'U')
   drop table cr_resultado_xml
create table cr_resultado_xml(linea xml)
go
-- ---------------------------------------------------------------------------------

use cobis
go
DELETE FROM ba_sarta WHERE sa_sarta =5
go

insert into cobis..ba_sarta ( sa_sarta, sa_nombre, sa_descripcion, sa_fecha_creacion, sa_creador, sa_producto, sa_dependencia, sa_autorizacion ) 
values ( 5, 'REPORTES DE CARTERA', 'REPORTES DE CARTERA', getDate(), 'admuser', 36, NULL, NULL )

-- ----------------------------------------------------
DELETE FROM ba_sarta_batch WHERE sb_sarta =5

insert into ba_sarta_batch ( sb_sarta, sb_batch, sb_secuencial, sb_dependencia, sb_repeticion, sb_critico, sb_left, sb_top, sb_lote_inicio, sb_habilitado ) 
values (5, 7006, 1, NULL, 'S', 'N', 500, 550, 5, 'S' )

insert into ba_sarta_batch ( sb_sarta, sb_batch, sb_secuencial, sb_dependencia, sb_repeticion, sb_critico, sb_left, sb_top, sb_lote_inicio, sb_habilitado ) 
values (5, 28537, 2, NULL, 'S', 'N', 2000, 550, 5, 'S' )

insert into ba_sarta_batch ( sb_sarta, sb_batch, sb_secuencial, sb_dependencia, sb_repeticion, sb_critico, sb_left, sb_top, sb_lote_inicio, sb_habilitado ) 
values (5, 28793, 3, NULL, 'S', 'N', 3500, 550, 5, 'S' )

insert into ba_sarta_batch (sb_sarta, sb_batch, sb_secuencial, sb_dependencia, sb_repeticion, sb_critico, sb_left, sb_top, sb_lote_inicio, sb_habilitado)
values (5, 36007, 4, NULL, 'S', 'N', 5500, 550, 5, 'S')

insert into ba_sarta_batch (sb_sarta, sb_batch, sb_secuencial, sb_dependencia, sb_repeticion, sb_critico, sb_left, sb_top, sb_lote_inicio, sb_habilitado)
values (5, 36008, 5, NULL, 'S', 'N', 7000, 550, 5, 'S')

insert into ba_sarta_batch (sb_sarta, sb_batch, sb_secuencial, sb_dependencia, sb_repeticion, sb_critico, sb_left, sb_top, sb_lote_inicio, sb_habilitado)
values (5, 36009, 6, NULL, 'S', 'N', 8500, 550, 5, 'S')
go

-- ----------------------------------------------------
DELETE FROM ba_enlace WHERE en_sarta =5

insert into ba_enlace ( en_sarta, en_batch_inicio, en_secuencial_inicio, en_batch_fin, en_secuencial_fin, en_tipo_enlace, en_puntos, en_entre_lotes ) 
values ( 5, 7006, 1, 28537, 2, 'S', NULL, 'N' )
insert into ba_enlace ( en_sarta, en_batch_inicio, en_secuencial_inicio, en_batch_fin, en_secuencial_fin, en_tipo_enlace, en_puntos, en_entre_lotes ) 
values ( 5, 28537, 2, 28793, 3, 'S', NULL, 'N' )
insert into ba_enlace ( en_sarta, en_batch_inicio, en_secuencial_inicio, en_batch_fin, en_secuencial_fin, en_tipo_enlace, en_puntos, en_entre_lotes ) 
values ( 5, 28793, 3, 36007, 4, 'S', NULL, 'N' )
insert into ba_enlace (en_sarta, en_batch_inicio, en_secuencial_inicio, en_batch_fin, en_secuencial_fin, en_tipo_enlace, en_puntos, en_entre_lotes)
values ( 5, 36007, 4, 36008, 5, 'S', NULL, 'N')
insert into ba_enlace (en_sarta, en_batch_inicio, en_secuencial_inicio, en_batch_fin, en_secuencial_fin, en_tipo_enlace, en_puntos, en_entre_lotes)
values ( 5, 36008, 5, 36009, 6, 'S', NULL, 'N')
insert into ba_enlace (en_sarta, en_batch_inicio, en_secuencial_inicio, en_batch_fin, en_secuencial_fin, en_tipo_enlace, en_puntos, en_entre_lotes)
values ( 5, 36009, 6,     0, 0, 'S', NULL, 'N')
go

-- ----------------------------------------------------
declare @w_server varchar(24),         @w_path_fuente_car varchar(255), @w_path_fuente_cre varchar(255),
        @w_path_dest_cre varchar(255), @w_path_fuente varchar(255),     @w_path_destino varchar(255)
select @w_server = pa_char
from cl_parametro 
where pa_producto = 'ADM'
and   pa_nemonico = 'SRVR'

select @w_path_fuente = pp_path_fuente, @w_path_destino = pp_path_destino
from ba_path_pro where pp_producto = 36
select @w_path_fuente_car = pp_path_fuente from ba_path_pro where pp_producto = 7
select @w_path_fuente_cre = pp_path_fuente ,
       @w_path_dest_cre = pp_path_destino 
from ba_path_pro where pp_producto = 21

delete from ba_batch where ba_batch in (36007,7006,28537,28793,36007,36008,36009)

insert into dbo.ba_batch (ba_batch, ba_nombre, ba_descripcion, ba_lenguaje, ba_fecha_creacion, ba_producto, ba_tipo_batch, ba_sec_corrida, ba_ente_procesado, ba_arch_resultado, ba_arch_fuente, ba_frec_reg_proc, ba_impresora, ba_serv_destino, ba_reproceso, ba_path_fuente, ba_path_destino)
values (36007, 'GENERACION DE REPORTE BURO INTF', 'RGENERACION DE REPORTE BURO INTF', 'SP', getdate(), 36, 'P', 1, 'sb_reporte_buro_cuentas', NULL, 'cob_conta_super..sp_genera_buro', 10000, NULL, @w_server, 'S', @w_path_fuente, @w_path_destino)
insert into dbo.ba_batch (ba_batch, ba_nombre, ba_descripcion, ba_lenguaje, ba_fecha_creacion, ba_producto, ba_tipo_batch, ba_sec_corrida, ba_ente_procesado, ba_arch_resultado, ba_arch_fuente, ba_frec_reg_proc, ba_impresora, ba_serv_destino, ba_reproceso, ba_path_fuente, ba_path_destino)
values (36008, 'GENERACION DE REPORTE CFDI-SAT', 'GENERACION DE REPORTE CFDI-SAT', 'SP', getdate(), 21, 'P', 1, null, 'CFDI_[CODCLI]_[FECHA].xml', 'cob_credito..sp_genera_estado_cta_xml', 10000, NULL, @w_server, 'S', @w_path_fuente_cre, @w_path_dest_cre)

insert into dbo.ba_batch (ba_batch, ba_nombre, ba_descripcion, ba_lenguaje, ba_fecha_creacion, ba_producto, ba_tipo_batch, ba_sec_corrida, ba_ente_procesado, ba_arch_resultado, ba_arch_fuente, ba_frec_reg_proc, ba_impresora, ba_serv_destino, ba_reproceso, ba_path_fuente, ba_path_destino)
values (36009, 'MOVIMIENTO ARCHIVOS PARA ESTADO CTA', 'NOTIFICACION ESTADO DE CTA', 'SP', getdate(), 21, 'P', 1, null, 'CFDI_[CODCLI]_[FECHA].xml', 'cob_credito..sp_cr_ejecuta_move_jar', 10000, NULL, @w_server, 'S', @w_path_dest_cre + 'estcta/', 'c:/Notificador/notification/reportes/estcta/')

insert into cobis..ba_batch ( ba_batch, ba_nombre, ba_descripcion, ba_lenguaje, ba_fecha_creacion, ba_producto, ba_tipo_batch, ba_sec_corrida, ba_ente_procesado, ba_arch_resultado, ba_arch_fuente, ba_frec_reg_proc, ba_impresora, ba_serv_destino, ba_reproceso, ba_path_fuente, ba_path_destino ) 
values ( 7006, 'CONSOLIDADOR CARTERA', 'CONSOLIDADOR CARTERA', 'SP ', getDate(), 7, 'P', 1, 'CARTERA', NULL, 'cob_cartera..sp_consolidador', 1, NULL, @w_server, 'S', @w_path_fuente_car , NULL)
insert into cobis..ba_batch ( ba_batch, ba_nombre, ba_descripcion, ba_lenguaje, ba_fecha_creacion, ba_producto, ba_tipo_batch, ba_sec_corrida, ba_ente_procesado, ba_arch_resultado, ba_arch_fuente, ba_frec_reg_proc, ba_impresora, ba_serv_destino, ba_reproceso, ba_path_fuente, ba_path_destino ) 
values ( 28537, 'PASO DE DATOS COB_EXTERNOS A TBL DEF COB_CONTA_SUPER', 'PASODE DATOS COB_EXTERNOS A TBL DEF COB_CONTA_SUPER', 'SP ', getDate(), 36, 'P', 1, 'OPERACION', NULL, 'cob_conta_super..sp_datos_operacion', 1000, NULL, @w_server, 'S', @w_path_fuente, @w_path_destino )
insert into cobis..ba_batch ( ba_batch, ba_nombre, ba_descripcion, ba_lenguaje, ba_fecha_creacion, ba_producto, ba_tipo_batch, ba_sec_corrida, ba_ente_procesado, ba_arch_resultado, ba_arch_fuente, ba_frec_reg_proc, ba_impresora, ba_serv_destino, ba_reproceso, ba_path_fuente, ba_path_destino ) 
values ( 28793, 'REPORTE OPERATIVO DE CARTERA', 'REPORTE OPERATIVO DE CARTERA', 'SP ', getDate(), 36, 'P', 1, NULL, NULL, 'cob_conta_super..sp_reporte_operativo', 10000, NULL, @w_server, 'S', @w_path_fuente, @w_path_destino )
go

delete from cobis..ba_parametro where  pa_batch in (36007,36008) and pa_sarta = 0
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 0, 36007, 0, 1, 'FECHA PROCESO', 'D', '06/16/2017' )
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 0, 36008, 0, 1, 'FECHA PROCESO', 'D', '06/16/2017' )
go
delete from cobis..ba_parametro 
where  pa_batch in (select sb_batch from ba_sarta_batch where sb_sarta=5) and pa_sarta = 5
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 5, 28537, 2, 1, 'FECHA DE PROCESO', 'D', '06/09/2017' )
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 5, 28537, 2, 2, 'OPERACION (TO/DO/DT/PY/DD)', 'C', 'DO' )
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 5, 28793, 3, 1, 'FECHA PROCESO', 'D', '06/09/2017' )
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 5, 28793, 3, 2, 'PROCESO', 'I', '28793' )
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 5, 36007, 4, 1, 'FECHA PROCESO', 'D', '06/16/2017' )
insert into cobis..ba_parametro ( pa_sarta, pa_batch, pa_ejecucion, pa_parametro, pa_nombre, pa_tipo, pa_valor ) 
values ( 5, 36008, 5, 1, 'FECHA PROCESO', 'D', '06/16/2017' )
go


-- ---------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------
use cob_conta_super
go
create table #temp_cat_equiv(
   codigo char(10) null,
   abrv varchar(4) null,
   descrip varchar(60) null
)

insert into #temp_cat_equiv(codigo,descrip,abrv) values('AFG','Afganistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ALA','Islas Åland','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ALB','Albania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DEU','Alemania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AND','Andorra','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AGO','Angola','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AIA','Anguila','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ATA','Antártida','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ATG','Antigua y Barbuda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SAU','Arabia Saudita','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DZA','Argelia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ARG','Argentina','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ARM','Armenia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ABW','Aruba','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AUS','Australia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AUT','Austria','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AZE','Azerbaiyán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BHS','Bahamas (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BGD','Bangladés','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BRB','Barbados','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BHR','Baréin','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BEL','Bélgica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BLZ','Belice','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BEN','Benín','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BMU','Bermudas','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BLR','Bielorrusia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MMR','Myanmar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BOL','Bolivia, Estado Plurinacional de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BIH','Bosnia y Herzegovina','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BWA','Botsuana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BRA','Brasil','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BRN','Brunéi Darussalam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BGR','Bulgaria','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BFA','Burkina Faso','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BDI','Burundi','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BTN','Bután','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CPV','Cabo Verde','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KHM','Camboya','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CMR','Camerún','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CAN','Canadá','[A-Z][0-9][A-Z] [0-9][A-Z][0-9]')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('QAT','Catar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BES','Bonaire, San Eustaquio y Saba','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TCD','Chad','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CHL','Chile','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CHN','China','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CYP','Chipre','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COL','Colombia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COM','Comoras','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRK','Corea (la República Democrática Popular de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KOR','Corea (la República de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CIV','Côte d Ivoire','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CRI','Costa Rica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HRV','Croacia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CUB','Cuba','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CUW','Curaçao','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DNK','Dinamarca','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DMA','Dominica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ECU','Ecuador','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('EGY','Egipto','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SLV','El Salvador','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ARE','Emiratos Árabes Unidos (Los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ERI','Eritrea','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SVK','Eslovaquia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SVN','Eslovenia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ESP','España','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('USA','Estados Unidos (los)','[0-9]{5}(-[0-9]{4})?')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('EST','Estonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ETH','Etiopía','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PHL','Filipinas (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FIN','Finlandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FJI','Fiyi','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FRA','Francia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GAB','Gabón','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GMB','Gambia (La)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GEO','Georgia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GHA','Ghana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GIB','Gibraltar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GRD','Granada','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GRC','Grecia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GRL','Groenlandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GLP','Guadalupe','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GUM','Guam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GTM','Guatemala','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GUF','Guayana Francesa','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GGY','Guernsey','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GIN','Guinea','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GNB','Guinea-Bisáu','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GNQ','Guinea Ecuatorial','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GUY','Guyana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HTI','Haití','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HND','Honduras','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HKG','Hong Kong','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HUN','Hungría','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IND','India','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IDN','Indonesia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IRQ','Irak','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IRN','Irán (la República Islámica de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IRL','Irlanda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BVT','Isla Bouvet','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IMN','Isla de Man','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CXR','Isla de Navidad','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NFK','Isla Norfolk','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ISL','Islandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CYM','Islas Caimán (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CCK','Islas Cocos (Keeling)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COK','Islas Cook (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FRO','Islas Feroe (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SGS','Georgia del sur y las islas sandwich del sur','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HMD','Isla Heard e Islas McDonald','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FLK','Islas Malvinas [Falkland] (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MNP','Islas Marianas del Norte (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MHL','Islas Marshall (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PCN','Pitcairn','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SLB','Islas Salomón (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TCA','Islas Turcas y Caicos (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UMI','Islas de Ultramar Menores de Estados Unidos (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VGB','Islas Vírgenes (Británicas)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VIR','Islas Vírgenes (EE.UU.)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ISR','Israel','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ITA','Italia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JAM','Jamaica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JPN','Japón','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JEY','Jersey','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JOR','Jordania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KAZ','Kazajistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KEN','Kenia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KGZ','Kirguistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KIR','Kiribati','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KWT','Kuwait','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LAO','Lao, (la) República Democrática Popular','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LSO','Lesoto','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LVA','Letonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LBN','Líbano','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LBR','Liberia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LBY','Libia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LIE','Liechtenstein','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LTU','Lituania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LUX','Luxemburgo','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MAC','Macao','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MDG','Madagascar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MYS','Malasia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MWI','Malaui','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MDV','Maldivas','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MLI','Malí','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MLT','Malta','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MAR','Marruecos','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MTQ','Martinica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MUS','Mauricio','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MRT','Mauritania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MYT','Mayotte','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MEX','México','[0-9]{5}')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FSM','Micronesia (los Estados Federados de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MDA','Moldavia (la República de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MCO','Mónaco','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MNG','Mongolia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MNE','Montenegro','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MSR','Montserrat','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MOZ','Mozambique','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NAM','Namibia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NRU','Nauru','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NPL','Nepal','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NIC','Nicaragua','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NER','Níger (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NGA','Nigeria','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NIU','Niue','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NOR','Noruega','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NCL','Nueva Caledonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NZL','Nueva Zelanda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('OMN','Omán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NLD','Países Bajos (los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PAK','Pakistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PLW','Palaos','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PSE','Palestina, Estado de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PAN','Panamá','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PNG','Papúa Nueva Guinea','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRY','Paraguay','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PER','Perú','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PYF','Polinesia Francesa','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('POL','Polonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRT','Portugal','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRI','Puerto Rico','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GBR','Reino Unido (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CAF','República Centroafricana (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CZE','República Checa (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MKD','Macedonia (la antigua República Yugoslava de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COG','Congo','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COD','Congo (la República Democrática del)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DOM','República Dominicana (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('REU','Reunión','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('RWA','Ruanda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ROU','Rumania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('RUS','Rusia, (la) Federación de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ESH','Sahara Occidental','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('WSM','Samoa','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ASM','Samoa Americana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BLM','San Bartolomé','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KNA','San Cristóbal y Nieves','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SMR','San Marino','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MAF','San Martín (parte francesa)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SPM','San Pedro y Miquelón','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VCT','San Vicente y las Granadinas','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SHN','Santa Helena, Ascensión y Tristán de Acuña','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LCA','Santa Lucía','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('STP','Santo Tomé y Príncipe','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SEN','Senegal','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SRB','Serbia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SYC','Seychelles','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SLE','Sierra leona','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SGP','Singapur','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SXM','Sint Maarten (parte holandesa)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SYR','Siria, (la) República Árabe','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SOM','Somalia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LKA','Sri Lanka','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SWZ','Suazilandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZAF','Sudáfrica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SDN','Sudán (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SSD','Sudán del Sur','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SWE','Suecia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CHE','Suiza','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SUR','Surinam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SJM','Svalbard y Jan Mayen','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('THA','Tailandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TWN','Taiwán (Provincia de China)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TZA','Tanzania, República Unida de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TJK','Tayikistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IOT','Territorio Británico del Océano Índico (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ATF','Territorios Australes Franceses (los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TLS','Timor-Leste','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TGO','Togo','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TKL','Tokelau','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TON','Tonga','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TTO','Trinidad y Tobago','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TUN','Túnez','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TKM','Turkmenistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TUR','Turquía','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TUV','Tuvalu','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UKR','Ucrania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UGA','Uganda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('URY','Uruguay','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UZB','Uzbekistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VUT','Vanuatu','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VAT','Santa Sede[Estado de la Ciudad del Vaticano] (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VEN','Venezuela, República Bolivariana de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VNM','Viet Nam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('WLF','Wallis y Futuna','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('YEM','Yemen','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DJI','Yibuti','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZMB','Zambia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZWE','Zimbabue','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZZZ','Países no declarados','')

delete from sb_equivalencias where eq_catalogo = 'ESTADOS_A7'

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
select 'ESTADOS_A7', c.codigo, tp.codigo, tp.descrip, 'V'
  from cobis..cl_catalogo c , #temp_cat_equiv tp
 where tabla = (select codigo from cobis..cl_tabla where tabla = 'cl_pais')
   and replace(replace(replace(replace(replace(upper(descrip),'Á','A'),'É','E'),'Í','I'),'Ó','O'),'Ú','U')
  like replace(replace(replace(replace(replace(upper(valor),'Á','A') ,'É','E'),'Í','I'),'Ó','O'),'Ú','U')
go
delete from #temp_cat_equiv
go

