DELETE cobis..cl_parametro
WHERE pa_producto = 'CCA'
AND pa_nemonico IN ('CCCOM',   'CCCON', 'CCVIV',  'CSMIC')
GO

--PARAMETROS PARA CLASES Y SUBTIPOS DE PRESTAMOS 
INSERT INTO cobis..cl_parametro VALUES('CODIGO CLASE COMERCIAL', 'CCCOM', 'C', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'CCA')
INSERT INTO cobis..cl_parametro VALUES('CODIGO CLASE CONSUMO', 'CCCON', 'C', '2', NULL, NULL, NULL, NULL, NULL, NULL, 'CCA')
INSERT INTO cobis..cl_parametro VALUES('CODIGO CLASE VIVIENDA', 'CCVIV', 'C', '3', NULL, NULL, NULL, NULL, NULL, NULL, 'CCA')
INSERT INTO cobis..cl_parametro VALUES('CODIGO SUBTIPO MICROCREDITO', 'CSMIC', 'C', '05', NULL, NULL, NULL, NULL, NULL, NULL, 'CCA')
GO