/*
 * Crédito en Línea
 * Servicios para aplicación de crédito en    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pablo.lopez@ndeveloper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cobiscorp.mobile.model;

import java.util.Objects;

/**
 * Client
 */
public class Client {

	private Long registryCode = null;

	private String nombres = null;

	private String apellidos = null;

	private String numeroTramite = null;

	private String telefono = null;

	private String idCliente = null;

	private String numeroCredito = null;
	
	private String ipLocal = null;
	
	private String idSesionCliente = null;

	public Client registryCode(Long registryCode) {
		this.registryCode = registryCode;
		return this;
	}

	/**
	 * Get registryCode
	 * 
	 * @return registryCode
	 **/
	public Long getRegistryCode() {
		return registryCode;
	}

	public void setRegistryCode(Long registryCode) {
		this.registryCode = registryCode;
	}

	public Client nombres(String nombres) {
		this.nombres = nombres;
		return this;
	}

	/**
	 * Get nombres
	 * 
	 * @return nombres
	 **/
	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public Client apellidos(String apellidos) {
		this.apellidos = apellidos;
		return this;
	}

	/**
	 * Get apellidos
	 * 
	 * @return apellidos
	 **/
	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Client numeroTramite(String numeroTramite) {
		this.numeroTramite = numeroTramite;
		return this;
	}

	/**
	 * Get numeroTramite
	 * 
	 * @return numeroTramite
	 **/
	public String getNumeroTramite() {
		return numeroTramite;
	}

	public void setNumeroTramite(String numeroTramite) {
		this.numeroTramite = numeroTramite;
	}

	public Client telefono(String telefono) {
		this.telefono = telefono;
		return this;
	}

	/**
	 * Get telefono
	 * 
	 * @return telefono
	 **/
	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Client idCliente(String idCliente) {
		this.idCliente = idCliente;
		return this;
	}

	/**
	 * Get idCliente
	 * 
	 * @return idCliente
	 **/
	public String getIdCliente() {
		return idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public String getNumeroCredito() {
		return numeroCredito;
	}

	public void setNumeroCredito(String codigoCredito) {
		this.numeroCredito = codigoCredito;
	}

	public String getIpLocal() {
		return ipLocal;
	}

	public void setIpLocal(String ipLocal) {
		this.ipLocal = ipLocal;
	}

	public String getIdSesionCliente() {
		return idSesionCliente;
	}

	public void setIdSesionCliente(String idSesionCliente) {
		this.idSesionCliente = idSesionCliente;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Client client = (Client) o;
		return Objects.equals(this.registryCode, client.registryCode) && Objects.equals(this.nombres, client.nombres) && Objects.equals(this.apellidos, client.apellidos)
				&& Objects.equals(this.numeroTramite, client.numeroTramite) && Objects.equals(this.telefono, client.telefono) && Objects.equals(this.idCliente, client.idCliente);
	}

	@Override
	public int hashCode() {
		return Objects.hash(registryCode, nombres, apellidos, numeroTramite, telefono, idCliente);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Client {\n");
		sb.append("    registryCode: ").append(toIndentedString(registryCode)).append("\n");
		sb.append("    nombres: ").append(toIndentedString(nombres)).append("\n");
		sb.append("    apellidos: ").append(toIndentedString(apellidos)).append("\n");
		sb.append("    numeroTramite: ").append(toIndentedString(numeroTramite)).append("\n");
		sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
		sb.append("    idCliente: ").append(toIndentedString(idCliente)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
