/*
 * Crédito en Línea
 * Servicios para aplicación de crédito en    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pablo.lopez@ndeveloper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cobiscorp.mobile.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.codehaus.jackson.annotate.JsonProperty;

/**
 * GeneralParameters
 */
public class GeneralParameters {

	private BigDecimal porcentajeIva = null;

	private BigDecimal montoMinDis = null;

	private List<TablaComision> tablaComision = null;

	private List<Notification> notificaciones = null;

	public GeneralParameters porcentajeIva(BigDecimal porcentajeIva, BigDecimal montoMinDis) {
		this.porcentajeIva = porcentajeIva;
		this.montoMinDis = montoMinDis;
		return this;
	}

	/**
	 * Get porcentajeIva
	 * 
	 * @return porcentajeIva
	 **/
	public BigDecimal getPorcentajeIva() {
		return porcentajeIva;
	}

	public void setPorcentajeIva(BigDecimal porcentajeIva) {
		this.porcentajeIva = porcentajeIva;
	}

	public BigDecimal getMontoMinDis() {
		return montoMinDis;
	}

	public void setMontoMinDis(BigDecimal montoMinDis) {
		this.montoMinDis = montoMinDis;
	}

	public GeneralParameters tablaComision(List<TablaComision> tablaComision) {
		this.tablaComision = tablaComision;
		return this;
	}

	public void addTablaComisionItem(TablaComision tablaComisionItem) {
		if (this.tablaComision == null) {
			this.tablaComision = new ArrayList<TablaComision>();
		}
		this.tablaComision.add(tablaComisionItem);
	}

	public void addNotificacionItem(Notification notificacion) {
		if (this.notificaciones == null) {
			this.notificaciones = new ArrayList<Notification>();
		}
		this.notificaciones.add(notificacion);
	}

	/**
	 * Get tablaComision
	 * 
	 * @return tablaComision
	 **/
	@JsonProperty("tablaComision")
	public List<TablaComision> getTablaComision() {
		return tablaComision;
	}

	public void setTablaComision(List<TablaComision> tablaComision) {
		this.tablaComision = tablaComision;
	}

	public List<Notification> getNotificaciones() {
		return notificaciones;
	}

	public void setNotificaciones(List<Notification> notificaciones) {
		this.notificaciones = notificaciones;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GeneralParameters generalParameters = (GeneralParameters) o;
		return Objects.equals(this.porcentajeIva, generalParameters.porcentajeIva) && Objects.equals(this.montoMinDis, generalParameters.montoMinDis)
				&& Objects.equals(this.tablaComision, generalParameters.tablaComision) && Objects.equals(this.notificaciones, generalParameters.notificaciones);
	}

	@Override
	public int hashCode() {
		return Objects.hash(porcentajeIva, montoMinDis, tablaComision, notificaciones);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GeneralParameters {\n");

		sb.append("    porcentajeIva: ").append(toIndentedString(porcentajeIva)).append("\n");
		sb.append("    montoMinDis: ").append(toIndentedString(montoMinDis)).append("\n");
		sb.append("    tablaComision: ").append(toIndentedString(tablaComision)).append("\n");
		sb.append("    notificacion: ").append(toIndentedString(notificaciones)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
