/*
 * Crédito en Línea
 * Servicios para aplicación de crédito en    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pablo.lopez@ndeveloper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cobiscorp.mobile.model;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * LoanRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-16T15:36:20.152Z")
public class LoanRequest {
	private BigDecimal amount = null;
	private String loanId = null;
	private BigDecimal vatPercentage = null;
	private BigDecimal commision = null;
	private BigDecimal amountCapital = null;

	public LoanRequest() {
		super();
	}

	public LoanRequest(String loanId, BigDecimal amount, BigDecimal vatPercentage, BigDecimal commision, BigDecimal amountCapital) {
		super();
		this.amount = amount;
		this.loanId = loanId;
		this.vatPercentage = vatPercentage;
		this.commision = commision;
		this.amountCapital = amountCapital;
	}

	/**
	 * Get amount
	 * 
	 * @return amount
	 **/
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * @return the loanId
	 */
	public String getLoanId() {
		return loanId;
	}

	/**
	 * @param loanId the loanId to set
	 */
	public void setLoanId(String loanId) {
		this.loanId = loanId;
	}

	/**
	 * @return the vatPercentage
	 */
	public BigDecimal getVatPercentage() {
		return vatPercentage;
	}

	/**
	 * @param vatPercentage the vatPercentage to set
	 */
	public void setVatPercentage(BigDecimal vatPercentage) {
		this.vatPercentage = vatPercentage;
	}

	/**
	 * @return the commision
	 */
	public BigDecimal getCommision() {
		return commision;
	}

	/**
	 * @param commision the commision to set
	 */
	public void setCommision(BigDecimal commision) {
		this.commision = commision;
	}

	/**
	 * @return the amountCapital
	 */
	public BigDecimal getAmountCapital() {
		return amountCapital;
	}

	/**
	 * @param amountCapital the amountCapital to set
	 */
	public void setAmountCapital(BigDecimal amountCapital) {
		this.amountCapital = amountCapital;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LoanRequest loanRequest = (LoanRequest) o;
		return Objects.equals(this.amount, loanRequest.amount);
	}

	@Override
	public int hashCode() {
		return Objects.hash(amount);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LoanRequest {\n");

		sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
		sb.append("    loanId: ").append(toIndentedString(loanId)).append("\n");
		sb.append("    vatPercentage: ").append(toIndentedString(vatPercentage)).append("\n");
		sb.append("    commision: ").append(toIndentedString(commision)).append("\n");
		sb.append("    amountCapital: ").append(toIndentedString(amountCapital)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
