/*
 * Crédito en Línea
 * Servicios para aplicación de crédito en    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pablo.lopez@ndeveloper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cobiscorp.mobile.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * Password
 */
public class Password implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String value = null;
	private String brandDevice = null;
	private String modelDevice = null;
	private String versionOS = null;
	private String carrier = null;
	private String device;
	private String connectAddress = null;

	public Password() {
		super();
	}

	public Password(String value, String brandDevice, String modelDevice, String versionOS, String carrier) {
		super();
		this.value = value;
		this.brandDevice = brandDevice;
		this.modelDevice = modelDevice;
		this.versionOS = versionOS;
		this.carrier = carrier;
	}

	public Password value(String value) {
		this.value = value;
		return this;
	}

	/**
	 * Get value
	 * 
	 * @return value
	 **/
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDevice() {
		return device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public Password brandDevice(String brandDevice) {
		this.brandDevice = brandDevice;
		return this;
	}

	/**
	 * Get brandDevice
	 * 
	 * @return brandDevice
	 **/
	public String getBrandDevice() {
		return brandDevice;
	}

	public void setBrandDevice(String brandDevice) {
		this.brandDevice = brandDevice;
	}

	public Password modelDevice(String modelDevice) {
		this.modelDevice = modelDevice;
		return this;
	}

	/**
	 * Get modelDevice
	 * 
	 * @return modelDevice
	 **/
	public String getModelDevice() {
		return modelDevice;
	}

	public void setModelDevice(String modelDevice) {
		this.modelDevice = modelDevice;
	}

	public Password versionOS(String versionOS) {
		this.versionOS = versionOS;
		return this;
	}

	/**
	 * Get versionOS
	 * 
	 * @return versionOS
	 **/
	public String getVersionOS() {
		return versionOS;
	}

	public void setVersionOS(String versionOS) {
		this.versionOS = versionOS;
	}

	public Password carrier(String carrier) {
		this.carrier = carrier;
		return this;
	}

	/**
	 * Get carrier
	 * 
	 * @return carrier
	 **/
	public String getCarrier() {
		return carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	public String getConnectAddress() {
		return connectAddress;
	}

	public void setConnectAddress(String connectAddress) {
		this.connectAddress = connectAddress;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Password password = (Password) o;
		return Objects.equals(this.value, password.value) && Objects.equals(this.brandDevice, password.brandDevice) && Objects.equals(this.modelDevice, password.modelDevice)
				&& Objects.equals(this.versionOS, password.versionOS) && Objects.equals(this.carrier, password.carrier);
	}

	@Override
	public int hashCode() {
		return Objects.hash(value, brandDevice, modelDevice, versionOS, carrier);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Password {\n");

		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("    brandDevice: ").append(toIndentedString(brandDevice)).append("\n");
		sb.append("    modelDevice: ").append(toIndentedString(modelDevice)).append("\n");
		sb.append("    versionOS: ").append(toIndentedString(versionOS)).append("\n");
		sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
