/*
 * Crédito en Línea
 * Servicios para aplicación de crédito en    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pablo.lopez@ndeveloper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cobiscorp.mobile.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Questions
 */
public class Questions {
	private List<Question> questions = null;

	public Questions questions(List<Question> questions) {
		this.questions = questions;
		return this;
	}

	public Questions addQuestionsItem(Question questionsItem) {
		if (this.questions == null) {
			this.questions = new ArrayList<Question>();
		}
		this.questions.add(questionsItem);
		return this;
	}

	/**
	 * Get questions
	 * 
	 * @return questions
	 **/
	public List<Question> getQuestions() {
		return questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Questions questions = (Questions) o;
		return Objects.equals(this.questions, questions.questions);
	}

	@Override
	public int hashCode() {
		return Objects.hash(questions);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Questions {\n");

		sb.append("    questions: ").append(toIndentedString(questions)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
