/*
 * Crédito en Línea
 * Servicios para aplicación de crédito en    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pablo.lopez@ndeveloper.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cobiscorp.mobile.model;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * GeneralParametersTablaComision
 */
public class TablaComision {
	private BigDecimal max = null;

	private BigDecimal min = null;

	private BigDecimal comission = null;

	private String operator = null;

	public TablaComision(BigDecimal max, BigDecimal min, BigDecimal comission, String operator) {
		super();
		this.max = max;
		this.min = min;
		this.comission = comission;
		this.operator = operator;
	}

	public TablaComision() {
		super();
	}

	public TablaComision max(BigDecimal max) {
		this.max = max;
		return this;
	}

	/**
	 * Get max
	 * 
	 * @return max
	 **/
	public BigDecimal getMax() {
		return max;
	}

	public void setMax(BigDecimal max) {
		this.max = max;
	}

	public TablaComision min(BigDecimal min) {
		this.min = min;
		return this;
	}

	/**
	 * Get min
	 * 
	 * @return min
	 **/
	public BigDecimal getMin() {
		return min;
	}

	public void setMin(BigDecimal min) {
		this.min = min;
	}

	public TablaComision comission(BigDecimal comission) {
		this.comission = comission;
		return this;
	}

	/**
	 * Get comission
	 * 
	 * @return comission
	 **/
	public BigDecimal getComission() {
		return comission;
	}

	public void setComission(BigDecimal comission) {
		this.comission = comission;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		TablaComision generalParametersTablaComision = (TablaComision) o;
		return Objects.equals(this.max, generalParametersTablaComision.max) && Objects.equals(this.min, generalParametersTablaComision.min)
				&& Objects.equals(this.comission, generalParametersTablaComision.comission) && Objects.equals(this.operator, generalParametersTablaComision.operator);
	}

	@Override
	public int hashCode() {
		return Objects.hash(max, min, comission);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GeneralParametersTablaComision {\n");

		sb.append("    max: ").append(toIndentedString(max)).append("\n");
		sb.append("    min: ").append(toIndentedString(min)).append("\n");
		sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
		sb.append("    comission: ").append(toIndentedString(comission)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
