bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Enero_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Febrero_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Marzo_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Abril_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Mayo_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Junio_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Julio_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Agosto_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Septiembre_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Octubre_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Noviembre_2019.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Diciembre_2019.dat -n -r \n -T -S
