bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Enero_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Febrero_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Marzo_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Abril_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Mayo_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Junio_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Julio_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Agosto_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Septiembre_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Octubre_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Noviembre_2021.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_sasiento in D:\Temp\Pruebas\cob_conta_tercero_ct_sasiento_Diciembre_2021.dat -n -r \n -T -S
