
    /************************************************************/
    /*******************Service Operations Script*********************/
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    use cobis
    GO
    
      IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'BusinessToBusiness.SecurityManagement.SendOtp')
        UPDATE cts_serv_catalog SET csc_class_name = 'cobiscorp.ecobis.businesstobusiness.service.ISecurityManagement', csc_method_name = 'sendOtp', csc_description = '', csc_trn = 0 WHERE csc_service_id = 'BusinessToBusiness.SecurityManagement.SendOtp'
      ELSE
        INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn ) VALUES ('BusinessToBusiness.SecurityManagement.SendOtp', 'cobiscorp.ecobis.businesstobusiness.service.ISecurityManagement', 'sendOtp', '', 0)
      GO
    
      IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'BusinessToBusiness.SecurityManagement.ValidationOtp')
        UPDATE cts_serv_catalog SET csc_class_name = 'cobiscorp.ecobis.businesstobusiness.service.ISecurityManagement', csc_method_name = 'validationOtp', csc_description = '', csc_trn = 0 WHERE csc_service_id = 'BusinessToBusiness.SecurityManagement.ValidationOtp'
      ELSE
        INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn ) VALUES ('BusinessToBusiness.SecurityManagement.ValidationOtp', 'cobiscorp.ecobis.businesstobusiness.service.ISecurityManagement', 'validationOtp', '', 0)
      GO
    