INSERT INTO CTS_ENTITY (CTS_ID, CTS_VALUE) VALUES (100, 'VALUE1');
INSERT INTO CTS_ENTITY (CTS_ID, CTS_VALUE) VALUES (101, 'VALUE2');
INSERT INTO CTS_ENTITY (CTS_ID, CTS_VALUE) VALUES (102, 'VALUE3');