
/************************************************************************/
/*    ARCHIVO:         validacion_equivalencias.sql                     */
/*    NOMBRE LOGICO:   validacion_equivalencias.sql                     */
/*    PRODUCTO:        AHORROS                                          */
/************************************************************************/
/*                     IMPORTANTE                                       */
/*  Esta aplicacion es parte de los paquetes bancarios propiedad        */
/*  de COBISCorp.                                                       */
/*  Su uso no    autorizado queda  expresamente   prohibido asi como    */
/*  cualquier    alteracion o  agregado  hecho por    alguno  de sus    */
/*  usuarios sin el debido consentimiento por   escrito de COBISCorp.   */
/*  Este programa esta protegido por la ley de   derechos de autor      */
/*  y por las    convenciones  internacionales   de  propiedad inte-    */
/*  lectual.    Su uso no  autorizado dara  derecho a    COBISCorp para */
/*  obtener ordenes  de secuestro o  retencion y para  perseguir        */
/*  penalmente a los autores de cualquier   infraccion.                 */
/************************************************************************/
/*                     PROPOSITO                                        */
/*   Script de validación de equivalencias codigos cobis,               */
/*  con los codigos del documento entregado                             */
/************************************************************************/
/*                            MODIFICACIONES                            */
/*      FECHA           AUTOR                   RAZON                   */
/*      26/08/2016     Karen Meza           Emision Inicial             */  
/************************************************************************/

--PARAMETRIZACION TABLA DE EQUIVALENCIAS

--Al validar la estructura de equivalencias en regulatorios(cob_conta_super), se debe validar 
--la equivalencia de los codigos cobis, con los codigos que se encuentran en el documento adjunto


use cob_conta_super
go

if exists(SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico ='IUDI' AND pa_producto = 'AHO')
begin
delete cob_conta_super..sb_equivalencias where eq_catalogo in ('TIPO_ENTE', 'CL_SEXO', 'AH_TIPOCTA','TIPO_MODO', 'TIPRODUCTO',
                                                               'TRN_PERFIL','CONCON_PRO')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TIPO_ENTE', '1', 'P', 'SOCIO PERSONA FISICA', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TIPO_ENTE', '2', 'C', 'SOCIO PERSONA MORAL', 'V')


insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('CL_SEXO', '1', 'F', 'FEMENINO', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('CL_SEXO', '2', 'M', 'MASCULINO', 'V')


insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('AH_TIPOCTA', '1', '16', 'SOCIO EN MATRIZ O SUCURSAL', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('AH_TIPOCTA', '3', '17', 'SOCIO A TRAVES DE COMISIONISTAS', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('AH_TIPOCTA', '4', '21', 'CUENTAS ABIERTAS EN LA SOCIEDAD', 'V')


insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TIPO_MODO', '2', 'I', 'SOCIO INDIVIDUAL', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TIPO_MODO', '3', 'O', 'SOCIO MANCOMUNADA', 'V')


insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TIPRODUCTO', 'AHORROS', '4', 'CUENTA DE AHORROS', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TIPRODUCTO', 'DPF', '14', 'DEPOSITOS A PLAZO FIJO', 'V')


insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('TRN_PERFIL', 'NDE', '4', 'NOTA DE DEBITO CUENTAS DE AHORRO', 'V')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
values ('CONCON_PRO', 'NDERTEFTE', '4', 'NOTA DE DEBITO IMPUESTO ISR CUENTAS DE AHORRO', 'V')

end

use cobis
go


IF EXISTS(SELECT 1 FROM cl_tabla WHERE tabla = 'ec_equivalencias')
BEGIN
DELETE cl_catalogo FROM cl_tabla
 WHERE cl_tabla.tabla IN ('ec_equivalencias')
   AND cl_tabla.codigo = cl_catalogo.tabla

DELETE cl_tabla WHERE tabla='ec_equivalencias'
END

declare @w_codigo smallint

select @w_codigo = isnull(max(codigo), 0) + 1
from cl_tabla

INSERT INTO cl_tabla (codigo, tabla, descripcion)
VALUES (@w_codigo, 'ec_equivalencias', 'TABLAS DE EQUIVALENCIAS')


INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'CODPAIS', 'CODIGO DE PAIS', 'V', NULL, NULL, NULL)


INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'CODPROV', 'CODIGO DE PROVINCIA', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'CODCIU', 'CODIGO DE CIUDAD', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'CODPARRQ', 'CODIGO DE PARROQUIA', 'V', NULL, NULL, NULL)


INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'TIPO_ENTE', 'TIPO DE ENTE', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'CL_SEXO', 'TIPO DE GENERO', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'AH_TIPOCTA', 'TIPO DE CUENTA', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'TIPO_MODO', 'TIPO DE MODALIDAD', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'TIPRODUCTO', 'TIPO DE PRODUCTOS', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'TRN_PERFIL', 'TIPOS DE TRANSACCIONES DEL PERFIL POR PRODUCTO', 'V', NULL, NULL, NULL)

INSERT INTO cobis..cl_catalogo (tabla, codigo, valor, estado, culture, equiv_code, type)
VALUES (@w_codigo, 'CONCON_PRO', 'CONCEPTOS CONTABLES POR PRODUCTO', 'V', NULL, NULL, NULL)

UPDATE cl_seqnos SET siguiente = CASE WHEN siguiente <= @w_codigo THEN siguiente END
WHERE tabla = 'cl_tabla'

-- -----------------------------------------------------------------------------------------
use cob_conta_super
go

--EQUIVALENCIAS PARA REPORTE BURO
delete from sb_equivalencias where eq_catalogo in ('CL_MONEDA','CR_TCRED')
go

insert into sb_equivalencias values ('CL_MONEDA','0','MX','PESOS MEXICANOS','V')
insert into sb_equivalencias values ('CL_MONEDA','2','US','DOLARES AMERICANOS','V')

insert into sb_equivalencias values ('CR_TCRED','INDIVIDUAL','I','INDIVIDUAL','V')
insert into sb_equivalencias values ('CR_TCRED','GRUPAL','C','MANCOMUNADO','V')
insert into sb_equivalencias values ('CR_TCRED','INTERCICLO','C','MANCOMUNADO','V')
GO

-- ABREVIATURAS DE PAISES PARA RPT BURO CREDITO
delete from sb_equivalencias where eq_catalogo = 'CL_PAIS_A6'
     
IF OBJECT_ID('tempdb..#temp_cat_equiv') IS NOT NULL 
drop table #temp_cat_equiv    

create table #temp_cat_equiv(
   codigo char(10) null,
   abrv varchar(4) null,
   descrip varchar(60) null
)
insert into #temp_cat_equiv values ('1','AF','Afganistan')
insert into #temp_cat_equiv values ('2','AL','Albania')
insert into #temp_cat_equiv values ('3','DE','Alemania')
insert into #temp_cat_equiv values ('4','AD','Andorra')
insert into #temp_cat_equiv values ('5','AO','Angola')
insert into #temp_cat_equiv values ('6','AI','Anguila')
insert into #temp_cat_equiv values ('7','AQ','Antartida')
insert into #temp_cat_equiv values ('8','AG','Antigua y Barbuda')
insert into #temp_cat_equiv values ('9','SA','Arabia Saudita')
insert into #temp_cat_equiv values ('10','DZ','Argelia')
insert into #temp_cat_equiv values ('11','AR','Argentina')
insert into #temp_cat_equiv values ('12','AM','Armenia')
insert into #temp_cat_equiv values ('13','AW','Aruba')
insert into #temp_cat_equiv values ('14','AU','Australia')
insert into #temp_cat_equiv values ('15','AT','Austria')
insert into #temp_cat_equiv values ('16','AZ','Azerbaiyan')
insert into #temp_cat_equiv values ('17','BS','Bahamas')
insert into #temp_cat_equiv values ('18','BH','Bahrein')
insert into #temp_cat_equiv values ('19','BD','Bangladesh')
insert into #temp_cat_equiv values ('20','BB','Barbados')
insert into #temp_cat_equiv values ('21','BE','Belgica')
insert into #temp_cat_equiv values ('22','BZ','Belice')
insert into #temp_cat_equiv values ('23','BJ','Benin')
insert into #temp_cat_equiv values ('24','BM','Bermudas')
insert into #temp_cat_equiv values ('25','BY','Bielorrusia')
insert into #temp_cat_equiv values ('26','BO','Bolivia')
insert into #temp_cat_equiv values ('27','BQ','Bonaire, San Eustaquio y Saba')
insert into #temp_cat_equiv values ('28','BA','Bosnia y Herzegovina (Republica de Bosnia)')
insert into #temp_cat_equiv values ('29','BW','Botsuana')
insert into #temp_cat_equiv values ('30','BR','Brasil')
insert into #temp_cat_equiv values ('31','BN','Brunei Darussalam')
insert into #temp_cat_equiv values ('32','BG','Bulgaria')
insert into #temp_cat_equiv values ('33','BF','Burkina Faso')
insert into #temp_cat_equiv values ('34','BI','Burundi')
insert into #temp_cat_equiv values ('35','BT','Butan')
insert into #temp_cat_equiv values ('36','CV','Cabo Verde')
insert into #temp_cat_equiv values ('37','KH','Camboya')
insert into #temp_cat_equiv values ('38','CM','Camerun')
insert into #temp_cat_equiv values ('39','CA','Canada')
insert into #temp_cat_equiv values ('40','CL','Chile')
insert into #temp_cat_equiv values ('41','CN','China')
insert into #temp_cat_equiv values ('42','CY','Chipre')
insert into #temp_cat_equiv values ('43','CO','Colombia')
insert into #temp_cat_equiv values ('44','CI','Costa de Marfil (Cote d Ivoire)')
insert into #temp_cat_equiv values ('45','CR','Costa Rica')
insert into #temp_cat_equiv values ('46','HR','Croacia')
insert into #temp_cat_equiv values ('47','CU','Cuba')
insert into #temp_cat_equiv values ('48','CW','Curaçao')
insert into #temp_cat_equiv values ('49','DK','Dinamarca')
insert into #temp_cat_equiv values ('50','DJ','Djibouti')
insert into #temp_cat_equiv values ('51','DM','Dominica')
insert into #temp_cat_equiv values ('52','EC','Ecuador')
insert into #temp_cat_equiv values ('53','EG','Egipto')
insert into #temp_cat_equiv values ('54','SV','El Salvador')
insert into #temp_cat_equiv values ('55','ER','Eritrea')
insert into #temp_cat_equiv values ('56','SK','Eslovaquia')
insert into #temp_cat_equiv values ('57','SI','Eslovenia')
insert into #temp_cat_equiv values ('58','ES','España')
insert into #temp_cat_equiv values ('59','US','Estados Unidos')
insert into #temp_cat_equiv values ('60','EE','Estonia')
insert into #temp_cat_equiv values ('61','ET','Ethiopia')
insert into #temp_cat_equiv values ('62','FJ','Fiji')
insert into #temp_cat_equiv values ('63','PH','Filipinas')
insert into #temp_cat_equiv values ('64','FI','Finlandia')
insert into #temp_cat_equiv values ('65','FR','Francia')
insert into #temp_cat_equiv values ('66','GA','Gabon')
insert into #temp_cat_equiv values ('67','GM','Gambia')
insert into #temp_cat_equiv values ('68','GS','Georgia del sur y las islas sandwich del sur')
insert into #temp_cat_equiv values ('69','GH','Ghana')
insert into #temp_cat_equiv values ('70','GI','Gibraltar')
insert into #temp_cat_equiv values ('71','GD','Granada')
insert into #temp_cat_equiv values ('72','GR','Grecia')
insert into #temp_cat_equiv values ('73','GL','Groenlandia')
insert into #temp_cat_equiv values ('74','GP','Guadalupe')
insert into #temp_cat_equiv values ('75','GU','Guam')
insert into #temp_cat_equiv values ('76','GT','Guatemala')
insert into #temp_cat_equiv values ('77','GY','Guayana')
insert into #temp_cat_equiv values ('78','GF','Guayana Francesa')
insert into #temp_cat_equiv values ('79','GG','Guernsey')
insert into #temp_cat_equiv values ('80','GN','Guinea')
insert into #temp_cat_equiv values ('81','GQ','Guinea Ecuatorial')
insert into #temp_cat_equiv values ('82','GW','Guinea-Bissau')
insert into #temp_cat_equiv values ('83','HT','Haiti')
insert into #temp_cat_equiv values ('84','HN','Honduras')
insert into #temp_cat_equiv values ('85','HK','Hong Kong')
insert into #temp_cat_equiv values ('86','HU','Hungria')
insert into #temp_cat_equiv values ('87','IN','India')
insert into #temp_cat_equiv values ('88','ID','Indonesia')
insert into #temp_cat_equiv values ('89','IQ','Irak')
insert into #temp_cat_equiv values ('90','IR','Iran')
insert into #temp_cat_equiv values ('91','IE','Irlanda')
insert into #temp_cat_equiv values ('92','BV','Isla Bouvet')
insert into #temp_cat_equiv values ('93','IM','Isla de Man')
insert into #temp_cat_equiv values ('94','CX','Isla de Navidad')
insert into #temp_cat_equiv values ('95','HM','Isla Heard e Islas McDonald')
insert into #temp_cat_equiv values ('96','NF','Isla Norfolk')
insert into #temp_cat_equiv values ('97','IS','Islandia')
insert into #temp_cat_equiv values ('98','AX','Islas Åland')
insert into #temp_cat_equiv values ('99','KY','Islas Caiman')
insert into #temp_cat_equiv values ('100','CK','Islas Cook (las)')
insert into #temp_cat_equiv values ('101','FK','Islas Falkland (Malvinas)')
insert into #temp_cat_equiv values ('102','FO','Islas Faroe')
insert into #temp_cat_equiv values ('103','MP','Islas Marianas del Norte (las)')
insert into #temp_cat_equiv values ('104','MH','Islas Marshall (las)')
insert into #temp_cat_equiv values ('105','PN','Islas Pitcairn')
insert into #temp_cat_equiv values ('106','RE','Islas Reunion')
insert into #temp_cat_equiv values ('107','SB','Islas Salomon (las)')
insert into #temp_cat_equiv values ('108','VI','Islas Virgenes (EE.UU.)')
insert into #temp_cat_equiv values ('109','VG','Islas Virgenes Inglesas')
insert into #temp_cat_equiv values ('110','IL','Israel')
insert into #temp_cat_equiv values ('111','IT','Italia')
insert into #temp_cat_equiv values ('112','JM','Jamaica')
insert into #temp_cat_equiv values ('113','JP','Japon')
insert into #temp_cat_equiv values ('114','JE','Jersey')
insert into #temp_cat_equiv values ('115','JO','Jordania')
insert into #temp_cat_equiv values ('116','QA','Katar')
insert into #temp_cat_equiv values ('117','KZ','Kazajistan')
insert into #temp_cat_equiv values ('118','KE','Kenya')
insert into #temp_cat_equiv values ('119','KG','Kirguistan')
insert into #temp_cat_equiv values ('120','KI','Kiribati')
insert into #temp_cat_equiv values ('121','KW','Kuwait')
insert into #temp_cat_equiv values ('122','SY','La Republica arabe de Siria')
insert into #temp_cat_equiv values ('123','KR','La Republica de Corea del Sur')
insert into #temp_cat_equiv values ('124','CD','La Republica Democratica del Congo (Zaire)')
insert into #temp_cat_equiv values ('125','KP','La Republica Democratica Popular de Corea')
insert into #temp_cat_equiv values ('126','LA','La Republica Democratica Popular Lao')
insert into #temp_cat_equiv values ('127','UM','Las Islas de Ultramar Menores de Estados Unidos')
insert into #temp_cat_equiv values ('128','TC','Las Islas Turcas y Caicos')
insert into #temp_cat_equiv values ('129','LS','Lesotho')
insert into #temp_cat_equiv values ('130','LV','Letonia')
insert into #temp_cat_equiv values ('131','LB','Libano')
insert into #temp_cat_equiv values ('132','LR','Liberia')
insert into #temp_cat_equiv values ('133','LY','Libia')
insert into #temp_cat_equiv values ('134','LI','Liechtenstein')
insert into #temp_cat_equiv values ('135','LT','Lituania')
insert into #temp_cat_equiv values ('136','AE','Los Emiratos arabes Unidos')
insert into #temp_cat_equiv values ('137','NL','Los Paises Bajos (Holanda)')
insert into #temp_cat_equiv values ('138','LU','Luxemburgo')
insert into #temp_cat_equiv values ('139','MO','Macao')
insert into #temp_cat_equiv values ('140','MK','Macedonia (la antigua Republica Yugoslava de)')
insert into #temp_cat_equiv values ('141','MG','Madagascar')
insert into #temp_cat_equiv values ('142','MY','Malasia')
insert into #temp_cat_equiv values ('143','MW','Malawi')
insert into #temp_cat_equiv values ('144','MV','Maldivias')
insert into #temp_cat_equiv values ('145','ML','Mali')
insert into #temp_cat_equiv values ('146','MT','Malta')
insert into #temp_cat_equiv values ('147','MA','Marruecos')
insert into #temp_cat_equiv values ('148','MQ','Martinica')
insert into #temp_cat_equiv values ('149','MU','Mauricio')
insert into #temp_cat_equiv values ('150','MR','Mauritania')
insert into #temp_cat_equiv values ('151','YT','Mayotte')
insert into #temp_cat_equiv values ('152','MX','Mexico')
insert into #temp_cat_equiv values ('153','FM','Micronesia (los Estados Federados de)')
insert into #temp_cat_equiv values ('154','MD','Moldavia (la Republica de)')
insert into #temp_cat_equiv values ('155','MC','Monaco')
insert into #temp_cat_equiv values ('156','MN','Mongolia')
insert into #temp_cat_equiv values ('157','ME','Montenegro')
insert into #temp_cat_equiv values ('158','MS','Montserrat')
insert into #temp_cat_equiv values ('159','MZ','Mozambique')
insert into #temp_cat_equiv values ('160','NA','Namibia')
insert into #temp_cat_equiv values ('161','NR','Nauru')
insert into #temp_cat_equiv values ('162','NP','Nepal')
insert into #temp_cat_equiv values ('163','NI','Nicaragua')
insert into #temp_cat_equiv values ('164','NE','Niger (el)')
insert into #temp_cat_equiv values ('165','NG','Nigeria')
insert into #temp_cat_equiv values ('166','NU','Niue')
insert into #temp_cat_equiv values ('167','NO','Noruega')
insert into #temp_cat_equiv values ('168','NC','Nueva Caledonia')
insert into #temp_cat_equiv values ('169','NZ','Nueva Zelandia')
insert into #temp_cat_equiv values ('170','OM','Oman')
insert into #temp_cat_equiv values ('171','PK','Pakistan')
insert into #temp_cat_equiv values ('172','PW','Palaos')
insert into #temp_cat_equiv values ('173','PS','Palestina, Estado de')
insert into #temp_cat_equiv values ('174','PA','Panama')
insert into #temp_cat_equiv values ('175','PG','Papua Nueva Guinea')
insert into #temp_cat_equiv values ('176','PY','Paraguay')
insert into #temp_cat_equiv values ('177','PE','Peru')
insert into #temp_cat_equiv values ('178','PF','Polinesia Francesa')
insert into #temp_cat_equiv values ('179','PL','Polonia')
insert into #temp_cat_equiv values ('180','PT','Portugal')
insert into #temp_cat_equiv values ('181','PR','Puerto Rico')
insert into #temp_cat_equiv values ('182','GB','Reino Unido')
insert into #temp_cat_equiv values ('183','CF','Rep. Central Africana')
insert into #temp_cat_equiv values ('184','CZ','Republica Checa (la)')
insert into #temp_cat_equiv values ('185','GE','Republica de Georgia')
insert into #temp_cat_equiv values ('186','MM','Republica de la Union de Myanmar (Birmania)')
insert into #temp_cat_equiv values ('187','TD','Republica del Chad')
insert into #temp_cat_equiv values ('188','CG','Republica del Congo')
insert into #temp_cat_equiv values ('189','ST','Republica Democratica de Santo Tome y Principe')
insert into #temp_cat_equiv values ('190','TL','Republica Democratica de Timor Oriental')
insert into #temp_cat_equiv values ('191','DO','Republica Dominicana')
insert into #temp_cat_equiv values ('192','TZ','Republica Unida de Tanzania')
insert into #temp_cat_equiv values ('193','RW','Ruanda')
insert into #temp_cat_equiv values ('194','RO','Rumania')
insert into #temp_cat_equiv values ('195','RU','Rusia')
insert into #temp_cat_equiv values ('196','EH','Sahara Occidental')
insert into #temp_cat_equiv values ('197','AS','Samoa Americana')
insert into #temp_cat_equiv values ('198','WS','Samoa Oeste')
insert into #temp_cat_equiv values ('199','BL','San Bartolome')
insert into #temp_cat_equiv values ('200','KN','San Cristobal y Nieves')
insert into #temp_cat_equiv values ('201','SM','San Marino')
insert into #temp_cat_equiv values ('202','MF','San Martin (parte francesa)')
insert into #temp_cat_equiv values ('203','PM','San Pedro y Miquelon')
insert into #temp_cat_equiv values ('204','VC','San Vicente y las Granadinas')
insert into #temp_cat_equiv values ('205','SH','Santa Helena (Santa Helena, Ascension y Tristan de Acuña)')
insert into #temp_cat_equiv values ('206','LC','Santa Lucia')
insert into #temp_cat_equiv values ('207','SN','Senegal')
insert into #temp_cat_equiv values ('208','RS','Serbia')
insert into #temp_cat_equiv values ('209','SC','Seychelles')
insert into #temp_cat_equiv values ('210','SL','Sierra leona')
insert into #temp_cat_equiv values ('211','SG','Singapur')
insert into #temp_cat_equiv values ('212','SX','Sint Maarten (parte holandesa)')
insert into #temp_cat_equiv values ('213','SO','Somalia')
insert into #temp_cat_equiv values ('214','LK','Sri Lanka')
insert into #temp_cat_equiv values ('215','ZA','Sudafrica')
insert into #temp_cat_equiv values ('216','SD','Sudan')
insert into #temp_cat_equiv values ('217','SS','Sudan del Sur')
insert into #temp_cat_equiv values ('218','SE','Suecia')
insert into #temp_cat_equiv values ('219','CH','Suiza')
insert into #temp_cat_equiv values ('220','SR','Surinam')
insert into #temp_cat_equiv values ('221','SJ','Svalbard y Jan Mayen')
insert into #temp_cat_equiv values ('222','SZ','Swazilandia')
insert into #temp_cat_equiv values ('223','TH','Tailandia')
insert into #temp_cat_equiv values ('224','TW','Taiwan (Provincia de China)')
insert into #temp_cat_equiv values ('225','TJ','Tayikistan')
insert into #temp_cat_equiv values ('226','IO','Territorio Britanico del Oceano indico (el)')
insert into #temp_cat_equiv values ('227','CC','Territorio de las Islas Cocos (Keeling)')
insert into #temp_cat_equiv values ('228','TF','Territorios Australes Franceses (los)')
insert into #temp_cat_equiv values ('229','TG','Togo')
insert into #temp_cat_equiv values ('230','TK','Tokelau')
insert into #temp_cat_equiv values ('231','TO','Tonga')
insert into #temp_cat_equiv values ('232','TT','Trinidad y Tobago')
insert into #temp_cat_equiv values ('233','TN','Tunez')
insert into #temp_cat_equiv values ('234','TM','Turkmenistan')
insert into #temp_cat_equiv values ('235','TR','Turquia')
insert into #temp_cat_equiv values ('236','TV','Tuvalu')
insert into #temp_cat_equiv values ('237','UA','Ucrania')
insert into #temp_cat_equiv values ('238','UG','Uganda')
insert into #temp_cat_equiv values ('239','KM','Union de las Comoras (Comoras o Comores)')
insert into #temp_cat_equiv values ('240','UY','Uruguay')
insert into #temp_cat_equiv values ('241','UZ','Uzbekistan')
insert into #temp_cat_equiv values ('242','VU','Vanuatu')
insert into #temp_cat_equiv values ('243','VA','Vaticano Santa Sede [Estado de la Ciudad del Vaticano]')
insert into #temp_cat_equiv values ('244','VE','Venezuela, Republica Bolivariana de')
insert into #temp_cat_equiv values ('245','VN','Viet Nam')
insert into #temp_cat_equiv values ('246','WF','Wallis y Futuna')
insert into #temp_cat_equiv values ('247','YE','Yemen')
insert into #temp_cat_equiv values ('248','ZM','Zambia')
insert into #temp_cat_equiv values ('249','ZW','Zimbabue')

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
select 'CL_PAIS_A6', c.codigo, tp.codigo, tp.abrv, 'V'
  from cobis..cl_catalogo c , #temp_cat_equiv tp
 where tabla = (select codigo from cobis..cl_tabla where tabla = 'cl_pais')
   and upper(descrip) like upper(valor)
go
delete from #temp_cat_equiv
go

-- TIPO DE VIVIENDA  - RPT BURO CREDITO
delete from sb_equivalencias where eq_catalogo = 'CL_TVIVIEN'
insert into sb_equivalencias values ('CL_TVIVIEN','001','1','Propietario','V')
insert into sb_equivalencias values ('CL_TVIVIEN','002','2','Renta','V')
insert into sb_equivalencias values ('CL_TVIVIEN','003','3','Pensión / Vive con familiares','V')
insert into sb_equivalencias values ('CL_TVIVIEN','004','2','Renta','V')
go

-- ESTADO CIVIL		cl_ecivil  - RPT BURO CREDITO
delete from sb_equivalencias where eq_catalogo = 'CL_ECIVIL'
insert into sb_equivalencias values ('CL_ECIVIL','DI','D','Divorciado','V')
insert into sb_equivalencias values ('CL_ECIVIL','UN','F','Unión Libre','V')
insert into sb_equivalencias values ('CL_ECIVIL','CA','M','Casado','V')
insert into sb_equivalencias values ('CL_ECIVIL','SO','S','Soltero','V')
insert into sb_equivalencias values ('CL_ECIVIL','VI','W','Viudo','V')
go
-- TABLA ASCII --> (CHAR_a_Reemplazar, ValorAlfabético, ValorAlfaNumérico)
delete from sb_equivalencias where eq_catalogo = 'CHAR_ASCII'
-- eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado
insert into sb_equivalencias values('CHAR_ASCII','á','A','A','V')
insert into sb_equivalencias values('CHAR_ASCII','é','E','E','V')
insert into sb_equivalencias values('CHAR_ASCII','í','I','I','V')
insert into sb_equivalencias values('CHAR_ASCII','ó','O','O','V')
insert into sb_equivalencias values('CHAR_ASCII','ú','U','U','V')
insert into sb_equivalencias values('CHAR_ASCII','Á','A','A','V')
insert into sb_equivalencias values('CHAR_ASCII','É','E','E','V')
insert into sb_equivalencias values('CHAR_ASCII','Í','I','I','V')
insert into sb_equivalencias values('CHAR_ASCII','Ó','O','O','V')
insert into sb_equivalencias values('CHAR_ASCII','Ú','U','U','V')

insert into sb_equivalencias values('CHAR_ASCII','#','','N','V')
insert into sb_equivalencias values('CHAR_ASCII','$','','N','V')
insert into sb_equivalencias values('CHAR_ASCII','%','','N','V')
insert into sb_equivalencias values('CHAR_ASCII','>','','#','V')
insert into sb_equivalencias values('CHAR_ASCII','@','','N','V')
insert into sb_equivalencias values('CHAR_ASCII','ñ','N','N','V')
insert into sb_equivalencias values('CHAR_ASCII','Ñ','N','N','V')
insert into sb_equivalencias values('CHAR_ASCII',' ',' ',' ','V')

insert into sb_equivalencias values('CHAR_ASCII','A','A','A','V')
insert into sb_equivalencias values('CHAR_ASCII','B','B','B','V')
insert into sb_equivalencias values('CHAR_ASCII','C','C','C','V')
insert into sb_equivalencias values('CHAR_ASCII','D','D','D','V')
insert into sb_equivalencias values('CHAR_ASCII','E','E','E','V')
insert into sb_equivalencias values('CHAR_ASCII','F','F','F','V')
insert into sb_equivalencias values('CHAR_ASCII','G','G','G','V')
insert into sb_equivalencias values('CHAR_ASCII','H','H','H','V')
insert into sb_equivalencias values('CHAR_ASCII','I','I','I','V')
insert into sb_equivalencias values('CHAR_ASCII','J','J','J','V')
insert into sb_equivalencias values('CHAR_ASCII','K','K','K','V')
insert into sb_equivalencias values('CHAR_ASCII','L','L','L','V')
insert into sb_equivalencias values('CHAR_ASCII','M','M','M','V')
insert into sb_equivalencias values('CHAR_ASCII','N','N','N','V')
insert into sb_equivalencias values('CHAR_ASCII','O','O','O','V')
insert into sb_equivalencias values('CHAR_ASCII','P','P','P','V')
insert into sb_equivalencias values('CHAR_ASCII','Q','Q','Q','V')
insert into sb_equivalencias values('CHAR_ASCII','R','R','R','V')
insert into sb_equivalencias values('CHAR_ASCII','S','S','S','V')
insert into sb_equivalencias values('CHAR_ASCII','T','T','T','V')
insert into sb_equivalencias values('CHAR_ASCII','U','U','U','V')
insert into sb_equivalencias values('CHAR_ASCII','V','V','V','V')
insert into sb_equivalencias values('CHAR_ASCII','W','W','W','V')
insert into sb_equivalencias values('CHAR_ASCII','X','X','X','V')
insert into sb_equivalencias values('CHAR_ASCII','Y','Y','Y','V')
insert into sb_equivalencias values('CHAR_ASCII','Z','Z','Z','V')

insert into sb_equivalencias values('CHAR_ASCII','a','A','A','V')
insert into sb_equivalencias values('CHAR_ASCII','b','B','B','V')
insert into sb_equivalencias values('CHAR_ASCII','c','C','C','V')
insert into sb_equivalencias values('CHAR_ASCII','d','D','D','V')
insert into sb_equivalencias values('CHAR_ASCII','e','E','E','V')
insert into sb_equivalencias values('CHAR_ASCII','f','F','F','V')
insert into sb_equivalencias values('CHAR_ASCII','g','G','G','V')
insert into sb_equivalencias values('CHAR_ASCII','h','H','H','V')
insert into sb_equivalencias values('CHAR_ASCII','i','I','I','V')
insert into sb_equivalencias values('CHAR_ASCII','j','J','J','V')
insert into sb_equivalencias values('CHAR_ASCII','k','K','K','V')
insert into sb_equivalencias values('CHAR_ASCII','l','L','L','V')
insert into sb_equivalencias values('CHAR_ASCII','m','M','M','V')
insert into sb_equivalencias values('CHAR_ASCII','n','N','N','V')
insert into sb_equivalencias values('CHAR_ASCII','o','O','O','V')
insert into sb_equivalencias values('CHAR_ASCII','p','P','P','V')
insert into sb_equivalencias values('CHAR_ASCII','q','Q','Q','V')
insert into sb_equivalencias values('CHAR_ASCII','r','R','R','V')
insert into sb_equivalencias values('CHAR_ASCII','s','S','S','V')
insert into sb_equivalencias values('CHAR_ASCII','t','T','T','V')
insert into sb_equivalencias values('CHAR_ASCII','u','U','U','V')
insert into sb_equivalencias values('CHAR_ASCII','v','V','V','V')
insert into sb_equivalencias values('CHAR_ASCII','w','W','W','V')
insert into sb_equivalencias values('CHAR_ASCII','x','X','X','V')
insert into sb_equivalencias values('CHAR_ASCII','y','Y','Y','V')
insert into sb_equivalencias values('CHAR_ASCII','z','Z','Z','V')

insert into sb_equivalencias values('CHAR_ASCII','0','','0','V')
insert into sb_equivalencias values('CHAR_ASCII','1','','1','V')
insert into sb_equivalencias values('CHAR_ASCII','2','','2','V')
insert into sb_equivalencias values('CHAR_ASCII','3','','3','V')
insert into sb_equivalencias values('CHAR_ASCII','4','','4','V')
insert into sb_equivalencias values('CHAR_ASCII','5','','5','V')
insert into sb_equivalencias values('CHAR_ASCII','6','','6','V')
insert into sb_equivalencias values('CHAR_ASCII','7','','7','V')
insert into sb_equivalencias values('CHAR_ASCII','8','','8','V')
insert into sb_equivalencias values('CHAR_ASCII','9','','9','V')

go

-- ESTADO DE LA REPUBLICA - RPT BURO CREDITO
delete from sb_equivalencias where eq_catalogo = 'ESTADOS_A7'
insert into sb_equivalencias values('ESTADOS_A7','1','AGS','Aguascalientes','V')
insert into sb_equivalencias values('ESTADOS_A7','2','BCN','Baja California Norte','V')
insert into sb_equivalencias values('ESTADOS_A7','3','BCS','Baja California Sur','V')
insert into sb_equivalencias values('ESTADOS_A7','4','CAM','Campeche','V')
insert into sb_equivalencias values('ESTADOS_A7','5','COA','Coahuila','V')
insert into sb_equivalencias values('ESTADOS_A7','6','COL','Colima','V')
insert into sb_equivalencias values('ESTADOS_A7','7','CHS','Chiapas','V')
insert into sb_equivalencias values('ESTADOS_A7','8','CHI','Chihuahua','V')
insert into sb_equivalencias values('ESTADOS_A7','9','DF','Distrito Federal','V')
insert into sb_equivalencias values('ESTADOS_A7','10','DGO','Durango','V')
insert into sb_equivalencias values('ESTADOS_A7','11','GTO','Guanajuato','V')
insert into sb_equivalencias values('ESTADOS_A7','12','GRO','Guerrero','V')
insert into sb_equivalencias values('ESTADOS_A7','13','HGO','Hidalgo','V')
insert into sb_equivalencias values('ESTADOS_A7','14','JAL','Jalisco','V')
insert into sb_equivalencias values('ESTADOS_A7','15','EM','Estado de México','V')
insert into sb_equivalencias values('ESTADOS_A7','16','MICH','Michoacán','V')
insert into sb_equivalencias values('ESTADOS_A7','17','MOR','Morelos','V')
insert into sb_equivalencias values('ESTADOS_A7','18','NAY','Nayarit','V')
insert into sb_equivalencias values('ESTADOS_A7','19','NL','Nuevo León','V')
insert into sb_equivalencias values('ESTADOS_A7','20','OAX','Oaxaca','V')
insert into sb_equivalencias values('ESTADOS_A7','21','PUE','Puebla','V')
insert into sb_equivalencias values('ESTADOS_A7','22','QRO','Querétaro','V')
insert into sb_equivalencias values('ESTADOS_A7','23','QR','Quintana Roo','V')
insert into sb_equivalencias values('ESTADOS_A7','24','SLP','San Luis Potosí','V')
insert into sb_equivalencias values('ESTADOS_A7','25','SIN','Sinaloa','V')
insert into sb_equivalencias values('ESTADOS_A7','26','SON','Sonora','V')
insert into sb_equivalencias values('ESTADOS_A7','27','TAB','Tabasco','V')
insert into sb_equivalencias values('ESTADOS_A7','28','TAM','Tamaulipas','V')
insert into sb_equivalencias values('ESTADOS_A7','29','TLA','Tlaxcala','V')
insert into sb_equivalencias values('ESTADOS_A7','30','VER','Veracruz','V')
insert into sb_equivalencias values('ESTADOS_A7','31','YUC','Yucatán','V')
insert into sb_equivalencias values('ESTADOS_A7','32','ZAC','Zacatecas','V')
go
-- FRECUENCIA DE PAGOS - RPT BURO CREDITO
delete from sb_equivalencias where eq_catalogo = 'FREC_PAGOS'
go
insert into sb_equivalencias values('FREC_PAGOS','B','B','Bimestral','V')
insert into sb_equivalencias values('FREC_PAGOS','D','D','Diario','V')
insert into sb_equivalencias values('FREC_PAGOS','S','H','Semestral','V')
insert into sb_equivalencias values('FREC_PAGOS','M','M','Mensual','V')
insert into sb_equivalencias values('FREC_PAGOS','T','Q','Trimestral','V')
insert into sb_equivalencias values('FREC_PAGOS','Q','S','Quincenal','V')
insert into sb_equivalencias values('FREC_PAGOS','W','W','Semanal','V')
insert into sb_equivalencias values('FREC_PAGOS','A','Y','Anual','V')
go
-- TPO VIVIENDA - RPT BURO CREDITO
delete from sb_equivalencias where eq_catalogo = 'TIPO_VVND'
go
insert into sb_equivalencias values('TIPO_VVND','PRO','1','Propietario','V')
insert into sb_equivalencias values('TIPO_VVND','REN','2','Renta','V')
insert into sb_equivalencias values('TIPO_VVND','FAM','3','Pensión/Vive con familiares','V')
go

-- Reporte CFDI - Catalogo Pais
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AFG','Afganistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ALA','Islas Åland','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ALB','Albania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DEU','Alemania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AND','Andorra','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AGO','Angola','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AIA','Anguila','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ATA','Antártida','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ATG','Antigua y Barbuda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SAU','Arabia Saudita','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DZA','Argelia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ARG','Argentina','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ARM','Armenia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ABW','Aruba','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AUS','Australia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AUT','Austria','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('AZE','Azerbaiyán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BHS','Bahamas (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BGD','Bangladés','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BRB','Barbados','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BHR','Baréin','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BEL','Bélgica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BLZ','Belice','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BEN','Benín','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BMU','Bermudas','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BLR','Bielorrusia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MMR','Myanmar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BOL','Bolivia, Estado Plurinacional de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BIH','Bosnia y Herzegovina','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BWA','Botsuana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BRA','Brasil','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BRN','Brunéi Darussalam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BGR','Bulgaria','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BFA','Burkina Faso','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BDI','Burundi','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BTN','Bután','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CPV','Cabo Verde','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KHM','Camboya','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CMR','Camerún','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CAN','Canadá','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('QAT','Catar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BES','Bonaire, San Eustaquio y Saba','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TCD','Chad','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CHL','Chile','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CHN','China','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CYP','Chipre','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COL','Colombia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COM','Comoras','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRK','Corea (la República Democrática Popular de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KOR','Corea (la República de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CIV','Côte d Ivoire','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CRI','Costa Rica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HRV','Croacia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CUB','Cuba','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CUW','Curaçao','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DNK','Dinamarca','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DMA','Dominica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ECU','Ecuador','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('EGY','Egipto','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SLV','El Salvador','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ARE','Emiratos Árabes Unidos (Los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ERI','Eritrea','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SVK','Eslovaquia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SVN','Eslovenia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ESP','España','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('USA','Estados Unidos (los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('EST','Estonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ETH','Etiopía','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PHL','Filipinas (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FIN','Finlandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FJI','Fiyi','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FRA','Francia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GAB','Gabón','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GMB','Gambia (La)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GEO','Georgia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GHA','Ghana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GIB','Gibraltar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GRD','Granada','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GRC','Grecia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GRL','Groenlandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GLP','Guadalupe','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GUM','Guam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GTM','Guatemala','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GUF','Guayana Francesa','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GGY','Guernsey','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GIN','Guinea','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GNB','Guinea-Bisáu','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GNQ','Guinea Ecuatorial','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GUY','Guyana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HTI','Haití','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HND','Honduras','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HKG','Hong Kong','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HUN','Hungría','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IND','India','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IDN','Indonesia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IRQ','Irak','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IRN','Irán (la República Islámica de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IRL','Irlanda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BVT','Isla Bouvet','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IMN','Isla de Man','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CXR','Isla de Navidad','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NFK','Isla Norfolk','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ISL','Islandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CYM','Islas Caimán (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CCK','Islas Cocos (Keeling)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COK','Islas Cook (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FRO','Islas Feroe (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SGS','Georgia del sur y las islas sandwich del sur','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('HMD','Isla Heard e Islas McDonald','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FLK','Islas Malvinas [Falkland] (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MNP','Islas Marianas del Norte (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MHL','Islas Marshall (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PCN','Pitcairn','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SLB','Islas Salomón (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TCA','Islas Turcas y Caicos (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UMI','Islas de Ultramar Menores de Estados Unidos (las)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VGB','Islas Vírgenes (Británicas)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VIR','Islas Vírgenes (EE.UU.)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ISR','Israel','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ITA','Italia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JAM','Jamaica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JPN','Japón','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JEY','Jersey','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('JOR','Jordania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KAZ','Kazajistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KEN','Kenia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KGZ','Kirguistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KIR','Kiribati','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KWT','Kuwait','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LAO','Lao, (la) República Democrática Popular','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LSO','Lesoto','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LVA','Letonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LBN','Líbano','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LBR','Liberia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LBY','Libia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LIE','Liechtenstein','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LTU','Lituania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LUX','Luxemburgo','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MAC','Macao','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MDG','Madagascar','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MYS','Malasia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MWI','Malaui','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MDV','Maldivas','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MLI','Malí','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MLT','Malta','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MAR','Marruecos','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MTQ','Martinica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MUS','Mauricio','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MRT','Mauritania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MYT','Mayotte','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MEX','México','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('FSM','Micronesia (los Estados Federados de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MDA','Moldavia (la República de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MCO','Mónaco','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MNG','Mongolia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MNE','Montenegro','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MSR','Montserrat','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MOZ','Mozambique','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NAM','Namibia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NRU','Nauru','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NPL','Nepal','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NIC','Nicaragua','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NER','Níger (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NGA','Nigeria','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NIU','Niue','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NOR','Noruega','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NCL','Nueva Caledonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NZL','Nueva Zelanda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('OMN','Omán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('NLD','Países Bajos (los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PAK','Pakistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PLW','Palaos','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PSE','Palestina, Estado de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PAN','Panamá','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PNG','Papúa Nueva Guinea','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRY','Paraguay','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PER','Perú','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PYF','Polinesia Francesa','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('POL','Polonia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRT','Portugal','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('PRI','Puerto Rico','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('GBR','Reino Unido (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CAF','República Centroafricana (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CZE','República Checa (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MKD','Macedonia (la antigua República Yugoslava de)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COG','Congo','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('COD','Congo (la República Democrática del)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DOM','República Dominicana (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('REU','Reunión','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('RWA','Ruanda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ROU','Rumania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('RUS','Rusia, (la) Federación de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ESH','Sahara Occidental','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('WSM','Samoa','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ASM','Samoa Americana','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('BLM','San Bartolomé','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('KNA','San Cristóbal y Nieves','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SMR','San Marino','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('MAF','San Martín (parte francesa)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SPM','San Pedro y Miquelón','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VCT','San Vicente y las Granadinas','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SHN','Santa Helena, Ascensión y Tristán de Acuña','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LCA','Santa Lucía','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('STP','Santo Tomé y Príncipe','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SEN','Senegal','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SRB','Serbia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SYC','Seychelles','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SLE','Sierra leona','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SGP','Singapur','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SXM','Sint Maarten (parte holandesa)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SYR','Siria, (la) República Árabe','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SOM','Somalia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('LKA','Sri Lanka','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SWZ','Suazilandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZAF','Sudáfrica','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SDN','Sudán (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SSD','Sudán del Sur','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SWE','Suecia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('CHE','Suiza','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SUR','Surinam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('SJM','Svalbard y Jan Mayen','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('THA','Tailandia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TWN','Taiwán (Provincia de China)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TZA','Tanzania, República Unida de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TJK','Tayikistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('IOT','Territorio Británico del Océano Índico (el)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ATF','Territorios Australes Franceses (los)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TLS','Timor-Leste','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TGO','Togo','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TKL','Tokelau','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TON','Tonga','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TTO','Trinidad y Tobago','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TUN','Túnez','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TKM','Turkmenistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TUR','Turquía','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('TUV','Tuvalu','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UKR','Ucrania','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UGA','Uganda','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('URY','Uruguay','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('UZB','Uzbekistán','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VUT','Vanuatu','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VAT','Santa Sede[Estado de la Ciudad del Vaticano] (la)','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VEN','Venezuela, República Bolivariana de','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('VNM','Viet Nam','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('WLF','Wallis y Futuna','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('YEM','Yemen','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('DJI','Yibuti','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZMB','Zambia','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZWE','Zimbabue','')
insert into #temp_cat_equiv(codigo,descrip,abrv) values('ZZZ','Países no declarados','')

delete from sb_equivalencias where eq_catalogo = 'PAIS_CFDI'

insert into sb_equivalencias (eq_catalogo, eq_valor_cat, eq_valor_arch, eq_descripcion, eq_estado)
select 'PAIS_CFDI', c.codigo, tp.codigo, tp.descrip, 'V'
  from cobis..cl_catalogo c , #temp_cat_equiv tp
 where tabla = (select codigo from cobis..cl_tabla where tabla = 'cl_pais')
   and replace(replace(replace(replace(replace(upper(descrip),'Á','A'),'É','E'),'Í','I'),'Ó','O'),'Ú','U')
  like replace(replace(replace(replace(replace(upper(valor),'Á','A') ,'É','E'),'Í','I'),'Ó','O'),'Ú','U')
go
delete from #temp_cat_equiv
go
-- -------------------------------------------------------------

use cob_credito
go
delete from cr_corresp_sib where tabla = 'ca_forma_pago_mop'
go
insert into cr_corresp_sib values('UR','ca_forma_pago_mop','UR','Cuenta si informacion',null,null,null,null)
insert into cr_corresp_sib values('00','ca_forma_pago_mop','00','Muy reciente para ser calificada',-1,-1,null,null)
insert into cr_corresp_sib values('01','ca_forma_pago_mop','01','Cuenta al corriente',0,0,null,null)
insert into cr_corresp_sib values('02','ca_forma_pago_mop','02','Cuenta con atraso de 1 a 29',1,29,null,null)
insert into cr_corresp_sib values('03','ca_forma_pago_mop','03','Cuenta con atraso de 30 a 59',30,59,null,null)
insert into cr_corresp_sib values('04','ca_forma_pago_mop','04','Cuenta con atraso de 60 a 89',60,89,null,null)
insert into cr_corresp_sib values('05','ca_forma_pago_mop','05','Cuenta con atraso de 90 a 119',90,119,null,null)
insert into cr_corresp_sib values('06','ca_forma_pago_mop','06','Cuenta con atraso de 120 a 149',120,149,null,null)
insert into cr_corresp_sib values('07','ca_forma_pago_mop','07','Cuenta con atraso de 150 días hasta 12 meses',150,360,null,null)
insert into cr_corresp_sib values('96','ca_forma_pago_mop','96','Cuenta con atraso de más de 12 meses',361,1000,null,null)
insert into cr_corresp_sib values('97','ca_forma_pago_mop','97','Cuenta con deuda parcial o total sin recuperar',1001,2000,null,null)
insert into cr_corresp_sib values('98','ca_forma_pago_mop','97','Fraude cometido por el Cliente',2001,10000,null,null)
go
DELETE cr_corresp_sib WHERE tabla = 'T1'

INSERT INTO cr_corresp_sib (codigo, tabla, codigo_sib, descripcion_sib, limite_inf, limite_sup, monto_inf, monto_sup)
VALUES ('GRUPAL', 'T1', '001', 'Credito Grupal', NULL, NULL, NULL, NULL)

INSERT INTO cr_corresp_sib (codigo, tabla, codigo_sib, descripcion_sib, limite_inf, limite_sup, monto_inf, monto_sup)
VALUES ('INDIVIDUAL', 'T1', '002', 'Credito Grupal', NULL, NULL, NULL, NULL)

INSERT INTO cr_corresp_sib (codigo, tabla, codigo_sib, descripcion_sib, limite_inf, limite_sup, monto_inf, monto_sup)
VALUES ('INTERCICLO', 'T1', '003', 'Credito Grupal', NULL, NULL, NULL, NULL)
GO

