//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 02:47:53 PM COT 
//


package com.cobiscorp.cloud.xmlgenerator.dto.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Cuenta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cuenta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="numero" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tasa" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="saldo" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="nombreCuenta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaCorte" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="fechaCierre" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="oficina" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="direccion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaPeriodoDesde" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="fechaPeriodoHasta" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="saldoAnterior" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="totalIntereses" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="saldoFechaCorte" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="mensaje1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mensaje2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mensaje3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cuenta")
public class Cuenta {

    @XmlAttribute(name = "numero")
    protected String numero;
    @XmlAttribute(name = "codigo")
    protected Integer codigo;
    @XmlAttribute(name = "tasa")
    protected Float tasa;
    @XmlAttribute(name = "saldo")
    protected Float saldo;
    @XmlAttribute(name = "nombreCuenta")
    protected String nombreCuenta;
    @XmlAttribute(name = "fechaCorte")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaCorte;
    @XmlAttribute(name = "fechaCierre")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaCierre;
    @XmlAttribute(name = "oficina")
    protected String oficina;
    @XmlAttribute(name = "direccion")
    protected String direccion;
    @XmlAttribute(name = "fechaPeriodoDesde")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaPeriodoDesde;
    @XmlAttribute(name = "fechaPeriodoHasta")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaPeriodoHasta;
    @XmlAttribute(name = "saldoAnterior")
    protected Float saldoAnterior;
    @XmlAttribute(name = "totalIntereses")
    protected Float totalIntereses;
    @XmlAttribute(name = "saldoFechaCorte")
    protected Float saldoFechaCorte;
    @XmlAttribute(name = "mensaje1")
    protected String mensaje1;
    @XmlAttribute(name = "mensaje2")
    protected String mensaje2;
    @XmlAttribute(name = "mensaje3")
    protected String mensaje3;

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigo(Integer value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the tasa property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasa() {
        return tasa;
    }

    /**
     * Sets the value of the tasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasa(Float value) {
        this.tasa = value;
    }

    /**
     * Gets the value of the saldo property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSaldo() {
        return saldo;
    }

    /**
     * Sets the value of the saldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSaldo(Float value) {
        this.saldo = value;
    }

    /**
     * Gets the value of the nombreCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreCuenta() {
        return nombreCuenta;
    }

    /**
     * Sets the value of the nombreCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreCuenta(String value) {
        this.nombreCuenta = value;
    }

    /**
     * Gets the value of the fechaCorte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaCorte() {
        return fechaCorte;
    }

    /**
     * Sets the value of the fechaCorte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaCorte(XMLGregorianCalendar value) {
        this.fechaCorte = value;
    }

    /**
     * Gets the value of the fechaCierre property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaCierre() {
        return fechaCierre;
    }

    /**
     * Sets the value of the fechaCierre property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaCierre(XMLGregorianCalendar value) {
        this.fechaCierre = value;
    }

    /**
     * Gets the value of the oficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the fechaPeriodoDesde property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPeriodoDesde() {
        return fechaPeriodoDesde;
    }

    /**
     * Sets the value of the fechaPeriodoDesde property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPeriodoDesde(XMLGregorianCalendar value) {
        this.fechaPeriodoDesde = value;
    }

    /**
     * Gets the value of the fechaPeriodoHasta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPeriodoHasta() {
        return fechaPeriodoHasta;
    }

    /**
     * Sets the value of the fechaPeriodoHasta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPeriodoHasta(XMLGregorianCalendar value) {
        this.fechaPeriodoHasta = value;
    }

    /**
     * Gets the value of the saldoAnterior property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSaldoAnterior() {
        return saldoAnterior;
    }

    /**
     * Sets the value of the saldoAnterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSaldoAnterior(Float value) {
        this.saldoAnterior = value;
    }

    /**
     * Gets the value of the totalIntereses property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTotalIntereses() {
        return totalIntereses;
    }

    /**
     * Sets the value of the totalIntereses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTotalIntereses(Float value) {
        this.totalIntereses = value;
    }

    /**
     * Gets the value of the saldoFechaCorte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Float getSaldoFechaCorte() {
        return saldoFechaCorte;
    }

    /**
     * Sets the value of the saldoFechaCorte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSaldoFechaCorte(Float value) {
        this.saldoFechaCorte = value;
    }

    /**
     * Gets the value of the mensaje1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje1() {
        return mensaje1;
    }

    /**
     * Sets the value of the mensaje1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje1(String value) {
        this.mensaje1 = value;
    }

    /**
     * Gets the value of the mensaje2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje2() {
        return mensaje2;
    }

    /**
     * Sets the value of the mensaje2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje2(String value) {
        this.mensaje2 = value;
    }

    /**
     * Gets the value of the mensaje3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje3() {
        return mensaje3;
    }

    /**
     * Sets the value of the mensaje3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje3(String value) {
        this.mensaje3 = value;
    }

}
