//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 02:47:53 PM COT 
//


package com.cobiscorp.cloud.xmlgenerator.dto.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Movimiento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Movimiento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="fecha" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oficina" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="depositos" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="retiros" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="saldo" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Movimiento")
public class Movimiento {

    @XmlAttribute(name = "fecha")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fecha;
    @XmlAttribute(name = "descripcion")
    protected String descripcion;
    @XmlAttribute(name = "oficina")
    protected String oficina;
    @XmlAttribute(name = "depositos")
    protected Float depositos;
    @XmlAttribute(name = "retiros")
    protected Float retiros;
    @XmlAttribute(name = "saldo")
    protected Float saldo;

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the oficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the depositos property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDepositos() {
        return depositos;
    }

    /**
     * Sets the value of the depositos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDepositos(Float value) {
        this.depositos = value;
    }

    /**
     * Gets the value of the retiros property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRetiros() {
        return retiros;
    }

    /**
     * Sets the value of the retiros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRetiros(Float value) {
        this.retiros = value;
    }

    /**
     * Gets the value of the saldo property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSaldo() {
        return saldo;
    }

    /**
     * Sets the value of the saldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSaldo(Float value) {
        this.saldo = value;
    }

}
