//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 02:47:53 PM COT 
//


package com.cobiscorp.cloud.xmlgenerator.dto.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cobiscorp.cloud.xmlgenerator.dto.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _EstadoCuenta_QNAME = new QName("http://www.example.org/EstadoCuenta", "EstadoCuenta");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cobiscorp.cloud.xmlgenerator.dto.jaxb
     */
    public ObjectFactory() {
    	//create new instances
    }

    /**
     * Create an instance of {@link Movimientos }
     * 
     */
    public Movimientos createMovimientos() {
        return new Movimientos();
    }

    /**
     * Create an instance of {@link Movimiento }
     * 
     */
    public Movimiento createMovimiento() {
        return new Movimiento();
    }

    /**
     * Create an instance of {@link Cuenta }
     * 
     */
    public Cuenta createCuenta() {
        return new Cuenta();
    }

    /**
     * Create an instance of {@link EstadoCuenta }
     * 
     */
    public EstadoCuenta createEstadoCuenta() {
        return new EstadoCuenta();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EstadoCuenta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/EstadoCuenta", name = "EstadoCuenta")
    public JAXBElement<EstadoCuenta> createEstadoCuenta(EstadoCuenta value) {
        return new JAXBElement<EstadoCuenta>(_EstadoCuenta_QNAME, EstadoCuenta.class, null, value);
    }

}
