use cob_conta
go

declare 
@w_secuencial    int ,
@w_cuenta        varchar(64),
@w_nombre_ante   varchar(84),
@w_nombre_nuevo  varchar(84)




create table #nombres_cuentas
(secuencial    int ,
 cuenta        varchar(64),
 nombre_ante   varchar(84),
 nombre_nuevo  varchar(84)
)

insert into #nombres_cuentas values(1,'13119001','MICROCRÉDITOS CAPITAL ','MICROCRÉDITOS CAPITAL ETAPA 1')
insert into #nombres_cuentas values(2,'1311900101','MICROCRÉDITOS CAPITAL NO EXIGIBLE ','MICROCRÉDITOS CAPITAL NO EXIGIBLE ETAPA 1')
insert into #nombres_cuentas values(3,'131190010101','MICROCRÉDITOS CAPITAL GRUPALES ','MICROCRÉDITOS CAPITAL GRUPALES ETAPA 1')
insert into #nombres_cuentas values(4,'131190010102','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ETAPA 1')
insert into #nombres_cuentas values(5,'131190010103','MICROCRÉDITOS CAPITAL INDIVIDUALES ','MICROCRÉDITOS CAPITAL INDIVIDUALES ETAPA 1')
insert into #nombres_cuentas values(6,'1311900102','MICROCRÉDITOS CAPITAL EXIGIBLE ','MICROCRÉDITOS CAPITAL EXIGIBLE ETAPA 1')
insert into #nombres_cuentas values(7,'131190010201','MICROCRÉDITOS CAPITAL GRUPALES ','MICROCRÉDITOS CAPITAL GRUPALES ETAPA 1')
insert into #nombres_cuentas values(8,'131190010202','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ETAPA 1')
insert into #nombres_cuentas values(9,'131190010203','MICROCRÉDITOS CAPITAL INDIVIDUALES ','MICROCRÉDITOS CAPITAL INDIVIDUALES ETAPA 1')
insert into #nombres_cuentas values(10,'13119003','MICROCRÉDITOS INTERÉS ','MICROCRÉDITOS INTERÉS ETAPA 1')
insert into #nombres_cuentas values(11,'1311900301','INTERESES DEVENGADO NO EXIGIBLE ','INTERESES DEVENGADO NO EXIGIBLE ETAPA 1')
insert into #nombres_cuentas values(12,'131190030101','MICROCRÉDITOS INTERESES GRUPALES','MICROCRÉDITOS INTERESES GRUPALES ETAPA 1')
insert into #nombres_cuentas values(13,'131190030102','MICROCRÉDITOS INTERESES INDIVIDUAL SIMPLE ','MICROCRÉDITOS INTERESES INDIVIDUAL SIMPLE ETAPA 1')
insert into #nombres_cuentas values(14,'131190030103','MICROCRÉDITOS INTERESES INDIVIDUALES ','MICROCRÉDITOS INTERESES INDIVIDUALES ETAPA 1')
insert into #nombres_cuentas values(15,'1311900302','INTERESES DEVENGADO EXIGIBLE ','INTERESES DEVENGADO EXIGIBLE ETAPA 1')
insert into #nombres_cuentas values(16,'131190030201','MICROCRÉDITOS INTERESES GRUPALES ','MICROCRÉDITOS INTERESES GRUPALES ETAPA 1')
insert into #nombres_cuentas values(17,'131190030202','MICROCRÉDITOS INTERESES INDIVIDUAL SIMPLE ','MICROCRÉDITOS INTERESES INDIVIDUAL SIMPLE ETAPA 1')
insert into #nombres_cuentas values(18,'131190030203','MICROCRÉDITOS INTERESES INDIVIDUALES ','MICROCRÉDITOS INTERESES INDIVIDUALES ETAPA 1')
insert into #nombres_cuentas values(19,'1361','CRÉDITOS VENCIDOS DE CONSUMO ','CRÉDITOS DE CONSUMO ETAPA 3')
insert into #nombres_cuentas values(20,'13619001','MICROCRÉDITOS CAPITAL ','MICROCRÉDITOS CAPITAL ETAPA 3')
insert into #nombres_cuentas values(21,'1361900101','MICROCRÉDITOS CAPITAL NO EXIGIBLE ','MICROCRÉDITOS CAPITAL NO EXIGIBLE ETAPA 3')
insert into #nombres_cuentas values(22,'136190010101','MICROCRÉDITOS CAPITAL GRUPALES ','MICROCRÉDITOS CAPITAL GRUPALES ETAPA 3')
insert into #nombres_cuentas values(23,'136190010102','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ETAPA 3')
insert into #nombres_cuentas values(24,'136190010103','MICROCRÉDITOS CAPITAL INDIVIDUALES ','MICROCRÉDITOS CAPITAL INDIVIDUALES ETAPA 3')
insert into #nombres_cuentas values(25,'1361900102','MICROCRÉDITOS CAPITAL EXIGIBLE ','MICROCRÉDITOS CAPITAL EXIGIBLE ETAPA 3')
insert into #nombres_cuentas values(26,'136190010201','MICROCRÉDITOS CAPITAL GRUPALES ','MICROCRÉDITOS CAPITAL GRUPALES ETAPA 3')
insert into #nombres_cuentas values(27,'136190010202','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ','MICROCRÉDITOS CAPITAL INDIVIDUAL SIMPLE ETAPA 3')
insert into #nombres_cuentas values(28,'136190010203','MICROCRÉDITOS CAPITAL INDIVIDUALES ','MICROCRÉDITOS CAPITAL INDIVIDUALES ETAPA 3')
insert into #nombres_cuentas values(29,'13619003','MICROCRÉDITOS INTERÉS ','MICROCRÉDITOS INTERÉS ETAPA 3')
insert into #nombres_cuentas values(30,'1361900301','MICROCRÉDITOS INTERÉS DEVENGADO EXIGIBLE ','MICROCRÉDITOS INTERÉS DEVENGADO EXIGIBLE ETAPA 3')
insert into #nombres_cuentas values(31,'136190030101','MICROCRÉDITOS INTERESES GRUPALES ','MICROCRÉDITOS INTERESES GRUPALES ETAPA 3')
insert into #nombres_cuentas values(32,'136190030102','MICROCRÉDITOS INTERESES INDIVIDUAL SIMPLE ','MICROCRÉDITOS INTERESES INDIVIDUAL SIMPLE ETAPA 3')
insert into #nombres_cuentas values(33,'136190030103','MICROCRÉDITOS INTERESES INDIVIDUALES ','MICROCRÉDITOS INTERESES INDIVIDUALES ETAPA 3')
insert into #nombres_cuentas values(34,'1391','ESTIMACIÓN PREVENTIVA PARA RIESGOS CREDITICIOS DERIVADA DE LA CALIFICACIÓN','ESTIMACIÓN PREVENTIVA PARA RIESGOS CREDITICIOS')
insert into #nombres_cuentas values(35,'5102','INTERESES DE CARTERA DE CRÉDITO VENCIDA','INTERESES DE CARTERA DE CRÉDITO ETAPA 3')
insert into #nombres_cuentas values(36,'510261','CRÉDITOS VENCIDOS DE CONSUMO','CRÉDITOS DE CONSUMO ETAPA 3')
insert into #nombres_cuentas values(37,'51026190','MICROCRÉDITOS INTERESES VENCIDOS','MICROCRÉDITOS INTERESES ETAPA 3')
insert into #nombres_cuentas values(38,'5102619001','MICROCRÉDITOS INTERESES VENCIDOS GRAVADOS (DEVENGADOS EXIGIBLES)','MICROCRÉDITOS INTERESES GRAVADOS (DEVENGADOS EXIGIBLES) ETAPA 3')
insert into #nombres_cuentas values(39,'510261900101','MICROCRÉDITOS GRUPAL (INT. VEN.)','MICROCRÉDITOS GRUPAL INT. ETAPA 3')
insert into #nombres_cuentas values(40,'510261900102','MICROCRÉDITOS INDIVIDUAL SIMPLE (INT. VEN.)','MICROCRÉDITOS INDIVIDUAL SIMPLE   INT. ETAPA 3')
insert into #nombres_cuentas values(41,'510261900103','MICROCRÉDITOS INDIVIDUAL   (INT. VEN.)','MICROCRÉDITOS INDIVIDUAL   INT. ETAPA 3')
insert into #nombres_cuentas values(42,'5105119001','MICROCRÉDITOS INTERESES GRAVADOS (DEVENGADOS EXIGIBLES)','MICROCRÉDITOS INTERESES GRAVADOS (DEVENGADOS EXIGIBLES) ETAPA 1')
insert into #nombres_cuentas values(43,'510511900101','MICROCRÉDITOS GRUPAL (INT. VIG.)','MICROCRÉDITOS GRUPAL INT. ETAPA 1')
insert into #nombres_cuentas values(44,'510511900102','MICROCRÉDITOS INDIVIDUAL SIMPLE (INT. VIG.)','MICROCRÉDITOS INDIVIDUAL SIMPLE INT. ETAPA 1')
insert into #nombres_cuentas values(45,'510511900103','MICROCRÉDITOS INDIVIDUAL (INT. VIG.)','MICROCRÉDITOS INDIVIDUAL INT. ETAPA 1')
insert into #nombres_cuentas values(46,'5105119002',' MICROCRÉDITOS INTERESES NO GRAVADOS (DEVENGADOS NO EXIGIBLES)','MICROCRÉDITOS INTERESES NO GRAVADOS (DEVENGADOS NO EXIGIBLES) ETAPA 1')
insert into #nombres_cuentas values(47,'510511900201','MICROCRÉDITOS GRUPAL (INT. VIG.)','MICROCRÉDITOS GRUPAL INT. ETAPA 1')
insert into #nombres_cuentas values(48,'510511900202','MICROCRÉDITOS INDIVIDUAL SIMPLE (INT. VIG.)','MICROCRÉDITOS INDIVIDUAL SIMPLE INT. ETAPA 1')
insert into #nombres_cuentas values(49,'510511900203','MICROCRÉDITOS INDIVIDUAL (INT. VIG.)','MICROCRÉDITOS INDIVIDUAL INT. ETAPA 1')
insert into #nombres_cuentas values(50,'6291','ESTIMACIÓN PREVENTIVA PARA RIESGOS CREDITICIOS DERIVADA DE LA CALIFICACIÓN','ESTIMACIÓN PREVENTIVA PARA RIESGOS CREDITICIOS')


select @w_secuencial = 0

while 1 = 1
begin
   select top 1
   @w_secuencial    = secuencial,
   @w_cuenta        = cuenta,
   @w_nombre_ante   = nombre_ante,
   @w_nombre_nuevo  = ltrim(rtrim(nombre_nuevo))
   from #nombres_cuentas
   where secuencial > @w_secuencial
   order by secuencial
   
   if @@rowcount = 0 break
   
   select * from cb_cuenta where cu_cuenta = ltrim(rtrim(@w_cuenta))
   
   update cb_cuenta set
   cu_nombre = @w_nombre_nuevo,
   cu_descripcion = @w_nombre_nuevo
   where cu_cuenta = ltrim(rtrim(@w_cuenta))
   
   select * from cb_cuenta where cu_cuenta = ltrim(rtrim(@w_cuenta))
   
end 



drop table #nombres_cuentas