package com.cobiscorp.ecobis.clientviewer.bl;

import com.cobiscorp.ecobis.clientviewer.dto.ProductsByClientDTO;

public interface QueryProductsManager {

	/**
	 * Method used to get the details of the products associated to a specific
	 * customer.
	 * 
	 * @param customer
	 *            , it's a customer code for the consultation.
	 * @param spid
	 *            , it's the sequential generated by the prepareProductsData
	 *            service and used for this method.
	 * @return A list with the information of the details of the products
	 *         associated to a customer.
	 */
	ProductsByClientDTO getQueryProductsByClientId(Integer customer, String documentId, Integer spid);

	/**
	 * Method used to get the details of the history products associated to a
	 * specific customer.
	 * 
	 * @param customer
	 *            , it's a customer code for the consultation.
	 * @param spid
	 *            , it's the sequential generated by the prepareProductsData
	 *            service and used for this method.
	 * @return A list with the information of the details of the products
	 *         associated to a customer.
	 */
	ProductsByClientDTO getQueryHistoryProductsByClientId(Integer customer, Integer spid);

	/**
	 * Method used to delete the details of the products associated to a
	 * specific customer.
	 * 
	 * @param spid
	 *            , it's the sequential generated by the prepareProductsData
	 *            service and used for this method.
	 */
	void deleteQueryProductsByClientId(Integer spid);
}
