//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:45:49 AM COT 
//


package com.cobiscorp.cloud.xmlgenerator.dto.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cobiscorp.cloud.xmlgenerator.dto.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EstadoCuentaCa_QNAME = new QName("http://www.example.org/EstadoCuentaCa", "EstadoCuentaCa");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cobiscorp.cloud.xmlgenerator.dto.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EstadoCuentaCa }
     * 
     */
    public EstadoCuentaCa createEstadoCuentaCa() {
        return new EstadoCuentaCa();
    }

    /**
     * Create an instance of {@link Operacion }
     * 
     */
    public Operacion createOperacion() {
        return new Operacion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EstadoCuentaCa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/EstadoCuentaCa", name = "EstadoCuentaCa")
    public JAXBElement<EstadoCuentaCa> createEstadoCuentaCa(EstadoCuentaCa value) {
        return new JAXBElement<EstadoCuentaCa>(_EstadoCuentaCa_QNAME, EstadoCuentaCa.class, null, value);
    }

}
