//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:45:49 AM COT 
//


package com.cobiscorp.cloud.xmlgenerator.dto.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Operacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Operacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Fecha" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="RFC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Cuenta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Cliente" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Nombres" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FechaLimitePago" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="PagoMinimo" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="DeudaTotal" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="SaldoFecha" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="Producto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Finalidad" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ImporteAutorizado" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="CreditoOtorgado" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="FechaDisposicion" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Plazo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="DiasPlazo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TipoPrestamo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="ProximoAbono" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaOrdinaria" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaMoratorio" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaOrdinariaConcep" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaMoratorioConcep" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaComisionesConcep" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaIvaConcep" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="CAT" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="PorcentajeCubierto" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="AbonoCapital" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaOrdinarioDet" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaMoratorioDet" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaComisionDet" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="TasaIvaDet" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="MontoPagado" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="FechaPago" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Capital" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="InteresOrdinario" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="InteresMoratorio" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="IVA" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Operacion")
public class Operacion {

    @XmlAttribute(name = "Fecha")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fecha;
    @XmlAttribute(name = "RFC")
    protected String rfc;
    @XmlAttribute(name = "Cuenta")
    protected String cuenta;
    @XmlAttribute(name = "Cliente")
    protected Integer cliente;
    @XmlAttribute(name = "Nombres")
    protected String nombres;
    @XmlAttribute(name = "Direccion")
    protected String direccion;
    @XmlAttribute(name = "FechaLimitePago")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaLimitePago;
    @XmlAttribute(name = "PagoMinimo")
    protected Float pagoMinimo;
    @XmlAttribute(name = "DeudaTotal")
    protected Float deudaTotal;
    @XmlAttribute(name = "SaldoFecha")
    protected Float saldoFecha;
    @XmlAttribute(name = "Producto")
    protected String producto;
    @XmlAttribute(name = "Finalidad")
    protected String finalidad;
    @XmlAttribute(name = "ImporteAutorizado")
    protected Float importeAutorizado;
    @XmlAttribute(name = "CreditoOtorgado")
    protected Float creditoOtorgado;
    @XmlAttribute(name = "FechaDisposicion")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaDisposicion;
    @XmlAttribute(name = "Plazo")
    protected Integer plazo;
    @XmlAttribute(name = "DiasPlazo")
    protected Integer diasPlazo;
    @XmlAttribute(name = "TipoPrestamo")
    protected String tipoPrestamo;
    @XmlAttribute(name = "FechaVencimiento")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaVencimiento;
    @XmlAttribute(name = "ProximoAbono")
    protected Float proximoAbono;
    @XmlAttribute(name = "TasaOrdinaria")
    protected Float tasaOrdinaria;
    @XmlAttribute(name = "TasaMoratorio")
    protected Float tasaMoratorio;
    @XmlAttribute(name = "TasaOrdinariaConcep")
    protected Float tasaOrdinariaConcep;
    @XmlAttribute(name = "TasaMoratorioConcep")
    protected Float tasaMoratorioConcep;
    @XmlAttribute(name = "TasaComisionesConcep")
    protected Float tasaComisionesConcep;
    @XmlAttribute(name = "TasaIvaConcep")
    protected Float tasaIvaConcep;
    @XmlAttribute(name = "CAT")
    protected Float cat;
    @XmlAttribute(name = "PorcentajeCubierto")
    protected Float porcentajeCubierto;
    @XmlAttribute(name = "AbonoCapital")
    protected Float abonoCapital;
    @XmlAttribute(name = "TasaOrdinarioDet")
    protected Float tasaOrdinarioDet;
    @XmlAttribute(name = "TasaMoratorioDet")
    protected Float tasaMoratorioDet;
    @XmlAttribute(name = "TasaComisionDet")
    protected Float tasaComisionDet;
    @XmlAttribute(name = "TasaIvaDet")
    protected Float tasaIvaDet;
    @XmlAttribute(name = "MontoPagado")
    protected Float montoPagado;
    @XmlAttribute(name = "FechaPago")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaPago;
    @XmlAttribute(name = "Capital")
    protected Float capital;
    @XmlAttribute(name = "InteresOrdinario")
    protected Float interesOrdinario;
    @XmlAttribute(name = "InteresMoratorio")
    protected Float interesMoratorio;
    @XmlAttribute(name = "IVA")
    protected Float iva;

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the rfc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFC() {
        return rfc;
    }

    /**
     * Sets the value of the rfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFC(String value) {
        this.rfc = value;
    }

    /**
     * Gets the value of the cuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuenta() {
        return cuenta;
    }

    /**
     * Sets the value of the cuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuenta(String value) {
        this.cuenta = value;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCliente(Integer value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the nombres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * Sets the value of the nombres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombres(String value) {
        this.nombres = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the fechaLimitePago property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaLimitePago() {
        return fechaLimitePago;
    }

    /**
     * Sets the value of the fechaLimitePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaLimitePago(XMLGregorianCalendar value) {
        this.fechaLimitePago = value;
    }

    /**
     * Gets the value of the pagoMinimo property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPagoMinimo() {
        return pagoMinimo;
    }

    /**
     * Sets the value of the pagoMinimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPagoMinimo(Float value) {
        this.pagoMinimo = value;
    }

    /**
     * Gets the value of the deudaTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDeudaTotal() {
        return deudaTotal;
    }

    /**
     * Sets the value of the deudaTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDeudaTotal(Float value) {
        this.deudaTotal = value;
    }

    /**
     * Gets the value of the saldoFecha property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSaldoFecha() {
        return saldoFecha;
    }

    /**
     * Sets the value of the saldoFecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSaldoFecha(Float value) {
        this.saldoFecha = value;
    }

    /**
     * Gets the value of the producto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducto() {
        return producto;
    }

    /**
     * Sets the value of the producto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducto(String value) {
        this.producto = value;
    }

    /**
     * Gets the value of the finalidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalidad() {
        return finalidad;
    }

    /**
     * Sets the value of the finalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalidad(String value) {
        this.finalidad = value;
    }

    /**
     * Gets the value of the importeAutorizado property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getImporteAutorizado() {
        return importeAutorizado;
    }

    /**
     * Sets the value of the importeAutorizado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setImporteAutorizado(Float value) {
        this.importeAutorizado = value;
    }

    /**
     * Gets the value of the creditoOtorgado property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCreditoOtorgado() {
        return creditoOtorgado;
    }

    /**
     * Sets the value of the creditoOtorgado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCreditoOtorgado(Float value) {
        this.creditoOtorgado = value;
    }

    /**
     * Gets the value of the fechaDisposicion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaDisposicion() {
        return fechaDisposicion;
    }

    /**
     * Sets the value of the fechaDisposicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaDisposicion(XMLGregorianCalendar value) {
        this.fechaDisposicion = value;
    }

    /**
     * Gets the value of the plazo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPlazo() {
        return plazo;
    }

    /**
     * Sets the value of the plazo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPlazo(Integer value) {
        this.plazo = value;
    }

    /**
     * Gets the value of the diasPlazo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDiasPlazo() {
        return diasPlazo;
    }

    /**
     * Sets the value of the diasPlazo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDiasPlazo(Integer value) {
        this.diasPlazo = value;
    }

    /**
     * Gets the value of the tipoPrestamo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPrestamo() {
        return tipoPrestamo;
    }

    /**
     * Sets the value of the tipoPrestamo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPrestamo(String value) {
        this.tipoPrestamo = value;
    }

    /**
     * Gets the value of the fechaVencimiento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * Sets the value of the fechaVencimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaVencimiento(XMLGregorianCalendar value) {
        this.fechaVencimiento = value;
    }

    /**
     * Gets the value of the proximoAbono property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getProximoAbono() {
        return proximoAbono;
    }

    /**
     * Sets the value of the proximoAbono property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setProximoAbono(Float value) {
        this.proximoAbono = value;
    }

    /**
     * Gets the value of the tasaOrdinaria property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaOrdinaria() {
        return tasaOrdinaria;
    }

    /**
     * Sets the value of the tasaOrdinaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaOrdinaria(Float value) {
        this.tasaOrdinaria = value;
    }

    /**
     * Gets the value of the tasaMoratorio property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaMoratorio() {
        return tasaMoratorio;
    }

    /**
     * Sets the value of the tasaMoratorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaMoratorio(Float value) {
        this.tasaMoratorio = value;
    }

    /**
     * Gets the value of the tasaOrdinariaConcep property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaOrdinariaConcep() {
        return tasaOrdinariaConcep;
    }

    /**
     * Sets the value of the tasaOrdinariaConcep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaOrdinariaConcep(Float value) {
        this.tasaOrdinariaConcep = value;
    }

    /**
     * Gets the value of the tasaMoratorioConcep property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaMoratorioConcep() {
        return tasaMoratorioConcep;
    }

    /**
     * Sets the value of the tasaMoratorioConcep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaMoratorioConcep(Float value) {
        this.tasaMoratorioConcep = value;
    }

    /**
     * Gets the value of the tasaComisionesConcep property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaComisionesConcep() {
        return tasaComisionesConcep;
    }

    /**
     * Sets the value of the tasaComisionesConcep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaComisionesConcep(Float value) {
        this.tasaComisionesConcep = value;
    }

    /**
     * Gets the value of the tasaIvaConcep property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaIvaConcep() {
        return tasaIvaConcep;
    }

    /**
     * Sets the value of the tasaIvaConcep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaIvaConcep(Float value) {
        this.tasaIvaConcep = value;
    }

    /**
     * Gets the value of the cat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCAT() {
        return cat;
    }

    /**
     * Sets the value of the cat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCAT(Float value) {
        this.cat = value;
    }

    /**
     * Gets the value of the porcentajeCubierto property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPorcentajeCubierto() {
        return porcentajeCubierto;
    }

    /**
     * Sets the value of the porcentajeCubierto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPorcentajeCubierto(Float value) {
        this.porcentajeCubierto = value;
    }

    /**
     * Gets the value of the abonoCapital property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAbonoCapital() {
        return abonoCapital;
    }

    /**
     * Sets the value of the abonoCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAbonoCapital(Float value) {
        this.abonoCapital = value;
    }

    /**
     * Gets the value of the tasaOrdinarioDet property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaOrdinarioDet() {
        return tasaOrdinarioDet;
    }

    /**
     * Sets the value of the tasaOrdinarioDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaOrdinarioDet(Float value) {
        this.tasaOrdinarioDet = value;
    }

    /**
     * Gets the value of the tasaMoratorioDet property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaMoratorioDet() {
        return tasaMoratorioDet;
    }

    /**
     * Sets the value of the tasaMoratorioDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaMoratorioDet(Float value) {
        this.tasaMoratorioDet = value;
    }

    /**
     * Gets the value of the tasaComisionDet property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaComisionDet() {
        return tasaComisionDet;
    }

    /**
     * Sets the value of the tasaComisionDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaComisionDet(Float value) {
        this.tasaComisionDet = value;
    }

    /**
     * Gets the value of the tasaIvaDet property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTasaIvaDet() {
        return tasaIvaDet;
    }

    /**
     * Sets the value of the tasaIvaDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTasaIvaDet(Float value) {
        this.tasaIvaDet = value;
    }

    /**
     * Gets the value of the montoPagado property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMontoPagado() {
        return montoPagado;
    }

    /**
     * Sets the value of the montoPagado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMontoPagado(Float value) {
        this.montoPagado = value;
    }

    /**
     * Gets the value of the fechaPago property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPago() {
        return fechaPago;
    }

    /**
     * Sets the value of the fechaPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPago(XMLGregorianCalendar value) {
        this.fechaPago = value;
    }

    /**
     * Gets the value of the capital property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCapital() {
        return capital;
    }

    /**
     * Sets the value of the capital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCapital(Float value) {
        this.capital = value;
    }

    /**
     * Gets the value of the interesOrdinario property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInteresOrdinario() {
        return interesOrdinario;
    }

    /**
     * Sets the value of the interesOrdinario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInteresOrdinario(Float value) {
        this.interesOrdinario = value;
    }

    /**
     * Gets the value of the interesMoratorio property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInteresMoratorio() {
        return interesMoratorio;
    }

    /**
     * Sets the value of the interesMoratorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInteresMoratorio(Float value) {
        this.interesMoratorio = value;
    }

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getIVA() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setIVA(Float value) {
        this.iva = value;
    }

}
