/*
*     REQ#149740
*     JCASTRO 16/12/2020
*/
use cob_conta_super
go

IF OBJECT_ID ('dbo.sb_rep_oper_mc_collect') IS NOT NULL
	DROP table dbo.sb_rep_oper_mc_collect
go

create table dbo.sb_rep_oper_mc_collect
		(
	secuencial_mc                        int identity not null,
	OFICINA                            varchar (64) not null,
	REGION                             varchar (64) not null,
	CC                                 varchar (40) not null,
	CONTRATO                           varchar (24) not null,
	[ID GRUPO]                         varchar (40) not null,
	[NOMBRE GRUPO]                     varchar (64) not null,
	[CICLO GRUPAL]                     varchar (20) not null,
	[NUMERO DE INTEGRANTES]            varchar (30) not null,
	RFC                                varchar (24) not null,
	CURP                               varchar (255) not null,
	[CLIENTE COBIS]                    varchar (40) not null,
	[APELLIDO PATERNO]                 varchar (64) not null,
	[APELLIDO MATERNO]                 varchar (64) not null,
	NOMBRE1                            varchar (64) not null,
	NOMBRE2                            varchar (64) not null,
	[CICLO INDIVIDUAL]                 varchar (20) not null,
	GENERO                             varchar (10) not null,
	EDAD                               varchar (4) not null,
	DOM_TELEFONO                       varchar (16) not null,
	DOM_DIRECCION                      varchar (254) not null,
	ESTADO                             varchar (64) not null,
	MUNICIPIO                          varchar (64) not null,
	LOCALIDAD                          varchar (64) not null,
	[C.P.]                             varchar (30) not null,
	[COORDENADAS DOMICILIO]            varchar (100) not null,
	NEG_TELEFONO                       varchar (16) not null,
	NEG_DIRECCION                      varchar (254) not null,
	NEG_ESTADO                         varchar (64) not null,
	NEG_MUNICIPIO                      varchar (64) not null,
	NEG_LOCALIDAD                      varchar (64) not null,
	NEG_CP                             varchar (30) not null,
	[NEG_TIPO DE LOCAL]                varchar (64) not null,
	[ACTIVIDAD ECONOMICA]              varchar (200) not null,
	[CORREO ELECTRONICO DEL CLIENTE]   varchar (254) not null,
	[NOMBRE GERENTE]                   varchar (64) not null,
	[NOMBRE COORDINADOR]               varchar (64) not null,
	[NOMBRE DEL ASESOR]                varchar (64) not null,
	[CORREO ELECTRONICO ASESOR]        varchar (64) not null,
	[TELEFONO DEL ASESOR]              varchar (64) not null,
	[ESTATUS ASESOR]                   varchar (64) not null,
	[PRODUCTO DE PRESTAMOS]            varchar (40) not null,
	[SUBPRODUCTO PRESTAMO]             varchar (64) not null,
	[MONTO CREDITO]                    varchar (40) not null,
	[FECHA SOLICITUD]                  varchar (30) not null,
	[FECHA APROBACION MONTOS]          varchar (30) not null,
	[FECHA VENCIMIENTO PRESTAMO]       varchar (30) not null,
	[NUMERO DE CONTRATO]               varchar (24) not null,
	PLAZO                              varchar (64) not null,
	[NUMERO CUOTAS]                    varchar (40) not null,
	[DIA DE PAGO]                      varchar (20) not null,
	[PLAZO DIAS]                       varchar (40) not null,
	[PLAZO MES]                        varchar (40) not null,
	[VALOR CUOTA]                      varchar (40) not null,
	[CAPITAL DE LA CUOTA]              varchar (40) not null,
	[INTERESES DE LA CUOTA]            varchar (40) not null,
	[IVA DE LA CUOTA]                  varchar (40) not null,
	[TASA INTERES (ANUAL)]             varchar (40) not null,
	[CUOTAS PENDIENTES]                varchar (40) not null,
	[CUOTAS VENCIDAS]                  varchar (40) not null,
	[CAPITAL VIGENTE EXIGIBLE]         varchar (40) not null,
	[CAPITAL VENCIDO EXIGIBLE]         varchar (40) not null,
	[SALDO CAP]                        varchar (40) not null,
	[INTERES VIGENTE EXIGIBLE]         varchar (40) not null,
	[INTERES SUSPENDIDO]               varchar (40) not null,
	[IVA INTERES EXIGIBLE]             varchar (40) not null,
	[IVA INTERES NO EXIGIBLE]          varchar (40) not null,
	COMISIONES                         varchar (40) not null,
	[IVA COMISION]                     varchar (40) not null,
	[SALDO INTERESES]                  varchar (40) not null,
	[SALDO REAL EXIGIBLE]              varchar (40) not null,
	[SALDO TOTAL]                      varchar (40) not null,
	[SALDO TOTAL EN MORA]              varchar (40) not null,
	[IMPORTE LIQUIDA CON]              varchar (40) not null,
	[DIAS MAX ATRASO ACT]              varchar (40) not null,
	[SEMANAS DE ATRASO]                varchar (40) not null,
	[DIAS MORA]                        varchar (40) not null,
	[FECHA RECIBO ANTIGUO IMP]         varchar (30) not null,
	[FECHA ULTIMA SITUACION DEUDA]     varchar (30) not null,
	[PORCENTAJE RESERVA]               varchar (40) not null,
	[CARTERA EN RIESGO]                varchar (40) not null,
	[NIVEL DE RIESGO]                  varchar (15) not null,
	[PUNTAJE DE RIESGO]                varchar (20) not null,
	[ROL MESA DIRECTIVA]               varchar (64) not null,
	[INDICADOR DE REUNION]             varchar (125) not null,
	[NUMERO DE EMPLEADO DEL ASESOR]    varchar (40) not null,
	[NUMERO DE EMPLEADO DEL COORDINADOR] varchar (40) not null,
	[NUMERO DE EMPLEADO DEL GERENTE]   varchar (40) not null,
	[DIA DE REUNION SEMANAL]           varchar (40) not null,
	[HORA DE REUNION SEMANAL]          varchar (30) not null,
	[COORDENADAS NEGOCIO]              varchar (100) not null,
	[NRO OPERACION GRUPAL]             varchar (24) not null,
	[NVO DOM_DIRECCION]                varchar (500) not null,
	[NVO ESTADO]                       varchar (500) not null,
	[NVO MUNICIPIO]                    varchar (500) not null,
	[NVO LOCALIDAD]                    varchar (500) not null,
	[NVO C.P.]                         varchar (100) not null,
	[NVAS COORDENADAS DOM]             varchar (500) not null,
	[Foto del Domicilio]               varchar (1024) not null,
	[Entre calle 1 Dom]                varchar (500) not null,
	[Entre calle 2 Dom]                varchar (500) not null,
	[Entre calle 3 Dom]                varchar (500) not null,
	[Entre calle 4 Dom]                varchar (500) not null,
	[Foto del Negocio]                 varchar (1024) not null,
	[Foto del Negocio 2]               varchar (1024) not null,
	[Entre calle 1 Neg]                varchar (500) not null,
	[Entre calle 2 Neg]                varchar (500) not null,
	[Entre calle 3 Neg]                varchar (500) not null,
	[Entre calle 4 Neg]                varchar (500) not null,
	[Foto del Domicilio Alterno]       varchar (1024) not null,
	[Entre calle 1 Dom Alterno]        varchar (500) not null,
	[Entre calle 2 Dom Alterno]        varchar (500) not null,
	[Entre calle 3 Dom Alterno]        varchar (500) not null,
	[Entre calle 4 Dom Alterno]        varchar (500) not null,
	asesor_login_mc                    varchar (64) not null,
	asesor_cargo_mc                    varchar (64) not null,
	fecha_prox_couta_mc                varchar (30) not null,
	[NUMERO_CUOTA]                     varchar(30),
	[MONTO_GARANTIA]                   varchar(30),
	CONSTRAINT PK_sb_rep_oper_mc_collect PRIMARY KEY NONCLUSTERED (secuencial_mc)
	)
go

create index idx_cliente_contrato on sb_rep_oper_mc_collect ([CLIENTE COBIS],[CONTRATO])
go