Attribute VB_Name = "MODIMG"
Option Explicit
' Módulo de manejo de firmas candidatas y condiciones de las cuentas
'TODO: Auto-fix by Project Analyzer v9.0.05 on 14/08/2010

'! removed Global VGGrafo() As String
'Arreglo con el código y la firma
' ***********************************************************8
' LLamadas a los DLL'S que manejan la compactación de imágenes
'
'! Declare Sub BitMap Lib "bitmap.dll" (Picture As Control, ByVal lpBits As String, ByVal Col As Integer, ByVal Row As Integer)
'! Declare Sub SvPicture Lib "bitmap.dll" (Picture As Control, ByVal path As String)
'! Declare Sub GetPicture Lib "bitmap.dll" (Picture As Control, ByVal path As String)
'! Declare Function DoScan Lib "scanner.dll" (ByVal hDC As Integer, ByVal a As String) As Integer
'! Declare Function GetPicStr Lib "bitmap.dll" (Picture As Control, ByVal VLImagen As String) As Integer



