package com.cobiscorp.ecobis.clientviewer;

import com.cobiscorp.ecobis.clientviewer.dto.ProductsByClientDTO;

public interface QueryProductsService {
	/**
	 * Method used to get the details of the products associated to a specific
	 * customer.
	 * 
	 * @param customerCode
	 *            , it's a customer code for the consultation.
	 * @param spid
	 *            , it's the sequential generated by the prepareProductsData
	 *            service and used for this method.
	 * @return A ProductsByClientDTO Object with the information of the details
	 *         of the products associated to a customer.
	 */
	ProductsByClientDTO queryProductsByClientId(Integer customerCode,
			String documentId, Integer spid);

	/**
	 * Method used to get the details of the history products associated to a
	 * specific customer.
	 * 
	 * @param customerCode
	 *            , it's a customer code for the consultation.
	 * @param spid
	 *            , it's the sequential generated by the prepareProductsData
	 *            service and used for this method.
	 * @return A ProductsByClientDTO Object with the information of the details
	 *         of the products associated to a customer.
	 */
	ProductsByClientDTO queryHistoryProductsByClientId(Integer customerCode,
			Integer spid);
}
