
/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class Balance implements Serializable {
	private double average1;
	private double average2;
	private double average3;
	private double average4;
	private double average5;
	private double average6;

	public double getAverage1() {
		return this.average1;
	}

	public void setAverage1(double average1) {
		this.average1 = average1;
	}

	public double getAverage2() {
		return this.average2;
	}

	public void setAverage2(double average2) {
		this.average2 = average2;
	}

	public double getAverage3() {
		return this.average3;
	}

	public void setAverage3(double average3) {
		this.average3 = average3;
	}

	public double getAverage4() {
		return this.average4;
	}

	public void setAverage4(double average4) {
		this.average4 = average4;
	}

	public double getAverage5() {
		return this.average5;
	}

	public void setAverage5(double average5) {
		this.average5 = average5;
	}

	public double getAverage6() {
		return this.average6;
	}

	public void setAverage6(double average6) {
		this.average6 = average6;
	}
}
