/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class Direction implements Serializable {
	private String no;
	private String directionDescription;
	private String stateCode;
	private String state;
	private String districtCode;
	private String district;
	private String typeDirectionCode;
	private String typeDirection;
	private String office;
	private String officeDesctiption;
	private String verified;
	private String principal;
	private String foreingCountry;
	private String countryName;
	private String townshipCode;
	private String neighborhood;
	private String street;
	private String apartment;
	private String townshipName;
	private String countryCode;
	private String neighborhoodCode;
	private String apartmentValue;
	private String directionCharge;
	private String mailAddress;
	private String otherAddress;

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getDirectionDescription() {
		return this.directionDescription;
	}

	public void setDirectionDescription(String directionDescription) {
		this.directionDescription = directionDescription;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getTypeDirectionCode() {
		return this.typeDirectionCode;
	}

	public void setTypeDirectionCode(String typeDirectionCode) {
		this.typeDirectionCode = typeDirectionCode;
	}

	public String getTypeDirection() {
		return this.typeDirection;
	}

	public void setTypeDirection(String typeDirection) {
		this.typeDirection = typeDirection;
	}

	public String getOffice() {
		return this.office;
	}

	public void setOffice(String office) {
		this.office = office;
	}

	public String getOfficeDesctiption() {
		return this.officeDesctiption;
	}

	public void setOfficeDesctiption(String officeDesctiption) {
		this.officeDesctiption = officeDesctiption;
	}

	public String getVerified() {
		return this.verified;
	}

	public void setVerified(String verified) {
		this.verified = verified;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getForeingCountry() {
		return this.foreingCountry;
	}

	public void setForeingCountry(String foreingCountry) {
		this.foreingCountry = foreingCountry;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getTownshipCode() {
		return this.townshipCode;
	}

	public void setTownshipCode(String townshipCode) {
		this.townshipCode = townshipCode;
	}

	public String getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getApartment() {
		return this.apartment;
	}

	public void setApartment(String apartment) {
		this.apartment = apartment;
	}

	public String getTownshipName() {
		return this.townshipName;
	}

	public void setTownshipName(String townshipName) {
		this.townshipName = townshipName;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getNeighborhoodCode() {
		return this.neighborhoodCode;
	}

	public void setNeighborhoodCode(String neighborhoodCode) {
		this.neighborhoodCode = neighborhoodCode;
	}

	public String getApartmentValue() {
		return this.apartmentValue;
	}

	public void setApartmentValue(String apartmentValue) {
		this.apartmentValue = apartmentValue;
	}

	public String getDirectionCharge() {
		return this.directionCharge;
	}

	public void setDirectionCharge(String directionCharge) {
		this.directionCharge = directionCharge;
	}

	public String getMailAddress() {
		return this.mailAddress;
	}

	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	public String getOtherAddress() {
		return this.otherAddress;
	}

	public void setOtherAddress(String otherAddress) {
		this.otherAddress = otherAddress;
	}
}
