/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class LegalClient implements Serializable {
	private int accountOfficer;
	private String accountOfficerName;
	private String activity;
	private String activityCode;
	private Character badReferences;
	private String birthDate;
	private Character blocked;
	private String branchHome;
	private int branchHomeCode;
	private String category;
	private String categoryDescripcion;
	private String centralAmericanCountryCode;
	private int childrenNumber;
	private String cityBithDate;
	private Integer cityCodeBirthDate;
	private int clientNumber;
	private String clientRatings;
	private String clientSituation;
	private String clientSituationDescription;
	private String comment;
	private String companyType;
	private String country;
	private int countryCode;
	private String coverage;
	private Integer dependents;
	private Character digit;
	private Integer documentCodePlace;
	private String documentEmisionDate;
	private String documentExpirationDate;
	private String documentNumber;
	private String documentPlace;
	private String documentType;
	private String economicGroup;
	private int economicGroupCode;
	private String economicSector;
	private int economicSectorCode;
	private String educationCode;
	private String educationLevel;
	private String employeesNumber;
	private Double expendituresLevel;
	private int externalReferredBy;
	private String externalReferredByName;
	private String firstLastName;
	private String gender;
	private Character genderCode;
	private Double grossEstate;
	private String grossEstateDate;
	private String housingType;
	private String housingTypeCode;
	private java.math.BigDecimal income;
	private Character isClient;
	private String joinDate;
	private String licenceNumber;
	private Character majorContributor;
	private String maritalStatus;
	private String maritalStatusCode;
	private String marriedName;
	private Double maxDebtQuota;
	private String mediaType;
	private String mediaTypeDescription;
	private String modificationDate;
	private String name;
	private String nationality;
	private int nationalityCode;
	private String officialAccountLogin;
	private String orderNumber;
	private String passport;
	private String personType;
	private String personTypeDescription;
	private String placeDescripcion;
	private Character por2Except;
	private Character preferredClient;
	private Integer presentedBy;
	private String profession;
	private String professionCode;
	private String promoterClient;
	private String promoterClientCode;
	private String ratingsCode;
	private String referredByName;
	private String relationship;
	private String relationshipType;
	private String relationshipTypeDescription;
	private Character retention;
	private String revenueClient;
	private String revenueCode;
	private String rucNumber;
	private String secondLastName;
	private String secondName;
	private String securityCode;
	private String segmentDescription;
	private Character siplaExcept;
	private int state;
	private String stateDescription;
	private Character superBancariaReported;
	private String supplementAccountLogin;
	private String supplementOfficer;
	private Integer supplementOfficerCode;
	private Double totalAssets;
	private String tutorName;
	private String tutorNumberId;
	private String typeIdDescription;
	private Character validatedDocument;

	public int getAccountOfficer() {
		return this.accountOfficer;
	}

	public void setAccountOfficer(int accountOfficer) {
		this.accountOfficer = accountOfficer;
	}

	public String getAccountOfficerName() {
		return this.accountOfficerName;
	}

	public void setAccountOfficerName(String accountOfficerName) {
		this.accountOfficerName = accountOfficerName;
	}

	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public Character getBadReferences() {
		return this.badReferences;
	}

	public void setBadReferences(Character badReferences) {
		this.badReferences = badReferences;
	}

	public String getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	public Character getBlocked() {
		return this.blocked;
	}

	public void setBlocked(Character blocked) {
		this.blocked = blocked;
	}

	public String getBranchHome() {
		return this.branchHome;
	}

	public void setBranchHome(String branchHome) {
		this.branchHome = branchHome;
	}

	public int getBranchHomeCode() {
		return this.branchHomeCode;
	}

	public void setBranchHomeCode(int branchHomeCode) {
		this.branchHomeCode = branchHomeCode;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCategoryDescripcion() {
		return this.categoryDescripcion;
	}

	public void setCategoryDescripcion(String categoryDescripcion) {
		this.categoryDescripcion = categoryDescripcion;
	}

	public String getCentralAmericanCountryCode() {
		return this.centralAmericanCountryCode;
	}

	public void setCentralAmericanCountryCode(String centralAmericanCountryCode) {
		this.centralAmericanCountryCode = centralAmericanCountryCode;
	}

	public int getChildrenNumber() {
		return this.childrenNumber;
	}

	public void setChildrenNumber(int childrenNumber) {
		this.childrenNumber = childrenNumber;
	}

	public String getCityBithDate() {
		return this.cityBithDate;
	}

	public void setCityBithDate(String cityBithDate) {
		this.cityBithDate = cityBithDate;
	}

	public Integer getCityCodeBirthDate() {
		return this.cityCodeBirthDate;
	}

	public void setCityCodeBirthDate(Integer cityCodeBirthDate) {
		this.cityCodeBirthDate = cityCodeBirthDate;
	}

	public int getClientNumber() {
		return this.clientNumber;
	}

	public void setClientNumber(int clientNumber) {
		this.clientNumber = clientNumber;
	}

	public String getClientRatings() {
		return this.clientRatings;
	}

	public void setClientRatings(String clientRatings) {
		this.clientRatings = clientRatings;
	}

	public String getClientSituation() {
		return this.clientSituation;
	}

	public void setClientSituation(String clientSituation) {
		this.clientSituation = clientSituation;
	}

	public String getClientSituationDescription() {
		return this.clientSituationDescription;
	}

	public void setClientSituationDescription(String clientSituationDescription) {
		this.clientSituationDescription = clientSituationDescription;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public int getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(int countryCode) {
		this.countryCode = countryCode;
	}

	public String getCoverage() {
		return this.coverage;
	}

	public void setCoverage(String coverage) {
		this.coverage = coverage;
	}

	public Integer getDependents() {
		return this.dependents;
	}

	public void setDependents(Integer dependents) {
		this.dependents = dependents;
	}

	public Character getDigit() {
		return this.digit;
	}

	public void setDigit(Character digit) {
		this.digit = digit;
	}

	public Integer getDocumentCodePlace() {
		return this.documentCodePlace;
	}

	public void setDocumentCodePlace(Integer documentCodePlace) {
		this.documentCodePlace = documentCodePlace;
	}

	public String getDocumentEmisionDate() {
		return this.documentEmisionDate;
	}

	public void setDocumentEmisionDate(String documentEmisionDate) {
		this.documentEmisionDate = documentEmisionDate;
	}

	public String getDocumentExpirationDate() {
		return this.documentExpirationDate;
	}

	public void setDocumentExpirationDate(String documentExpirationDate) {
		this.documentExpirationDate = documentExpirationDate;
	}

	public String getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	public String getDocumentPlace() {
		return this.documentPlace;
	}

	public void setDocumentPlace(String documentPlace) {
		this.documentPlace = documentPlace;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public String getEconomicGroup() {
		return this.economicGroup;
	}

	public void setEconomicGroup(String economicGroup) {
		this.economicGroup = economicGroup;
	}

	public int getEconomicGroupCode() {
		return this.economicGroupCode;
	}

	public void setEconomicGroupCode(int economicGroupCode) {
		this.economicGroupCode = economicGroupCode;
	}

	public String getEconomicSector() {
		return this.economicSector;
	}

	public void setEconomicSector(String economicSector) {
		this.economicSector = economicSector;
	}

	public int getEconomicSectorCode() {
		return this.economicSectorCode;
	}

	public void setEconomicSectorCode(int economicSectorCode) {
		this.economicSectorCode = economicSectorCode;
	}

	public String getEducationCode() {
		return this.educationCode;
	}

	public void setEducationCode(String educationCode) {
		this.educationCode = educationCode;
	}

	public String getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(String educationLevel) {
		this.educationLevel = educationLevel;
	}

	public String getEmployeesNumber() {
		return this.employeesNumber;
	}

	public void setEmployeesNumber(String employeesNumber) {
		this.employeesNumber = employeesNumber;
	}

	public Double getExpendituresLevel() {
		return this.expendituresLevel;
	}

	public void setExpendituresLevel(Double expendituresLevel) {
		this.expendituresLevel = expendituresLevel;
	}

	public int getExternalReferredBy() {
		return this.externalReferredBy;
	}

	public void setExternalReferredBy(int externalReferredBy) {
		this.externalReferredBy = externalReferredBy;
	}

	public String getExternalReferredByName() {
		return this.externalReferredByName;
	}

	public void setExternalReferredByName(String externalReferredByName) {
		this.externalReferredByName = externalReferredByName;
	}

	public String getFirstLastName() {
		return this.firstLastName;
	}

	public void setFirstLastName(String firstLastName) {
		this.firstLastName = firstLastName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Character getGenderCode() {
		return this.genderCode;
	}

	public void setGenderCode(Character genderCode) {
		this.genderCode = genderCode;
	}

	public Double getGrossEstate() {
		return this.grossEstate;
	}

	public void setGrossEstate(Double grossEstate) {
		this.grossEstate = grossEstate;
	}

	public String getGrossEstateDate() {
		return this.grossEstateDate;
	}

	public void setGrossEstateDate(String grossEstateDate) {
		this.grossEstateDate = grossEstateDate;
	}

	public String getHousingType() {
		return this.housingType;
	}

	public void setHousingType(String housingType) {
		this.housingType = housingType;
	}

	public String getHousingTypeCode() {
		return this.housingTypeCode;
	}

	public void setHousingTypeCode(String housingTypeCode) {
		this.housingTypeCode = housingTypeCode;
	}

	public java.math.BigDecimal getIncome() {
		return this.income;
	}

	public void setIncome(java.math.BigDecimal income) {
		this.income = income;
	}

	public Character getIsClient() {
		return this.isClient;
	}

	public void setIsClient(Character isClient) {
		this.isClient = isClient;
	}

	public String getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(String joinDate) {
		this.joinDate = joinDate;
	}

	public String getLicenceNumber() {
		return this.licenceNumber;
	}

	public void setLicenceNumber(String licenceNumber) {
		this.licenceNumber = licenceNumber;
	}

	public Character getMajorContributor() {
		return this.majorContributor;
	}

	public void setMajorContributor(Character majorContributor) {
		this.majorContributor = majorContributor;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getMaritalStatusCode() {
		return this.maritalStatusCode;
	}

	public void setMaritalStatusCode(String maritalStatusCode) {
		this.maritalStatusCode = maritalStatusCode;
	}

	public String getMarriedName() {
		return this.marriedName;
	}

	public void setMarriedName(String marriedName) {
		this.marriedName = marriedName;
	}

	public Double getMaxDebtQuota() {
		return this.maxDebtQuota;
	}

	public void setMaxDebtQuota(Double maxDebtQuota) {
		this.maxDebtQuota = maxDebtQuota;
	}

	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	public String getMediaTypeDescription() {
		return this.mediaTypeDescription;
	}

	public void setMediaTypeDescription(String mediaTypeDescription) {
		this.mediaTypeDescription = mediaTypeDescription;
	}

	public String getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(String modificationDate) {
		this.modificationDate = modificationDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public int getNationalityCode() {
		return this.nationalityCode;
	}

	public void setNationalityCode(int nationalityCode) {
		this.nationalityCode = nationalityCode;
	}

	public String getOfficialAccountLogin() {
		return this.officialAccountLogin;
	}

	public void setOfficialAccountLogin(String officialAccountLogin) {
		this.officialAccountLogin = officialAccountLogin;
	}

	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getPassport() {
		return this.passport;
	}

	public void setPassport(String passport) {
		this.passport = passport;
	}

	public String getPersonType() {
		return this.personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	public String getPersonTypeDescription() {
		return this.personTypeDescription;
	}

	public void setPersonTypeDescription(String personTypeDescription) {
		this.personTypeDescription = personTypeDescription;
	}

	public String getPlaceDescripcion() {
		return this.placeDescripcion;
	}

	public void setPlaceDescripcion(String placeDescripcion) {
		this.placeDescripcion = placeDescripcion;
	}

	public Character getPor2Except() {
		return this.por2Except;
	}

	public void setPor2Except(Character por2Except) {
		this.por2Except = por2Except;
	}

	public Character getPreferredClient() {
		return this.preferredClient;
	}

	public void setPreferredClient(Character preferredClient) {
		this.preferredClient = preferredClient;
	}

	public Integer getPresentedBy() {
		return this.presentedBy;
	}

	public void setPresentedBy(Integer presentedBy) {
		this.presentedBy = presentedBy;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getProfessionCode() {
		return this.professionCode;
	}

	public void setProfessionCode(String professionCode) {
		this.professionCode = professionCode;
	}

	public String getPromoterClient() {
		return this.promoterClient;
	}

	public void setPromoterClient(String promoterClient) {
		this.promoterClient = promoterClient;
	}

	public String getPromoterClientCode() {
		return this.promoterClientCode;
	}

	public void setPromoterClientCode(String promoterClientCode) {
		this.promoterClientCode = promoterClientCode;
	}

	public String getRatingsCode() {
		return this.ratingsCode;
	}

	public void setRatingsCode(String ratingsCode) {
		this.ratingsCode = ratingsCode;
	}

	public String getReferredByName() {
		return this.referredByName;
	}

	public void setReferredByName(String referredByName) {
		this.referredByName = referredByName;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getRelationshipType() {
		return this.relationshipType;
	}

	public void setRelationshipType(String relationshipType) {
		this.relationshipType = relationshipType;
	}

	public String getRelationshipTypeDescription() {
		return this.relationshipTypeDescription;
	}

	public void setRelationshipTypeDescription(
			String relationshipTypeDescription) {
		this.relationshipTypeDescription = relationshipTypeDescription;
	}

	public Character getRetention() {
		return this.retention;
	}

	public void setRetention(Character retention) {
		this.retention = retention;
	}

	public String getRevenueClient() {
		return this.revenueClient;
	}

	public void setRevenueClient(String revenueClient) {
		this.revenueClient = revenueClient;
	}

	public String getRevenueCode() {
		return this.revenueCode;
	}

	public void setRevenueCode(String revenueCode) {
		this.revenueCode = revenueCode;
	}

	public String getRucNumber() {
		return this.rucNumber;
	}

	public void setRucNumber(String rucNumber) {
		this.rucNumber = rucNumber;
	}

	public String getSecondLastName() {
		return this.secondLastName;
	}

	public void setSecondLastName(String secondLastName) {
		this.secondLastName = secondLastName;
	}

	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	public String getSegmentDescription() {
		return this.segmentDescription;
	}

	public void setSegmentDescription(String segmentDescription) {
		this.segmentDescription = segmentDescription;
	}

	public Character getSiplaExcept() {
		return this.siplaExcept;
	}

	public void setSiplaExcept(Character siplaExcept) {
		this.siplaExcept = siplaExcept;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getStateDescription() {
		return this.stateDescription;
	}

	public void setStateDescription(String stateDescription) {
		this.stateDescription = stateDescription;
	}

	public Character getSuperBancariaReported() {
		return this.superBancariaReported;
	}

	public void setSuperBancariaReported(Character superBancariaReported) {
		this.superBancariaReported = superBancariaReported;
	}

	public String getSupplementAccountLogin() {
		return this.supplementAccountLogin;
	}

	public void setSupplementAccountLogin(String supplementAccountLogin) {
		this.supplementAccountLogin = supplementAccountLogin;
	}

	public String getSupplementOfficer() {
		return this.supplementOfficer;
	}

	public void setSupplementOfficer(String supplementOfficer) {
		this.supplementOfficer = supplementOfficer;
	}

	public Integer getSupplementOfficerCode() {
		return this.supplementOfficerCode;
	}

	public void setSupplementOfficerCode(Integer supplementOfficerCode) {
		this.supplementOfficerCode = supplementOfficerCode;
	}

	public Double getTotalAssets() {
		return this.totalAssets;
	}

	public void setTotalAssets(Double totalAssets) {
		this.totalAssets = totalAssets;
	}

	public String getTutorName() {
		return this.tutorName;
	}

	public void setTutorName(String tutorName) {
		this.tutorName = tutorName;
	}

	public String getTutorNumberId() {
		return this.tutorNumberId;
	}

	public void setTutorNumberId(String tutorNumberId) {
		this.tutorNumberId = tutorNumberId;
	}

	public String getTypeIdDescription() {
		return this.typeIdDescription;
	}

	public void setTypeIdDescription(String typeIdDescription) {
		this.typeIdDescription = typeIdDescription;
	}

	public Character getValidatedDocument() {
		return this.validatedDocument;
	}

	public void setValidatedDocument(Character validatedDocument) {
		this.validatedDocument = validatedDocument;
	}
}
