/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.dto;

import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;

public class MaxDebt implements Serializable {
	private int creditCode;
	private int debtorCode;
	private Character approved;
	private Character exceedsLimit;
	private Character okProcess;
	private int errorCode;
	private String errorDescription;
	private java.math.BigDecimal debtAmount;
	private int limit;
	private java.math.BigDecimal limitDebt;
	private int groupCode;

	public int getCreditCode() {
		return this.creditCode;
	}

	public void setCreditCode(int creditCode) {
		this.creditCode = creditCode;
	}

	public int getDebtorCode() {
		return this.debtorCode;
	}

	public void setDebtorCode(int debtorCode) {
		this.debtorCode = debtorCode;
	}

	public Character getApproved() {
		return this.approved;
	}

	public void setApproved(Character approved) {
		this.approved = approved;
	}

	public Character getExceedsLimit() {
		return this.exceedsLimit;
	}

	public void setExceedsLimit(Character exceedsLimit) {
		this.exceedsLimit = exceedsLimit;
	}

	public Character getOkProcess() {
		return this.okProcess;
	}

	public void setOkProcess(Character okProcess) {
		this.okProcess = okProcess;
	}

	public int getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(int errorCode) {
		this.errorCode = errorCode;
	}

	public String getErrorDescription() {
		return this.errorDescription;
	}

	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}

	public java.math.BigDecimal getDebtAmount() {
		return this.debtAmount;
	}

	public void setDebtAmount(java.math.BigDecimal debtAmount) {
		this.debtAmount = debtAmount;
	}

	public int getLimit() {
		return this.limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public java.math.BigDecimal getLimitDebt() {
		return this.limitDebt;
	}

	public void setLimitDebt(java.math.BigDecimal limitDebt) {
		this.limitDebt = limitDebt;
	}

	public int getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(int groupCode) {
		this.groupCode = groupCode;
	}
}
