/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ProductPosition implements Serializable {
	private String account;
	private String amount_ml;
	private String amount_orig;
	private String amount_pig;
	private String amount_used;
	private String annuity;
	private String assessment;
	private String available;
	private String available_ml;
	private String balance;
	private String balance_due;
	private String beneficiary;
	private String blockades;
	private String capital_balance;
	private String client_id;
	private String clientName;
	private String comment;
	private String created_by;
	private String current_value;
	private java.util.Calendar date;
	private String date_apt;
	private String date_last_mov;
	private String date_vto;
	private String deposit_account;
	private String deposit_amount;
	private String doc_number_warranty;
	private String endorsement;
	private String endorsement_ml;
	private Integer group;
	private String guaranty_id;
	private String inicial_value;
	private String insurance_company;
	private String line;
	private String module;
	private String money;
	private String money_desc;
	private String number_guaranteed;
	private String operation;
	private String overdraft_limit;
	private String policy_number;
	private String por_mrc;
	private String product;
	private String productStatus;
	private String profile;
	private String protest;
	private String quota_online;
	private String rate;
	private String rating;
	private String retentions;
	private String rol;
	private String sec;
	private String sec_pol;
	private String secure;
	private String shipping_date;
	private String state;
	private String total_cca;
	private String total_contingent;
	private String total_risk;
	private String total_step;
	private String total_warranty;
	private String tramit;
	private String type_account;
	private String type_op_desc;
	private String type_operation;
	private String type_policy;
	private String warranty_desc;
	private String warranty_name;
	private String warranty_type;
	private String risk_ml;
	private String balance_ml;

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAmount_ml() {
		return this.amount_ml;
	}

	public void setAmount_ml(String amount_ml) {
		this.amount_ml = amount_ml;
	}

	public String getAmount_orig() {
		return this.amount_orig;
	}

	public void setAmount_orig(String amount_orig) {
		this.amount_orig = amount_orig;
	}

	public String getAmount_pig() {
		return this.amount_pig;
	}

	public void setAmount_pig(String amount_pig) {
		this.amount_pig = amount_pig;
	}

	public String getAmount_used() {
		return this.amount_used;
	}

	public void setAmount_used(String amount_used) {
		this.amount_used = amount_used;
	}

	public String getAnnuity() {
		return this.annuity;
	}

	public void setAnnuity(String annuity) {
		this.annuity = annuity;
	}

	public String getAssessment() {
		return this.assessment;
	}

	public void setAssessment(String assessment) {
		this.assessment = assessment;
	}

	public String getAvailable() {
		return this.available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

	public String getAvailable_ml() {
		return this.available_ml;
	}

	public void setAvailable_ml(String available_ml) {
		this.available_ml = available_ml;
	}

	public String getBalance() {
		return this.balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	public String getBalance_due() {
		return this.balance_due;
	}

	public void setBalance_due(String balance_due) {
		this.balance_due = balance_due;
	}

	public String getBeneficiary() {
		return this.beneficiary;
	}

	public void setBeneficiary(String beneficiary) {
		this.beneficiary = beneficiary;
	}

	public String getBlockades() {
		return this.blockades;
	}

	public void setBlockades(String blockades) {
		this.blockades = blockades;
	}

	public String getCapital_balance() {
		return this.capital_balance;
	}

	public void setCapital_balance(String capital_balance) {
		this.capital_balance = capital_balance;
	}

	public String getClient_id() {
		return this.client_id;
	}

	public void setClient_id(String client_id) {
		this.client_id = client_id;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCreated_by() {
		return this.created_by;
	}

	public void setCreated_by(String created_by) {
		this.created_by = created_by;
	}

	public String getCurrent_value() {
		return this.current_value;
	}

	public void setCurrent_value(String current_value) {
		this.current_value = current_value;
	}

	public java.util.Calendar getDate() {
		return this.date;
	}

	public void setDate(java.util.Calendar date) {
		this.date = date;
	}

	public String getDate_apt() {
		return this.date_apt;
	}

	public void setDate_apt(String date_apt) {
		this.date_apt = date_apt;
	}

	public String getDate_last_mov() {
		return this.date_last_mov;
	}

	public void setDate_last_mov(String date_last_mov) {
		this.date_last_mov = date_last_mov;
	}

	public String getDate_vto() {
		return this.date_vto;
	}

	public void setDate_vto(String date_vto) {
		this.date_vto = date_vto;
	}

	public String getDeposit_account() {
		return this.deposit_account;
	}

	public void setDeposit_account(String deposit_account) {
		this.deposit_account = deposit_account;
	}

	public String getDeposit_amount() {
		return this.deposit_amount;
	}

	public void setDeposit_amount(String deposit_amount) {
		this.deposit_amount = deposit_amount;
	}

	public String getDoc_number_warranty() {
		return this.doc_number_warranty;
	}

	public void setDoc_number_warranty(String doc_number_warranty) {
		this.doc_number_warranty = doc_number_warranty;
	}

	public String getEndorsement() {
		return this.endorsement;
	}

	public void setEndorsement(String endorsement) {
		this.endorsement = endorsement;
	}

	public String getEndorsement_ml() {
		return this.endorsement_ml;
	}

	public void setEndorsement_ml(String endorsement_ml) {
		this.endorsement_ml = endorsement_ml;
	}

	public Integer getGroup() {
		return this.group;
	}

	public void setGroup(Integer group) {
		this.group = group;
	}

	public String getGuaranty_id() {
		return this.guaranty_id;
	}

	public void setGuaranty_id(String guaranty_id) {
		this.guaranty_id = guaranty_id;
	}

	public String getInicial_value() {
		return this.inicial_value;
	}

	public void setInicial_value(String inicial_value) {
		this.inicial_value = inicial_value;
	}

	public String getInsurance_company() {
		return this.insurance_company;
	}

	public void setInsurance_company(String insurance_company) {
		this.insurance_company = insurance_company;
	}

	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getMoney() {
		return this.money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	public String getMoney_desc() {
		return this.money_desc;
	}

	public void setMoney_desc(String money_desc) {
		this.money_desc = money_desc;
	}

	public String getNumber_guaranteed() {
		return this.number_guaranteed;
	}

	public void setNumber_guaranteed(String number_guaranteed) {
		this.number_guaranteed = number_guaranteed;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public String getOverdraft_limit() {
		return this.overdraft_limit;
	}

	public void setOverdraft_limit(String overdraft_limit) {
		this.overdraft_limit = overdraft_limit;
	}

	public String getPolicy_number() {
		return this.policy_number;
	}

	public void setPolicy_number(String policy_number) {
		this.policy_number = policy_number;
	}

	public String getPor_mrc() {
		return this.por_mrc;
	}

	public void setPor_mrc(String por_mrc) {
		this.por_mrc = por_mrc;
	}

	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	public String getProductStatus() {
		return this.productStatus;
	}

	public void setProductStatus(String productStatus) {
		this.productStatus = productStatus;
	}

	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	public String getProtest() {
		return this.protest;
	}

	public void setProtest(String protest) {
		this.protest = protest;
	}

	public String getQuota_online() {
		return this.quota_online;
	}

	public void setQuota_online(String quota_online) {
		this.quota_online = quota_online;
	}

	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public String getRetentions() {
		return this.retentions;
	}

	public void setRetentions(String retentions) {
		this.retentions = retentions;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getSec() {
		return this.sec;
	}

	public void setSec(String sec) {
		this.sec = sec;
	}

	public String getSec_pol() {
		return this.sec_pol;
	}

	public void setSec_pol(String sec_pol) {
		this.sec_pol = sec_pol;
	}

	public String getSecure() {
		return this.secure;
	}

	public void setSecure(String secure) {
		this.secure = secure;
	}

	public String getShipping_date() {
		return this.shipping_date;
	}

	public void setShipping_date(String shipping_date) {
		this.shipping_date = shipping_date;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getTotal_cca() {
		return this.total_cca;
	}

	public void setTotal_cca(String total_cca) {
		this.total_cca = total_cca;
	}

	public String getTotal_contingent() {
		return this.total_contingent;
	}

	public void setTotal_contingent(String total_contingent) {
		this.total_contingent = total_contingent;
	}

	public String getTotal_risk() {
		return this.total_risk;
	}

	public void setTotal_risk(String total_risk) {
		this.total_risk = total_risk;
	}

	public String getTotal_step() {
		return this.total_step;
	}

	public void setTotal_step(String total_step) {
		this.total_step = total_step;
	}

	public String getTotal_warranty() {
		return this.total_warranty;
	}

	public void setTotal_warranty(String total_warranty) {
		this.total_warranty = total_warranty;
	}

	public String getTramit() {
		return this.tramit;
	}

	public void setTramit(String tramit) {
		this.tramit = tramit;
	}

	public String getType_account() {
		return this.type_account;
	}

	public void setType_account(String type_account) {
		this.type_account = type_account;
	}

	public String getType_op_desc() {
		return this.type_op_desc;
	}

	public void setType_op_desc(String type_op_desc) {
		this.type_op_desc = type_op_desc;
	}

	public String getType_operation() {
		return this.type_operation;
	}

	public void setType_operation(String type_operation) {
		this.type_operation = type_operation;
	}

	public String getType_policy() {
		return this.type_policy;
	}

	public void setType_policy(String type_policy) {
		this.type_policy = type_policy;
	}

	public String getWarranty_desc() {
		return this.warranty_desc;
	}

	public void setWarranty_desc(String warranty_desc) {
		this.warranty_desc = warranty_desc;
	}

	public String getWarranty_name() {
		return this.warranty_name;
	}

	public void setWarranty_name(String warranty_name) {
		this.warranty_name = warranty_name;
	}

	public String getWarranty_type() {
		return this.warranty_type;
	}

	public void setWarranty_type(String warranty_type) {
		this.warranty_type = warranty_type;
	}

	public String getRisk_ml() {
		return this.risk_ml;
	}

	public void setRisk_ml(String risk_ml) {
		this.risk_ml = risk_ml;
	}

	public String getBalance_ml() {
		return this.balance_ml;
	}

	public void setBalance_ml(String balance_ml) {
		this.balance_ml = balance_ml;
	}
}
