/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.ucsp.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ProductPositionCollection implements Serializable {
	private ProductPosition[] currentAccount;
	private ProductPosition[] savingAccount;
	private ProductPosition[] fixedTerm;
	private ProductPosition[] overdraft;
	private ProductPosition[] guarantees;
	private ProductPosition[] credits;
	private ProductPosition[] contingencies;
	private ProductPosition[] insurancePolicy;
	private ProductPosition[] debitCard;
	private ProductPosition[] contingencies2;
	private ProductPosition[] promissoryNote;
	private ProductPosition[] globalNet;
	private ProductPosition[] loanPortfolio;
	private ProductPosition[] indirectPortfolio;
	private ProductPosition[] totalRisk;

	public ProductPosition[] getCurrentAccount() {
		return this.currentAccount;
	}

	public void setCurrentAccount(ProductPosition[] currentAccount) {
		this.currentAccount = currentAccount;
	}

	public ProductPosition[] getSavingAccount() {
		return this.savingAccount;
	}

	public void setSavingAccount(ProductPosition[] savingAccount) {
		this.savingAccount = savingAccount;
	}

	public ProductPosition[] getFixedTerm() {
		return this.fixedTerm;
	}

	public void setFixedTerm(ProductPosition[] fixedTerm) {
		this.fixedTerm = fixedTerm;
	}

	public ProductPosition[] getOverdraft() {
		return this.overdraft;
	}

	public void setOverdraft(ProductPosition[] overdraft) {
		this.overdraft = overdraft;
	}

	public ProductPosition[] getGuarantees() {
		return this.guarantees;
	}

	public void setGuarantees(ProductPosition[] guarantees) {
		this.guarantees = guarantees;
	}

	public ProductPosition[] getCredits() {
		return this.credits;
	}

	public void setCredits(ProductPosition[] credits) {
		this.credits = credits;
	}

	public ProductPosition[] getContingencies() {
		return this.contingencies;
	}

	public void setContingencies(ProductPosition[] contingencies) {
		this.contingencies = contingencies;
	}

	public ProductPosition[] getInsurancePolicy() {
		return this.insurancePolicy;
	}

	public void setInsurancePolicy(ProductPosition[] insurancePolicy) {
		this.insurancePolicy = insurancePolicy;
	}

	public ProductPosition[] getDebitCard() {
		return this.debitCard;
	}

	public void setDebitCard(ProductPosition[] debitCard) {
		this.debitCard = debitCard;
	}

	public ProductPosition[] getContingencies2() {
		return this.contingencies2;
	}

	public void setContingencies2(ProductPosition[] contingencies2) {
		this.contingencies2 = contingencies2;
	}

	public ProductPosition[] getPromissoryNote() {
		return this.promissoryNote;
	}

	public void setPromissoryNote(ProductPosition[] promissoryNote) {
		this.promissoryNote = promissoryNote;
	}

	public ProductPosition[] getGlobalNet() {
		return this.globalNet;
	}

	public void setGlobalNet(ProductPosition[] globalNet) {
		this.globalNet = globalNet;
	}

	public ProductPosition[] getLoanPortfolio() {
		return this.loanPortfolio;
	}

	public void setLoanPortfolio(ProductPosition[] loanPortfolio) {
		this.loanPortfolio = loanPortfolio;
	}

	public ProductPosition[] getIndirectPortfolio() {
		return this.indirectPortfolio;
	}

	public void setIndirectPortfolio(ProductPosition[] indirectPortfolio) {
		this.indirectPortfolio = indirectPortfolio;
	}

	public ProductPosition[] getTotalRisk() {
		return this.totalRisk;
	}

	public void setTotalRisk(ProductPosition[] totalRisk) {
		this.totalRisk = totalRisk;
	}
}
