/************************************************************/
/*******************Service Operations Script****************/
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

use cobis
GO

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Channels.Token.Services.GenerateTokenUser')
UPDATE cts_serv_catalog SET csc_procedure_validation='Y', csc_class_name = 'com.cobiscorp.ecobis.admintoken.interfaces.IAdminTokenUser', csc_method_name = 'generateTokenUser', csc_description = '', csc_trn = 1875900 WHERE csc_service_id = 'Channels.Token.Services.GenerateTokenUser'
ELSE
INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn, csc_procedure_validation) VALUES ('Channels.Token.Services.GenerateTokenUser', 'com.cobiscorp.ecobis.admintoken.interfaces.IAdminTokenUser', 'generateTokenUser', '', 1875900, 'Y')
GO

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Channels.Token.Services.ValidateTokenUser')
UPDATE cts_serv_catalog SET csc_procedure_validation='Y', csc_class_name = 'com.cobiscorp.ecobis.admintoken.interfaces.IAdminTokenUser', csc_method_name = 'validateTokenUser', csc_description = '', csc_trn = 1875901 WHERE csc_service_id = 'Channels.Token.Services.ValidateTokenUser'
ELSE
INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn, csc_procedure_validation) VALUES ('Channels.Token.Services.ValidateTokenUser', 'com.cobiscorp.ecobis.admintoken.interfaces.IAdminTokenUser', 'validateTokenUser', '', 1875901, 'Y')
GO