IF %PROCESSOR_ARCHITECTURE%==X86 GOTO SET_PATHS_X86
IF %PROCESSOR_ARCHITECTURE%==AMD64 GOTO SET_PATHS_X64

:SET_PATHS_X86
SET PATH_ASM=%ProgramFiles%\COBIS\COBIS Services Generator
GOTO GENERATE_INSTALL

:SET_PATHS_X64
SET PATH_ASM=%ProgramFiles% (x86)\COBIS\COBIS Services Generator

:GENERATE_INSTALL

mvn clean install

pause
