bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Enero_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Febrero_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Marzo_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Abril_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Mayo_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Junio_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Julio_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Agosto_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Septiembre_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Octubre_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Noviembre_2020.dat -n -r \n -T -S
bcp cob_conta_tercero.dbo.ct_scomprobante in D:\Temp\Pruebas\cob_conta_tercero_ct_scomprobante_Diciembre_2020.dat -n -r \n -T -S
