/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.card.dto;

import java.io.Serializable;

public class CardData implements Serializable {
	private String codigoTarjeta;
	private String numeroTarjeta;
	private String marca;
	private String tipoTarjeta;
	private String moneda;
	private String monedaDesc;
	private double limiteAprobado;
	private double saldoDisponible;
	private double montoUtilizado;
	private String estado;
	private String descripcion;
	private java.util.Calendar fechaExpira;
	private String seguro;
	private String oficina;
	private java.util.Calendar fechaCancela;
	private String codigoLinea;
	private String cuentaAsociada;

	public String getCuentaAsociada() {
		return cuentaAsociada;
	}

	public void setCuentaAsociada(String cuentaAsociada) {
		this.cuentaAsociada = cuentaAsociada;
	}

	public String getCodigoTarjeta() {
		return this.codigoTarjeta;
	}

	public void setCodigoTarjeta(String codigoTarjeta) {
		this.codigoTarjeta = codigoTarjeta;
	}

	public String getNumeroTarjeta() {
		return this.numeroTarjeta;
	}

	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getTipoTarjeta() {
		return this.tipoTarjeta;
	}

	public void setTipoTarjeta(String tipoTarjeta) {
		this.tipoTarjeta = tipoTarjeta;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public double getLimiteAprobado() {
		return this.limiteAprobado;
	}

	public void setLimiteAprobado(double limiteAprobado) {
		this.limiteAprobado = limiteAprobado;
	}

	public double getSaldoDisponible() {
		return this.saldoDisponible;
	}

	public void setSaldoDisponible(double saldoDisponible) {
		this.saldoDisponible = saldoDisponible;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public java.util.Calendar getFechaExpira() {
		return this.fechaExpira;
	}

	public void setFechaExpira(java.util.Calendar fechaExpira) {
		this.fechaExpira = fechaExpira;
	}

	public String getSeguro() {
		return this.seguro;
	}

	public void setSeguro(String seguro) {
		this.seguro = seguro;
	}

	public String getOficina() {
		return this.oficina;
	}

	public void setOficina(String oficina) {
		this.oficina = oficina;
	}

	public java.util.Calendar getFechaCancela() {
		return this.fechaCancela;
	}

	public void setFechaCancela(java.util.Calendar fechaCancela) {
		this.fechaCancela = fechaCancela;
	}

	public double getMontoUtilizado() {
		return montoUtilizado;
	}

	public void setMontoUtilizado(double montoUtilizado) {
		this.montoUtilizado = montoUtilizado;
	}

	public String getCodigoLinea() {
		return codigoLinea;
	}

	public void setCodigoLinea(String codigoLinea) {
		this.codigoLinea = codigoLinea;
	}

	public String getMonedaDesc() {
		return monedaDesc;
	}

	public void setMonedaDesc(String monedaDesc) {
		this.monedaDesc = monedaDesc;
	}

}
