
/************************************************************/
/*                     IMPORTANTE                           */
/*   Esta aplicacion es parte de los  paquetes bancarios    */
/*   propiedad de COBISCORP.                                */
/*   Su uso no autorizado queda  expresamente  prohibido    */
/*   asi como cualquier alteracion o agregado hecho  por    */
/*   alguno de sus usuarios sin el debido consentimiento    */
/*   por escrito de COBISCORP.                              */
/*   Este programa esta protegido por la ley de derechos    */
/*   de autor  y por las convenciones internacionales de    */
/*   propiedad intelectual.   Su  uso no autorizado dara    */
/*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
/*   secuestro o retencion  y  para perseguir penalmente    */
/*   a los autores de cualquier infraccion.                 */
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

package cobiscorp.ecobis.card.dto;

import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class CardInformation implements Serializable {
  private int customer;
  private String categoria;
  private String operacion;
  public int getCustomer(){
    return this.customer;
  }
  public void setCustomer(int customer ){
    this.customer=customer;
  }
  public String getCategoria(){
    return this.categoria;
  }
  public void setCategoria(String categoria ){
    this.categoria=categoria;
  }
  public String getOperacion(){
    return this.operacion;
  }
  public void setOperacion(String operacion ){
		this.operacion = operacion;
	}
}
