use cobis
go


update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1444' where di_ente = 14 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 1 MZ 1464' where di_ente = 15 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2 A MZ 628 LT 14 15' where di_ente = 29 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21' where di_ente = 32 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21' where di_ente = 32 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 47 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 47 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21' where di_ente = 48 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21' where di_ente = 48 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443' where di_ente = 50 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 51 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 51 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21 ' where di_ente = 65 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21' where di_ente = 68 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 69 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 70 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 27 OTE 2 A' where di_ente = 73 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 27 MZ 628 LT 13' where di_ente = 74 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 4 MZ54 LT8' where di_ente = 75 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT1' where di_ente = 81 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ1553 LT2' where di_ente = 85 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 513' where di_ente = 89 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 56 LT 3' where di_ente = 94 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 220 LT 20' where di_ente = 97 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 A MZ 147 LT 3' where di_ente = 105 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 A MZ 147 LT 3' where di_ente = 175 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 A MZ 147 LT 3' where di_ente = 175 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ1119 LT26' where di_ente = 227 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ1120 LT7' where di_ente = 229 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44C MZ 132 LT5' where di_ente = 261 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ73 LT25' where di_ente = 264 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ72 LT2' where di_ente = 270 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 146 LT19' where di_ente = 275 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 36 A MZ 63 LT 24' where di_ente = 276 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 72 LT4' where di_ente = 284 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 58 MZ 173 LT 5' where di_ente = 295 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 73 LT25' where di_ente = 297 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 8 MZ 145 LT 15' where di_ente = 300 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 8 MZ125 LT 5' where di_ente = 302 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 58 MZ 173 LT6 INT 1' where di_ente = 303 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 146 LT 2' where di_ente = 308 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 8 MZ 145 LT 15' where di_ente = 309 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 144 LT 15' where di_ente = 313 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 57 MZ 15 LT7' where di_ente = 314 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ 145 LT 22' where di_ente = 317 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37 MZ 74 LT 7' where di_ente = 319 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 57 MZ 15 LT 7' where di_ente = 325 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 57 MZ 15 LT 7' where di_ente = 325 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32A MZ 24 LT 10' where di_ente = 331 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 60 MZ 175 LT 7' where di_ente = 334 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 58 MZ 174 LT 14' where di_ente = 335 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ73 LT 25' where di_ente = 336 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 58 MZ 174 ' where di_ente = 338 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22MZ71 LT4' where di_ente = 340 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 60 MZ 175 LT 7' where di_ente = 358 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 58 MZ 3 LT 12' where di_ente = 359 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37 C MZ 185 LT ' where di_ente = 362 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 38' where di_ente = 363 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 245 LT 12' where di_ente = 367 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 245 LT 12' where di_ente = 368 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 31 MZ 230 LT 12' where di_ente = 369 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 31 MZ 230 LT 12' where di_ente = 372 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 16B MZ 227 LT 19' where di_ente = 377 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 16B MZ 227 LT 19' where di_ente = 383 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ20 LT24' where di_ente = 426 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT 1' where di_ente = 466 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ856 LT 1' where di_ente = 466 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 856 LT1' where di_ente = 482 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A LT 6 MZ 93' where di_ente = 506 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 22' where di_ente = 507 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 ' where di_ente = 515 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 70' where di_ente = 572 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 365' where di_ente = 574 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 6 MZ 277 L 2' where di_ente = 587 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 26 LT 13' where di_ente = 589 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 26 LT 13' where di_ente = 590 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4' where di_ente = 591 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 40 LT 1006' where di_ente = 595 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 6 MZ 277 L2' where di_ente = 602 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 132' where di_ente = 630 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 132' where di_ente = 686 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ 119 LT10' where di_ente = 689 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4A MZ 12 LT27A' where di_ente = 691 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 132 LT' where di_ente = 692 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4A MZ 12 LT 27A' where di_ente = 693 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4A MZ 12 LT 27A' where di_ente = 695 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 480 LT 7' where di_ente = 703 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 182 LT 18 ' where di_ente = 705 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 182 LT 18 ' where di_ente = 705 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 27 LT 15' where di_ente = 732 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 27 LT 15' where di_ente = 732 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 27 LT 13 ' where di_ente = 734 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 ' where di_ente = 737 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 ' where di_ente = 737 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11' where di_ente = 740 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 53' where di_ente = 791 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 67' where di_ente = 794 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 68' where di_ente = 796 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 67' where di_ente = 799 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 67' where di_ente = 802 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2 MZ 41 LT 12 ' where di_ente = 804 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2 MZ 41 LT 12' where di_ente = 811 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 64 LT 3' where di_ente = 830 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 15 MZ 73 LT 11' where di_ente = 890 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ1418 LT5' where di_ente = 916 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12 MZ1416 LT0' where di_ente = 921 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12 MZ 1416 LT10' where di_ente = 928 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE MZ93 LT18' where di_ente = 936 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 ' where di_ente = 941 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR ONCE ' where di_ente = 941 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6' where di_ente = 943 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6' where di_ente = 943 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 15 LT 30 5' where di_ente = 963 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 15 LT 30 5' where di_ente = 965 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 4 LT 52' where di_ente = 967 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 4 LT 61' where di_ente = 970 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 9 MZ 105 LT 10' where di_ente = 972 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1553 LT 2' where di_ente = 980 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1095 LT 25' where di_ente = 1003 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1095 LT 25' where di_ente = 1005 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 856 LT 1 ' where di_ente = 1017 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 55 LT20' where di_ente = 1018 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 62 LT3' where di_ente = 1025 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 74 LT ' where di_ente = 1045 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 8 LT 3' where di_ente = 1059 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 29 MZ251 LT15' where di_ente = 1083 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 29 MZ 251 LT15' where di_ente = 1090 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR ONCE MZ 35 LT 1' where di_ente = 1105 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ 60 ' where di_ente = 1106 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 1 MZ 32 LT9' where di_ente = 1111 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 1072 LT 1' where di_ente = 1149 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 32 LT 7 ' where di_ente = 1180 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24' where di_ente = 1182 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NTE 17 MZ 181 LT 58' where di_ente = 1185 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NTE 17 MZ 181 LT 58' where di_ente = 1193 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 25 MZ 639 LT 4' where di_ente = 1195 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 46 LT 17' where di_ente = 1221 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 46 LT 17' where di_ente = 1224 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 44 MZ149 ' where di_ente = 1246 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1082 LT 8' where di_ente = 1287 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1132 LT 5' where di_ente = 1301 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1593 LT 14' where di_ente = 1309 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1593 LT 14' where di_ente = 1309 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 1072 LT 1' where di_ente = 1318 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 1189' where di_ente = 1331 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1097 LT 5' where di_ente = 1339 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 1176 LT 7' where di_ente = 1345 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 35MZ36 LT5' where di_ente = 1352 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ1442 LT2' where di_ente = 1354 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ1442 LT2' where di_ente = 1356 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ1442 LT2' where di_ente = 1359 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18MZ1442 LT 2' where di_ente = 1364 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT 2' where di_ente = 1374 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT2' where di_ente = 1379 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 35 MZ62 LT10 ' where di_ente = 1380 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443 LT 13' where di_ente = 1381 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443 LT 13' where di_ente = 1381 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 9 MZ 1' where di_ente = 1382 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 7 MZ 35' where di_ente = 1386 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 7 MZ 35' where di_ente = 1390 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 25 MZ167 LT 14' where di_ente = 1392 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 7 MZ 35' where di_ente = 1394 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18' where di_ente = 1412 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 225' where di_ente = 1419 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 224' where di_ente = 1428 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT 2' where di_ente = 1440 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT2 ' where di_ente = 1441 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT2 ' where di_ente = 1441 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 22 MZ 1194 LT3' where di_ente = 1456 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MANZANA 616 LOTE 14' where di_ente = 1457 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MANZANA 616 LOTE 14 ' where di_ente = 1458 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MANZANA 616 LOTE 14 ' where di_ente = 1490 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 36 MZ1384 LT 13' where di_ente = 1494 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 5 MZ 646 LT 13 ' where di_ente = 1518 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1097 LT 5' where di_ente = 1532 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 ' where di_ente = 1534 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 104 LT 2' where di_ente = 1539 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ53' where di_ente = 1542 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 M192' where di_ente = 1550 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 13 M192' where di_ente = 1550 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 929 LT 16' where di_ente = 1555 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 929 LT 16' where di_ente = 1560 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 1 NTE 27' where di_ente = 1560 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 105 LT 17' where di_ente = 1581 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ82 LT 12' where di_ente = 1584 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ82 LT 12' where di_ente = 1584 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 12 Y NORTE 35' where di_ente = 1585 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 24 SN MZ 498 LT 25' where di_ente = 1602 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 35 MZ1388 LT7' where di_ente = 1620 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 35 MZ 1388 LT 7' where di_ente = 1620 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 1422 LT 2' where di_ente = 1625 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 1422 LT 2' where di_ente = 1625 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ1422 LT2' where di_ente = 1631 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 1323 LT 23' where di_ente = 1636 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ82 LT 12' where di_ente = 1637 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ1401 LT6' where di_ente = 1650 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ1401 LT6' where di_ente = 1650 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ1401 LT 6' where di_ente = 1654 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 12 MZ 194 LT 2' where di_ente = 1671 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 37 MANZANA1363 LOTE 3' where di_ente = 1679 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33' where di_ente = 1698 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1422 LT 15' where di_ente = 1702 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1422 LT 15' where di_ente = 1702 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ1428 LT 2' where di_ente = 1709 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 10 MZ148' where di_ente = 1722 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 1839' where di_ente = 1764 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 37 MANZANA1363 LOTE3' where di_ente = 1773 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19A MZ1428 LT 2' where di_ente = 1787 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 16 MZ1422 LT2 DEL CARMEN' where di_ente = 1790 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ104 LT2' where di_ente = 1797 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ140 LT 6' where di_ente = 1802 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 LT 12' where di_ente = 1812 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 233' where di_ente = 1828 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1550 LT 5 E' where di_ente = 1828 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 533 LT4' where di_ente = 1834 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 533 LT 4' where di_ente = 1834 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1855 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 20' where di_ente = 1855 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1858 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210 ' where di_ente = 1858 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 MZ 210' where di_ente = 1858 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1129' where di_ente = 1864 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 LT 12' where di_ente = 1868 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1410' where di_ente = 1902 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6MZ 1410' where di_ente = 1910 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6MZ 1410' where di_ente = 1910 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 5' where di_ente = 1924 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ 35 LT' where di_ente = 1927 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 79 LT' where di_ente = 1928 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 49 MZ 49 LT ' where di_ente = 1929 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 79 LT ' where di_ente = 1931 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 47 MZ 98 LT ' where di_ente = 1940 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 36 MZ1384 LT13' where di_ente = 1999 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 26 MZ 896 LT 8A' where di_ente = 2022 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 17 PTE 7A' where di_ente = 2043 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 37 1363 LT 3' where di_ente = 2044 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1298' where di_ente = 2063 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 31 LT 47' where di_ente = 2064 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1363 LT' where di_ente = 2068 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 1P MZ 1367 LT ' where di_ente = 2070 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32 A MZ 245 LT' where di_ente = 2073 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 A  MZ 39B LT 27' where di_ente = 2074 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32 A MZ 245 LT' where di_ente = 2075 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 12 LT 11' where di_ente = 2076 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32A MZ 33' where di_ente = 2078 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 1E MZ 1326 LT ' where di_ente = 2080 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 31 LT 47' where di_ente = 2081 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1363 LT ' where di_ente = 2082 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 480 LT 7 ' where di_ente = 2135 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 A MZ39B LT27' where di_ente = 2143 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 28 MZ460 LT3 ' where di_ente = 2144 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 28 MZ 460 LT 3' where di_ente = 2144 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 LT 10 MZ 62' where di_ente = 2147 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 62 LT 10' where di_ente = 2147 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 13 LT 27' where di_ente = 2152 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 D MZ 127 LT 32' where di_ente = 2160 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 13 LT 27' where di_ente = 2164 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 19 A MZ 156 LT 22' where di_ente = 2185 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37' where di_ente = 2243 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 31 LT 52' where di_ente = 2246 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 31 LT 52' where di_ente = 2251 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 A LA 39 B LT27' where di_ente = 2253 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37' where di_ente = 2255 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 7 MZ 67 LT 8' where di_ente = 2256 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MANZANA 664 LOTE 9' where di_ente = 2270 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 665 LT12 ' where di_ente = 2271 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 665 LT12 ' where di_ente = 2272 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 665 LT12 ' where di_ente = 2273 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE6TA MZ43 LT 23' where di_ente = 2311 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6TA MZ43LT23' where di_ente = 2312 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 1175' where di_ente = 2322 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 ' where di_ente = 2369 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 21 MZ 1401 LT 6' where di_ente = 2381 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 22 ' where di_ente = 2383 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 21 MZ1401 LT 6' where di_ente = 2384 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 2 LT 31' where di_ente = 2386 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ737 LT3' where di_ente = 2401 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 93 LT ' where di_ente = 2413 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR TRECE MZ 61 LT ' where di_ente = 2423 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12B MZ1452 LT18' where di_ente = 2426 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 1189 LT 2' where di_ente = 2438 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1454 LT 30' where di_ente = 2450 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE MZ 41 LT 28 ' where di_ente = 2451 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 4 LT 5' where di_ente = 2460 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 13 LT 27' where di_ente = 2468 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P 1 LT' where di_ente = 2470 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 2A MZ 61 LT 7' where di_ente = 2494 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 21 MZ1401 LT 6' where di_ente = 2508 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 699 LT 4' where di_ente = 2520 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 12 MZ 555 LT 2' where di_ente = 2523 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 D MZ 127 LT 32' where di_ente = 2529 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT12' where di_ente = 2532 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 8 MZ1009 LT22' where di_ente = 2536 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT 153' where di_ente = 2539 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 3' where di_ente = 2544 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 5' where di_ente = 2546 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 89 LT ' where di_ente = 2551 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 8 MZ1009 LT 22' where di_ente = 2552 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 LT ' where di_ente = 2553 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT12' where di_ente = 2555 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 89 LT ' where di_ente = 2556 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 P1 LT ' where di_ente = 2557 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 35 LT ' where di_ente = 2558 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 32 MZ 32 LT ' where di_ente = 2560 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 3 MZ 46 LT 20' where di_ente = 2562 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 42 MZ 102 LT 7' where di_ente = 2563 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MZ 854 LT 11' where di_ente = 2597 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 29 MZ 854 LT 11' where di_ente = 2600 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 984 LT 15' where di_ente = 2613 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 34 MZ1386 ' where di_ente = 2640 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 36 MZ 1373 LT 4' where di_ente = 2645 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12B MZA1452 LT 18' where di_ente = 2649 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 12 MZ1451 LT4' where di_ente = 2656 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 LT 18 MZ1451' where di_ente = 2673 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 LT18 MZ1451' where di_ente = 2674 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 A MZ1443 LT 3' where di_ente = 2675 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 7A MZ988 LT 11' where di_ente = 2685 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 7A MZ988 LT 10' where di_ente = 2688 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 07A MANZANA 1008 LOTE 2' where di_ente = 2689 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 1411 MZ 1290 LT 10' where di_ente = 2696 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 5 MZ 271 LT 11' where di_ente = 2711 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 6A MZ 21 LT 2 ' where di_ente = 2714 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 3 MZ 6 LT 23' where di_ente = 2746 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 5 MZ 14 LT 4' where di_ente = 2748 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 984 LT14' where di_ente = 2783 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZA984 LT15' where di_ente = 2786 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 11 LT 6 D9' where di_ente = 2804 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 17 M 69 LT 9' where di_ente = 2806 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 65 LT9' where di_ente = 2810 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 62 LT 10' where di_ente = 2865 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ 823 LT 30' where di_ente = 2869 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 5 MZ 5 LT 13 ' where di_ente = 2871 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1550LT 5 E' where di_ente = 2877 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 69 LT 9' where di_ente = 2886 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 8 MZ 125' where di_ente = 2901 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 33 MZ1425 LT13' where di_ente = 2908 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21' where di_ente = 2909 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 356' where di_ente = 2915 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 2956 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 2966 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1410 LT 31' where di_ente = 2975 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1410 LT 31' where di_ente = 2975 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 272  LT' where di_ente = 2994 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 15 MZ 279 LT' where di_ente = 3011 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 M1426 L13 3' where di_ente = 3029 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 8 MZ 22 LT' where di_ente = 3033 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 8 MZ 22 LT' where di_ente = 3038 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 40 LT' where di_ente = 3042 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 217 LT 8' where di_ente = 3060 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6' where di_ente = 3083 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6' where di_ente = 3085 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10' where di_ente = 3096 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5' where di_ente = 3097 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5' where di_ente = 3097 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1426 LT 13 3' where di_ente = 3099 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1405 LT 12' where di_ente = 3113 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 8A MZ 1009' where di_ente = 3114 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1422 LT 15' where di_ente = 3120 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 7 ESQ NORTE 36' where di_ente = 3165 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 29 MZ 251' where di_ente = 3212 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 10 ESQ OTE 30' where di_ente = 3224 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 7A ESQ NTE 36' where di_ente = 3230 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 11 ' where di_ente = 3245 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 36 MZ 1373 LT 4' where di_ente = 3269 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 1324 LT 20 7' where di_ente = 3275 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 MZ 168' where di_ente = 3277 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1383 LT' where di_ente = 3284 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 22 MZ 456' where di_ente = 3298 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 7A ' where di_ente = 3309 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 1324 LT 20 7' where di_ente = 3352 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 132 LT 1' where di_ente = 3367 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20' where di_ente = 3417 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT 09' where di_ente = 3420 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 1222 LT 20' where di_ente = 3423 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 1222 LT 20' where di_ente = 3427 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1377 LT 10' where di_ente = 3428 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9' where di_ente = 3428 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 132 LT 1' where di_ente = 3429 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 B MZ 117 LT 13' where di_ente = 3440 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7 MZ 39 LT 21' where di_ente = 3444 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 A MZ 57 LT ' where di_ente = 3447 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7 MZ 39 LT 21' where di_ente = 3452 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7 MZ 39 LT 21' where di_ente = 3455 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT 09' where di_ente = 3467 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 33 MZ 1048 LT15' where di_ente = 3470 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NTE 16 MZ 1472 LT 4' where di_ente = 3471 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 33 MZ1048 LT 15' where di_ente = 3473 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 1222 LT 20' where di_ente = 3478 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ1002 LT4' where di_ente = 3480 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ LT' where di_ente = 3486 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 79 LT ' where di_ente = 3503 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 1345 LT 5' where di_ente = 3519 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 1336 LT 2' where di_ente = 3532 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 1336 LT 2' where di_ente = 3534 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ LT' where di_ente = 3568 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 1 MZ 1466 LT11 ' where di_ente = 3579 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1413 LT 5' where di_ente = 3586 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1280 LT 3' where di_ente = 3587 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 8A MZ986 LT 11' where di_ente = 3615 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1458 LT 29' where di_ente = 3633 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 30' where di_ente = 3687 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13' where di_ente = 3695 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13 ' where di_ente = 3700 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 147 LT 13 ' where di_ente = 3706 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 22 MZ 1196 LT 2' where di_ente = 3713 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 93 LT 1' where di_ente = 3721 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 93 LT 1' where di_ente = 3723 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10 LT 6 MZ 1069' where di_ente = 3750 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10 LT 6 MZ 1069' where di_ente = 3754 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 12 MZ 1094 LT 1' where di_ente = 3759 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 79 LT ' where di_ente = 3760 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10 LT 6 MZ 1069' where di_ente = 3768 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ LT' where di_ente = 3782 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ37 LT 15' where di_ente = 3827 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ37 LT 15' where di_ente = 3827 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21' where di_ente = 3836 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 1215 LT 26' where di_ente = 3843 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR7 MZ 320 LT17' where di_ente = 3846 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 984 LT 12' where di_ente = 3848 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 512 LT 13' where di_ente = 3850 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 7 MZ 320 LT17' where di_ente = 3851 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ984 LT 12' where di_ente = 3852 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1413 LT 5' where di_ente = 3853 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 512 LT 13' where di_ente = 3858 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 512 LT 13' where di_ente = 3858 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT 09' where di_ente = 3860 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 23 MZ 141 LT 1' where di_ente = 3919 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 273 LT ' where di_ente = 3924 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ 32 LT ' where di_ente = 3925 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 95 LT' where di_ente = 3927 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6 MZ 95 LT' where di_ente = 3927 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 93  LT ' where di_ente = 3931 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ 32 LT ' where di_ente = 3935 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ 32 LT ' where di_ente = 3940 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ37 LT15' where di_ente = 3945 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ37 LT15' where di_ente = 3945 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 38 MZ LT' where di_ente = 3957 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 M1275 LT 8' where di_ente = 4002 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1279 LT 8' where di_ente = 4009 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 5 A MZ 96 LT 8' where di_ente = 4017 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT 09' where di_ente = 4029 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 93 LT' where di_ente = 4062 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 17 MZ 32 LT ' where di_ente = 4069 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1279 LT 8' where di_ente = 4071 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1380 L3' where di_ente = 4073 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE8' where di_ente = 4075 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1295 LT 2' where di_ente = 4076 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 8 ' where di_ente = 4077 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1305 LT 13' where di_ente = 4078 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 1305 LT 13' where di_ente = 4081 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1458 LT 29' where di_ente = 4082 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15' where di_ente = 4084 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1295 LT 30' where di_ente = 4087 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 8 A' where di_ente = 4090 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 8A  ESQ NORTE 36' where di_ente = 4090 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 M1295 L30' where di_ente = 4091 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1299 LT 18' where di_ente = 4101 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 4105 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 11' where di_ente = 4128 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37 MZ 75' where di_ente = 4137 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 01 LT 405' where di_ente = 4150 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 27 LT' where di_ente = 4154 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 27 LT' where di_ente = 4154 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 93 LT' where di_ente = 4155 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 11 A MZ 1723 LT 10' where di_ente = 4159 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 38 LT 9' where di_ente = 4168 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 29 A MZ 252 LT 13' where di_ente = 4171 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 38 L9' where di_ente = 4172 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 35 MZ 58 LT 10' where di_ente = 4175 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 38 LT2' where di_ente = 4177 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 39 LT 27' where di_ente = 4179 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 139  LT 3' where di_ente = 4189 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 141 LT 70' where di_ente = 4200 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 38 LT 9' where di_ente = 4202 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 141 LT 70' where di_ente = 4203 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE ' where di_ente = 4207 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 38 LT9' where di_ente = 4208 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 38 LT 9' where di_ente = 4213 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE ' where di_ente = 4217 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 48 MZ 48 LT ' where di_ente = 4221 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 27 LT ' where di_ente = 4239 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 27 LT ' where di_ente = 4239 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 93 LT ' where di_ente = 4244 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18  MZ 77' where di_ente = 4244 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 LT 7 MZ 1413' where di_ente = 4250 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1414 LT 8' where di_ente = 4257 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1412 LT 10' where di_ente = 4260 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1401 LT 22' where di_ente = 4264 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 95 LT ' where di_ente = 4280 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 29 LT' where di_ente = 4282 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 29 LT' where di_ente = 4282 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 116 LT 28' where di_ente = 4293 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 46 MZ 52 LT ' where di_ente = 4296 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 1210' where di_ente = 4298 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 1210' where di_ente = 4302 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 158 LT 12' where di_ente = 4308 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 1199 LT 15' where di_ente = 4310 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 ' where di_ente = 4312 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 ' where di_ente = 4318 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 MZ 168' where di_ente = 4320 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1225' where di_ente = 4321 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 MZ 31 LT 31' where di_ente = 4327 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ 64 LT 7 ' where di_ente = 4332 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 29 LT ' where di_ente = 4334 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 MZ 82 LT 4' where di_ente = 4339 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 74 LT 10' where di_ente = 4341 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 53 MZ 3 LT ' where di_ente = 4348 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1469 LT8' where di_ente = 4352 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 23 MZ 141 LT 1' where di_ente = 4356 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 16 MZ 1469 LT 8' where di_ente = 4360 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 29 MZ 3 LT 23' where di_ente = 4381 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 29 MZ 3 LT 23' where di_ente = 4387 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 29 ' where di_ente = 4429 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NTE 12 MZ 794 LT 4' where di_ente = 4438 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 770 LT 1' where di_ente = 4444 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ 64 LT 7' where di_ente = 4455 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 12 ESQ SOTO Y GAMA' where di_ente = 4459 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 29   MZA 04 LTE 22' where di_ente = 4463 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 983 LT 4' where di_ente = 4464 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 1I MZ 93' where di_ente = 4471 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 11 MZ983 LT 4' where di_ente = 4473 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 1199 LT 15' where di_ente = 4502 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 29 LT' where di_ente = 4504 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 29 LT' where di_ente = 4504 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 17' where di_ente = 4539 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 13 LT 41' where di_ente = 4545 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 26 MZ 902 LT' where di_ente = 4550 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 34 MZ 220 LT 19' where di_ente = 4569 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 37 LT 41 MZ 13' where di_ente = 4626 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36 MZ 65 LT 9' where di_ente = 4655 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 54 MZ MZ 74 LT ' where di_ente = 4735 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 54 MZ 74 LT' where di_ente = 4741 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 54 MZ 74 LT' where di_ente = 4741 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 13 M 193 L' where di_ente = 4743 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 130 L 9' where di_ente = 4779 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 MZ 942 LT 9' where di_ente = 4842 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 14 LT 11 1' where di_ente = 4870 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 M 83 L 26' where di_ente = 4874 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 14 LT 11 1' where di_ente = 4879 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 MZ 130 LOTE 26' where di_ente = 4885 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 MZ 1366 LT 8' where di_ente = 4932 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 9' where di_ente = 4933 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1451 LT 9' where di_ente = 4938 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 2 MZ 145 LT 9' where di_ente = 4942 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 23 MZ 159 LT 30' where di_ente = 4950 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1443 LT 11' where di_ente = 4990 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 169 LT 5' where di_ente = 5028 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 169 LT 5' where di_ente = 5030 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 512 LT 13' where di_ente = 5032 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 169 LT5' where di_ente = 5039 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 55 LT 20' where di_ente = 5058 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 MZ 28 LT 24' where di_ente = 5082 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 MZ 129 LT 8' where di_ente = 5089 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20 MZ 155 LT 20' where di_ente = 5093 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 1448 LT' where di_ente = 5191 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT 09' where di_ente = 5225 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 20 MZ 1242 LT ' where di_ente = 5225 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 L8 MZ 1295' where di_ente = 5390 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 ' where di_ente = 5390 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 12 ESQ NTE 33 MZA 1453 LT 1' where di_ente = 5499 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ56' where di_ente = 5502 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ56' where di_ente = 5506 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18' where di_ente = 5513 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 189 LT 2' where di_ente = 5516 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 27 MZ 629 LT 10' where di_ente = 5732 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 107  LT' where di_ente = 5761 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 225 LT' where di_ente = 5764 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 16' where di_ente = 5766 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 32' where di_ente = 5786 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 32 ' where di_ente = 5788 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 32' where di_ente = 5794 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 1 MZ 1621 LT 5' where di_ente = 5803 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 1601 LT 4' where di_ente = 5805 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 11 MZ 107 LT' where di_ente = 5843 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 172' where di_ente = 5874 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 209' where di_ente = 5924 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 172 ' where di_ente = 5944 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 4 MZ 490 LT 10' where di_ente = 5969 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1407 LT 7' where di_ente = 6013 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 1100 LT 6' where di_ente = 6049 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 2 MZ 231 LT 1' where di_ente = 6094 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 MZ 12 LT ' where di_ente = 6112 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 24 MZ 99 LT 3' where di_ente = 6118 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 11 N 413' where di_ente = 6147 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 15 MZ 225' where di_ente = 6165 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 16 A MZ 226' where di_ente = 6170 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 172' where di_ente = 6187 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 34 MZ 225 ' where di_ente = 6194 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 209' where di_ente = 6203 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 15 MZ 225' where di_ente = 6206 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 14 MZ 209 ' where di_ente = 6222 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 43 MZ 56 LT ' where di_ente = 6241 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 A MZ 1846 LT 7' where di_ente = 6246 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 1583 LT 13' where di_ente = 6256 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 MZ 12 LT' where di_ente = 6263 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 192' where di_ente = 6293 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 7 Y NORTE 26' where di_ente = 6392 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 7 NORTE 26' where di_ente = 6392 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 7 NORTE 26' where di_ente = 6392 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 27' where di_ente = 6392 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 15 MZ 208 ' where di_ente = 6403 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 21 MZ 968 LT 8' where di_ente = 6438 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ60 LT9' where di_ente = 6543 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE20 50' where di_ente = 6550 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ1012 LT9' where di_ente = 6551 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ60 LT 9' where di_ente = 6554 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ1012 LT 9' where di_ente = 6561 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 192' where di_ente = 6565 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 19 ESQ TORRES' where di_ente = 6583 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 9 MZ 91 LT 3' where di_ente = 6684 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 192' where di_ente = 6687 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 161 LT 20 ' where di_ente = 6695 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 36 MZ1383 LT 18' where di_ente = 6819 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ29 LT 25' where di_ente = 6838 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4 MZ 13 LT 19' where di_ente = 6840 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 1090 LT2' where di_ente = 6897 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 25 M 505' where di_ente = 6933 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ1441 LT 12' where di_ente = 6963 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ1290 LT 5' where di_ente = 6971 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 358 ' where di_ente = 7004 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE MZ 129 LT 10' where di_ente = 7012 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 129 LT 10' where di_ente = 7017 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4' where di_ente = 7100 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4' where di_ente = 7101 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 349 LT 12' where di_ente = 7123 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 145 LT 4 ' where di_ente = 7135 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 170 LT 22' where di_ente = 7144 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 20' where di_ente = 7165 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 19 ' where di_ente = 7173 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 13 LT 27' where di_ente = 7213 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 13 LT 27' where di_ente = 7214 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 31 ' where di_ente = 7216 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 2 MZ 100 LT 9' where di_ente = 7221 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 170 LT 20' where di_ente = 7253 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 10 MZ 86 LT 12' where di_ente = 7263 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 5 A MZ 112 LT 8' where di_ente = 7270 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 3' where di_ente = 7322 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'OTE 7' where di_ente = 7349 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 8' where di_ente = 7435 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 31 MZ 1864 LT 9' where di_ente = 7438 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 8' where di_ente = 7464 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 24' where di_ente = 7466 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 4' where di_ente = 7503 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 67' where di_ente = 7505 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 16' where di_ente = 7507 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 4' where di_ente = 7535 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40A MZA 87' where di_ente = 7542 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23' where di_ente = 7583 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 15 LT 30 ' where di_ente = 7601 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 55 LT ' where di_ente = 7632 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 55 LT ' where di_ente = 7632 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ67' where di_ente = 7635 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 55 LT' where di_ente = 7636 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 29 LT' where di_ente = 7642 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 2 LT ' where di_ente = 7647 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 2 LT ' where di_ente = 7656 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 56 LT' where di_ente = 7663 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 21 MZ 56 LT' where di_ente = 7670 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 15 LT 30 ' where di_ente = 7715 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 23 MZ 54 LT' where di_ente = 7718 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 514 LT 13B ' where di_ente = 7777 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 514 LT 13B ' where di_ente = 7777 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15' where di_ente = 7802 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 15' where di_ente = 7808 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 29A MZ 5' where di_ente = 7825 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 14' where di_ente = 7831 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 16' where di_ente = 7834 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22' where di_ente = 7838 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 514 LT 13' where di_ente = 7846 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 514 LT 13' where di_ente = 7846 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 14' where di_ente = 7856 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 1 MZ 348 LT 7' where di_ente = 7867 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 348 L 7' where di_ente = 7873 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ1290 LT5' where di_ente = 7902 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ1290 LT 5' where di_ente = 7916 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 75 LT 7' where di_ente = 7977 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 179 LT 4 ' where di_ente = 7991 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ1290 LT5' where di_ente = 7993 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19' where di_ente = 7995 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 8 MZ 179 LT 4' where di_ente = 7998 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 30 MZ 16' where di_ente = 8003 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 2A MZ 67' where di_ente = 8034 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 MZ 67' where di_ente = 8039 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 18 MZ 15 LT 30 5' where di_ente = 8040 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 15' where di_ente = 8055 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 15 LT ' where di_ente = 8061 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 41 MZ 36 LT ' where di_ente = 8063 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 14' where di_ente = 8077 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 135' where di_ente = 8104 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7 MZ 57 LT 7 ' where di_ente = 8114 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 7 MZ 57 LT7 ' where di_ente = 8117 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 1B' where di_ente = 8119 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 3 ' where di_ente = 8130 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 89 LT 24' where di_ente = 8166 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 11 MZ 89 LT 24' where di_ente = 8169 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 U 17 MZ 45 LT 12' where di_ente = 8184 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 U 17 MZ 45 LT 12' where di_ente = 8201 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 19 MZ 75 LT 18' where di_ente = 8203 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 16 MZ 62 LT 3 ' where di_ente = 8209 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 13 MZ 100 LT 10' where di_ente = 8269 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 30 MZ 23 LT 10' where di_ente = 8270 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 1307 LT 6 6' where di_ente = 8492 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 1312 LT 13' where di_ente = 8496 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 5 MZ 1422 LT 15' where di_ente = 8497 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 42 MZ 103 LT 9' where di_ente = 8500 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10 MZ 1368 LT 19' where di_ente = 8502 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 14 MZ 1307LT 6 6' where di_ente = 8513 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 1313 LT 8' where di_ente = 8515 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PTE 14 ' where di_ente = 8663 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 14' where di_ente = 8666 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 18 MZ 163 LT 7' where di_ente = 8805 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 10C 8 MZ 656 SN' where di_ente = 8809 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 19 MZ 155 LT 10' where di_ente = 8812 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 12 Y PTE 16' where di_ente = 8828 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 13 MZ 41 LT 13' where di_ente = 8835 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 22 LT 608' where di_ente = 8922 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 6 MZ 607 LT 3' where di_ente = 8931 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 M 221' where di_ente = 8967 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 34 MZ 221' where di_ente = 8968 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 716 L 5' where di_ente = 9055 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 747 LT 4' where di_ente = 9062 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 13 LT 7' where di_ente = 9083 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 16 Y PTE 15' where di_ente = 9111 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40 MZ 173' where di_ente = 9160 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 22 MZ 962 LT 1' where di_ente = 9177 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 1270 LT 9' where di_ente = 9374 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 4' where di_ente = 9458 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 2' where di_ente = 9552 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 17 MZ 534 LT 5 ' where di_ente = 9561 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 9 M464 LT 5' where di_ente = 9564 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 ESQ PONIENTE 02 MZ 857 LT 23 ' where di_ente = 9683 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 7 ESQ PONIENTE 02 MZ 857 LT 23 ' where di_ente = 9683 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36A MZ 211' where di_ente = 9705 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 10' where di_ente = 9731 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 10' where di_ente = 9763 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 15 MZ 747 LT 4' where di_ente = 9847 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'SUR 7 ESA PONIENTE 7 MZ 249 LT' where di_ente = 9848 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 36A MZ 211' where di_ente = 10163 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 219' where di_ente = 10166 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 40A MZ 165' where di_ente = 10178 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 22 MZ 2 LT' where di_ente = 10201 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 15' where di_ente = 10202 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR ONCE ' where di_ente = 10237 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 11 MZ 25 LT 15' where di_ente = 10253 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6A LT 12 MZ 991' where di_ente = 10298 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6A LT 12 MZ 991' where di_ente = 10298 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 6' where di_ente = 10381 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 29' where di_ente = 10387 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 30' where di_ente = 10399 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 30 ' where di_ente = 10402 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'ORIENTE 39 MZ 30 ' where di_ente = 10402 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 14 MZ 11 LT 7' where di_ente = 10498 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 951 LT 6' where di_ente = 10503 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3' where di_ente = 10728 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 3' where di_ente = 10728 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 945 LT 16' where di_ente = 10751 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 484 LT 1 ' where di_ente = 10873 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 MZ 857 LT 23' where di_ente = 10928 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 6 MZ 1583LT 6' where di_ente = 10937 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 12 MZ 1085 LT' where di_ente = 11232 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 23 MZ 514 LT 11' where di_ente = 11280 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 35 MZ 63' where di_ente = 11309 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 39 MZ 84' where di_ente = 11320 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR  12 MZ 275' where di_ente = 11331 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 40 MZ 84' where di_ente = 11334 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 15 MZ 290' where di_ente = 11342 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'SUR 1 MZ 98' where di_ente = 11348 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'OTE 38 LT 24' where di_ente = 11367 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3' where di_ente = 11385 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 391' where di_ente = 11399 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 5' where di_ente = 11406 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 8' where di_ente = 11444 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PTE 22 MZ 90 LT 31' where di_ente = 11721 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'PONIENTE 18 A MZ 43 LT 11' where di_ente = 11857 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 7 ESQ PONIENTE 7' where di_ente = 11965 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 4 ESQUINA PONIENTE 2' where di_ente = 11972 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 4' where di_ente = 12162 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 39' where di_ente = 12163 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'ORIENTE 33 MZ 37' where di_ente = 12166 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 22 MZ 105 LTE 23' where di_ente = 12253 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 22  MZ 105 LTE 23 ' where di_ente = 12257 and di_tipo = 'RE'
update cobis..cl_direccion set di_calle = 'NORTE 23' where di_ente = 12365 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 3 MZ 1440 LT 16 ' where di_ente = 12389 and di_tipo = 'AE'
update cobis..cl_direccion set di_calle = 'NORTE 24 ' where di_ente = 12456 and di_tipo = 'AE'
