use cob_conta_super
go

print '*****  sb_equivalencia_cuentas'
if not object_id('sb_equivalencia_cuentas') is null
drop table sb_equivalencia_cuentas
go

create table sb_equivalencia_cuentas
(
   sb_cuenta_cobis             varchar(25)      not null,
   sb_desc_cuenta_cobis        varchar(80)      not null,
   sb_tipo_cuenta_altair       varchar(2)           null,
   sb_tipo_divisa_altair       int                  null,
   sb_cls_sdo_altair           char(1)              null,
   sb_cod_estado_altair        varchar(2)           null,
   sb_cuenta_altair            varchar(25)          null,
   sb_desc_cuenta_altair       varchar(80)          null
)
go

insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020201','BANCO CONCENTRADORA','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020202','BANCO COBRANZA H2H','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020203','BANCO RECAUDO DE PRESTAMOS EN BANCO SANTANDER','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020204','BANCO DISPERSIÓN','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020205','BANCO GARANTÍAS','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020206','BANCO PAGO PROVEEDORES','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020207','BANCO PAGO NÓMINA','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('11020208','BANCO RECEPTORA SEGUROS','A',1,'K','01','110304010101000','DEPOSITOS EN OTRAS ENTIDADES FINANCIERAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('110390','OTRAS DISPONIBILIDADES','A',1,'K','01','110310010101000','MXP BANCO SANTANDER MEXICANO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('131190010101','MICROCRÉDITOS CAPITAL GRUPALES','A',1,'K','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('131190010201','MICROCRÉDITOS CAPITAL GRUPALES','A',1,'K','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('131190030101','MICROCRÉDITOS INTERESES GRUPALES','A',1,'K','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('131190030201','MICROCRÉDITOS INTERESES GRUPALES','A',1,'K','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('139150619007','GRADO DE RIESGO A MICROCRÉDITOS  GRUPALES','A',1,'K','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('14010401','I.V.A.  PAGO A PROVEEDORES','A',1,'K','01','140501010101000','MXP IMPUESTO AL VALOR AGREGADO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('14010402','IVA A FAVOR','A',1,'K','01','151001010101001','MXP SALDO A FAVOR IVA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('14010403','ISR A FAVOR','A',1,'K','01','191601010101000','MXP ISR A FAVOR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('14019004','CUENTA LIQUIDADORA','A',1,'K','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('16010301','OBRAS EN PROCESO','A',1,'K','01','190203010101000','OBRAS Y ADAPTACIONES EN PROCESO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('160104','EQUIPO DE TRANSPORTE','A',1,'K','01','180104010101000','EQUIPO TRANSPORTE TERRESTRE')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('160106','MOBILIARIO','A',1,'K','01','180101020101000','MOBILIARIO Y EQUIPO DE OFICINA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('16010701','GTO INSTALACION TRASF. ARRENDADOR','A',1,'K','01','190201010101000','GTOS INST TRANSFERIBLES ARREND')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('161104','EQUIPO DE TRANSPORTE','A',1,'K','01','310304010101000',' DEP EQ TRANSPORTE VAL HISTORICO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('161106','MOBILIARIO','A',1,'K','01','310301010201000',' DEP MOB Y EQ. OFICINA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('16110702','GTO. INSTALAC. PROPIOS','A',1,'K','01','310701010101000','AMORTIZACION ACUMULADA GASTOS INSTALAC TERC')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('180110','DIFERENCIAS TEMPORALES','A',1,'K','01','191207010101000','MXP PROVISIONES')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('190101','ISR RETENIDOS POR INVERSIONES','A',1,'K','01','190701010101001','MXP ISR RETENIDO POR INTERES')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('19030207','ARRENDAMIENTOS PAGADOS POR ANTICIPADO','A',1,'K','01','145100000000000','RENTAS SEGUROS Y COMS PAGADOS X ANT')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('19030290','OTROS PAGOS ANTICIPADOS','A',1,'K','01','190190060101000','MXP PAGO ANT OTROS SERVICIOS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('190303900101','LICENCIAS ANUALES','A',1,'K','01','190501010101000','MXP GASTOS ANTICIPADOS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('24010702','IMPUESTO AL VALOR AGREGADO COBRADO','P',1,'K','01','231502030101000','MXP IVA COBRADO INTS Y COM TC')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('240108','OTROS IMPUESTOS Y DERECHOS POR PAGAR','P',1,'K','01','231502030101000','MXP IVA COBRADO INTS Y COM TC')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('240109','IMPUESTOS Y APORTACIONES DE SEGURIDAD SOCIAL RETENIDOS POR ENTERAR','P',1,'K','01','2311-07-04-01-01-000','MXP ISR RETENIDO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('24011202','HONORARIOS Y ARRENDAMIENTOS','P',1,'K','01','250390070101000','MXP CUENTAS POR PAGAR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('2401129001','PROVISION GASTOS GENERALES','P',1,'K','01','250390070101000','MXP CUENTAS POR PAGAR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('2401129003','PROVISION BANCO','P',1,'K','01','250390070201000','MXP PROV SERV ADMON BANCO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('2401129004','PROVISION GESBAN','P',1,'K','01','250390070101000','MXP CUENTAS POR PAGAR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('2401129006','AUDITORIA FINANCIERA','P',1,'K','01','250390070101000','MXP CUENTAS POR PAGAR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('240190','OTROS ACREEDORES DIVERSOS','P',1,'K','01','250390070101000','MXP CUENTAS POR PAGAR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('241302','OPERACIONES DE CRÉDITO','P',1,'K','01','250390070101000','MXP CUENTAS POR PAGAR')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('293290','OTROS COBROS ANTICIPADOS','P',1,'K','01','261706010101000','MXP PAGOS ANTICIPADOS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('410101','CERTIFICADOS DE APORTACIÓN ORDINARIOS','T',1,'K','01','420102010101000','MXP ACCIONES SERIE B')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('420301','RESULTADO POR APLICAR','T',1,'K','01','420403010101000','MXP DE RESULTADOS DE EJERCICIOS ANT')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('50502309','OTRAS RECUPERACIONES','RG',1,'I','01','520701010101000','MXP RECUP ADEUDOS DE DEUD DIV')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('505090','OTRAS PARTIDAS DE LOS INGRESOS (EGRESOS) DE LA OPERACIÓN','RG',1,'I','01','520690020101000','MXP OTROS INGRESOS EXTRAORD')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('510101','BANCOS','RG',1,'I','01','520101020101000','MXP BANCO SANTANDER MEXICANO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('510511900101','MICROCRÉDITOS GRUPAL (INT. VIG.)','RG ',1,'I','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('510511900201','MICROCRÉDITOS GRUPAL (INT. VIG.)','RG ',1,'I','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('5321111101','MICROCRÉDITOS GRUPAL  (INT. VEN.)','RG ',1,'I','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('560101','DIFERENCIAS TEMPORALES','RG ',1,'I','01','523901010101000','MXP IMPUESTO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('629101619007','GRADO DE RIESGO A MICROCRÉDITOS  GRUPALES','RP ',1,'I','01',null,null)
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('6390','OTRAS COMISIONES Y TARIFAS PAGADAS','RP',1,'I','01','510301010101000','COMISIONES PAGADAS A INTERM')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020101','SERV ADMTVOS BANCO SANTANDER','RP',1,'I','01','510801010101000',' SERVS ADMINISTRATIVOS BCO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020102','SERV ADMTVOS GESBAN','RP',1,'I','01','510801010401000',' HONOR.SERV.ADMVTOS GESBAN')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020103','AUDITORIA FINANCIERA','RP',1,'I','01','510801010601000',' AUDITORIA FINANCIERA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020106','AGENCIA DE RATING','RP',1,'I','01','510801012101000',' AGENCIAS DE RATING')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020107','CONSULTORIAS','RP',1,'I','01','510801012001000',' CONSULTORIAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020201','ABOGADOS','RP',1,'I','01','510801010801000',' HONORARIOS A ABOGADOS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64020202','BANCO SANTANDER','RP',1,'I','01','510801010101000',' SERVS ADMINISTRATIVOS BCO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64030101','LOCALES PARA OFICINA','RP',1,'I','01','510901010101000',' DE LOCALES PARA OFICINA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64030201','LOCALES PARA OFICINA','RP',1,'I','01','510901010101000',' DE LOCALES PARA OFICINA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64040103','APOYOS MEDIOS DE PAGO','RP',1,'I','01','511001900201000',' HONORARIOS PUBLICIDAD')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64040104','PRODUCCIÓN EN PUBLICIDAD','RP',1,'I','01','511001900201000',' HONORARIOS PUBLICIDAD')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('6406','IMPUESTOS Y DERECHOS DIVERSOS','RP',1,'I','01','514601010101801','IMPUESTOS Y DERECHOS CAUSADOS POR O')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('6408','GASTOS NO DEDUCIBLES','RP',1,'I','01','511790010301000','MXP GASTOS SIN COMPROBANTES')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('64090101','TERCEROS (OTROS PROVEEDORES)','RP',1,'I','01','522205210101000','MANTENIMIENTO SOFTWARE Y RENOVACION DE LICENCIAS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649001','EQUIPO DE TRANSPORTE','RP',1,'I','01','511501050101000','DEPRECIACION EJERCICIO TRANSPORTE')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649003','MOBILIARIO Y EQ. OFICINA','RP',1,'I','01','511501020301000','DEPRECIACION EJER MOBILIARIO Y EQUIPO DE OFICINA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649006','GTO. INSTALAC. PROPIOS','RP',1,'I','01','511502900201000','GASTOS DE INSTALACION')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649101','CUOTAS DE INSPECCIÓN','RP',1,'I','01','511101010101000',' CUOTA DE INSPECCION CNBV')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649103','INFORMES DE CRÉDITO','RP',1,'I','01','511124011601000','MXP INFORME DE CREDITO CONSUMO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649104','PUBLICACION ESTADOS FINANCIEROS','RP',1,'I','01','511117010101000','PUBLICACION OBLIGATORIA ESTADOS FINANCIEROS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649105','OTROS','RP',1,'I','01','510311040501000','OTROS GASTOS VARIOS ADMINISTRACION')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649106','ENERGÍA ELÉCTRICA','RP',1,'I','01','511114010101000',' ENERGIA ELECTRICA')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('649107','TELEFONÍA','RP',1,'I','01','511111021001000','TELEFONIA VOZ Y DATOS')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('6601','IMPUESTOS A LA UTILIDAD CAUSADOS','RP',1,'I','01','511801010101000','MXP DEL EJERCICIO')
insert into dbo.sb_equivalencia_cuentas (sb_cuenta_cobis, sb_desc_cuenta_cobis, sb_tipo_cuenta_altair, sb_tipo_divisa_altair, sb_cls_sdo_altair, sb_cod_estado_altair, sb_cuenta_altair, sb_desc_cuenta_altair) values ('6699','INCREMENTO POR ACTUALIZACIÓN DE IMPUESTOS A LA UTILIDAD CAUSADOS (1)','RP',1,'I','01','512499010101000','MXP INCREMENTO POR ACTUALIZACION')
