use cobis;
go
update cew_menu set me_id_cobis_product = 1, me_description = 'Administración' where me_name = 'MNU_ADMIN'
update cew_menu set me_id_cobis_product = 73, me_description = 'Administrador de Vista Consolidada' where me_name = 'MNU_ADMIN_VCC'
update cew_menu set me_id_cobis_product = 69, me_description = 'Administrador de Productos Financieros' where me_name = 'MNU_APF'
update cew_menu set me_id_cobis_product = 7, me_description = 'Cartera' where me_name = 'MNU_ASSETS'
update cew_menu set me_id_cobis_product = 7, me_description = 'Cartera' where me_name = 'MNU_ASSETS_ADM'
update cew_menu set me_id_cobis_product = 7, me_description = 'Cambio de Estado' where me_name = 'MNU_ASSETS_CAMBIOEST'
update cew_menu set me_id_cobis_product = 7, me_description = 'Cláusula Aceleratoria' where me_name = 'MNU_ASSETS_CLAUSE'
update cew_menu set me_id_cobis_product = 7, me_description = 'Conciliación' where me_name = 'MNU_ASSETS_CONCILIATION'
update cew_menu set me_id_cobis_product = 7, me_description = 'Desembolso de Préstamo' where me_name = 'MNU_ASSETS_DESEMBOLSO'
update cew_menu set me_id_cobis_product = 7, me_description = 'Consulta Ahorro Individual' where me_name = 'MNU_ASSETS_DETAILSAHO'
update cew_menu set me_id_cobis_product = 7, me_description = 'Prórroga Cuota' where me_name = 'MNU_ASSETS_EXTENDSQUONTA'
update cew_menu set me_id_cobis_product = 7, me_description = 'Búsqueda de Operaciones Grupales' where me_name = 'MNU_ASSETS_GROUP'
update cew_menu set me_id_cobis_product = 7, me_description = 'Reportes de Desembolso' where me_name = 'MNU_ASSETS_IMPDISBURS'
update cew_menu set me_id_cobis_product = 7, me_description = 'Impresión de Documentos' where me_name = 'MNU_ASSETS_IMPDOC'
update cew_menu set me_id_cobis_product = 7, me_description = 'Ingreso de Otros Cargos' where me_name = 'MNU_ASSETS_INGREOTROCARGO'
update cew_menu set me_id_cobis_product = 7, me_description = 'Log de Procesamiento de Ordenes de Débito' where me_name = 'MNU_ASSETS_LOG_PROC_ORD_DEBITOS'
update cew_menu set me_id_cobis_product = 7, me_description = 'Mantenimiento de Forma de Pago' where me_name = 'MNU_ASSETS_MANTENIMIENTO_PAG'
update cew_menu set me_id_cobis_product = 7, me_description = 'Mantenimiento' where me_name = 'MNU_ASSETS_MANTN'
update cew_menu set me_id_cobis_product = 7, me_description = 'Pago Grupales con uso de garantÃ­a' where me_name = 'MNU_ASSETS_PAGO_GRUPALES_GRANTIA'
update cew_menu set me_id_cobis_product = 7, me_description = 'Pagos de Préstamos' where me_name = 'MNU_ASSETS_PAYMENTS'
update cew_menu set me_id_cobis_product = 7, me_description = 'Proyección Cuota' where me_name = 'MNU_ASSETS_PROYCUOTA'
update cew_menu set me_id_cobis_product = 7, me_description = 'Cartera' where me_name = 'MNU_ASSETS_QUERY'
update cew_menu set me_id_cobis_product = 7, me_description = 'Consulta de Datos Generales' where me_name = 'MNU_ASSETS_QUERYSGENERALINFORMATION'
update cew_menu set me_id_cobis_product = 7, me_description = 'Reajustes del Préstamo' where me_name = 'MNU_ASSETS_READJUSTMENT'
update cew_menu set me_id_cobis_product = 7, me_description = 'Renovación de Préstamo' where me_name = 'MNU_ASSETS_RENOVACIONES'
update cew_menu set me_id_cobis_product = 7, me_description = '' where me_name = 'MNU_ASSETS_RENOVACIONES_IYU'
update cew_menu set me_id_cobis_product = 7, me_description = 'Reversa' where me_name = 'MNU_ASSETS_REVERSE'
update cew_menu set me_id_cobis_product = 7, me_description = 'Pruebas' where me_name = 'MNU_ASSETS_SOL_PAYMENT_SRV'
update cew_menu set me_id_cobis_product = 7, me_description = 'Operaciones' where me_name = 'MNU_ASSETS_TRNSC'
update cew_menu set me_id_cobis_product = 7, me_description = 'Fecha Valor' where me_name = 'MNU_ASSETS_VALDATE'
update cew_menu set me_id_cobis_product = 7, me_description = 'Valores / Tasas Aplicar' where me_name = 'MNU_ASSETS_VALUES_RATES'
update cew_menu set me_id_cobis_product = 7, me_description = 'ReenvÃ­o de correo' where me_name = 'MNU_ASSETS_VOUCHER_MAIL'
update cew_menu set me_id_cobis_product = 43, me_description = '' where me_name = 'MNU_BACK_OFFICE'
update cew_menu set me_id_cobis_product = 43, me_description = 'Reglas de Negocio' where me_name = 'MNU_BUSINESS_RULES'
update cew_menu set me_id_cobis_product = 43, me_description = 'Seguridades de Reglas y PolÃ­ticas' where me_name = 'MNU_BUSSINESS_RULES_ADMIN'
update cew_menu set me_id_cobis_product = 7, me_description = 'Carga de Archivo' where me_name = 'MNU_CARGA_ARCH'
update cew_menu set me_id_cobis_product = 43, me_description = 'CategorÃ­as y SubCategorÃ­as' where me_name = 'MNU_CAT_SUBCAT'
update cew_menu set me_id_cobis_product = 43, me_description = 'Buzón de Tareas de Oficial' where me_name = 'MNU_CONTAINER_INBOX_FF'
update cew_menu set me_id_cobis_product = 43, me_description = 'Buzón de Tareas de Supervisor' where me_name = 'MNU_CONTAINER_INBOX_SS'
update cew_menu set me_id_cobis_product = 69, me_description = 'Contenidos' where me_name = 'MNU_CONTENT_ADM'
update cew_menu set me_id_cobis_product = 73, me_description = 'Sección de Contenidos' where me_name = 'MNU_CONTENT_SECTION'
update cew_menu set me_id_cobis_product = 73, me_description = 'Seguridad Sección de Contenidos' where me_name = 'MNU_CONTENT_SECTION_SECURITY'
update cew_menu set me_id_cobis_product = 87, me_description = 'Creación' where me_name = 'MNU_CREATION_PROS'
update cew_menu set me_id_cobis_product = 2, me_description = 'Mantenimiento de Personas Naturales' where me_name = 'MNU_CSTMR_SEACHCUSTOMER'
update cew_menu set me_id_cobis_product = 2, me_description = 'Prospectos' where me_name = 'MNU_CUSTOMER_ADM'
update cew_menu set me_id_cobis_product = 7, me_description = 'Prospectos' where me_name = 'MNU_CUSTOMER_OPER'
update cew_menu set me_id_cobis_product = 2, me_description = '' where me_name = 'MNU_DESEMBOLSO'
update cew_menu set me_id_cobis_product = 73, me_description = 'Dtos y Propiedades' where me_name = 'MNU_DTOS_AND_PROPERTIES'
update cew_menu set me_id_cobis_product = 7, me_description = 'Prueba Impresión de Contratos' where me_name = 'MNU_DUMMY_REPORTS'
update cew_menu set me_id_cobis_product = 43, me_description = 'Editor de Políticas' where me_name = 'MNU_EDITOR_POLITICAS'
update cew_menu set me_id_cobis_product = 2, me_description = '' where me_name = 'MNU_EJEMPLO_MODL'
update cew_menu set me_id_cobis_product = 43, me_description = '' where me_name = 'MNU_FRONTOFFICE'
update cew_menu set me_id_cobis_product = 7, me_description = 'Manejo de fondos' where me_name = 'MNU_FUND'
update cew_menu set me_id_cobis_product = 87, me_description = 'Grupos' where me_name = 'MNU_GROUPMNU'
update cew_menu set me_id_cobis_product = 2, me_description = 'Grupos' where me_name = 'MNU_GROUP_ADM'
update cew_menu set me_id_cobis_product = 0, me_description = '' where me_name = 'MNU_GROUP_ADMINISTRATION'
update cew_menu set me_id_cobis_product = 43, me_description = 'Buzón de Tareas' where me_name = 'MNU_INBOX'
update cew_menu set me_id_cobis_product = 69, me_description = 'Buzón de Tareas' where me_name = 'MNU_INBOX_ADM'
update cew_menu set me_id_cobis_product = 43, me_description = 'Tareas' where me_name = 'MNU_INBOX_QUERY'
update cew_menu set me_id_cobis_product = 43, me_description = 'Buzón de Tareas' where me_name = 'MNU_INBOX_QUERY_MAIN'
update cew_menu set me_id_cobis_product = 1, me_description = 'Creación de Grupos' where me_name = 'MNU_LOANGROUP'
update cew_menu set me_id_cobis_product = 1, me_description = 'Mantenimiento de Grupos' where me_name = 'MNU_LOANGROUPUP'
update cew_menu set me_id_cobis_product = 87, me_description = 'Mantenimiento' where me_name = 'MNU_MAINTENANCE_PROS'
update cew_menu set me_id_cobis_product = 0, me_description = 'Maker and Checker' where me_name = 'MNU_MAKER_CHECKER'
update cew_menu set me_id_cobis_product = 1, me_description = 'Gestión de Reclamos' where me_name = 'MNU_MANAGEMENT_CLAIMS'
update cew_menu set me_id_cobis_product = 2, me_description = '' where me_name = 'MNU_MEMBERSACCOUNT'
update cew_menu set me_id_cobis_product = 1, me_description = 'Administración de Dispositivos Móviles' where me_name = 'MNU_MOBILE_DIVICE_MGNT'
update cew_menu set me_id_cobis_product = 0, me_description = 'Operaciones' where me_name = 'MNU_OPER'
update cew_menu set me_id_cobis_product = 2, me_description = 'Creación de Prospectos' where me_name = 'MNU_PROSPECTS'
update cew_menu set me_id_cobis_product = 87, me_description = 'Prospectos' where me_name = 'MNU_PROSPECTSMNU'
update cew_menu set me_id_cobis_product = 0, me_description = 'Consultas' where me_name = 'MNU_QUERY'
update cew_menu set me_id_cobis_product = 7, me_description = 'Documentos Digitalizados' where me_name = 'MNU_QUERY_DOCUMENTS'
update cew_menu set me_id_cobis_product = 21, me_description = 'Reimpresión De Documentos' where me_name = 'MNU_REPRINT_DOCUMENT'
update cew_menu set me_id_cobis_product = 87, me_description = 'Mantenimiento de Relaciones entre Clientes' where me_name = 'MNU_RLATION_CUSTOMER'
update cew_menu set me_id_cobis_product = 7, me_description = 'Reportes Grupales' where me_name = 'MNU_RPT_GRUPALES'
update cew_menu set me_id_cobis_product = 43, me_description = 'Consulta de Reclamos' where me_name = 'MNU_SEARCH_CLAIMS'
update cew_menu set me_id_cobis_product = 0, me_description = 'Transacciones de Negocio' where me_name = 'MNU_SEARCH_TRAN_MKCHK'
update cew_menu set me_id_cobis_product = 73, me_description = 'Administrador de Secciones' where me_name = 'MNU_SECTION_ADMINISTRATOR'
update cew_menu set me_id_cobis_product = 2, me_description = '' where me_name = 'MNU_TALLER_ERROR'
update cew_menu set me_id_cobis_product = 7, me_description = '' where me_name = 'MNU_TEST_SMO'
update cew_menu set me_id_cobis_product = 100, me_description = '' where me_name = 'MNU_TEST_SMO2'
update cew_menu set me_id_cobis_product = 43, me_description = 'Variables y Programas' where me_name = 'MNU_VARIABLES_PROGRAMS'
update cew_menu set me_id_cobis_product = 73, me_description = 'Vista Consolidada' where me_name = 'MNU_VCC'
update cew_menu set me_id_cobis_product = 19, me_description = 'Garantías' where me_name = 'MNU_WARRANTIES'
update cew_menu set me_id_cobis_product = 19, me_description = 'Consultas' where me_name = 'MNU_WARRANTIESQUERY'
update cew_menu set me_id_cobis_product = 19, me_description = 'General de Garantías' where me_name = 'MNU_WARRANTIESQUERY_GENERAL'
update cew_menu set me_id_cobis_product = 19, me_description = 'Mantenimiento' where me_name = 'MNU_WARR_MANT'
update cew_menu set me_id_cobis_product = 19, me_description = 'Creación de Garantías' where me_name = 'MNU_WARR_MANT_CREATION'
update cew_menu set me_id_cobis_product = 19, me_description = 'Modificación de Garantías' where me_name = 'MNU_WARR_MANT_MODIFICATION'
update cew_menu set me_id_cobis_product = 19, me_description = '' where me_name = 'MNU_WARR_SPECIFICATION'
update cew_menu set me_id_cobis_product = 43, me_description = 'Workflow' where me_name = 'MNU_WORKFLOW'
update cew_menu set me_id_cobis_product = 43, me_description = 'Editor' where me_name = 'MNU_WORKFLOW_EDITOR'
update cew_menu set me_id_cobis_product = 43, me_description = 'Estadísticas ' where me_name = 'MNU_WORKFLOW_STATISTICS'
update cew_menu set me_id_cobis_product = 19, me_description = 'Garantías' where me_name = 'MNU_WRRNT_QUERY'
go

