use cobis
go

delete cl_parametro
where pa_producto in ('CRE','GAR')
go

insert into cl_parametro values('MONTO DEL SALARIO','10SMML','S',NULL,NULL,10,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('APROBAR UN MONTO SUPERIOR','15AMS','S',NULL,NULL,150,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR PATRIMONIO Y DECLARACION','1MAPD','I',NULL,NULL,NULL,120,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR PATRIMONIO Y DECLARACION','1MEPD','I',NULL,NULL,NULL,120,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MONTO DEL SALARIO','1SMMLV','S',NULL,NULL,1,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MONTO DEL SALARIO','2.5SML','F',NULL,NULL,NULL,NULL,NULL,NULL,2.5,'CRE')
insert into cl_parametro values('MONTO DEL SALARIO','25SMML','S',NULL,NULL,25,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR PATRIMONIO Y DECLARACION','2MAPD','I',NULL,NULL,NULL,200,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR PATRIMONIO Y DECLARACION','2MEPD','I',NULL,NULL,NULL,200,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PLAZO MAXIMO DEL CREDITO','30MES','S',NULL,NULL,30,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VERIFICACION DE LA NOTA','3NOT','T',NULL,3,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VERIFICACION DE LA NOTA','4NOT','T',NULL,4,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MONTO DEL SALARIO','5SMML','F',NULL,NULL,NULL,NULL,NULL,NULL,5.0,'CRE')
insert into cl_parametro values('PLAZO VIVIENDA (CR - VIV','60MES','F',NULL,NULL,NULL,NULL,NULL,NULL,60.0,'CRE')
insert into cl_parametro values('LIQUIDEZ DISPONIBLE','9LIQD','S',NULL,NULL,90,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE LA CASA DE COBRANZA','ABOGCC','C','CC',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DEL ABOGADO','ABOGEX','C','AA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ACCION COMPROMISO DE PAGO','ACMPG','C','00CMP',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ACTIVACION PROVISIONES CIR 004 SUPER','ACTCIR','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ANTIGUEDAD PARA CUPO PRUEBA 11','ANPACU','S',NULL,NULL,24,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SIN GARANTIA','APROG','C','02',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO SALARIOS MINIMOS ACUMULADOS AÑO','ASMLV','I',NULL,NULL,NULL,25000,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE PROCESOS SIMULTANEOS','ATRASO','T',NULL,120,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE AVAL DE LA NACION','AVALNA','C','5300',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO BAC','BAC','C','040',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('BANCAMIA','BANCO','C','BANCAMIA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LINEA BONOS DE PRENDA','BPREN','C','2240115102',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CUENTA ACTIVOS FIJOS','CAF','I',NULL,NULL,NULL,90,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CIERRE DE CALIFICACION','CALIF','C','I',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DEL CARGO ASESOR DE OFICINA','CAO','S',NULL,NULL,1611,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DEL CAPITAL','CAP','C','1',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CAUSAL DE BLOQUEO EN CUENTAS DE AHORRO','CBLOAH','C','17',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CAUSAL DE BLOQUEO EN CUENTAS CORRIENTES','CBLOCC','C','18',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PROCESO DE COBRANZA POR DEFAULT','CBPROC','C','NA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CANTIDAD DE CUOTAS CANCELADAS','CCAN10','S',NULL,NULL,10,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR CLAUSULA ACELERATORIA','CCCJ','C','E',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE VARIABLE CUOTA PARA LOS DETALLES PASIVOS','CCDP','I',NULL,NULL,NULL,4,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA GASTOS FAMILIARES','CCGF','I',NULL,NULL,NULL,290,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA GASTOS DE PERSONAL','CCGP','I',NULL,NULL,NULL,240,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA MATERIA PRIMA','CCMP','I',NULL,NULL,NULL,60,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA DE OBLIGACIONES DE LA EMPRESA','CCOE','I',NULL,NULL,NULL,260,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO PARA CARTERA COMERCIAL','CCOM','C','1',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO PARA CARTERA CONSUMO','CCON','C','2',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CLIENTES QUE HAN CANCELADO OBLIGACIONES EN N MESES','CCONM','I',NULL,NULL,NULL,6,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA OBLIGACIONES PERSONALES','CCOP','I',NULL,NULL,NULL,300,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA PRODUCTOS EN PROCESO','CCPP','I',NULL,NULL,NULL,70,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA PRODUCTO TERMINADO','CCPT','I',NULL,NULL,NULL,80,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO CDM','CDM','C','CDM',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DEL CARGO DIRECTOR DE OFICINA','CDO','S',NULL,NULL,1608,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DEL DOLAR NORTEAMERICANO','CDOLAR','T',NULL,1,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO ETAPA FINAL','CEF','T',NULL,5,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CONTROL DEL CEM','CEM','C','N',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CLIENTES EN EL RUTERO EN ESTADO TODOS','CERALL','C','ALL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CLIENTES EN EL RUTERO EN ESTADO CANCELADOS','CERCAN','C','CAN',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CLIENTES EN EL RUTERO EN ESTADO MORA','CERMOR','C','MOR',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CLIENTES EN EL RUTERO EN ESTADO NO RENOVADOS','CERNRE','C','NRE',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CLIENTES EN EL RUTERO EN ESTADO SOLICITUDES','CERSOL','C','SOL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO PARA CARTERA MICROCREDITO','CMIC','C','4',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CUENTA COSTO MERCANCIA VENDIDA','CMV','I',NULL,NULL,NULL,220,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('COBERTURA POLIZA','COBPOL','C','COBPOL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO ALMACENADORA','CODALM','C','CODALM',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO ASEGURADORA','CODASE','C','CODASE',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO BANCO AGRARIO','CODBT','I',NULL,NULL,NULL,143,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO EXPEDICION FAG','CODEXP','I',NULL,NULL,NULL,6,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO MUNICIPIO BODEGA','CODMU','C','CODMU',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO RECONOCIMIENTO FAG','CODPAG','I',NULL,NULL,NULL,37,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE POLIZA','CODPOL','C','CODPOL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS HABILES PARA REDESCUENTO','CODRED','T',NULL,2,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO RUTA RENOVACION FAG','CODREN','I',NULL,NULL,NULL,7,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO MUNICIPIO DE LA BODEGA','COMU','C','CODMU',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR CONCORDATO','CON','C','CON',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('COSTOS COBRANZAS JUDICIALES','COSCOB','C','T25',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('AREA CONTABLE GASTOS JUDICIALES','CRAREA','I',NULL,NULL,NULL,6810,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CREDITOS CANCELADOS LINEA PARALELO','CREC0','T',NULL,0,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CREDITOS VIGENTES LINEA PARALELO','CREV1','T',NULL,1,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO SALARIOS PARA MAYOR CUANTIA','CUANT','I',NULL,NULL,NULL,300,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CUOTA PARA CREDITO SOLICITADO','CUOSOL','S',NULL,NULL,18,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO PARA CARTERA VIVIENDA','CVIV','C','3',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE VARIABLE LARGO PARA LOS DETALLES PASIVOS','CVLP','I',NULL,NULL,NULL,6,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS PARA EL AVISO DE SINIESTRO','DADMC','I',NULL,NULL,NULL,95,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DESTINO CARTA AVALISTA','DECAAV','C','AVA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DESTINO CARTA CLIENTE','DECACL','C','CLI',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DESTINO CARTA CODEUDOR','DECACO','C','COD',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION DEFINITIVA','DEF','C','DEF',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS VALIDOS PARA LA ELEGIBILIDAD','DEICR','I',NULL,NULL,NULL,180,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS DE ANTIGUEDAD DEL BALANCE DEL CLIENTE','DIABCL','I',NULL,NULL,NULL,90,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS DE ANTIGUEDAD DE INFORME DE PASIVOS DEL CLIENTE','DIAPCL','I',NULL,NULL,NULL,30,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS DE VENCIMIENTO DEL CUPO','DIAVC','S',NULL,NULL,91,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS DE VENCIMIENTO PARA CARTA CONMINATORIA','DIAVCC','S',NULL,NULL,61,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO GERENTE DE COBRANZAS','DICOCA','S',NULL,NULL,4,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PASSWORD ENVIO ESTADO DE CUENTAS - CLIENTE', 'PWDEEC', 'C', 'cobiscorp2017', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('DIAS INICIALES QUE NO SE HA INICIADO TRAMITE DE PROCESO FAG','DINITP','I',NULL,NULL,NULL,31,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIRECCION ALMACENADORA','DIRALM','C','DIRALM',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS DE CUPO','DISCUP','I',NULL,NULL,NULL,360,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DISPONIBILIDAD MAYOR A 300.000','DISMA3','M',NULL,NULL,NULL,NULL,300000.0,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO CIUU FALTA ACTIVIDAD','DMCIUU','C','000000',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIRECCION PREDIO','DP','C','DP',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS PRORROGA PARA LA ELEGIBILIDAD','DPEICR','I',NULL,NULL,NULL,90,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS PARA LA SOLICITUD DE PAGO','DSPFAG','I',NULL,NULL,NULL,165,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS TOPE QUE NO SE HA INICIADO TRAMITE DE PROCESO FAG','DTNITP','I',NULL,NULL,NULL,35,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS VENCIMIENTO OP ORIGINAL','DVAOO','S',NULL,NULL,91,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('EDAD PARA SEGURO EXEQUIAL','ESE','I',NULL,NULL,NULL,31,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO ADMITIDO EN CONCORDATO','ESTA','C','A',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO ANULADO DE CARTERA','ESTANU','T',NULL,6,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO CANCELADO DE CARTERA','ESTCAN','T',NULL,3,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO CASTIGADO DE CARTERA','ESTCAS','T',NULL,4,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO DE COBRO PREJURIDICO','ESTCPR','C','CP',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO EN CREDITO DE CARTERA','ESTCRE','T',NULL,99,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO HOMOLOGADO EN CONCORDATO','ESTH','C','H',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO DE COBRANZAS JURIDICO','ESTJUR','C','CJ',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO DE COBRANZA NORMALIZADO','ESTNR','C','NR',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO NO VIGENTE DE CARTERA','ESTNVG','T',NULL,0,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('COBRO JURIDICO ACTIVAS','ESTPRE','T',NULL,5,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO SUSPENSO DE CARTERA','ESTRES','T',NULL,9,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO VENCIDO DE CARTERA','ESTVEN','T',NULL,2,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTADO VIGENTE DE CARTERA','ESTVG','T',NULL,1,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ETAPA DE APROBACION PREVIA','ETAPRE','I',NULL,NULL,NULL,85,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ETAPA RUTA RECONOCIMIENTO FAG','ETRFAG','T',NULL,235,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('EXCEPCIONES PARA LAS GARANTIAS','EXCGAR','C','1',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CREDITOS QUE SUPERAN LIMITE MAXIMO DE EXPOSICION','EXCLIM','C','EXCLIM',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ESTACION LOGICA FABRICA','FABRIC','S',NULL,NULL,2350,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS DE VENCIMIENTO DE OPERACIONES PARA GARANTIAS FAG','FAG359','C','',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('FECHA DE CORTE DE LA CALIFICACION','FCCAL','D',NULL,NULL,NULL,NULL,NULL,'Dec 31 2008 12:00AM',NULL,'CRE')
insert into cl_parametro values('FECHA DE CORTE DE OPERACIONES MIGRADAS FINAGRO','FCOMF','D',NULL,NULL,NULL,NULL,NULL,'Sep 1 2004 12:00AM',NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR FALLECIMIENTO','FDO','C','FDO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('FECHA CONTROL MALLAS','FECFAC','D',NULL,NULL,NULL,NULL,NULL,'Mar 1 2007 12:00AM',NULL,'CRE')
insert into cl_parametro values('FECHA VIGENCIA','FECVIG','C','FECVIG',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('FUENTE PROPIA AUTONOMO','FUPRA','C','1',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('IND CALIDAD INFORMES','GCALIN','C','4',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR GERENTE','GER','C','GER',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('IND EVALUACION','GEVAL','C','6',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CUENTA GASTOS GENERALES - OTROS','GGO','I',NULL,NULL,NULL,255,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CUENTA GASTOS GENERALES - TRANSPORTADOR','GGT','I',NULL,NULL,NULL,250,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('IND OPORTUNIDAD','GOPOR','C','5',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR INTERVENCION ECONOMICA','INE','C','INE',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DEL INTERES','INT','C','2',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('JERARQUIA PARA APROBACION','JERAR','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LINEA DE CREDITO POR DEFECTO','LCD','C','CAMPO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LIMITE DE ENDEUDAMIENTO','LENDEU','I',NULL,NULL,NULL,120,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LINEA AGROPECUARIO','LINAGR','C','R',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR LIQUIDACION OBLIGATORIA','LOB','C','LOB',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LINEA REMESAS DEL EXTERIOR','LREX','C','MCREXT',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LINEA TARJETAS DE CREDITO','LTDC','C','1',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIRECCION NACIONAL','MAT','S',NULL,NULL,1,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('OFICINA MATRIZ','MATC','S',NULL,NULL,1,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MATINV','MATINV','C','A',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MATTOT','MATTOT','C','B',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MAXIMO CREDITOS ACTIVOS','MCACT','S',NULL,NULL,3,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MONTO DE CREDITO PARA TARJETAS','MCTAR','M',NULL,NULL,NULL,NULL,10000000.0,NULL,NULL,'CRE')
insert into cl_parametro values('MARGEN DESCUENTO','MDTO','C','MDTO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MERCADO PARA PAQUETE DE PRODUCTOS','MERPAQ','C','P',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
go
insert into cl_parametro values('MONEDA LOCAL DEFAULT DE CREDITO','MLOCR','T',NULL,0,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MERCADO OBJETIVO PARA PAQUETES DE PRODUCTOS','MOBPAQ','C','007',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MOMRC','MOMRC','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MONTO PARA CREDITO SOLICITADO','MONSOL','S',NULL,NULL,15,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MUJER RURAL DE BAJOS INGRESOS','MRBI','C','110',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('MONTO MAXIMO DE SOBREPASAMIENTO','MSOB','M',NULL,NULL,NULL,NULL,0.0,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE EMPLEADOS PLANTA','NEMIC','T',NULL,10,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO MINIMO DE FIRMAS DE APROBACION','NFIR','T',NULL,1,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NORMA LEGAL PARA ARCHIVO REDESCUENTO','NLLF','C','NL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE DIAS MAXIMO PARA REASIGNACION DE EJECUTIVO','NMAXDR','T',NULL,30,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE DIAS MINIMO PARA REASIGNACION DE EJECUTIVO','NMINDR','T',NULL,5,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NOMBRE ALMACENADORA','NOMALM','C','NOMALM',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NOMBRE OFICINA REPOSA PAGARE','NOPAG','C','BOGOTA SETECSA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('LINEA CREDITO SIN MIPYMES','NOPYME','C','A-MICRO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO AGROPECUARIO','NOTA','C','NO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NOTA PENULTIMO CREDITO','NOTPEU','S',NULL,NULL,4,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NOTA ULTIMO CREDITO','NOTULT','S',NULL,NULL,5,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ETAPA DE COBRANZA NORMAL','NRETAP','C','NORMAL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PROCESO DE COBRANZA NORMAL','NRPROC','C','NORMAL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE SALARIOS DEUDA PARA MICROCREDITO','NSMC','T',NULL,120,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO SALARIOS MINIMOS PARA CLASE DE CARTERA','NSMCC','S',NULL,NULL,300,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE SALARIOS PARA ACTIVOS MICROCREDITO','NSMIC','S',NULL,NULL,500,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO SALARIOS MINIMOS INDIVIDUALES','NSMLV','I',NULL,NULL,NULL,2500,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('L-MITE DE SALARIOS M-NIMOS MENSUALES LEGALES VIGENTES','NSMVL1','I',NULL,NULL,NULL,1000,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('L-MITE DE SALARIOS M-NIMOS MENS. LEGALES VIG. PARA CRED. PERSON.','NSMVL7','I',NULL,NULL,NULL,200,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('L-MIT DE SALAR. M-N. MENS. LEGAL. VIG. X RIESGO TOTAL DEL CLTE','NSMVL8','I',NULL,NULL,NULL,1000,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE CREDITOS CANCELADOS','NUMCRE','S',NULL,NULL,2,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VENCIMIENTO OPERACIONES COMERCIO EXTERIOR','NUMDIA','T',NULL,30,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE CREDITOS VIGENTES','NUMVIG','S',NULL,NULL,1,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO UNIDADES','NUNID','C','NUNID',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('OFICINA REPOSA PAGARE','OFPAG','I',NULL,NULL,NULL,3030,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('GERENTE REPITE','OFRPT','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE PARTICIONES PARALELISMO CREDITO','PART','I',NULL,NULL,NULL,250,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CLIENTE PATRIMONIO TECNICO','PATEC','I',NULL,NULL,NULL,2226280,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PORCENTAJE DE CUOTAS CANCELADAS','PCAN50','F',NULL,NULL,NULL,NULL,NULL,NULL,50.0,'CRE')
insert into cl_parametro values('PORCENTAJE DE CUOTAS CANDELADA','PCC','I',NULL,NULL,NULL,60,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIRECCION PREDIO','PD','C','PD',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PERIODO DE VIGENCIA CONSULTA CIFIN','PERCRI','C','30',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PLAZO MAXIMO DE AMORTIZACION CREDITO CLASE VIVIENDA','PFCV','I',NULL,NULL,NULL,10800,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PROVISION GENERAL - ACUMULADA','PGACM','M',NULL,NULL,NULL,NULL,3613737426.0,NULL,NULL,'CRE')
insert into cl_parametro values('PROVISION GENERAL - PERIODOS ANTERIORES','PGANT','M',NULL,NULL,NULL,NULL,3491261704.0,NULL,NULL,'CRE')
insert into cl_parametro values('PROVISION GENERAL - FECHA INICIO VIGENCIA','PGFINI','D',NULL,NULL,NULL,NULL,NULL,'Jul 31 1999 12:00AM',NULL,'CRE')
insert into cl_parametro values('PROVISION GENERAL - MESES DE VIGENCIA','PGMES','S',NULL,NULL,36,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PORCENTAJE DE PROVISION GENERAL','PGPCT','F',NULL,NULL,NULL,NULL,NULL,NULL,1.0,'CRE')
insert into cl_parametro values('PORCENTAJE HONORARIO ABOGADO CON REESTRUCTURACION','PHACR','F',NULL,NULL,NULL,NULL,NULL,NULL,50.0,'CRE')
insert into cl_parametro values('PORCENTAJE HONORARIO ABOGADO SIN REESTRUCTURACION','PHASR','F',NULL,NULL,NULL,NULL,NULL,NULL,100.0,'CRE')
insert into cl_parametro values('PLAZO MINIMO DE AMORTIZACION CREDITO CLASE VIVIENDA','PICV','I',NULL,NULL,NULL,1800,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PARAMETRO SECUENCIAL DE FINAGRO','PISF','I',NULL,NULL,NULL,131374,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR MAXIMO SECUENCIAL FINAGRO','PISFM','I',NULL,NULL,NULL,999999,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PLAZO DE UN TRAMITE','PLA','C','PLAZO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PLAZO PARA CREDITO SOLICITADO','PLASOL','S',NULL,NULL,4,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PORCENTAJE DE LIQUIDEZ PARALELO','PLIQ80','F',NULL,NULL,NULL,NULL,NULL,NULL,80.0,'CRE')
insert into cl_parametro values('% DE PARTICIPACION DE CAPITAL','PORCUP','F',NULL,NULL,NULL,NULL,NULL,NULL,20.0,'CRE')
insert into cl_parametro values('% DE GARANTIAS NO IDONEAS','PORGNI','F',NULL,NULL,NULL,NULL,NULL,NULL,10.0,'CRE')
insert into cl_parametro values('PORCENTAJE REDESCUENTO','PORRED','F',NULL,NULL,NULL,NULL,NULL,NULL,100.0,'CRE')
insert into cl_parametro values('PORCENTAJE DEL VALOR DE PROYECTO','PORVPR','F',NULL,NULL,NULL,NULL,NULL,NULL,80.0,'CRE')
insert into cl_parametro values('L-MITE SECTOR AGROPECUARIO INDIVIDUAL','PPTIAG','F',NULL,NULL,NULL,NULL,NULL,NULL,1.0,'CRE')
insert into cl_parametro values('L-MITE DE CR+DITOS RESPALDADO POR FAG EN RELACIÓN AL PTI','PPTIF4','F',NULL,NULL,NULL,NULL,NULL,NULL,5.0,'CRE')
insert into cl_parametro values('L-MITE DE CR+DITOS SINDICADOS EN RELACIÓN AL PTI','PPTIF6','F',NULL,NULL,NULL,NULL,NULL,NULL,5.0,'CRE')
insert into cl_parametro values('NUMERO DE INTENTOS PARA CADA PROCESO','PRETRY','T',NULL,3,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO DE PROCESOS','PROC','T',NULL,24,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CIERRE DE PROVISION','PROV','C','I',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PRUEBAS MPN..','PRUE','F',NULL,NULL,NULL,NULL,NULL,NULL,7.3,'CRE')
insert into cl_parametro values('LINEA PROVISION GENERICA','PRVGEN','C','ZPROVGENA0',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PORCENTAJE DE SOBREPASAMIENTO','PSOB','F',NULL,NULL,NULL,NULL,NULL,NULL,0.0,'CRE')
insert into cl_parametro values('L-MITE DE CR+DIT RESPALDADO X FAG EN RELACIÓN AL VLR DEL PROYECT','PVPFL3','F',NULL,NULL,NULL,NULL,NULL,NULL,80.0,'CRE')
insert into cl_parametro values('L-MITE DE CR+DITOS SINDICADOS EN RELACIÓN AL VALOR DEL PROYECTO','PVPFL5','F',NULL,NULL,NULL,NULL,NULL,NULL,33.0,'CRE')
insert into cl_parametro values('AFINIDAD CON FUNCIONARIO','RAFINF','I',NULL,NULL,NULL,300,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('ORIGEN - REFERENCIA INHIBITORIA','REFORI','C','F',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR RESTRUCTURACION','RES','C','RES',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('REESTRUCTURADOS - NUMERO DE CUOTAS','RESNC','T',NULL,2,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('REESTRUCTURADOS - PERIODO DE GRACIA','RESPG','T',NULL,1,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SE EVALUA EL RIESGO INDIRECTO','RIESIN','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('RETORNAR TODOS LOS TIPOS DE VISTIAS','RTTV','C','ALL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('RUTA PARA ALTA MASIVA DE SOLICITUDES','RUTMAS','C','0',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CUPO PAQUETE PRODUCTOS','RUTPAQ','C','0',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO SALARIOS MINIMOS FABRICA','SALFAB','S',NULL,NULL,15,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUM.SALARIOS AUT.DES. DIRECTOR COB','SAUTD','I',NULL,NULL,NULL,60,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CONDICIONES SIDAC PARA CUENTAS POR PAGAR','SCCON','C','02',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SECTOR AGROPECUARIO','SECAGR','C','3',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SISTEMA DE ALMACENAMIENTO','SISTAL','C','SISTAL',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO AGROPECUARIO','SITA','C','SI',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DEL CONCORDATO','SITC','C','CON',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DE CASTIGO','SITCS','C','CAS',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DE FALLECIMIENTO','SITF','C','FDO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DE INTERVENCION ECONOMICA CAUSA','SITIC','C','IEC',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DE INTERVENCION ECONOMICA NO CAUSA','SITIN','C','IEN',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DE LIQUIDACION OBLIGATORIA','SITL','C','LOB',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SITUACION DE PRECASTIGO','SITPC','C','PCA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SALARIOS MINIMOS GRANDES PRODUCTORES','SMGP','I',NULL,NULL,NULL,2500,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('NUMERO SALARIOS EVALUACION TESORERIA PROPIOS','SMLTES','C','1000',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SALARIOS MINIMOS MEDIANO PRODUCTOR','SMMP','I',NULL,NULL,NULL,2500,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SALARIOS MINIMOS MRBI','SMMR','I',NULL,NULL,NULL,82,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SALARIOS MINIMOS PEQUENO PRODUCTOR','SMPP','I',NULL,NULL,NULL,117,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CONCEPTO CUENTAS POR COBRAR','STREF','C','03',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SUBTIPO FAG','SUBFAG','C','F',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('SUBTIPO ICR','SUBICR','C','I',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VA A FUNCIONARIO SUPERIOR O A INFERIOR','SUPIN','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
go
insert into cl_parametro values('TIPO DE BIEN','TBIEN','C','2',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TARJETA CR','TC M','M',NULL,NULL,NULL,NULL,530.0,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO CALIFICACION POR COBRO JURIDICO','TCCJ','C','CJ',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO CUOTA PARA CREDITO SOLICITADO','TCUOSO','S',NULL,NULL,14,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO DE EMPRESA','TEMP','C','1',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO DE EMPRESA DEFAULT','TEMPDF','C','B',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO TENENCIA','TENEN','C','TENEN',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO DIRECCION PARA ENVIO CARTAS','TIDICA','C','D',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIEMPO NECESARIO PARA ENVIO CARTA CONMINATORIA','TIEMCO','S',NULL,NULL,999,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIEMPO NECESARIO PARA ENVIO CARTA RECORDATORIA','TIEMCR','S',NULL,NULL,999,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO DE LOCAL ARRENDADO','TLO','C','2',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO PLAZO PARA CREDITO SOLICITADO','TPLASO','S',NULL,NULL,13,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TRANSACCION PARA CAMBIO DE GERENTE','TRANAU','I',NULL,NULL,NULL,21054,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CARTERA AGROPECUARIA','TRCA','C','A',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO RUTA DE REDESCUENTO NOVEDAD','TRURER','T',NULL,11,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('RUTA DE CONVENIOS','TRUTAO','T',NULL,0,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('TIPO RUTA DE REDESCUENTO ORIGINAL','TRUTRE','T',NULL,29,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('UTILIDAD NETA','UN','I',NULL,NULL,NULL,270,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('USUARIO PARA ALMASIVA DE SOLICITUDES','USUMAS','C','AUTOMATICA',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('UTILIZACIONES POR CUPO','UTICUP','S',NULL,NULL,3,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALIDACION DE SALDOS VS CONCEPTOS','VALSAL','C','N',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VISITAS DE CONTROL DE INVERSION','VCTINV','C','VCTINV',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA INF. FINANCIERA VENTAS DIARIAS','VDIA','I',NULL,NULL,NULL,210,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VIGENCIA DE CUPO','VIGCUP','I',NULL,NULL,NULL,540,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VIGENCIA MINIMA PARA AMPLIACION DE CUPO','VMAC','I',NULL,NULL,NULL,360,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA INF. FINANCIERA VENTAS MENSUAL','VMES','I',NULL,NULL,NULL,200,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VISITAS DE CONTROL DE PLANIFICACION','VPLANI','C','VPLANIF',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR MERCANCIA','VRMCI','C','VRMCI',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR UNIDAD','VRUNI','C','VRUNI',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CALIFICACION POR VENCIMIENTO','VTO','C','VTO',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PORCENTAJE DE CUOTAS CANCELADAS PARA CREDITO','PCCC','F',NULL,NULL,NULL,NULL,NULL,NULL,70,'CRE')
insert into cl_parametro values('SE EXIGE ABONO PARA REESTRUCTURACION','EABORE','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('DIAS PARA ABONO DE REESTRUCTURACION','DABORE','I',NULL,NULL,NULL,15,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CODIGO DE GARANTIA TIPO ACCIONES','ACCIO','C','0',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('AREA CONTABLE DEL PRODUCTO GARANTIAS','ARG','S',NULL,NULL,3262,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('VALOR AVALUO','AVAL','C','AVAL',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('NOMBRE DE LA CENTRAL DE CUSTODIA','CCUST','C','0',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('FECHA EXPEDICION DEL CERTIFICADO DE LIBERTAD','CERTRA','C','FECHA EXP. CERT.LIBERTAD',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('DESCRIPCION DEL CODIGO DE GARANTIA FNG','CODFNG','C','2200',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CODIGO DE CONTRAPAGARE CUENTAS CORRIENTES','COGCTE','C','6210',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CODIGO DE CONTRAPAGARE TARJETA DE CREDITO','COGTCR','C','6210',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CONCEPTO DE PAGO DE COMISION FAG','COMISI','C','COMISIOFAG',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CONTRAGARANTIA','CONTRG','C','6200',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('DIAS PARA GENERACION DE REPORTE GARANTIAS FAG DESPUES DEL DESEMB','DCAFAG','I',NULL,NULL,NULL,5,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('DOCUMENTOS','DOCUME','C','DOCUMENT',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('ERROR CONTA GARANTIAS','ERRCO','C','ERRCO',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('ESCRITURA PUBLICA','ESCRI','C','ESCRITURA PUBLICA',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIPO DE GARANTIA FAG','FAG','C','5210',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('FECHA DE AMPLIACION','FAMP','C','FECHA REG. INSTRUM. PUBLICOS',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('FECHA DE REGISTRO EN INSTRUMENTOS PUBLICOS','FINSTR','C','FECHA REG. INSTRUM. PUBLICOS',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIPO GARANTIA','GAR','C','GAR',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIPO GARANTIAS ESPECIALES','GARESP','C','2000',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIPO DE GARANTIA BIENES INMUEBLES','GARINM','C','4000',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIPO DE GARANTIA VALORES MOBILIARIOS','GARVLM','C','5000',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('GARANTIA EN DOLARES','GSTABY','C','5300',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('ITEM PARA RECONOCER EL ESTRATO','ITEST','C','ESTRATO',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CONCEPTO DE PAGO DE IVA COMISION FAG','IVAFAG','C','IVACOMGFAG',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('MATRICULA INMOBILIARIA','MAINM','C','MATRICULA INMOBILIARIA',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('NOTARIA','NOTARI','C','NOTARIA',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('NUMERO DE DIAS PARA SOLICITUD DE CERTIFICADO','NUMDIA','S',NULL,NULL,20,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('OFICINA PARA CONTABILIZAR LAS CONTRAGARANTIAS DE TARJ. DE CREDIT','OCTCR','S',NULL,NULL,3029,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('OFICINA CONTABLE DEL PRODUCTO GARANTIAS','OFG','S',NULL,NULL,9000,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('NUMERO DEL PAGARE','PAGA','C','NUMERO DEL PAGARE',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CONDICION PARA PAGO A AVALUADORES O ABOGADOS','PCONDI','C','99',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CONCEPTO PARA PAGO A ABOGADOS','PGAAB','C','251010CO08',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('CONCEPTO PARA PAGO A AVALUADORES','PGAAV','C','251010CO08',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('PROCESOS PARALELISMO','PROC','T',NULL,24,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIPO DE REFERENCIA PARA PAGO A AVALUADORES O ABOGADOS','PTIRE','C','CC',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('NUMERO DE CEDULA CATASTRAL','REGCA','C','NUMERO DE CEDULA CATASTRAL',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('SIN GARANTIA MRC','SGMRC','C','SGMRC',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIEMPO VALORIZACION OBLIGACIONES NORMALES','TVOBNO','I',NULL,NULL,NULL,360,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('TIEMPO VALORIZACION OBLIGACIONES REESTRUCTURADOS','TVOBRE','I',NULL,NULL,NULL,720,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('AVALUO COMERCIAL DE LA CONSTRUCCION PARA HIPOTECAR','VCONS','C','VALOR CONSTRUCCION',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('AVALUO COMERCIAL DE OTRO COMPONENTE DE LA HIPOTECA','VINV','C','VALOR OTROS',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values('AVALUO COMERCIAL DEL TERRENO PARA HIPOTECA','VTERR','C','VALOR TERRENO',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values ('DIAS DE MORA PARA CUSTODIAS/COLATERALES','DIAMCS','I', NULL, NULL, NULL, 30, NULL, NULL, NULL,'GAR')
insert into cl_parametro values ('SALDO MINIMO PARA CUSTODIAS/COLATERALES','SMINCS','M', NULL, NULL, NULL, NULL, 100000, NULL, NULL,'GAR')
insert into cl_parametro values ('CALIFICACION MINIMA PARA CUSTODIAS/COLATERALES','CLMNCS','C','A', NULL, NULL, NULL, NULL, NULL, NULL,'GAR')
insert into cl_parametro values ('FILIAL BANCAMIA','FILIAL','T',null,1, null,null, null, null,null,'CRE')  
insert into cl_parametro values ('FILIAL SANTANDER','FILSAN','I',null,null,null,1,null,null,null,'CRE')  
insert into cl_parametro values ('VALOR DE LA GARANTIA TIPO PAGARE','VGP','M' ,null,null,null,null,1, null,null,'CRE')
insert into cl_parametro values ('FUENTE DE RECURSOS AECI BANCOLDEX','FRAB','C' ,'3',null,null,null,null, null,null,'CRE')
insert into cl_parametro values ('SALARIOS MINIMOS FUENTE RECURSOS BANCOLDEX AICE CAP.TRAB','SMFRCT','T' ,null,25,null,null,null, null,null,'CRE')
insert into cl_parametro values ('SALARIOS MINIMOS FUENTE RECURSOS BANCOLDEX AICE ACT.FIJOS','SMFRAF','T' ,null,75,null,null,null, null,null,'CRE')
insert into cl_parametro values ('PLAZO FUENTE RECURSOS BANCOLDEX AICE CAP.TRAB','PFRCT','T' ,null,2,null,null,null, null,null,'CRE')
insert into cl_parametro values ('PLAZO FUENTE RECURSOS BANCOLDEX AICE ACT.FIJOS','PFRAF','T' ,null,5,null,null,null, null,null,'CRE')
insert into cl_parametro values ('CODIGO CAPITAL DE TRABAJO','CT','C' ,'01',null,null,null,null, null,null,'CRE')
insert into cl_parametro values('% DE GARANTIAS IDONEAS','PORGI','F',NULL,NULL,NULL,NULL,NULL,NULL,10.0,'CRE')
insert into cl_parametro values('CODIGO DE CUENTA DE VALORACION DE ACTIVIDADES RURALES','CCVAR','I',NULL,NULL,NULL,75,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR % DE PARTICIPACION DEL CLIENTE EN EL CAPITAL','VPORPC','F',NULL,NULL,NULL,NULL,NULL,NULL,50,'CRE')
insert into cl_parametro values('VALOR MAXIMO EN GRID DE CREDITOS RURALES PARA LA CUENTA 10','VMCR10','I',NULL,NULL,NULL,99999,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR MAXIMO EN GRID DE CREDITOS RURALES PARA LA CUENTA 3','VMCR3','I',NULL,NULL,NULL,10000,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR MAXIMO EN GRID DE CREDITOS RURALES PARA LA CUENTA 5','VMCR5','I',NULL,NULL,NULL,99999,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('VALOR MAXIMO EN GRID DE CREDITOS RURALES PARA LA CUENTA 9','VMCR9','I',NULL,NULL,NULL,1080,NULL,NULL,NULL,'CRE')
insert into cl_parametro values ('CODIGO DEL PAGARE DE CARTERA','CODPAC','C','1200',NULL,NULL,NULL,NULL,NULL,NULL,'GAR')
insert into cl_parametro values ('PERIODICIDAD DE EJECUCION PROCESO COBRANZA','PCOB','C','S',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values ('NUMERO MAXIMO DE DIAS MORA POR CUOTA','MAXDMO','T',NULL,30,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values ('MAXIMO DE UTILIZACIONES POR CUPO','NMUTIL','S', null,null,1,null,null,null,null,'CRE')   
insert into cl_parametro values ('Servidor SSH Adminfo Parametro 1','SSH1','C','bancamia',null,null,null,null,null,null,'CRE')
insert into cl_parametro values ('Servidor SSH Adminfo Parametro 2','SSH2','C','bancassh',null,null,null,null,null,null,'CRE')
insert into cl_parametro values ('Servidor SSH Adminfo Parametro 3','SSH3','C','190.248.12.170',null,null,null,null,null,null,'CRE')
insert into cl_parametro values ('Servidor SSH Adminfo Parametro 4 Host Key','SSH4','C','ssh-rsa 2048 1c:9a:55:c5:ff:07',null,null,null,null,null,null,'CRE')
insert into cl_parametro values ('Servidor SSH Adminfo Parametro 5 Host Key','SSH5','C',':f9:d6:00:be:c7:75:86:fc:5e:52',null,null,null,null,null,null,'CRE')
insert into cl_parametro values ('CODIGO DEL CARGO ENCARGADO OFICINA OPI','ENCOPI','S',null,null,1607,null,null,null,null,'CRE')
insert into cl_parametro values ('LIMITE GRUPO ICE','LIMICE','T',null,30,null,null,null,null,null,'CRE')
insert into cl_parametro values ('LIMITE DE CREDITO / CAPITAL AJUSTADO','LPTMAX','F',null,null,null,null,null,null,20,'CRE')
insert into cl_parametro values ('MONTO CAPITAL AJUSTADO','PTI','M',null,null,null,null,5000000.00,null,null,'CRE')
insert into cl_parametro values ('OBLIGATORIEDAD FAG OBLFAG', 'OBLFAG', 'C', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cobis..cl_parametro values ('MONTO SALARIO VALIDACION GARANTIA ESPECIAL','SALMIN','M',null,null,null,null,644350.00,null,null,'CRE')
insert into cl_parametro values ('VALOR DE AHORRO VOLUNTARIO', 'VAHVO', 'I', NULL, NULL, NULL, 10, NULL, NULL, NULL,'CRE')
--Parámetros Variables Grupo Solidario
insert into cl_parametro values ('DIAS ATRASO GRUPAL CICLO ANTERIOR', 'DAGCA', 'I', NULL, NULL, NULL, 1, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values ('DIAS ATRASO GRUPAL CICLOS ANTERIORES', 'DAGCAS', 'I', NULL, NULL, NULL, 2, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('CODIGO RELACION CONYUGE','RCONY','I',NULL,NULL,NULL,209,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('CONYUGE', 'COU', 'T', NULL, 209, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('FRECUENCIA EN MESES', 'PFRMES', 'C', 'M', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('RESULTADO VER DATOS GRP','RVDGR' , 'T',NULL, 10, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('RESULTADO VER DATOS IND','RVDIN' , 'T',NULL, 7, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro(pa_parametro, pa_nemonico, pa_tipo, pa_char,pa_producto)
values('RPT CFDI ESTADO DE CUENTA - CAMPO RI EMISOR','RIEMIS','C','000000000000','CRE')
--Parametros Varable Crediticia
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NUM DIAS CUENTAS ABIERTAS', 'NDCCAB', 'I', NULL, NULL, NULL, 90, NULL, NULL, NULL, 'CRE')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NUM DIAS CUENTAS CERRADAS', 'NDCCCE', 'I', NULL, NULL, NULL, 360, NULL, NULL, NULL, 'CRE')
--Para reportes Ini
insert into cl_parametro values('REPORTE SOLIC CREDITO INCLUSION NOMBRE FINANCIERA UNO', 'NF1CCI', 'C', 'Norma Angélica Castro Reyes', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE SOLIC CREDITO INCLUSION NOMBRE FINANCIERA DOS', 'NF2CCI', 'C', 'Hugo Suastegui Cervantes', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE SOLIC CREDITO INCLUSION NOMBRE BANCO DOS', 'NB1CCI', 'C', 'Didier Mena Campos', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE SOLIC CREDITO INCLUSION NOMBRE BANCO DOS', 'NB2CCI', 'C', 'Octavio Fraga Medina', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('NUMERO REGISTRO REPORT CONTRA CREDITO INCLUSION', 'NRGCCI', 'C', '14795-439-028351/01-06036-1117', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('LUGAR PAGO REPORT CONTRA CREDITO INCLUSION 1', 'LPGCC1', 'C', 'Avenida Prolongación Paseo', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('LUGAR PAGO REPORT CONTRA CREDITO INCLUSION 2', 'LPGCC2', 'C', 'de la Reforma No 500 PB,', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('LUGAR PAGO REPORT CONTRA CREDITO INCLUSION 3', 'LPGCC3', 'C', 'Col. Lomas de Santa Fe,', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('LUGAR PAGO REPORT CONTRA CREDITO INCLUSION 4', 'LPGCC4', 'C', 'Delegación Álvaro Obregón,', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('LUGAR PAGO REPORT CONTRA CREDITO INCLUSION 5', 'LPGCC5', 'C', 'C.P. 01219,', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('LUGAR PAGO REPORT CONTRA CREDITO INCLUSION 6', 'LPGCC6', 'C', 'Ciudad de México', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE DATO RECA', 'RDRECA', 'C', '14795-439-028351/03-00011-0123', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE PIE CREDITO INDIVIDUAL', 'REPCRI', 'C', 'JUR-970 (112021)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE PIE SOLICITUD CREDITO INDIVIDUAL', 'RPSCRI', 'C', 'IF-038 (112021)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE DATO RECA OPERACION SIN GRACIA', 'RECASG', 'C', '14795-439-028351/03-00011-0123', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE CARATULA GRUPAL ASEGURADORA', 'RCGASE', 'C', 'ASSURANT VIDA MÉXICO, S.A.', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE CARATULA GRUPAL SEGURO1', 'RCGSG1', 'C', 'Seguro de Vida + ', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('REPORTE CARATULA GRUPAL SEGURO2', 'RCGSG2', 'C', 'Enfermedades Graves', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values('GERENTE AGENCIA', 'PGEREA', 'C', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cobis..cl_parametro(pa_parametro, pa_nemonico, pa_tipo, pa_smallint,pa_producto) values ('B2C DIAS VIGENCIA REGISTRO ', 'B2CDVR', 'S', 1, 'CRE')
go
--Para reportes Fin
go

delete from cobis..cl_parametro where pa_nemonico in ('RES', 'REN', 'EMP', 'BCAL', 'MCAL') and pa_producto = 'REC'

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto) 
values('CALIFICACION POR RESTRUCTURACION', 'RES', 'C', 'RES', NULL, NULL, NULL, NULL, NULL, NULL, 'REC')
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto) 
values('CALIFICACION POR RENOVACION', 'REN', 'C', 'REN', NULL, NULL, NULL, NULL, NULL, NULL, 'REC')
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto) 
values('CALIFICACION CLIENTE EMPROBLEMADO', 'EMP', 'C', 'EMP', NULL, NULL, NULL, NULL, NULL, NULL, 'REC')
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto) 
values('BUENA CALIFICACION', 'BCAL', 'C', 'A', NULL, NULL, NULL, NULL, NULL, NULL, 'REC')
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto) 
values('MALA CALIFICACION', 'MCAL', 'C', 'B', NULL, NULL, NULL, NULL, NULL, NULL, 'REC')
go
--Parametros para workflow
insert into  cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('Meses de vigencia del Cuestionario del cliente', 'MESVCC', 'T', null, 6, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('Porcentaje Patrimonio', 'PORPAT', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 30.0, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('Patrimonio Técnico Institucional', 'PATTI', 'M', 'NULL', NULL, NULL, NULL, 100000000, NULL, NULL, 'CRE')
go

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE APODERADO SOFOM','NASOF','C','Alberto Ruiz',null,null,null,null,null,null,'CRE')

go
if not exists (select 1 from cobis..cl_parametro WHERE pa_nemonico = 'OFIAPP' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_smallint, pa_producto)
    values ('OFICINA DEFECTO MOVIL','OFIAPP','S',9001, 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_smallint = 9001
    WHERE pa_nemonico = 'OFIAPP' and pa_producto = 'CRE'
go


delete from cobis..cl_parametro where pa_nemonico in ('URLSAN', 'IDCSAN', 'SECSAN', 'SIMSAN') and pa_producto = 'CRE'

--Parametros para integracion santander

--parametro URL  --
if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'URLSA1' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_char = 'https://tibimodal.'
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'URLSA1'
end
else
BEGIN

INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('URL Santander', 'URLSA1', 'C', 'https://tibimodal.', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

END

if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'URLSA2' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_char = 'mx.corp/'
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'URLSA2'
end
else
BEGIN

INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('URL Santander2', 'URLSA2', 'C', 'mx.corp/', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

END


if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'URLSA3' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_char = 'cobis'
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'URLSA3'
end
else
BEGIN
INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('URL Santander3', 'URLSA3', 'C', 'cobis', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
END

--parametro  IDCSAN para conexión de la Orquestacion --

if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'IDCSA1' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_char = '5373cdb8-0bce-4ffb-9998-5ddff3'
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'IDCSA1'
end
else
BEGIN
INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('Santander Cliente id ', 'IDCSA1', 'C', '5373cdb8-0bce-4ffb-9998-5ddff3', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
END

if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'IDCSA2' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_char = '8671a8'
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'IDCSA2'
end
else
BEGIN
INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('Santander Cliente id1 ', 'IDCSA2', 'C', '8671a8', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
END
-- cliente id secreto para conexión de la Orquestacion

if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'SECSAN' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_char = ';13aFA7s8ocrrG*fhi>1,{eA>JPOvd'
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'SECSAN'
end
else
BEGIN
INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('Santander secreto del cliente', 'SECSAN', 'C', ';13aFA7s8ocrrG*fhi>1,{eA>JPOvd', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
END

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('Simular integracion santader','SIMSAN','I', null,null,null,0,null,null,null,'CRE')

INSERT INTO cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('PORCENTAJE DE MONTO GRUPAL', 'PMMGR', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 30, 'CRE')

go


delete cobis..cl_parametro
where pa_nemonico in('PAHO')
  and pa_producto = 'CRE'
go

insert into cobis..cl_parametro (
pa_parametro,     pa_nemonico,     pa_tipo,        pa_char,       pa_tinyint,     pa_smallint,    pa_int,      pa_money,    pa_datetime,    pa_float,       pa_producto)
values(
'PORCENTAJE AHORRO CREDITOS GRUPALES','PAHO',          'F',            null,          null,           null,             null,        null,        null,           10.00,           'CRE')
go


 
PRINT '<<<<< INFORMACION DE BURO DE CREDITO" >>>>>'
PRINT '==========================================='
PRINT '<<<<< PARAMETRO "BURO DE CREDITO VERSION" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCVR' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO VERSION','BCVR','C', '13', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '13'
    WHERE pa_nemonico = 'BCVR' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO NUMERO DE REFERENCIA OPERADOR" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCNO' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO NUMERO DE REFERENCIA OPERADOR','BCNO','C', '                         ', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '                         '
    WHERE pa_nemonico = 'BCNO' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO PRODUCTO REQUERIDO" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCPR' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO PRODUCTO REQUERIDO','BCPR','C', '548', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '548'
    WHERE pa_nemonico = 'BCPR' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO CLAVE PAIS" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCCP' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO CLAVE PAIS','BCCP','C', 'MX', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = 'MX'
    WHERE pa_nemonico = 'BCCP' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO CLAVE USUARIO" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCCU' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO CLAVE USUARIO','BCCU','C', 'ZM11001029', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = 'ZM11001029'
    WHERE pa_nemonico = 'BCCU' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO PASSWORD" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCPW' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO PASSWORD','BCPW','C', '7w8ic2ZF', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '7w8ic2ZF'
    WHERE pa_nemonico = 'BCPW' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO TIPO CONSULTA" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCTQ' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO TIPO CONSULTA','BCTQ','C', 'I', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = 'I'
    WHERE pa_nemonico = 'BCTQ' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO TIPO CONTRATO" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCTC' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO TIPO CONTRATO','BCTC','C', 'SE', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = 'SE'
    WHERE pa_nemonico = 'BCTC' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO CLAVE UNIDAD MONETARIA" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCUM' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO CLAVE UNIDAD MONETARIA','BCUM','C', 'MX', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = 'MX'
    WHERE pa_nemonico = 'BCUM' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO IMPORTE CONTRATO" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCIC' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO IMPORTE CONTRATO','BCIC','C', '000000000', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '000000000'
    WHERE pa_nemonico = 'BCIC' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO IDIOMA" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCID' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO IDIOMA','BCID','C','SP', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = 'SP'
    WHERE pa_nemonico = 'BCID' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO TIPO SALIDA" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCTS' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO TIPO SALIDA','BCTS','C', '01', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '01'
    WHERE pa_nemonico = 'BCTS' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO PARAMETRO CADUCIDAD" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCPC' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_int, pa_producto)
    values ('BURO DE CREDITO PARAMETRO CADUCIDAD','BCPC','I', 60, 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'I', pa_int = 60
    WHERE pa_nemonico = 'BCPC' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO IP" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCIP' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO IP','BCIP','C', '128.9.55.102', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '128.9.55.102'
    WHERE pa_nemonico = 'BCIP' and pa_producto = 'CRE'

PRINT '<<<<< PARAMETRO "BURO DE CREDITO PUERTO" >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'BCPO' and pa_producto = 'CRE')
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
    values ('BURO DE CREDITO PUERTO','BCPO','C', '45000', 'CRE')
else
    UPDATE cobis..cl_parametro SET pa_tipo = 'C', pa_char = '45000'
    WHERE pa_nemonico = 'BCPO' and pa_producto = 'CRE'

PRINT '<<<<< OBTENER BURO DE CREDITO DESDE SERVICIO >>>>>'
if not exists (select * from cobis..cl_parametro WHERE pa_nemonico = 'OBCDS' and pa_producto = 'CRE')    
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_int, pa_producto)
    values ('OBTENER BURO DE CREDITO DESDE SERVICIO','OBCDS','I', 1, 'CRE')

else
    UPDATE cobis..cl_parametro SET pa_tipo = 'I', pa_int = 1
    WHERE pa_nemonico = 'OBCDS' and pa_producto = 'CRE'
GO

PRINT '<<<<< VALIDACION DE PARAMETROS DE INTEGRANTES" >>>>>'	
---validacion de parentesco
if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'PPGRU' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_float = 40
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'PPGRU'
end
else
begin
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
    VALUES ('PORCENTAJE DE PARENTESCO', 'PPGRU', 'F', NULL, NULL, NULL,NULL, NULL, NULL,40, 'CRE')
END
---VALIDACION DE CONYUGE--
if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'RCONY' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_int=209
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'RCONY'
end
else
begin
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
    VALUES ('CODIGO RELACION CONYUGE', 'RCONY', 'I', NULL, NULL, NULL,209, NULL, NULL,NULL, 'CRE')
END

---VALIDACION DE MUJERES--
if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'PMGRU' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_float=80
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'PMGRU'
end
else
begin
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
    VALUES ('PORCENTAJE DE MUJERES', 'PMGRU', 'F', NULL, NULL, NULL,NULL, NULL, NULL,80, 'CRE')
END	
--parametro para numero  de emprendedores --
if exists (SELECT 1 FROM cobis..cl_parametro WHERE pa_nemonico = 'MAXEMP' AND pa_producto = 'CRE')
begin
    UPDATE cobis..cl_parametro 
    SET pa_float =20
    WHERE pa_producto = 'CRE'
    AND pa_nemonico = 'MAXEMP'
end
else
begin
    INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
    VALUES ('PORCENTAJE EMPRENDEDORES', 'MAXEMP', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 20, 'CRE')
END


/*** PAGOS REFERENCIADOS ***/

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
VALUES ('PAGO REFERENCIADO - GARANTIA', 'PRGRNT', 'C', '65506362002', 'CRE')

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
VALUES ('PAGO REFERENCIADO - CREDITO', 'PRCRDT', 'C', '65506362155', 'CRE')


/*** SOLICITUD GRUPAL E INDIVIDUAL ***/
INSERT INTO dbo.cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('WORKFLOW SOLICITUD CREDITO INDIVIDUAL PARTE 2', 'WSCIN2', 'C', 'SANTANDER', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO dbo.cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('WORKFLOW SOLICITUD CREDITO INDIVIDUAL PARTE 1', 'WSCIN1', 'C', 'SOLICITUD CREDITO INDIVIDUAL ', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO dbo.cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('WORKFLOW SOLICITUD CREDITO GRUPAL PARTE 1', 'WSCGR1', 'C', 'SOLICITUD CREDITO GRUPAL ', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO dbo.cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('WORKFLOW SOLICITUD CREDITO GRUPAL PARTE 2', 'WSCGR2', 'C', 'SANTANDER', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')


/*** CRIPTOGRAFIA ***/

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
VALUES ('RUTA DE ARCHIVOS DE IEN PARA PROCESOS DE CRIPTOGRAFIA', 'CRYPFL', 'C', 'cryptography', 'CRE')

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
VALUES ('RUTA DE SOFTWARE DE CRIPTOGRAFIA', 'CRYPSW', 'C', 'c:\apicifrado\', 'CRE')

/*** LISTA NEGRA ***/

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
VALUES ('LISTA NEGRA - RUTA ARCHIVO', 'BLPATH', 'C', 'E:\LN\', 'CRE')

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto)
VALUES ('LISTA NEGRA - NOMBRE ARCHIVO', 'BLNAME', 'C', 'SofomSantander.txt', 'CRE') 

/* GRUPO PROMO */
insert into cobis..cl_parametro values ('MINIMO INTEGRANTES ENTIDAD ORIGNIAL', 'MINEO', 'T', null, 6, null, null, null, null, null, 'CRE')
insert into cobis..cl_parametro values ('MAXIMO INTEGRANTES LLEGAN FUERA', 'MAXLF', 'T', null, 2, null, null, null, null, null, 'CRE')

	
--Parametro Sandino

delete FROM  cobis..cl_parametro WHERE pa_nemonico IN('OAA') AND 
pa_producto='CWF'

INSERT INTO cobis..cl_parametro (pa_parametro,	pa_nemonico,	pa_tipo,	pa_char,	pa_tinyint,	pa_smallint,	pa_int,	pa_money,	pa_datetime,	pa_float,	pa_producto)
VALUES ('OBSERVACION AUTOMATICA ASESOR',	'OAA',  	'I',	NULL,	NULL,	NULL,	4,	NULL,	NULL,	NULL,	'CWF')

/*** ARCHIVO NEGATIVE FILE ***/
INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('PATH NEGATIVE FILE', 'PHNFDE', 'C', 'C:\NegativeFile\', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')	

/*** INGRESAR SOLICITUD INICIO USO PARA MOVIL IDENTIFICAR EN QUE ETAPA SE ENCUENTRA EL TRAMITE***/
INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('NOMBRE DE LA ETAPA DE INGRESO', 'ETINGR', 'C', 'INGRESAR SOLICITUD', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')	

/*** NOMBRE DE LA ETAPA DE ELIMINAR INICIO USO PARA MOVIL IDENTIFICAR EN QUE ETAPA SE ENCUENTRA EL TRAMITE***/
INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('NOMBRE DE LA ETAPA DE ELIMINAR', 'ETELIM', 'C', 'ELIMINAR PARTICIPANTES', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

/*** NOMBRE DE LA ETAPA DE APROBACION PRESTAMO USO PARA MOVIL IDENTIFICAR EN QUE ETAPA SE ENCUENTRA EL TRAMITE***/
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA DE APROBACION', 'ETAPRO', 'C', 'APROBAR PRÉSTAMO', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE') 	

--Parametros Estefy BURO Creacion de parametros para URL
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto) values
('URL REPORTE', 'URLREP', 'C', 'http://192.168.64.253:9090/', 'CRE')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_producto) values
('DIRECCION REPORTE', 'DIRREP', 'C', 'CTSProxy/services/cobis/web/', 'CRE')
--Parametro de hora cuando se ejecutara el job de rfc no valido de Interfactura 
INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('EJECUCION HORA JOB RFC NO VALIDO INTERFACTURA', 'JRFCNV', 'C', '8:00|14:00', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
--Parametro de hora cuando se ejecutara el job que genera el xml de rfc no valido de Interfactura 
INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('EJECUCION HORA JOB XML RFC NO VALIDO INTERFACTURA', 'JXMRNV', 'C', '14:15|15:00', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
GO

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
     VALUES ('PORCENTAJE DE PAGO GRUPO PROMO', 'POPAGP'   , 'T'    , NULL   , 40        , NULL, NULL, NULL, NULL, NULL, 'CRE')
GO

delete from cobis..cl_parametro where pa_nemonico in 
('ETACGR', 'ETARVI', 'ETACFD','ETACCB','ETABLN', 'ETACRL','ETACFC','ETAFCC','QESCOL','ESASEX', 'NICBS', 'NDCBS','ETAVDA','CLNUSG')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA APLICAR CUESTIONARIO - GRUPAL', 'ETACGR', 'C', 'APLICAR CUESTIONARIO - GRUPAL', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA REVISAR Y VALIDAR INFORMACIÓN', 'ETARVI', 'C', 'REVISAR Y VALIDAR INFORMACIÓN', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA CAPTURAR FIRMAS Y DOCUMENTOS', 'ETACFD', 'C', 'CAPTURAR FIRMAS Y DOCUMENTOS', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

-------------------------------------------
----------   COLECTIVOS -------------------
-------------------------------------------

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA CONSULTAR CUENTA Y BUC', 'ETACCB', 'C', 'CONSULTAR CUENTA Y BUC', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA CONSULTAR BURO LN Y NF', 'ETABLN', 'C', 'CONSULTAR BURO LN Y NF', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA CALCULAR CALIFICACION RIESGO Y', 'ETACRL', 'C', 'CALCULAR CALIFICACION RIESGO Y', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA CAPTURAR FIRMAS Y CUESTIONARIO', 'ETACFC', 'C', 'CAPTURAR FIRMAS Y CUESTIONARIO', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA FIRMAS Y CUESTIONARIO COLECTIVOS', 'ETAFCC', 'C', 'FIRMAS Y CUESTIONARIO', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NUMERO DE PREGUNTAS ETAPA FIRMAS Y CUESTIONARIO', 'QESCOL', 'I', null, 23, NULL, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES ('ESPERA DE ASIGNACION DE ASESOR EXTERNO', 'ESASEX', 'C', 'ESPERA DE ASIGNACION DE ASESOR', NULL, NULL, NULL, NULL, NULL, NULL, 'CCA')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NOMBRE DE LA ETAPA VERIFICAR DATOS', 'ETAVDA', 'C', 'VERIFICAR DATOS', null, null, null, 0, null, null, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NUMERO INTENTOS CUENTA BUC SANTANDER', 'NICBS', 'I', null, 4, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('NUMERO DIAS INTENTOS CUENTA BUC SANTANDER', 'NDCBS', 'I', null, 4, NULL, NULL, NULL, NULL, NULL, 'CRE')


/*se añaden debido a que no estaban en los instaladores por otro requerimeitno - se anade dos veces el mismo valor debido a que pueden cambiar los valores*/
--'
insert into cl_parametro values('FREPORTE DATO ADHESION','RDADHS','C','14795-440-033778/03-00350-0122',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('REPORTE DATO ADHESION RAYAS','RDADHR','C','14795-440-033778/03-00350-0122',NULL,NULL,NULL,NULL,NULL,NULL,'CRE')
insert into cl_parametro values('PIE PERIODO REPORTES', 'PPREPA', 'C', '(062023)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')


insert into cobis..cl_parametro values ('TIPO CONTRATO PROMO', 'TCONT', 'C', 'CS,PL', null, null, null, null, null, null, 'CRE')
insert into cobis..cl_parametro values ('TIPO CUENTA PROMO', 'TICTA', 'C', 'I', null, null, null, null, null, null, 'CRE')
insert into cobis..cl_parametro values ('TIPO RESPONSABILIDAD PROMO', 'TRESP', 'C', 'I,J', null, null, null, null, null, null, 'CRE')
insert into cobis..cl_parametro values ('FRECUENCIA PAGO PROMO', 'FRCPG', 'C', 'W,K,M', null, null, null, null, null, null, 'CRE')
go

--Parametro  para eliminacion de integrantes del grupo  con creditos  vigentes
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('ELIMINAR INTEGRANTES CREDITO VIGENTE', 'EICRVI', 'I', NULL, NULL, NULL, 30, NULL, NULL, NULL, 'CRE')

/*Parametro para activar o desactivar para que se muestre o no el registro del Formato de DOMICILIACION*/
insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('ACTIVAR DOCUMENTO DOMICILIACION S/N', 'ADODOM', 'C', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('CLIENTES NUEVOS EN SOLICITUD GRUPAL', 'CLNUSG', 'C', 'S', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

delete from cl_parametro where pa_nemonico='CA3DR'

insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char,pa_producto)
values('CLIENTE CON A3 DR','CA3DR','C','A3 DR','CLI')
go

delete from cl_parametro where pa_nemonico in ('RGASE1', 'RGASE2')

INSERT INTO cobis..cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('REPORTE CARATULA GRUPAL ASEGURADORA 1', 'RGASE1', 'C', 'Zúrich Santander Seguros', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO cobis..cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES
('REPORTE CARATULA GRUPAL ASEGURADORA 2', 'RGASE2', 'C', ' México, S.A.', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

------------------------------INGRESO DE PARAMETRO para obtener informacion de historicos para el reporte de Buro, casos especiales bajo listado
delete cobis..cl_parametro where pa_nemonico = 'AHURO' and pa_producto = 'CRE'
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('ACTIVAR BURO HISTORICOS', 'AHURO', 'C', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

delete cobis..cl_parametro where pa_nemonico = 'CLGRRP' and pa_producto = 'CRE'
insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('PARAMETROS GENERAR REPORTE BURO', 'CLGRRP', 'C', '101038,1862006235', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
go

--PARÁMETROS FLUJO DE RENOVACIÓN
use cobis
go

--PARÁMETROS FLUJO DE RENOVACIÓN
delete from cl_parametro where pa_nemonico in ('PTRREN','PCAREN', 'ATMREN','ATAREN','CICREN', 'RDTGRP', 'PORREN', 'MNPRTG' , 'RNRECA', 'PPREPR', 'PPREPC', 'WSCRN1','WSCRN2','TTPREN')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('PORCENTAJE DE PLAZO TRANSCURRIDO DE RENOVACION', 'PTRREN', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 80, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('PORCENTAJE DE CAPITAL DE RENOVACION', 'PCAREN', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 60, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('ATRASO MAXIMO DE RENOVACION', 'ATMREN', 'I', NULL, NULL, 30, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('ATRASO ACTUAL DE RENOVACION', 'ATAREN', 'I', NULL, NULL, 0, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('CICLO DE RENOVACION', 'CICREN', 'I', NULL, NULL, 4, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('REDUCCION TASA GRUPAL RENOVACION', 'RDTGRP', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 3.0, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('PORCENTAJE REINGRESO RENOVACION', 'PORREN', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 20, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('TIEMPO TRANSCURRIDO RENOVACION', 'TTPREN', 'I', NULL, NULL, NULL, 12, NULL, NULL, NULL, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('MINIMO PORCENTAJE TASA GRUPAL', 'MNPRTG', 'F', NULL, NULL, NULL, NULL, NULL, NULL, 70, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('WORKFLOW SOLICITUD CREDITO RENOVACION PARTE 1', 'WSCRN1', 'C', 'SOLICITUD CREDITO GRUPAL', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

INSERT INTO cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
VALUES 
('WORKFLOW SOLICITUD CREDITO RENOVACION PARTE 2', 'WSCRN2', 'C', ' - RENOVACIÓN', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

go


--OFERTA PRODUCTO 140073--

delete from cl_parametro where pa_nemonico in ( 'OFEPRO', 'RGASE1', 'RGASE2', 'RECASG')

insert into cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values 
('OFERTA PRODUCTO', 'OFEPRO', 'C', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values 
('REPORTE CARATULA GRUPAL ASEGURADORA 1', 'RGASE1', 'C', 'ZURICH SANTANDER SEGUROS', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values 
('REPORTE CARATULA GRUPAL ASEGURADORA 2', 'RGASE2', 'C', ' MEXICO, S.A.', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cl_parametro
(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values 
('REPORTE DATO RECA OP SIN GRACIA', 'RECASG', 'C', '14795-439-028351/02-00343-0119', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

--Reporte renovaciones
insert into cl_parametro values ('REPORTE DATO RECA RENOVACION', 'RNRECA', 'C', '14795-439-034275/01-00897-0321', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values ('PIE PERIODO RENOVACIONES CONTRATO', 'PPREPC', 'C', 'JUR-963-(062021)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cl_parametro values ('PIE PERIODO RENOVACIONES', 'PPREPR', 'C', '-(062021)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

insert into cobis..cl_parametro (pa_parametro, pa_nemonico, pa_tipo,  pa_tinyint,  pa_producto)
values ('NUMERO MESES DE VIGENCIA DE REGISTROS', 'NMVIGR', 'T', 2,   'CRE')

--REQ 162288 Cambios Simple F1
insert into cl_parametro values ('FRECUENCIA PLAZO DEFECTO INDIVIDUAL', 'FPDIND', 'C', 'W;16', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

--ERR 171995 - Documento de Seguros sin informacion ID Grupo= 22513
insert into cl_parametro values ('VALIDA VALOR MONTO DEL SEGURO', 'SEVIDV', 'C', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')


--Reportes AutoOnboarding -Req.168293
delete from cobis..cl_parametro where pa_nemonico in ('CRSIAO', 'PRSIAO', 'PCTSIO')
insert into cobis..cl_parametro values ('CONDUSEF REPORTE SIMPLE INDIVIDUAL AUTO-ONBOARDING', 'CRSIAO', 'C', '14795-439-034696/02-00349-0122', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cobis..cl_parametro values ('PIE REPORTE SIMPLE INDIVIDUAL AUTO-ONBOARDING', 'PRSIAO', 'C', 'IF-041 (032022)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
insert into cobis..cl_parametro values ('PIE CONTRATO TAB-AMORT REPORTE SIMPLE INDIVIDUAL AUTO-ONBOARDING', 'PCTSIO', 'C', 'IF-038 (032022)', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

go

-- ONBOARDING REQUERIMIENTO 168293
delete cl_parametro where pa_nemonico = 'WSOBOA'
insert into cl_parametro(pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto)
values ('WORKFLOW SOLICITUD ONBOARDING', 'WSOBOA', 'C', 'SOLICITUD ONBOARDING', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')

go

--ACTIVAR VALIDACION SIGUIENTE ETAPA BIO
insert into cl_parametro (pa_parametro, pa_nemonico, pa_tipo, pa_char, pa_tinyint, pa_smallint, pa_int, pa_money, pa_datetime, pa_float, pa_producto) 
values ('ACTIVAR VALIDACION SIGUIENTE ETAPA BIO', 'AVUSEB', 'C', 'S', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
go

-- PARAMETRO REPORTE SOLICITUD PRELLENADA NOMBRE 1
delete cl_parametro where pa_nemonico = 'NRSPN1'
insert into cl_parametro values('REPORTE SOLIC PRELLENADA NOMBRE 1', 'NRSPN1', 'C', 'Hugo Suastegui Cervantes', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
go

-- PARAMETRO REPORTE SOLICITUD PRELLENADA NOMBRE 2'
delete cl_parametro where pa_nemonico = 'NRSPN2'
insert into cl_parametro values('REPORTE SOLIC PRELLENADA NOMBRE 2', 'NRSPN2', 'C', 'Norma Angelica Castro Reyes', NULL, NULL, NULL, NULL, NULL, NULL, 'CRE')
go

INSERT INTO cobis..cl_parametro (pa_parametro,pa_nemonico,pa_tipo,pa_char,pa_tinyint,pa_smallint,pa_int,pa_money,pa_datetime,pa_float,pa_producto) 
VALUES('CANTIDAD DOCUMENTOS GENERADOS','CDOGEN','T',null,4,null,null,null,null,null,'CRE')

go

--Caso#200142 Aplicaci+on Cuestionario
insert into cl_parametro values ('CODIGO ROL COORDINADOR WORKFLOW', 'CDWCOO', 'I', NULL, NULL, NULL, 4, NULL, NULL, NULL, 'CRE')
go
