
    #region Copyright © 2010 COBIS Corporation.
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/
    #endregion
    using System.Runtime.Serialization;
using COBISCorp.eCOBIS.Commons.DataBinding;
using System.Collections.Generic;
using System.Collections;
using System;
using COBISCorp.eCOBIS.Commons.BLI.DTO;
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://cobiscorp.ecobis.admin.ctascteaho.dto", ClrNamespace="cobiscorp.ecobis.admin.ctascteaho.dto")]

namespace COBISCorp.eCOBIS.Admin.CtasCteAho.DTO
{
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")] 
  [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://cobiscorp.ecobis.admin.ctascteaho.dto")]
[Serializable]
  public partial class Movimiento: ICloneable
    
 {
  public Movimiento(){
}
  private string fecha;
  private string causa;
  private int oficina;
  private string correccion;
  private string descripcion;
  private string signo;
  private double valor;
  private string terminal;
  private double saldoContable;
  private double saldoDisponible;
  private double interes;
  private string ssnBranch;
  private string codAlterno;
  private string serial;
  private string usuario;
  private string hora;
  private string secuencial;
  private double valorComision;
  private double montoImp;
 [System.Runtime.Serialization.DataMemberAttribute(Name = "fecha", IsRequired = true, Order =0)] 
  public string  Fecha
   {
    get
     {
          return this.fecha;
   }
    set
     {
          this.fecha=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "causa", IsRequired = true, Order =0)] 
  public string  Causa
   {
    get
     {
          return this.causa;
   }
    set
     {
          this.causa=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "oficina", IsRequired = true, Order =0)] 
  public int  Oficina
   {
    get
     {
          return this.oficina;
   }
    set
     {
          this.oficina=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "correccion", IsRequired = true, Order =0)] 
  public string  Correccion
   {
    get
     {
          return this.correccion;
   }
    set
     {
          this.correccion=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "descripcion", IsRequired = true, Order =0)] 
  public string  Descripcion
   {
    get
     {
          return this.descripcion;
   }
    set
     {
          this.descripcion=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "signo", IsRequired = true, Order =0)] 
  public string  Signo
   {
    get
     {
          return this.signo;
   }
    set
     {
          this.signo=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "valor", IsRequired = true, Order =0)] 
  public double  Valor
   {
    get
     {
          return this.valor;
   }
    set
     {
          this.valor=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "terminal", IsRequired = true, Order =0)] 
  public string  Terminal
   {
    get
     {
          return this.terminal;
   }
    set
     {
          this.terminal=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "saldoContable", IsRequired = true, Order =0)] 
  public double  SaldoContable
   {
    get
     {
          return this.saldoContable;
   }
    set
     {
          this.saldoContable=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "saldoDisponible", IsRequired = true, Order =0)] 
  public double  SaldoDisponible
   {
    get
     {
          return this.saldoDisponible;
   }
    set
     {
          this.saldoDisponible=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "interes", IsRequired = true, Order =0)] 
  public double  Interes
   {
    get
     {
          return this.interes;
   }
    set
     {
          this.interes=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "ssnBranch", IsRequired = true, Order =0)] 
  public string  SsnBranch
   {
    get
     {
          return this.ssnBranch;
   }
    set
     {
          this.ssnBranch=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "codAlterno", IsRequired = true, Order =0)] 
  public string  CodAlterno
   {
    get
     {
          return this.codAlterno;
   }
    set
     {
          this.codAlterno=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "serial", IsRequired = true, Order =0)] 
  public string  Serial
   {
    get
     {
          return this.serial;
   }
    set
     {
          this.serial=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "usuario", IsRequired = true, Order =0)] 
  public string  Usuario
   {
    get
     {
          return this.usuario;
   }
    set
     {
          this.usuario=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "hora", IsRequired = true, Order =0)] 
  public string  Hora
   {
    get
     {
          return this.hora;
   }
    set
     {
          this.hora=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "secuencial", IsRequired = true, Order =0)] 
  public string  Secuencial
   {
    get
     {
          return this.secuencial;
   }
    set
     {
          this.secuencial=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "valorComision", IsRequired = true, Order =0)] 
  public double  ValorComision
   {
    get
     {
          return this.valorComision;
   }
    set
     {
          this.valorComision=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "montoImp", IsRequired = true, Order =0)] 
  public double  MontoImp
   {
    get
     {
          return this.montoImp;
   }
    set
     {
          this.montoImp=value;
   }

 }

    #region ICloneable Members

    public object Clone()
    {
    return this.MemberwiseClone();
    }

    #endregion
    
 }
}