
    #region Copyright © 2010 COBIS Corporation.
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/
    #endregion
    using System.Runtime.Serialization;
using COBISCorp.eCOBIS.Commons.DataBinding;
using System.Collections.Generic;
using System.Collections;
using System;
using COBISCorp.eCOBIS.Commons.BLI.DTO;
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://cobiscorp.ecobis.admin.ctascteaho.dto", ClrNamespace="cobiscorp.ecobis.admin.ctascteaho.dto")]

namespace COBISCorp.eCOBIS.Admin.CtasCteAho.DTO
{
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")] 
  [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://cobiscorp.ecobis.admin.ctascteaho.dto")]
[Serializable]
  public partial class QueryVacio: ICloneable
    
 {
  public QueryVacio(){
}
  private string vacioS;
  private int vacioI;
  private double vacioD;
 [System.Runtime.Serialization.DataMemberAttribute(Name = "vacioS", IsRequired = true, Order =0)] 
  public string  VacioS
   {
    get
     {
          return this.vacioS;
   }
    set
     {
          this.vacioS=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "vacioI", IsRequired = true, Order =0)] 
  public int  VacioI
   {
    get
     {
          return this.vacioI;
   }
    set
     {
          this.vacioI=value;
   }

 }
 [System.Runtime.Serialization.DataMemberAttribute(Name = "vacioD", IsRequired = true, Order =0)] 
  public double  VacioD
   {
    get
     {
          return this.vacioD;
   }
    set
     {
          this.vacioD=value;
   }

 }

    #region ICloneable Members

    public object Clone()
    {
    return this.MemberwiseClone();
    }

    #endregion
    
 }
}