/************************************************************/
/*******************Service Operations Script*********************/
/************************************************************/
/*   This code was generated by CEN-SG.                     */
/*   Changes to this file may cause incorrect behavior      */
/*   and will be lost if the code is regenerated.           */
/************************************************************/

use cobis
go

declare @w_rol    int

if not exists (select 1 from cobis..ad_rol where ro_descripcion = 'MENU POR PROCESOS')
begin
	select @w_rol =  max(ro_rol)+1 from cobis..ad_rol
	insert into cobis..ad_rol (ro_rol, ro_filial, ro_descripcion, ro_fecha_crea, ro_creador, ro_estado, ro_fecha_ult_mod, ro_time_out)
	values (@w_rol, 1, 'MENU POR PROCESOS', getdate(), 1, 'V', getdate(), 9000)
end
select @w_rol = ro_rol from cobis..ad_rol where ro_descripcion = 'MENU POR PROCESOS'

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Scheduler.SrvProcessInstance.GetProcessInstanceList')
UPDATE cts_serv_catalog SET csc_class_name = 'cobiscorp.ecobis.scheduler.service.ISrvProcessInstance', csc_method_name = 'getProcessInstanceList', csc_description = '', csc_trn = 0 WHERE csc_service_id = 'Scheduler.SrvProcessInstance.GetProcessInstanceList'
ELSE
INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn, csc_procedure_validation) VALUES ('Scheduler.SrvProcessInstance.GetProcessInstanceList', 'cobiscorp.ecobis.scheduler.service.ISrvProcessInstance', 'getProcessInstanceList', '', 0, 'Y')

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Scheduler.SrvScheduler.GetSchedulerConfig')
UPDATE cts_serv_catalog SET csc_class_name = 'cobiscorp.ecobis.scheduler.service.ISrvScheduler', csc_method_name = 'getSchedulerConfig', csc_description = '', csc_trn = 0 WHERE csc_service_id = 'Scheduler.SrvScheduler.GetSchedulerConfig'
ELSE
INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn, csc_procedure_validation) VALUES ('Scheduler.SrvScheduler.GetSchedulerConfig', 'cobiscorp.ecobis.scheduler.service.ISrvScheduler', 'getSchedulerConfig', '', 0, 'Y')

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Scheduler.SrvScheduler.GetSchedulerJobs')
UPDATE cts_serv_catalog SET csc_class_name = 'cobiscorp.ecobis.scheduler.service.ISrvScheduler', csc_method_name = 'getSchedulerJobs', csc_description = '', csc_trn = 0 WHERE csc_service_id = 'Scheduler.SrvScheduler.GetSchedulerJobs'
ELSE
INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn, csc_procedure_validation) VALUES ('Scheduler.SrvScheduler.GetSchedulerJobs', 'cobiscorp.ecobis.scheduler.service.ISrvScheduler', 'getSchedulerJobs', '', 0, 'Y')

IF EXISTS (SELECT * FROM cts_serv_catalog WHERE csc_service_id = 'Scheduler.SrvProcessInstance.GetProcessAlert')
UPDATE cts_serv_catalog SET csc_class_name = 'cobiscorp.ecobis.scheduler.service.ISrvProcessInstance', csc_method_name = 'getProcessAlert', csc_description = '', csc_trn = 0 WHERE csc_service_id = 'Scheduler.SrvProcessInstance.GetProcessAlert'
ELSE
INSERT INTO cts_serv_catalog (csc_service_id, csc_class_name, csc_method_name, csc_description, csc_trn, csc_procedure_validation) VALUES ('Scheduler.SrvProcessInstance.GetProcessAlert', 'cobiscorp.ecobis.scheduler.service.ISrvProcessInstance', 'getProcessAlert', '', 0, 'Y')

if not exists (select 1 from ad_servicio_autorizado where ts_servicio = 'Scheduler.SrvProcessInstance.GetProcessAlert')
insert into ad_servicio_autorizado (ts_servicio,ts_rol,ts_producto,ts_tipo,ts_moneda,ts_fecha_aut,ts_estado,ts_fecha_ult_mod) values('Scheduler.SrvProcessInstance.GetProcessAlert',@w_rol,1,'R',0,getdate(),'V',getdate())

if not exists (select 1 from ad_servicio_autorizado where ts_servicio = 'Scheduler.SrvProcessInstance.GetProcessInstanceList')
insert into ad_servicio_autorizado (ts_servicio,ts_rol,ts_producto,ts_tipo,ts_moneda,ts_fecha_aut,ts_estado,ts_fecha_ult_mod) values('Scheduler.SrvProcessInstance.GetProcessInstanceList',@w_rol,1,'R', 0,getdate(),'V',getdate())

if not exists (select 1 from ad_servicio_autorizado where ts_servicio = 'Scheduler.SrvScheduler.GetSchedulerConfig')
insert into ad_servicio_autorizado (ts_servicio,ts_rol,ts_producto,ts_tipo,ts_moneda,ts_fecha_aut,ts_estado,ts_fecha_ult_mod) values('Scheduler.SrvScheduler.GetSchedulerConfig',@w_rol,1,'R', 0,getdate(),'V',getdate())

if not exists (select 1 from ad_servicio_autorizado where ts_servicio = 'Scheduler.SrvScheduler.GetSchedulerJobs')
insert into ad_servicio_autorizado (ts_servicio,ts_rol,ts_producto,ts_tipo,ts_moneda,ts_fecha_aut,ts_estado,ts_fecha_ult_mod) values('Scheduler.SrvScheduler.GetSchedulerJobs',@w_rol,1,'R', 0,getdate(),'V',getdate())

go
