use cob_fpm
go
delete from fp_productauthorization where bp_product_idfk ='CRE'
delete from fp_productauthorization where bp_product_idfk ='LIQ'
delete from fp_productauthorization where bp_product_idfk ='CCI'
delete from fp_productauthorization where bp_product_idfk ='CCD'
delete from fp_productauthorization where bp_product_idfk ='STB'
delete from fp_productauthorization where bp_product_idfk ='GRB'
delete from fp_productauthorization where bp_product_idfk ='GRA'
delete from fp_productauthorization where bp_product_idfk ='AVB'
delete from fp_productauthorization where bp_product_idfk ='AVE'
delete from fp_productauthorization where bp_product_idfk ='CCE'
delete from fp_productauthorization where bp_product_idfk ='CTE'
delete from fp_productauthorization where bp_product_idfk ='CRECON'
delete from fp_productauthorization where bp_product_idfk ='CREAUT'
delete from fp_productauthorization where bp_product_idfk ='CRECOM'
delete from fp_productauthorization where bp_product_idfk ='TARCRE'
delete from fp_productauthorization where bp_product_idfk ='MICROC'
delete from fp_productauthorization where bp_product_idfk ='CREDAUT'
delete from fp_productauthorization where bp_product_idfk ='PERS'
delete from fp_productauthorization where bp_product_idfk ='AHORRO'
delete from fp_productauthorization where bp_product_idfk ='CREDVIV'
delete from fp_productauthorization where bp_product_idfk ='CREDUE'
delete from fp_productauthorization where bp_product_idfk ='CREDSEM'
delete from fp_productauthorization where bp_product_idfk ='DPF'
delete from fp_productauthorization where bp_product_idfk ='VIVOTRAS'
delete from fp_productauthorization where bp_product_idfk ='VIVSOCIAL'
delete from fp_productauthorization where bp_product_idfk ='AVAL'
delete from fp_productauthorization where bp_product_idfk ='HIP'
delete from fp_productauthorization where bp_product_idfk ='PRUEBACRE'
delete from fp_productauthorization where bp_product_idfk ='CRECON1'
delete from fp_productauthorization where bp_product_idfk ='CREVIV'
delete from fp_productauthorization where bp_product_idfk ='CREDCAR'
delete from fp_productauthorization where bp_product_idfk ='PREN'
delete from fp_productauthorization where bp_product_idfk ='PERSONAL'
delete from fp_productauthorization where bp_product_idfk ='VEHICULO'
delete from fp_productauthorization where bp_product_idfk ='PAGARE'
go
