use cob_fpm
go
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8143
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8144
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8145
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8146
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8147
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8148
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8149
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8151
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8152
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8155
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8156
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8158
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8159
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8160
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8162
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8163
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8164
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8165
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8166
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7883
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7884
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7885
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7886
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7887
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7888
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7889
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7891
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7892
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7895
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7896
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7898
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7899
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7900
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7902
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7903
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7904
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7905
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7906
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7753
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7754
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7755
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7756
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7757
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7758
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7759
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7761
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7762
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7765
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7766
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7768
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7769
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7770
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7772
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7773
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7774
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7775
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7776
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7831
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7832
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7833
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7834
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7835
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7836
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7837
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7839
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7840
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7843
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7844
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7846
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7847
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7848
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7850
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7851
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7852
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7853
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7854
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8013
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8014
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8015
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8016
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8017
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8018
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8019
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8021
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8022
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8025
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8026
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8028
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8029
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8030
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8032
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8033
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8034
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8035
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=8036
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8143
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8144
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8145
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8146
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8147
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8148
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8149
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8151
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8152
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8155
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8156
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8158
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8159
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8160
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8162
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8163
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8164
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8165
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8166
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7883
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7884
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7885
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7886
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7887
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7888
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7889
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7891
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7892
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7895
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7896
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7898
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7899
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7900
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7902
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7903
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7904
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7905
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7906
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7753
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7754
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7755
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7756
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7757
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7758
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7759
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7761
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7762
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7765
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7766
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7768
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7769
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7770
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7772
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7773
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7774
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7775
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7776
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7779
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7780
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7781
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7782
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7783
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7784
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7785
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7787
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7788
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7791
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7792
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7794
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7795
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7796
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7798
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7799
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7800
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7801
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7802
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8143
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8144
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8145
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8146
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8147
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8148
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8149
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8151
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8152
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8155
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8156
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8158
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8159
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8160
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8162
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8163
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8164
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8165
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8166
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7883
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7884
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7885
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7886
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7887
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7888
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7889
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7891
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7892
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7895
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7896
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7898
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7899
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7900
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7902
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7903
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7904
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7905
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7906
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7753
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7754
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7755
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7756
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7757
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7758
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7759
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7761
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7762
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7765
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7766
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7768
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7769
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7770
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7772
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7773
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7774
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7775
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7776
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7779
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7780
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7781
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7782
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7783
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7784
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7785
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7787
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7788
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7791
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7792
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7794
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7795
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7796
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7798
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7799
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7800
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7801
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7802
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7831
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7832
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7833
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7834
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7835
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7836
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7837
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7839
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7840
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7843
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7844
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7846
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7847
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7848
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7850
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7851
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7852
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7853
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=7854
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8013
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8014
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8015
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8016
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8017
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8018
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8019
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8021
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8022
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8025
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8026
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8028
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8029
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8030
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8032
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8033
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8034
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8035
delete from fp_itemvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=8036
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7831
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7832
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7833
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7834
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7835
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7836
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7837
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7839
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7840
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7843
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7844
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7846
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7847
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7848
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7850
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7851
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7852
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7853
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=7854
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8013
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8014
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8015
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8016
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8017
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8018
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8019
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8021
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8022
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8025
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8026
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8028
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8029
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8030
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8032
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8033
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8034
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8035
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8036
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8117
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8118
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8119
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8120
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8121
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8122
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8123
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8125
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8126
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8129
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8130
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8132
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8133
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8134
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8136
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8137
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8138
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8139
delete from fp_itemvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=8140
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8143
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8144
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8145
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8146
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8147
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8148
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8149
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8151
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8152
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8155
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8156
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8158
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8159
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8160
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8162
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8163
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8164
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8165
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8166
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8013
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8014
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8015
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8016
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8017
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8018
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8019
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8021
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8022
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8025
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8026
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8028
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8029
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8030
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8032
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8033
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8034
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8035
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8036
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8117
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8118
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8119
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8120
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8121
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8122
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8123
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8125
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8126
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8129
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8130
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8132
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8133
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8134
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8136
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8137
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8138
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8139
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=8140
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7779
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7780
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7781
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7782
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7783
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7784
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7785
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7787
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7788
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7791
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7792
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7794
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7795
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7796
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7798
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7799
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7800
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7801
delete from fp_itemvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=7802
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7883
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7884
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7885
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7886
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7887
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7888
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7889
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7891
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7892
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7895
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7896
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7898
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7899
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7900
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7902
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7903
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7904
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7905
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7906
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7753
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7754
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7755
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7756
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7757
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7758
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7759
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7761
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7762
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7765
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7766
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7768
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7769
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7770
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7772
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7773
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7774
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7775
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7776
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7779
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7780
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7781
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7782
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7783
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7784
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7785
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7787
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7788
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7791
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7792
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7794
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7795
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7796
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7798
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7799
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7800
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7801
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7802
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7831
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7832
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7833
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7834
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7835
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7836
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7837
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7839
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7840
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7843
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7844
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7846
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7847
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7848
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7850
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7851
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7852
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7853
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=7854
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8013
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8014
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8015
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8016
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8017
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8018
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8019
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8021
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8022
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8025
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8026
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8028
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8029
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8030
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8032
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8033
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8034
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8035
delete from fp_itemvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=8036
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7883
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7884
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7885
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7886
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7887
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7888
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7889
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7891
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7892
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7895
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7896
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7898
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7899
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7900
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7902
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7903
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7904
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7905
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7906
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7753
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7754
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7755
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7756
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7757
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7758
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7759
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7761
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7762
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7765
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7766
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7768
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7769
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7770
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7772
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7773
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7774
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7775
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7776
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7779
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7780
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7781
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7782
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7783
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7784
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7785
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7787
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7788
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7791
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7792
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7794
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7795
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7796
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7798
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7799
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7800
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7801
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7802
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7831
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7832
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7833
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7834
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7835
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7836
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7837
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7839
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7840
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7843
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7844
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7846
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7847
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7848
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7850
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7851
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7852
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7853
delete from fp_itemvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=7854
go
