use cob_fpm
go
delete from fp_amountitemvalues where bp_product_idfk ='CRECON1' and iaw_itemappliesway_idfk=2500 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CRECON1' and iaw_itemappliesway_idfk=2501 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CRECON1' and iaw_itemappliesway_idfk=2502 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CRECON1' and iaw_itemappliesway_idfk=2806 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CRECON1' and iaw_itemappliesway_idfk=2809 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDAUT' and iaw_itemappliesway_idfk=2428 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDAUT' and iaw_itemappliesway_idfk=2432 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDAUT' and iaw_itemappliesway_idfk=2433 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDAUT' and iaw_itemappliesway_idfk=2505 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDAUT' and iaw_itemappliesway_idfk=2507 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDAUT' and iaw_itemappliesway_idfk=2904 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDCAR' and iaw_itemappliesway_idfk=2509 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDCAR' and iaw_itemappliesway_idfk=2511 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDCAR' and iaw_itemappliesway_idfk=2513 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDCAR' and iaw_itemappliesway_idfk=2514 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDCAR' and iaw_itemappliesway_idfk=2515 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDCAR' and iaw_itemappliesway_idfk=2516 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2408 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2410 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2411 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2419 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2420 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2518 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDSEM' and iaw_itemappliesway_idfk=2810 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDUE' and iaw_itemappliesway_idfk=2700 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDUE' and iaw_itemappliesway_idfk=2800 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDUE' and iaw_itemappliesway_idfk=2802 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDUE' and iaw_itemappliesway_idfk=2803 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDUE' and iaw_itemappliesway_idfk=2804 and cp_currency_idfk='0'
delete from fp_amountitemvalues where bp_product_idfk ='CREDUE' and iaw_itemappliesway_idfk=2805 and cp_currency_idfk='0'
go
