use cob_fpm
go
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=108
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1103
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1105
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1121
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=100
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1127
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CRECOM' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='MICROC' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='PRUEBACRE' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1138
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1403
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=201
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=202
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=206
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1122
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1133
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1135
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1136
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1139
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=106
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=109
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=204
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1124
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1130
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=110
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1000
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CRECON1' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1120
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1134
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1128
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1132
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=107
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1161
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=203
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=200
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1123
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1129
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=301
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1137
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1101
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1102
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDUE' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=302
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=1131
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=212
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CREDSEM' and dc_fields_idfk=213
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=300
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=207
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=215
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=205
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=208
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=209
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=211
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=214
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1125
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDCAR' and dc_fields_idfk=1126
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=210
delete from fp_generalparametersvalues where bp_product_idfk ='CREDAUT' and dc_fields_idfk=210
go
