use cob_fpm
go
insert into fp_amountitemvalues values('CRECON1',2500,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CRECON1',2501,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CRECON1',2502,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CRECON1',2806,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CRECON1',2809,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDAUT',2428,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDAUT',2432,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDAUT',2433,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDAUT',2505,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDAUT',2507,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDAUT',2904,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDCAR',2509,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDCAR',2511,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDCAR',2513,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDCAR',2514,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDCAR',2515,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDCAR',2516,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2408,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2410,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2411,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2419,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2420,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2518,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDSEM',2810,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDUE',2700,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDUE',2800,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDUE',2802,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDUE',2803,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,null,'N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDUE',2804,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
insert into fp_amountitemvalues values('CREDUE',2805,'0',null,null,null,null,'TFIJA',null,null,0,null,0,null,0,null,null,null,0,0,null,null,null,'N',0,null,'','N',null,null,0,null,0,null,0,0,'','')
go
