use cob_fpm
go
insert into fp_dicfunctionalitygroup values(100,1,100,'PG','Parámetros Generales','Parámetros Generales','Parámetros Generales','S')
insert into fp_dicfunctionalitygroup values(200,1,100,'PG','Parámetros Generales','Tabla de Amortización','Tabla de Amortización','S')
insert into fp_dicfunctionalitygroup values(300,1,100,'PG','Parámetros Generales','Formas de Pago','Formas de Pago','S')
insert into fp_dicfunctionalitygroup values(25002,1,100,'R ','Capital','Capital','Capital','S')
insert into fp_dicfunctionalitygroup values(25102,1,100,'R ','Interes','Interes','Interés','S')
insert into fp_dicfunctionalitygroup values(25202,1,100,'R ','IVA Interes','IVA Interes','IVA Interés','S')
insert into fp_dicfunctionalitygroup values(25302,1,100,'R ','Interes Mora','Interes Mora','Interés Mora','S')
insert into fp_dicfunctionalitygroup values(25402,1,100,'R ','IVA Mora','IVA Mora','IVA Mora','S')
insert into fp_dicfunctionalitygroup values(1301,1,103,'SR','Información Adicional','Items','Items de Garantias','S')
insert into fp_dicfunctionalitygroup values(1402,1,103,'PR','Tipo de Garantia','Tipo de Garantía','Tipo de Garantía','S')
insert into fp_dicfunctionalitygroup values(25502,1,100,'R ','Comision Desembolso','Comision Desembolso','Comisión Desembolso','S')
insert into fp_dicfunctionalitygroup values(25602,1,100,'R ','IVA Comision Desembolso','IVA Comision Desembolso','IVA Comisión Desembolso','S')
insert into fp_dicfunctionalitygroup values(25702,1,100,'R ','Comision Periodica','Comision Periodica','Comisión Periodica','S')
insert into fp_dicfunctionalitygroup values(25802,1,100,'R ','IVA Comision Periodica','IVA Comision Periodica','IVA Comisión Periodica','S')
insert into fp_dicfunctionalitygroup values(25902,1,100,'R ','Gasto Desembolso','Gasto Desembolso','Gasto Desembolso','S')
insert into fp_dicfunctionalitygroup values(26002,1,100,'R ','Multa','Multa','Multa','S')
insert into fp_dicfunctionalitygroup values(26102,1,100,'R ','IVA Multa','IVA Multa','IVA Multa','S')
insert into fp_dicfunctionalitygroup values(26202,1,100,'R ','Gastos Judiciales','Gastos Judiciales','Gastos Judiciales','S')
insert into fp_dicfunctionalitygroup values(26302,1,100,'R ','Seguro Cobrado Desembolso','Seguro Cobrado Desembolso','Seguro Cobrado al Desembolso','S')
insert into fp_dicfunctionalitygroup values(26402,1,100,'R ','Seguro Periodico','Seguro Periodico','Seguro Periódico','S')
insert into fp_dicfunctionalitygroup values(26502,1,100,'R ','Honorarios Abogado','Honorarios Abogado','Honorarios Abogado','S')
insert into fp_dicfunctionalitygroup values(26602,1,100,'R ','IVA Honorarios Abogado','IVA Honorarios Abogado','IVA Honorarios Abogado','S')
insert into fp_dicfunctionalitygroup values(1000,1,103,'PG','Parámetros generales','Parámetros generales','Parámetros generales','S')
go
