use cob_fpm
go
insert into fp_diccompanyproducttype values(1,100,'PG','Parámetros Generales','Parámetros Generales',null)
insert into fp_diccompanyproducttype values(1,100,'R ','Capital','Capital','C')
insert into fp_diccompanyproducttype values(1,100,'R ','Interes','Interés','I')
insert into fp_diccompanyproducttype values(1,100,'R ','IVA Interes','IVA Interés','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Interes Mora','Interés Mora','M')
insert into fp_diccompanyproducttype values(1,100,'R ','IVA Mora','IVA Mora','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Comision Desembolso','Comisión Desembolso','V')
insert into fp_diccompanyproducttype values(1,103,'PG','Parámetros generales','Parámetros generales',null)
insert into fp_diccompanyproducttype values(1,103,'PR','Tipo de Garantia','Tipo de Garantía','A')
insert into fp_diccompanyproducttype values(1,100,'R ','IVA Comision Desembolso','IVA Comisión Desembolso','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Comision Periodica','Comisión Periodica','O')
insert into fp_diccompanyproducttype values(1,100,'R ','IVA Comision Periodica','IVA Comisión Periodica','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Gasto Desembolso','Gasto Desembolso','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Multa','Multa','O')
insert into fp_diccompanyproducttype values(1,100,'R ','IVA Multa','IVA Multa','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Gastos Judiciales','Gastos Judiciales','O')
insert into fp_diccompanyproducttype values(1,100,'R ','Seguro Cobrado Desembolso','Seguro Cobrado al Desembolso','Q')
insert into fp_diccompanyproducttype values(1,100,'R ','Seguro Periodico','Seguro Periódico','Q')
insert into fp_diccompanyproducttype values(1,100,'R ','Honorarios Abogado','Honorarios Abogado','V')
insert into fp_diccompanyproducttype values(1,100,'R ','IVA Honorarios Abogado','IVA Honorarios Abogado','O')
insert into fp_diccompanyproducttype values(1,103,'SR','Información Adicional','Información Adicional',null)
go
