use cob_fpm
go
insert into fp_generalparametersvalues values(101,'CREDAUT','N','CREDAUT',0,null,'NORMAL')
insert into fp_generalparametersvalues values(1300,'CREDAUT','01','CREDAUT',0,null,'Quirografarias')
insert into fp_generalparametersvalues values(212,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(103,'CRECON1','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(213,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(212,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(108,'CRECON1','15','CRECOM',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(212,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(213,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(300,'CREDAUT','A','CREDAUT',0,null,'Acumulados')
insert into fp_generalparametersvalues values(300,'CRECON1','A','CRECON1',0,null,'Acumulados')
insert into fp_generalparametersvalues values(300,'CREDUE','A','CREDUE',0,null,'Acumulados')
insert into fp_generalparametersvalues values(102,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1300,'CREDCAR','01','CREDCAR',0,null,'Quirografarias')
insert into fp_generalparametersvalues values(1121,'CREDSEM','99','CREDSEM',0,null,'No aplica')
insert into fp_generalparametersvalues values(100,'CRECON1','A','CRECOM',0,null,'ACTIVO')
insert into fp_generalparametersvalues values(103,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(201,'CRECON1','E','CRECOM',0,null,'Comercial')
insert into fp_generalparametersvalues values(202,'CRECON1','360','CRECOM',0,null,'360')
insert into fp_generalparametersvalues values(1123,'CREDCAR','0','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(1129,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(205,'CRECON1','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(106,'CREDAUT','7','CREDAUT',0,null,'CARTERA')
insert into fp_generalparametersvalues values(207,'CRECON1','S','CRECOM',0,null,'Distribuir en cuotas restantes')
insert into fp_generalparametersvalues values(209,'CREDAUT','36','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(206,'CRECON1','M         ','CRECON1',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(211,'CRECON1','L','CRECOM',0,null,'Causación Lineal')
insert into fp_generalparametersvalues values(214,'CRECON1','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(107,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1122,'CRECON1','0','CRECOM',0,null,'0')
insert into fp_generalparametersvalues values(1125,'CRECON1','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(108,'CREDAUT','15','CREDAUT',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(1133,'CRECON1','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1136,'CRECON1','N','CRECOM',0,null,'Normal')
insert into fp_generalparametersvalues values(1139,'CRECON1','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(109,'CREDAUT','999','CREDAUT',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(110,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1000,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1161,'CREDAUT','4','CREDAUT',0,null,'Personales')
insert into fp_generalparametersvalues values(1102,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1103,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(1105,'CREDAUT','V','CREDAUT',0,null,'VIGENTE')
insert into fp_generalparametersvalues values(204,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(100,'CREDAUT','A','CREDAUT',0,null,'ACTIVO')
insert into fp_generalparametersvalues values(1403,'CREDAUT','2','CREDAUT',0,null,'CONSUMO')
insert into fp_generalparametersvalues values(200,'CREDAUT','FRANCESA','CREDAUT',0,null,'FRANCESA')
insert into fp_generalparametersvalues values(201,'CREDAUT','E','CREDAUT',0,null,'Comercial')
insert into fp_generalparametersvalues values(202,'CREDAUT','360','CREDAUT',0,null,'360')
insert into fp_generalparametersvalues values(203,'CREDAUT','365','CREDAUT',0,null,'365')
insert into fp_generalparametersvalues values(1122,'CREDAUT','0','CREDAUT',0,null,'0')
insert into fp_generalparametersvalues values(205,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(207,'CREDAUT','S','CREDAUT',0,null,'Distribuir en cuotas restantes')
insert into fp_generalparametersvalues values(208,'CREDAUT','1','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1123,'CREDAUT','1','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(211,'CREDAUT','L','CREDAUT',0,null,'Causación Lineal')
insert into fp_generalparametersvalues values(215,'CREDAUT','1','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1129,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1124,'CREDAUT','0','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1125,'CREDAUT','1','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1126,'CREDAUT','9999999999','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(302,'CREDAUT','D','CREDAUT',0,null,'Pagos por Cuotas')
insert into fp_generalparametersvalues values(102,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(1133,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(1127,'CREDAUT','0','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1403,'CREDSEM','1','CREDSEM',0,null,'COMERCIAL')
insert into fp_generalparametersvalues values(101,'CREDSEM','N','CRECOM',0,null,'NORMAL')
insert into fp_generalparametersvalues values(102,'CREDSEM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1136,'CREDAUT','N','CREDAUT',0,null,'Normal')
insert into fp_generalparametersvalues values(103,'CREDSEM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(106,'CREDSEM','7','CRECOM',0,null,'CARTERA')
insert into fp_generalparametersvalues values(1139,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(1120,'CREDAUT','1','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1134,'CREDAUT','1','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1127,'CREDSEM','0','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1128,'CREDAUT','0','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(107,'CREDSEM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(108,'CREDSEM','15','CRECOM',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(109,'CREDSEM','999','CRECOM',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(110,'CREDSEM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(1000,'CREDSEM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(1101,'CREDSEM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(206,'CREDSEM','M         ','CREDSEM',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(1103,'CREDSEM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1105,'CREDSEM','V','CRECOM',0,null,'VIGENTE')
insert into fp_generalparametersvalues values(208,'CREDSEM','3','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(209,'CREDSEM','15','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(100,'CREDSEM','A','CRECOM',0,null,'ACTIVO')
insert into fp_generalparametersvalues values(204,'CREDSEM','S','CREDSEM',0,null,'Si')
insert into fp_generalparametersvalues values(201,'CREDSEM','E','CRECOM',0,null,'Comercial')
insert into fp_generalparametersvalues values(202,'CREDSEM','360','CRECOM',0,null,'360')
insert into fp_generalparametersvalues values(210,'CREDSEM','M         ','CREDSEM',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(205,'CREDSEM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(215,'CREDSEM','15','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1120,'CREDSEM','1','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1124,'CREDSEM','0','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1125,'CREDSEM','1','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(211,'CREDSEM','L','CRECOM',0,null,'Causación Lineal')
insert into fp_generalparametersvalues values(1126,'CREDSEM','1000000000','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1134,'CREDSEM','1','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1128,'CREDSEM','0','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1129,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(1130,'CREDSEM','S','CREDSEM',0,null,'Si')
insert into fp_generalparametersvalues values(1122,'CREDSEM','0','CRECOM',0,null,'0')
insert into fp_generalparametersvalues values(207,'CREDSEM','S','CREDSEM',0,null,'Distribuir en cuotas restantes')
insert into fp_generalparametersvalues values(1132,'CREDSEM','0','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(301,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(1135,'CREDSEM','S','CREDSEM',0,null,'Si')
insert into fp_generalparametersvalues values(1137,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(1138,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(1123,'CREDSEM','1','CREDSEM',0,null,'')
insert into fp_generalparametersvalues values(1133,'CREDSEM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1136,'CREDSEM','N','CRECOM',0,null,'Normal')
insert into fp_generalparametersvalues values(1139,'CREDSEM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1102,'CREDSEM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(1161,'CREDSEM','1','CRECOM',0,null,'Actividad Empresarial o Comercial')
insert into fp_generalparametersvalues values(1300,'CREDSEM','05','CRECOM',0,null,'Microcréditos')
insert into fp_generalparametersvalues values(1121,'CREDUE','0','CREDUE',0,null,'Unidades')
insert into fp_generalparametersvalues values(203,'CREDSEM','365','CRECOM',0,null,'365')
insert into fp_generalparametersvalues values(1101,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(101,'CRECON1','N','CRECON1',0,null,'NORMAL')
insert into fp_generalparametersvalues values(1121,'CREDCAR','999','CREDCAR',0,null,'No aplica')
insert into fp_generalparametersvalues values(206,'CREDAUT','M         ','CREDAUT',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(1127,'CREDUE','0','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1138,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(215,'CREDUE','24','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(102,'CRECON1','S','CRECON1',0,null,'Si')
insert into fp_generalparametersvalues values(1122,'CREDUE','0','CREDUE',0,null,'0')
insert into fp_generalparametersvalues values(1124,'CREDUE','0','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1105,'CRECON1','V','CRECON1',0,null,'VIGENTE')
insert into fp_generalparametersvalues values(1127,'CRECON1','0','CRECON1',0,null,'')
insert into fp_generalparametersvalues values(1102,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(1135,'CRECON1','S','CRECON1',0,null,'Si')
insert into fp_generalparametersvalues values(1138,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(1103,'CRECON1','S','CRECON1',0,null,'Si')
insert into fp_generalparametersvalues values(1126,'CRECON1','9999999999','CRECON1',0,null,'')
insert into fp_generalparametersvalues values(1129,'CRECON1','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(1131,'CRECON1','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(1120,'CRECON1','1','CRECON1',0,null,'')
insert into fp_generalparametersvalues values(1134,'CRECON1','1','CRECON1',0,null,'')
insert into fp_generalparametersvalues values(212,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1138,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1124,'CREDCAR','0','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(1131,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(107,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1102,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1103,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(203,'CREDCAR','365','CREDCAR',0,null,'365')
insert into fp_generalparametersvalues values(301,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1137,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1130,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(1131,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1121,'CREDAUT','0','CREDAUT',0,null,'Unidades')
insert into fp_generalparametersvalues values(213,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(1300,'CRECON1','01','CRECON1',0,null,'Quirografarias')
insert into fp_generalparametersvalues values(1403,'CRECON1','1','CRECON1',0,null,'CREDITOS COMERCIALES')
insert into fp_generalparametersvalues values(301,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(101,'CREDUE','N','CREDUE',0,null,'NORMAL')
insert into fp_generalparametersvalues values(214,'CREDSEM','S','CREDSEM',0,null,'Si')
insert into fp_generalparametersvalues values(103,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(106,'CREDUE','7','CREDUE',0,null,'CARTERA')
insert into fp_generalparametersvalues values(108,'CREDUE','15','CREDUE',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(109,'CREDUE','999','CREDUE',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(110,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1000,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1103,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(1105,'CREDUE','V','CREDUE',0,null,'VIGENTE')
insert into fp_generalparametersvalues values(100,'CREDUE','A','CREDUE',0,null,'ACTIVO')
insert into fp_generalparametersvalues values(1403,'CREDUE','3','CREDUE',0,null,'VIVIENDA')
insert into fp_generalparametersvalues values(200,'CREDUE','FRANCESA','CREDUE',0,null,'FRANCESA')
insert into fp_generalparametersvalues values(201,'CREDUE','E','CREDUE',0,null,'Comercial')
insert into fp_generalparametersvalues values(202,'CREDUE','360','CREDUE',0,null,'360')
insert into fp_generalparametersvalues values(204,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(205,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(206,'CREDUE','M         ','CREDUE',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(210,'CREDUE','M         ','CREDUE',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(211,'CREDUE','L','CREDUE',0,null,'Causación Lineal')
insert into fp_generalparametersvalues values(214,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(1130,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(1133,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(302,'CREDUE','D','CREDUE',0,null,'Pagos por Cuotas')
insert into fp_generalparametersvalues values(1135,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(1136,'CREDUE','N','CREDUE',0,null,'Normal')
insert into fp_generalparametersvalues values(1139,'CREDUE','S','CREDUE',0,null,'Si')
insert into fp_generalparametersvalues values(1121,'CRECON1','0','CRECON1',0,null,'Unidades')
insert into fp_generalparametersvalues values(101,'CREDCAR','N','CREDCAR',0,null,'NORMAL')
insert into fp_generalparametersvalues values(102,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(103,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(106,'CREDCAR','7','CREDCAR',0,null,'CARTERA')
insert into fp_generalparametersvalues values(101,'CRECOM','C','CRECOM',0,null,'CON FINANCIAMIENTO')
insert into fp_generalparametersvalues values(101,'MICROC','C','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(101,'PRUEBACRE','C','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(102,'CRECOM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(102,'MICROC','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(102,'PRUEBACRE','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(103,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(103,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(103,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(106,'CRECOM','1','CRECOM',0,null,'ADMINISTRACION')
insert into fp_generalparametersvalues values(106,'MICROC','1','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(106,'PRUEBACRE','1','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(107,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(107,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(107,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(108,'CRECOM','15','CRECOM',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(108,'MICROC','15','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(108,'PRUEBACRE','15','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(109,'CRECOM','999','CRECOM',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(109,'MICROC','999','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(109,'PRUEBACRE','999','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(108,'CREDCAR','15','CREDCAR',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(110,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(110,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(110,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1000,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1000,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1000,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1101,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1101,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1101,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1102,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1102,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1102,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1103,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1103,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1103,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(109,'CREDCAR','999','CREDCAR',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(1105,'CRECOM','V','CRECOM',0,null,'VIGENTE')
insert into fp_generalparametersvalues values(1105,'MICROC','V','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1105,'PRUEBACRE','V','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(110,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1161,'CRECOM','01','CRECOM',0,null,'Quirografarias')
insert into fp_generalparametersvalues values(1161,'MICROC','01','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1161,'PRUEBACRE','01','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1300,'CRECOM','07','CRECOM',0,null,'Otros')
insert into fp_generalparametersvalues values(1300,'MICROC','07','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1300,'PRUEBACRE','07','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1000,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(100,'CRECOM','A','CRECOM',0,null,'ACTIVO')
insert into fp_generalparametersvalues values(100,'MICROC','A','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(100,'PRUEBACRE','A','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(200,'CRECOM','FRANCESA','CRECOM',0,null,'FRANCESA')
insert into fp_generalparametersvalues values(200,'MICROC','FRANCESA','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(200,'PRUEBACRE','FRANCESA','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1101,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(201,'CRECOM','E','CRECOM',0,null,'Comercial')
insert into fp_generalparametersvalues values(201,'MICROC','E','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(201,'PRUEBACRE','E','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(202,'CRECOM','360','CRECOM',0,null,'360')
insert into fp_generalparametersvalues values(202,'MICROC','360','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(202,'PRUEBACRE','360','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(203,'CRECOM','360','CRECOM',0,null,'360')
insert into fp_generalparametersvalues values(203,'MICROC','360','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(203,'PRUEBACRE','360','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(204,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(204,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(204,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(205,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(205,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(205,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(206,'CRECOM','A         ','CRECOM',0,null,'AÑO(S)')
insert into fp_generalparametersvalues values(206,'MICROC','A         ','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(206,'PRUEBACRE','A         ','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(207,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(207,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(207,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(208,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(208,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(208,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(209,'CRECOM','20','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(209,'MICROC','20','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(209,'PRUEBACRE','20','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(210,'CRECOM','A         ','CRECOM',0,null,'AÑO(S)')
insert into fp_generalparametersvalues values(210,'MICROC','A         ','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(210,'PRUEBACRE','A         ','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(211,'CRECOM','L','CRECOM',0,null,'Causación Lineal')
insert into fp_generalparametersvalues values(211,'MICROC','L','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(211,'PRUEBACRE','L','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(212,'CRECOM','N','CRECOM',0,null,'No reajustable')
insert into fp_generalparametersvalues values(212,'MICROC','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(212,'PRUEBACRE','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1105,'CREDCAR','V','CREDCAR',0,null,'VIGENTE')
insert into fp_generalparametersvalues values(213,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(213,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(213,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(214,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(214,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(214,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(215,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(215,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(215,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1120,'CRECOM','5','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1120,'MICROC','5','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1120,'PRUEBACRE','5','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1161,'CREDCAR','6','CREDCAR',0,null,'Automotriz')
insert into fp_generalparametersvalues values(1121,'CRECOM','0','CRECOM',0,null,'Unidades')
insert into fp_generalparametersvalues values(1121,'MICROC','0','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1121,'PRUEBACRE','0','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1122,'CRECOM','0','CRECOM',0,null,'0')
insert into fp_generalparametersvalues values(1122,'MICROC','0','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1122,'PRUEBACRE','0','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1123,'CRECOM','5','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1123,'MICROC','5','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1123,'PRUEBACRE','5','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1124,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1124,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1124,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1125,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1125,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1125,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1126,'CRECOM','20','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1126,'MICROC','20','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1126,'PRUEBACRE','20','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(100,'CREDCAR','A','CREDCAR',0,null,'ACTIVO')
insert into fp_generalparametersvalues values(1134,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1134,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1134,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1127,'CRECOM','30','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1127,'MICROC','30','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1127,'PRUEBACRE','30','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1128,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1128,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1128,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1129,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1129,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1129,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1130,'CRECOM','N','CRECOM',0,null,'No evitar feriados')
insert into fp_generalparametersvalues values(1130,'MICROC','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1130,'PRUEBACRE','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1131,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1131,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1131,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1132,'CRECOM','10','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1132,'MICROC','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1132,'PRUEBACRE','10','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1133,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1133,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1133,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(300,'CRECOM','A','CRECOM',0,null,'Acumulados')
insert into fp_generalparametersvalues values(300,'MICROC','A','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(300,'PRUEBACRE','A','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(301,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(301,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(301,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(302,'CRECOM','C','CRECOM',0,null,'Cuotas')
insert into fp_generalparametersvalues values(302,'MICROC','C','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(302,'PRUEBACRE','C','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1135,'CRECOM','N','CRECOM',0,null,'No')
insert into fp_generalparametersvalues values(1135,'MICROC','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1135,'PRUEBACRE','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1136,'CRECOM','N','CRECOM',0,null,'Normal')
insert into fp_generalparametersvalues values(1136,'MICROC','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1136,'PRUEBACRE','N','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1137,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1137,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1137,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1138,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1138,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1138,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1139,'CRECOM','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(1139,'MICROC','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1139,'PRUEBACRE','S','CRECOM',0,null,null)
insert into fp_generalparametersvalues values(1135,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(1137,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1138,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(1403,'CREDCAR','2','CREDCAR',0,null,'CONSUMO')
insert into fp_generalparametersvalues values(200,'CREDCAR','FRANCESA','CREDCAR',0,null,'FRANCESA')
insert into fp_generalparametersvalues values(201,'CREDCAR','E','CREDCAR',0,null,'Comercial')
insert into fp_generalparametersvalues values(202,'CREDCAR','360','CREDCAR',0,null,'360')
insert into fp_generalparametersvalues values(300,'CREDSEM','A','CREDSEM',0,null,'Acumulados')
insert into fp_generalparametersvalues values(204,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(206,'CREDCAR','M         ','CREDCAR',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(210,'CREDCAR','M         ','CREDCAR',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(1120,'CREDCAR','1','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(1122,'CREDCAR','0','CREDCAR',0,null,'0')
insert into fp_generalparametersvalues values(1132,'CREDAUT','0','CREDAUT',0,null,'')
insert into fp_generalparametersvalues values(1128,'CREDCAR','0','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(1130,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(1132,'CREDCAR','0','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(1133,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(302,'CREDCAR','D','CREDCAR',0,null,'Pagos por Cuotas')
insert into fp_generalparametersvalues values(1135,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(1136,'CREDCAR','N','CREDCAR',0,null,'Normal')
insert into fp_generalparametersvalues values(1139,'CREDCAR','S','CREDCAR',0,null,'Si')
insert into fp_generalparametersvalues values(1101,'CREDAUT','N','CREDAUT',0,null,'No')
insert into fp_generalparametersvalues values(214,'CREDAUT','S','CREDAUT',0,null,'Si')
insert into fp_generalparametersvalues values(106,'CRECON1','7','CRECON1',0,null,'CARTERA')
insert into fp_generalparametersvalues values(109,'CRECON1','999','CRECON1',0,null,'BANCAMIA')
insert into fp_generalparametersvalues values(1161,'CRECON1','1','CRECOM',0,null,'Actividad Empresarial o Comercial')
insert into fp_generalparametersvalues values(200,'CRECON1','FRANCESA','CRECON1',0,null,'FRANCESA')
insert into fp_generalparametersvalues values(204,'CRECON1','S','CRECOM',0,null,'Si')
insert into fp_generalparametersvalues values(208,'CRECON1','6','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(209,'CRECON1','999','CRECON1',0,null,'')
insert into fp_generalparametersvalues values(210,'CRECON1','M         ','CRECON1',0,null,'MES(ES)')
insert into fp_generalparametersvalues values(215,'CRECON1','36','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1123,'CRECON1','1','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1124,'CRECON1','0','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(107,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(1128,'CRECON1','0','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(1130,'CRECON1','S','CRECON1',0,null,'Si')
insert into fp_generalparametersvalues values(1132,'CRECON1','0','CRECOM',0,null,'')
insert into fp_generalparametersvalues values(110,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(302,'CRECON1','D','CRECOM',0,null,'Pagos por Cuotas')
insert into fp_generalparametersvalues values(1000,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(203,'CRECON1','365','CRECON1',0,null,'365')
insert into fp_generalparametersvalues values(301,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(1137,'CRECON1','N','CRECON1',0,null,'No')
insert into fp_generalparametersvalues values(207,'CREDUE','S','CREDUE',0,null,'Distribuir en cuotas restantes')
insert into fp_generalparametersvalues values(1120,'CREDUE','1','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1134,'CREDUE','1','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1128,'CREDUE','0','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1132,'CREDUE','0','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(107,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1161,'CREDUE','10','CREDUE',0,null,'Media y Residencial')
insert into fp_generalparametersvalues values(203,'CREDUE','365','CREDUE',0,null,'365')
insert into fp_generalparametersvalues values(208,'CREDUE','6','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(209,'CREDUE','999','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(200,'CREDSEM','FRANCESA','CRECOM',0,null,'FRANCESA')
insert into fp_generalparametersvalues values(1123,'CREDUE','1','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1129,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1131,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(301,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1137,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1125,'CREDUE','10','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(1101,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1102,'CREDUE','N','CREDUE',0,null,'No')
insert into fp_generalparametersvalues values(1126,'CREDUE','9999999999','CREDUE',0,null,'')
insert into fp_generalparametersvalues values(302,'CREDSEM','D','CREDSEM',0,null,'Pagos por Cuotas')
insert into fp_generalparametersvalues values(1131,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(212,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(213,'CREDSEM','N','CREDSEM',0,null,'No')
insert into fp_generalparametersvalues values(300,'CREDCAR','A','CREDCAR',0,null,'Acumulados')
insert into fp_generalparametersvalues values(207,'CREDCAR','N','CREDCAR',0,null,'Pagar en primera cuota')
insert into fp_generalparametersvalues values(215,'CREDCAR','12','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(205,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(208,'CREDCAR','1','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(209,'CREDCAR','48','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(211,'CREDCAR','E','CREDCAR',0,null,'Causación Exponencial')
insert into fp_generalparametersvalues values(214,'CREDCAR','N','CREDCAR',0,null,'No')
insert into fp_generalparametersvalues values(1125,'CREDCAR','1','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(1126,'CREDCAR','100000000','CREDCAR',0,null,'')
insert into fp_generalparametersvalues values(210,'CREDAUT','M         ','CREDAUT',0,null,'MES(ES)')
go
