use cob_fpm
go
insert into fp_itemsbyproduct values('CRECON1',1400,'C')
insert into fp_itemsbyproduct values('CRECON1',1900,'I')
insert into fp_itemsbyproduct values('CRECON1',2100,'M')
insert into fp_itemsbyproduct values('CRECON1',2103,'O')
insert into fp_itemsbyproduct values('CRECON1',2200,'V')
insert into fp_itemsbyproduct values('CREDAUT',1400,'C')
insert into fp_itemsbyproduct values('CREDAUT',1900,'I')
insert into fp_itemsbyproduct values('CREDAUT',2100,'M')
insert into fp_itemsbyproduct values('CREDAUT',2102,'V')
insert into fp_itemsbyproduct values('CREDAUT',2103,'O')
insert into fp_itemsbyproduct values('CREDAUT',2200,'V')
insert into fp_itemsbyproduct values('CREDCAR',1400,'C')
insert into fp_itemsbyproduct values('CREDCAR',1900,'I')
insert into fp_itemsbyproduct values('CREDCAR',2100,'M')
insert into fp_itemsbyproduct values('CREDCAR',2102,'V')
insert into fp_itemsbyproduct values('CREDCAR',2103,'O')
insert into fp_itemsbyproduct values('CREDCAR',2104,'Q')
insert into fp_itemsbyproduct values('CREDCAR',2200,'V')
insert into fp_itemsbyproduct values('CREDSEM',1400,'C')
insert into fp_itemsbyproduct values('CREDSEM',1900,'I')
insert into fp_itemsbyproduct values('CREDSEM',2100,'M')
insert into fp_itemsbyproduct values('CREDSEM',2102,'V')
insert into fp_itemsbyproduct values('CREDSEM',2103,'O')
insert into fp_itemsbyproduct values('CREDSEM',2200,'V')
insert into fp_itemsbyproduct values('CREDUE',1400,'C')
insert into fp_itemsbyproduct values('CREDUE',1900,'I')
insert into fp_itemsbyproduct values('CREDUE',2100,'M')
insert into fp_itemsbyproduct values('CREDUE',2102,'V')
insert into fp_itemsbyproduct values('CREDUE',2103,'O')
insert into fp_itemsbyproduct values('CREDUE',2104,'Q')
insert into fp_itemsbyproduct values('CREDUE',2200,'V')
go
