use cob_fpm
go
insert into fp_mappingtypegroup values('01','C',1,1)
insert into fp_mappingtypegroup values('02','I',1,1)
insert into fp_mappingtypegroup values('02','M',1,1)
insert into fp_mappingtypegroup values('03','O',1,1)
insert into fp_mappingtypegroup values('03','Q',1,1)
insert into fp_mappingtypegroup values('03','V',1,1)
insert into fp_mappingtypegroup values('04','O',1,1)
insert into fp_mappingtypegroup values('04','Q',1,1)
insert into fp_mappingtypegroup values('04','V',1,1)
insert into fp_mappingtypegroup values('05','O',1,1)
insert into fp_mappingtypegroup values('05','Q',1,1)
insert into fp_mappingtypegroup values('05','V',1,1)
insert into fp_mappingtypegroup values('06','O',1,1)
insert into fp_mappingtypegroup values('06','Q',1,1)
insert into fp_mappingtypegroup values('06','V',1,1)
insert into fp_mappingtypegroup values('07','O',1,1)
insert into fp_mappingtypegroup values('07','Q',1,1)
insert into fp_mappingtypegroup values('07','V',1,1)
insert into fp_mappingtypegroup values('08','O',1,1)
insert into fp_mappingtypegroup values('08','Q',1,1)
insert into fp_mappingtypegroup values('08','V',1,1)
insert into fp_mappingtypegroup values('09','O',1,1)
insert into fp_mappingtypegroup values('09','Q',1,1)
insert into fp_mappingtypegroup values('09','V',1,1)
insert into fp_mappingtypegroup values('10','O',1,1)
insert into fp_mappingtypegroup values('10','Q',1,1)
insert into fp_mappingtypegroup values('10','V',1,1)
go
