use cob_fpm
go
insert into fp_productauthorization values('CRE',null,'N',null,null)
insert into fp_productauthorization values('LIQ',null,'N',null,null)
insert into fp_productauthorization values('CCI',null,'N',null,null)
insert into fp_productauthorization values('CCD',null,'N',null,null)
insert into fp_productauthorization values('STB',null,'N',null,null)
insert into fp_productauthorization values('GRB',null,'N',null,null)
insert into fp_productauthorization values('GRA',null,'N',null,null)
insert into fp_productauthorization values('AVB',null,'N',null,null)
insert into fp_productauthorization values('AVE',null,'N',null,null)
insert into fp_productauthorization values('CCE',null,'N',null,null)
insert into fp_productauthorization values('CTE',null,'N',null,null)
insert into fp_productauthorization values('CRECON',null,'N',null,null)
insert into fp_productauthorization values('CREAUT',null,'N',null,null)
insert into fp_productauthorization values('CRECOM',null,'N',null,null)
insert into fp_productauthorization values('TARCRE',null,'N',null,null)
insert into fp_productauthorization values('MICROC',null,'N',null,null)
insert into fp_productauthorization values('CREDAUT',null,'N',null,null)
insert into fp_productauthorization values('PERS',null,'N',null,null)
insert into fp_productauthorization values('AHORRO',null,'N',null,null)
insert into fp_productauthorization values('CREDVIV',null,'N',null,null)
insert into fp_productauthorization values('CREDUE',null,'N',null,null)
insert into fp_productauthorization values('CREDSEM',null,'N',null,null)
insert into fp_productauthorization values('DPF',null,'N',null,null)
insert into fp_productauthorization values('VIVOTRAS',null,'N',null,null)
insert into fp_productauthorization values('VIVSOCIAL',null,'N',null,null)
insert into fp_productauthorization values('AVAL',null,'N',null,null)
insert into fp_productauthorization values('HIP',null,'N',null,null)
insert into fp_productauthorization values('PRUEBACRE',null,'N',null,null)
insert into fp_productauthorization values('CRECON1',null,'N',null,null)
insert into fp_productauthorization values('CREVIV',null,'N',null,null)
insert into fp_productauthorization values('CREDCAR',null,'N',null,null)
insert into fp_productauthorization values('PREN',null,'N',null,null)
insert into fp_productauthorization values('PERSONAL',null,'N',null,null)
insert into fp_productauthorization values('VEHICULO',null,'N',null,null)
insert into fp_productauthorization values('PAGARE',null,'N',null,null)
go
