use cob_fpm
go
insert into fp_unitfunctionalityvalues values(4,1831,'PAGARE','AVAL','AVALES')
insert into fp_unitfunctionalityvalues values(4,8201,'PAGARE','PAGARE','PAGARE')
insert into fp_unitfunctionalityvalues values(4,8194,'PAGARE','I','IDONEA')
insert into fp_unitfunctionalityvalues values(4,8195,'PAGARE','C',' CERRADA                                                          ')
insert into fp_unitfunctionalityvalues values(4,1828,'PAGARE','A         ','AÑO(S)')
insert into fp_unitfunctionalityvalues values(4,1829,'PAGARE','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(4,1832,'PAGARE','E',' EQUIPARABLES A GARANTIAS IDONEAS                                 ')
insert into fp_unitfunctionalityvalues values(4,1833,'PAGARE','100','100')
insert into fp_unitfunctionalityvalues values(4,1830,'PAGARE','S','Si')
insert into fp_unitfunctionalityvalues values(4,8196,'PAGARE','S','Si')
insert into fp_unitfunctionalityvalues values(4,8197,'PAGARE','N','No')
insert into fp_unitfunctionalityvalues values(4,8198,'PAGARE','N','No')
insert into fp_unitfunctionalityvalues values(4,8199,'PAGARE','N','No')
insert into fp_unitfunctionalityvalues values(5,1831,'AHORRO','LIQ','GARANTIAS LIQUIDAS')
insert into fp_unitfunctionalityvalues values(5,8201,'AHORRO','AHORROS','AHORROS')
insert into fp_unitfunctionalityvalues values(7,1831,'VIVOTRAS','HIP','GARANTIAS HIPOTECARIAS')
insert into fp_unitfunctionalityvalues values(7,8201,'VIVOTRAS','VIVOTRAS','VIVOTRAS')
insert into fp_unitfunctionalityvalues values(7,8194,'VIVOTRAS','I','IDONEA')
insert into fp_unitfunctionalityvalues values(7,8195,'VIVOTRAS','A',' ABIERTA                                                          ')
insert into fp_unitfunctionalityvalues values(7,1828,'VIVOTRAS','A         ','AÑO(S)')
insert into fp_unitfunctionalityvalues values(7,1829,'VIVOTRAS','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(7,1832,'VIVOTRAS','N',' OTRAS GARANTIAS NO IDONEAS                                       ')
insert into fp_unitfunctionalityvalues values(7,1833,'VIVOTRAS','100','100')
insert into fp_unitfunctionalityvalues values(7,1830,'VIVOTRAS','S','Si')
insert into fp_unitfunctionalityvalues values(7,8196,'VIVOTRAS','N','No')
insert into fp_unitfunctionalityvalues values(7,8197,'VIVOTRAS','N','No')
insert into fp_unitfunctionalityvalues values(7,8198,'VIVOTRAS','N','No')
insert into fp_unitfunctionalityvalues values(7,8199,'VIVOTRAS','N','No')
insert into fp_unitfunctionalityvalues values(8,1831,'VIVSOCIAL','HIP','GARANTIAS HIPOTECARIAS')
insert into fp_unitfunctionalityvalues values(8,8201,'VIVSOCIAL','VIVSOCIAL','VIVSOCIAL')
insert into fp_unitfunctionalityvalues values(8,8194,'VIVSOCIAL','I','IDONEA')
insert into fp_unitfunctionalityvalues values(8,8195,'VIVSOCIAL','A',' ABIERTA                                                          ')
insert into fp_unitfunctionalityvalues values(8,1828,'VIVSOCIAL','A         ','AÑO(S)')
insert into fp_unitfunctionalityvalues values(8,1829,'VIVSOCIAL','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(8,1832,'VIVSOCIAL','cu_tipo_bien',null)
insert into fp_unitfunctionalityvalues values(8,1833,'VIVSOCIAL','100','100')
insert into fp_unitfunctionalityvalues values(8,1830,'VIVSOCIAL','S','Si')
insert into fp_unitfunctionalityvalues values(8,8196,'VIVSOCIAL','N','No')
insert into fp_unitfunctionalityvalues values(8,8197,'VIVSOCIAL','N','No')
insert into fp_unitfunctionalityvalues values(8,8198,'VIVSOCIAL','N','No')
insert into fp_unitfunctionalityvalues values(8,8199,'VIVSOCIAL','N','No')
insert into fp_unitfunctionalityvalues values(9,1831,'VEHICULO','PREN','GARANTIAS PRENDARIAS')
insert into fp_unitfunctionalityvalues values(9,8201,'VEHICULO','VEHICULO','VEHICULO')
insert into fp_unitfunctionalityvalues values(9,8194,'VEHICULO','I','IDONEA')
insert into fp_unitfunctionalityvalues values(9,8195,'VEHICULO','C',' CERRADA                                                          ')
insert into fp_unitfunctionalityvalues values(9,1828,'VEHICULO','A         ','AÑO(S)')
insert into fp_unitfunctionalityvalues values(9,1829,'VEHICULO','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(9,1832,'VEHICULO','N',' OTRAS GARANTIAS NO IDONEAS                                       ')
insert into fp_unitfunctionalityvalues values(9,1833,'VEHICULO','70','70')
insert into fp_unitfunctionalityvalues values(9,1830,'VEHICULO','S','Si')
insert into fp_unitfunctionalityvalues values(9,8196,'VEHICULO','N','No')
insert into fp_unitfunctionalityvalues values(9,8197,'VEHICULO','N','No')
insert into fp_unitfunctionalityvalues values(9,8198,'VEHICULO','N','No')
insert into fp_unitfunctionalityvalues values(9,8199,'VEHICULO','N','No')
insert into fp_unitfunctionalityvalues values(5,8194,'AHORRO','I','IDONEA')
insert into fp_unitfunctionalityvalues values(3,1831,'PERSONAL','PERS','GARANTIAS PERSONALES')
insert into fp_unitfunctionalityvalues values(3,8201,'PERSONAL','PERSONALE','PERSONALE')
insert into fp_unitfunctionalityvalues values(3,8194,'PERSONAL','I','IDONEA')
insert into fp_unitfunctionalityvalues values(3,8195,'PERSONAL','C',' CERRADA                                                          ')
insert into fp_unitfunctionalityvalues values(3,1828,'PERSONAL','M         ','MES(ES)')
insert into fp_unitfunctionalityvalues values(3,1829,'PERSONAL','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(3,1832,'PERSONAL','N',' OTRAS GARANTIAS NO IDONEAS                                       ')
insert into fp_unitfunctionalityvalues values(3,1833,'PERSONAL','0','0')
insert into fp_unitfunctionalityvalues values(3,1830,'PERSONAL','N','No')
insert into fp_unitfunctionalityvalues values(3,8196,'PERSONAL','N','No')
insert into fp_unitfunctionalityvalues values(3,8197,'PERSONAL','N','No')
insert into fp_unitfunctionalityvalues values(3,8198,'PERSONAL','N','No')
insert into fp_unitfunctionalityvalues values(3,8199,'PERSONAL','N','No')
insert into fp_unitfunctionalityvalues values(5,8195,'AHORRO','A',' ABIERTA                                                          ')
insert into fp_unitfunctionalityvalues values(5,1828,'AHORRO','A         ','AÑO(S)')
insert into fp_unitfunctionalityvalues values(5,1829,'AHORRO','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(5,1832,'AHORRO','E',' EQUIPARABLES A GARANTIAS IDONEAS                                 ')
insert into fp_unitfunctionalityvalues values(5,1833,'AHORRO','0','0')
insert into fp_unitfunctionalityvalues values(5,1830,'AHORRO','N','No')
insert into fp_unitfunctionalityvalues values(5,8196,'AHORRO','N','No')
insert into fp_unitfunctionalityvalues values(5,8197,'AHORRO','N','No')
insert into fp_unitfunctionalityvalues values(5,8198,'AHORRO','N','No')
insert into fp_unitfunctionalityvalues values(5,8199,'AHORRO','N','No')
insert into fp_unitfunctionalityvalues values(6,1831,'DPF','LIQ','GARANTIAS LIQUIDAS')
insert into fp_unitfunctionalityvalues values(6,8201,'DPF','DEPÓSITOS A PLAZO FIJO','DEPÓSITOS A PLAZO FIJO')
insert into fp_unitfunctionalityvalues values(6,8194,'DPF','I','IDONEA')
insert into fp_unitfunctionalityvalues values(6,8195,'DPF','A',' ABIERTA                                                          ')
insert into fp_unitfunctionalityvalues values(6,1828,'DPF','A         ','AÑO(S)')
insert into fp_unitfunctionalityvalues values(6,1829,'DPF','V','VIGENTE')
insert into fp_unitfunctionalityvalues values(6,1832,'DPF','E',' EQUIPARABLES A GARANTIAS IDONEAS                                 ')
insert into fp_unitfunctionalityvalues values(6,1833,'DPF','0','0')
insert into fp_unitfunctionalityvalues values(6,1830,'DPF','N','No')
insert into fp_unitfunctionalityvalues values(6,8196,'DPF','N','No')
insert into fp_unitfunctionalityvalues values(6,8197,'DPF','N','No')
insert into fp_unitfunctionalityvalues values(6,8198,'DPF','N','No')
insert into fp_unitfunctionalityvalues values(6,8199,'DPF','N','No')
go
