'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BClientes.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ico30000() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico30000", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ico30001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico30001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ico30002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico30002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ico30003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico30003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ico31000() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico31000", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK..Búsqueda de Clientes.
        '''</summary>
        Friend ReadOnly Property str10000() As String
            Get
                Return ResourceManager.GetString("str10000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR.
        '''</summary>
        Friend ReadOnly Property str15000() As String
            Get
                Return ResourceManager.GetString("str15000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADVERTENCIA.
        '''</summary>
        Friend ReadOnly Property str15001() As String
            Get
                Return ResourceManager.GetString("str15001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MENSAJE DEL SERVIDOR.
        '''</summary>
        Friend ReadOnly Property str15002() As String
            Get
                Return ResourceManager.GetString("str15002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DATOS REQUERIDOS.
        '''</summary>
        Friend ReadOnly Property str15003() As String
            Get
                Return ResourceManager.GetString("str15003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda Alfabética.
        '''</summary>
        Friend ReadOnly Property str15004() As String
            Get
                Return ResourceManager.GetString("str15004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Límite de Consulta Excedido.
        '''</summary>
        Friend ReadOnly Property str15005() As String
            Get
                Return ResourceManager.GetString("str15005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese Apellido Paterno.
        '''</summary>
        Friend ReadOnly Property str15006() As String
            Get
                Return ResourceManager.GetString("str15006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese Apellido Materno.
        '''</summary>
        Friend ReadOnly Property str15007() As String
            Get
                Return ResourceManager.GetString("str15007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Criterio de búsqueda debe tener valor de búsqueda específico.
        '''</summary>
        Friend ReadOnly Property str15008() As String
            Get
                Return ResourceManager.GetString("str15008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor fuera de Rango.
        '''</summary>
        Friend ReadOnly Property str15009() As String
            Get
                Return ResourceManager.GetString("str15009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El Nombre no es valor de búsqueda sin el Apellido del Cliente.
        '''</summary>
        Friend ReadOnly Property str15010() As String
            Get
                Return ResourceManager.GetString("str15010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El Apellido como criterio de búsqueda debe tener un valor específico.
        '''</summary>
        Friend ReadOnly Property str15011() As String
            Get
                Return ResourceManager.GetString("str15011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Criterio de búsqueda no válido. Utilice símbolo (%) únicamente al final.
        '''</summary>
        Friend ReadOnly Property str15012() As String
            Get
                Return ResourceManager.GetString("str15012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Buscar.
        '''</summary>
        Friend ReadOnly Property str2000() As String
            Get
                Return ResourceManager.GetString("str2000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S&amp;igtes..
        '''</summary>
        Friend ReadOnly Property str2001() As String
            Get
                Return ResourceManager.GetString("str2001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esco&amp;ger.
        '''</summary>
        Friend ReadOnly Property str2002() As String
            Get
                Return ResourceManager.GetString("str2002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Salir.
        '''</summary>
        Friend ReadOnly Property str2003() As String
            Get
                Return ResourceManager.GetString("str2003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar Clientes.
        '''</summary>
        Friend ReadOnly Property str3000() As String
            Get
                Return ResourceManager.GetString("str3000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Buscar Clientes de acuerdo a Criterios Indicados.
        '''</summary>
        Friend ReadOnly Property str4000() As String
            Get
                Return ResourceManager.GetString("str4000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Buscar el siguiente grupo de Clientes.
        '''</summary>
        Friend ReadOnly Property str4001() As String
            Get
                Return ResourceManager.GetString("str4001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Escoger un Cliente.
        '''</summary>
        Friend ReadOnly Property str4002() As String
            Get
                Return ResourceManager.GetString("str4002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Salir de la Forma de Búsqueda.
        '''</summary>
        Friend ReadOnly Property str4003() As String
            Get
                Return ResourceManager.GetString("str4003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Doble-click para Escoger un Cliente.
        '''</summary>
        Friend ReadOnly Property str4004() As String
            Get
                Return ResourceManager.GetString("str4004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Seleccionar el Tipo de Cliente que se desea Buscar.
        '''</summary>
        Friend ReadOnly Property str4005() As String
            Get
                Return ResourceManager.GetString("str4005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Seleccionar el Criterio de Búsqueda.
        '''</summary>
        Friend ReadOnly Property str4006() As String
            Get
                Return ResourceManager.GetString("str4006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Seleccionar el Tipo de Busqueda.
        '''</summary>
        Friend ReadOnly Property str4007() As String
            Get
                Return ResourceManager.GetString("str4007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Ingresar Nombres.
        '''</summary>
        Friend ReadOnly Property str4008() As String
            Get
                Return ResourceManager.GetString("str4008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Ingresar Apellido Paterno.
        '''</summary>
        Friend ReadOnly Property str4009() As String
            Get
                Return ResourceManager.GetString("str4009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Ingresar Apellido Materno.
        '''</summary>
        Friend ReadOnly Property str4010() As String
            Get
                Return ResourceManager.GetString("str4010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Dar el valor inicial de Búsqueda.
        '''</summary>
        Friend ReadOnly Property str4011() As String
            Get
                Return ResourceManager.GetString("str4011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda de Clientes.
        '''</summary>
        Friend ReadOnly Property str5000() As String
            Get
                Return ResourceManager.GetString("str5000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de Cliente.
        '''</summary>
        Friend ReadOnly Property str5001() As String
            Get
                Return ResourceManager.GetString("str5001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Criterios de Búsqueda.
        '''</summary>
        Friend ReadOnly Property str5002() As String
            Get
                Return ResourceManager.GetString("str5002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apellido &amp;Paterno.
        '''</summary>
        Friend ReadOnly Property str5003() As String
            Get
                Return ResourceManager.GetString("str5003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P. &amp;Jurídica.
        '''</summary>
        Friend ReadOnly Property str5004() As String
            Get
                Return ResourceManager.GetString("str5004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P. &amp;Natural.
        '''</summary>
        Friend ReadOnly Property str5005() As String
            Get
                Return ResourceManager.GetString("str5005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Alfabético.
        '''</summary>
        Friend ReadOnly Property str5006() As String
            Get
                Return ResourceManager.GetString("str5006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Consecutivo.
        '''</summary>
        Friend ReadOnly Property str5007() As String
            Get
                Return ResourceManager.GetString("str5007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;No. de Id..
        '''</summary>
        Friend ReadOnly Property str5008() As String
            Get
                Return ResourceManager.GetString("str5008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pasapo&amp;rte.
        '''</summary>
        Friend ReadOnly Property str5009() As String
            Get
                Return ResourceManager.GetString("str5009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apell. Ca&amp;sada.
        '''</summary>
        Friend ReadOnly Property str5010() As String
            Get
                Return ResourceManager.GetString("str5010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RUC.
        '''</summary>
        Friend ReadOnly Property str5011() As String
            Get
                Return ResourceManager.GetString("str5011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patente.
        '''</summary>
        Friend ReadOnly Property str5012() As String
            Get
                Return ResourceManager.GetString("str5012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registro Inscripción.
        '''</summary>
        Friend ReadOnly Property str5013() As String
            Get
                Return ResourceManager.GetString("str5013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre:.
        '''</summary>
        Friend ReadOnly Property str5014() As String
            Get
                Return ResourceManager.GetString("str5014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor de Búsqueda:.
        '''</summary>
        Friend ReadOnly Property str5015() As String
            Get
                Return ResourceManager.GetString("str5015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apellido Casada:.
        '''</summary>
        Friend ReadOnly Property str5016() As String
            Get
                Return ResourceManager.GetString("str5016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apellido Paterno:.
        '''</summary>
        Friend ReadOnly Property str5017() As String
            Get
                Return ResourceManager.GetString("str5017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clientes.
        '''</summary>
        Friend ReadOnly Property str5018() As String
            Get
                Return ResourceManager.GetString("str5018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prospectos.
        '''</summary>
        Friend ReadOnly Property str5019() As String
            Get
                Return ResourceManager.GetString("str5019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Todos.
        '''</summary>
        Friend ReadOnly Property str5020() As String
            Get
                Return ResourceManager.GetString("str5020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar.
        '''</summary>
        Friend ReadOnly Property str5021() As String
            Get
                Return ResourceManager.GetString("str5021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cifrada.
        '''</summary>
        Friend ReadOnly Property str5022() As String
            Get
                Return ResourceManager.GetString("str5022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;CR.
        '''</summary>
        Friend ReadOnly Property str5023() As String
            Get
                Return ResourceManager.GetString("str5023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Apell. Casada.
        '''</summary>
        Friend ReadOnly Property str5024() As String
            Get
                Return ResourceManager.GetString("str5024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;CI.
        '''</summary>
        Friend ReadOnly Property str5025() As String
            Get
                Return ResourceManager.GetString("str5025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Nombre Comercial.
        '''</summary>
        Friend ReadOnly Property str5026() As String
            Get
                Return ResourceManager.GetString("str5026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;No. de Id..
        '''</summary>
        Friend ReadOnly Property str5027() As String
            Get
                Return ResourceManager.GetString("str5027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Razón Social.
        '''</summary>
        Friend ReadOnly Property str5028() As String
            Get
                Return ResourceManager.GetString("str5028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primer Apellido.
        '''</summary>
        Friend ReadOnly Property str5029() As String
            Get
                Return ResourceManager.GetString("str5029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primer Nombre.
        '''</summary>
        Friend ReadOnly Property str5030() As String
            Get
                Return ResourceManager.GetString("str5030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apellido de Casada.
        '''</summary>
        Friend ReadOnly Property str5031() As String
            Get
                Return ResourceManager.GetString("str5031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;CA4.
        '''</summary>
        Friend ReadOnly Property str5032() As String
            Get
                Return ResourceManager.GetString("str5032", resourceCulture)
            End Get
        End Property
    End Module
End Namespace


