use cob_conta
go

declare @w_empresa   int,
        @w_modulo    int

if exists (select 1 from cob_conta..sysobjects where name = 'cb_relparam')
begin
   select @w_modulo = 7
   select @w_empresa = pa_tinyint from cobis..cl_parametro where pa_nemonico = 'EMP' and pa_producto = 'ADM'

   delete from cob_conta..cb_relparam where re_empresa = @w_empresa and re_producto = @w_modulo
   
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1311NE','2.9.99.GRUPAL','131190010101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1311NE','2.9.99.INDIVIDUAL','131190010102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1311NE','2.9.99.INDIVIDUAL','131190010103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1311EX','2.9.99.GRUPAL','131190010201',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1311EX','2.9.99.INDIVIDUAL','131190010202',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1311EX','2.9.99.INDIVIDUAL','131190010203',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1361NE','2.9.99.GRUPAL','136190010101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1361NE','2.9.99.INDIVIDUAL','136190010102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1361NE','2.9.99.INDIVIDUAL','136190010103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1361EX','2.9.99.GRUPAL','136190010201',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1361EX','2.9.99.INDIVIDUAL','136190010202',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAP_1361EX','2.9.99.INDIVIDUAL','136190010203',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAS_1391','2.9.99.GRUPAL','139150619004',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAS_1391','2.9.99.INDIVIDUAL','139150619005',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAS_1391','2.9.99.INDIVIDUAL','139150619006',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'COM_5321','2.9.99.GRUPAL','5321111101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'COM_5321','2.9.99.INDIVIDUAL','5321111102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'COM_5321','2.9.99.INDIVIDUAL','5321111103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'QUI_1391','2.9.99.GRUPAL','139150619001',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'QUI_1391','2.9.99.INDIVIDUAL','139150619002',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'QUI_1391','2.9.99.INDIVIDUAL','139150619003',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'F_PAGO','OPEN_PAY','11020203',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'F_PAGO','SANTANDER','11020203',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'F_PAGO','NC_BCO_MN','11020202',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'F_PAGO','ND_BCO_MN','11020202',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'F_PAGO','GAR_DEB','241302',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'F_PAGO','RENOVACION','14019004',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (1, 'F_PAGO','OXXO','14910101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (1, 'F_PAGO','SOBRANTE','11020201',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1311NE','2.9.99.GRUPAL','131190030101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1311NE','2.9.99.INDIVIDUAL','131190030102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1311NE','2.9.99.INDIVIDUAL','131190030103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1311EX','2.9.99.GRUPAL','131190030201',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1311EX','2.9.99.INDIVIDUAL','131190030202',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1311EX','2.9.99.INDIVIDUAL','131190030203',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1361','2.9.99.GRUPAL','136190030101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1361','2.9.99.INDIVIDUAL','136190030102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_1361','2.9.99.INDIVIDUAL','136190030103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5102','2.9.99.GRUPAL','510261900101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5102','2.9.99.INDIVIDUAL','510261900102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5102','2.9.99.INDIVIDUAL','510261900103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5105NE','2.9.99.GRUPAL','510511900201',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5105NE','2.9.99.INDIVIDUAL','510511900202',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5105NE','2.9.99.INDIVIDUAL','510511900203',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5105EX','2.9.99.GRUPAL','510511900101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5105EX','2.9.99.INDIVIDUAL','510511900102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_5105EX','2.9.99.INDIVIDUAL','510511900103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_7711','2.9.99.GRUPAL','7711900101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_7711','2.9.99.INDIVIDUAL','7711900102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'INT_7711','2.9.99.INDIVIDUAL','7711900103',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'IVA_1401','2.9.99.GRUPAL','14019001',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'IVA_1401','2.9.99.INDIVIDUAL','14019002',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'IVA_1401','2.9.99.INDIVIDUAL','14019003',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAS_5050','2.9.99.GRUPAL','50500101',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAS_5050','2.9.99.INDIVIDUAL','50500102',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'CAS_5050','2.9.99.INDIVIDUAL','50500103',@w_modulo, 'CTB_OF','D')   
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.A1','139150619007',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.A2','139150619007',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.A1','139150619008',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.A2','139150619008',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.A1','139150619009',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.A2','139150619009',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.B1','139150619010',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.B2','139150619010',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.B3','139150619010',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.B1','139150619011',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.B2','139150619011',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.B3','139150619011',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.B1','139150619012',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.B2','139150619012',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.B3','139150619012',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.C1','139150619013',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.C2','139150619013',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.C1','139150619014',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.C2','139150619014',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.C1','139150619015',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.C2','139150619015',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.D','139150619016',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.D','139150619017',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.D','139150619018',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','GRUPAL.E','139150619019',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.E','139150619020',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES (@w_empresa, 'PRO_1391','INDIVIDUAL.E','139150619021',@w_modulo, 'CTB_OF','D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES( @w_empresa, 'F_PAGO' , 'DEV_SEG', '240123', @w_modulo, 'CTB_OF', 'D')
   insert into cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) values (@w_empresa, 'F_PAGO', 'OBJETADO', '14019006', 7, 'CTB_OF', 'D')
   insert into cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest)values  (@w_empresa, 'F_PAGO', 'QUEBRANTO', '50502604', 7, 'CTB_OF', 'D')
   INSERT INTO cob_conta..cb_relparam (re_empresa, re_parametro, re_clave, re_substring, re_producto, re_tipo_area, re_origen_dest) VALUES( @w_empresa, 'F_PAGO' , 'FALLECIMIENTO', '50502605', @w_modulo, 'CTB_OF', 'D')
   
   end
else
    print 'NO EXISTE TABLA cb_relparam'
go
