use cob_cartera
go

delete from ca_producto

insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('CHEPRO',    'PAGOS RECIBIDOS EN CHEQUES PROPIOS',             'CHPR',    0, 102, 'N', 'N', 'N', 0, 'N', NULL, 'REAPLICA',   NULL, 'E', 'A',NULL, 'OFI')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('CHLOCAL',   'PAGOS RECIBIDOS EN CHEQUES LOCALES',             'CHLO',    0, 103, 'N', 'N', 'N', 0, 'N', NULL, 'DEV_CANJE',  NULL, 'E', 'A',NULL, 'OFI')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('CHOTPLAZA', 'PAGOS RECIBIDOS EN CHEQUES OTRAS PLAZAS',        'CHOT',    0, 104, 'N', 'N', 'N', 0, 'N', NULL, 'REAPLICA',   NULL, 'E', 'A',NULL, 'OFI')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('DEV_CANJE', 'DEVOLUCION DE CANJE',                            'OTRO',    0, 122, 'N', 'N', 'N', 0, 'N', NULL, 'REAPLICA',   NULL, 'E', 'A',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('EFMN',      'EFECTIVO MONEDA NACIONAL (POR CAJAS COBIS)',     'EFEC',    0, 101, 'N', 'N', 'N', 0, 'N', NULL, 'REAPLICA',   NULL, 'E', 'A',NULL, 'OFI')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('NCAH',      'NOTA CREDITO AHORROS',                           'NCAH',    0, 127, 'N', 'N', 'N', 0, 'N', 99,   'NDAH',       'C',  'E', 'A',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('NDAH',      'NOTA DEBITO AHORROS',                            'NDAH',    0, 126, 'N', 'N', 'N', 0, 'N', 99,   'NCAH',       'D',  'E', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('PAGCOND',   'PAGO CONDONACION',                               'PLANO',   0, 123, 'N', 'N', 'N', 0, 'N', NULL, 'PAGCOND',    NULL, 'E', 'A',NULL, 'POSNOPRO')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('PAGONOMINA','PAGOS DE NOMINA',                                'PLANO',   0, 130, 'N', 'N', 'N', 0, 'N', NULL, 'PAGONOMINA', NULL, 'E', 'A',NULL, 'POSNOPRO')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('REAPLICA',  'REAPLICACION DE PAG Y DES REVERSADOS',           'OTRO',    0, 120, 'N', 'N', 'N', 0, 'N', NULL, 'REAPLICA',   NULL, 'E', 'A',NULL, 'OFI')
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('VAC0',      'TRANSFERENCIA CONTABLE PARA PAGOS MONEDA LEGAL', 'TCON',    0, 100, 'N', 'N', 'N', 0, 'N', NULL, 'VAC0',       NULL, 'E', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('RENOVACION','PAGO POR RENOVACION',                            'OTRO',    0, 110, 'N', 'N', 'N', 0, 'N', 7,    'RENOVACION', NULL, 'V', 'A',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('NC_BCO_MN', 'NOTA CREDITO MN',                                'NCAH',    0, 128, 'N', 'N', 'N', 0, 'N', 99,   'ND_BCO_MN',  'C',  'V', 'A',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('ND_BCO_MN', 'NOTA DEBITO MN',                                 'NDAH',    0, 129, 'N', 'S', 'N', 0, 'S', 99,   'NC_BCO_MN',  'D',  'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('OPEN_PAY',  'OPEN PAY',                                       'CORRESP', 0, 137, 'N', 'N', 'N', 0, 'N', NULL, 'OPEN_PAY',   'D',  'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('SANTANDER', 'BANCO SANTANDER',                                'CORRESP', 0, 131, 'N', 'N', 'N', 0, 'N', NULL, 'SANTANDER',  'D',  'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('GAR_DEB',   'DISMINUIR VALOR DE LA GARANTIA',                 'OTRO',    0, 132, 'N', 'N', 'N', 0, 'N', 19,   'GAR_CRE',    'D',  'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('GAR_CRE',   'INCREMENTAR VALOR DE LA GARANTIA',               'OTRO',    0, 133, 'N', 'N', 'N', 0, 'N', 19,   'GAR_DEB',    'C',  'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('SOBRANTE',  'SOBRANTE EN CANCELACION TOTAL',                  'TCON',    0, 136, 'N', 'N', 'N', 0, 'N', NULL, 'SOBRANTE',    NULL,'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('DEV_SEG',   'DEVOLUCION PAGO SEGURO',                         'OTRO',    0, 138, 'N', 'S', 'N', 0, 'S', NULL, 'DEV_SEG',     NULL,'V', 'T',NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('SALDOSMINI','PAGO PARA SALDOS MENOR CUANTIA',			'SALDOSMINI',     0, 140, 'N', 'S', 'N', 0, 'N', NULL, 'SALDOSMINI', 'D', 'V', 'T', NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('OBJETADO' ,'OBJETADO'										,'OTRO', 	  0 ,142 ,'N', 'S' ,'N' ,0, 'N',NULL , 'OBJETADO'  , 'D'  ,'V', 'T', NULL  ,NULL ) 
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('QUEBRANTO' ,'QUEBRANTO'									,'OTRO'	,	 0, 143 ,'N', 'S' ,'N' ,0 , 'N',NULL  ,'QUEBRANTO' , 'D'  ,'V', 'T' , NULL , NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('FALLECIDO', 'FALLECIDO',			                           'OTRO',    0, 144, 'N', 'S', 'N', 0, 'N', NULL, 'FALLECIDO',  'D', 'V', 'T', NULL, NULL)
insert into ca_producto(cp_producto, cp_descripcion, cp_categoria, cp_moneda, cp_codvalor, cp_desembolso, cp_pago, cp_atx, cp_retencion, cp_pago_aut, cp_pcobis, cp_producto_reversa, cp_afectacion, cp_estado, cp_act_pas, cp_instrum_SB, cp_canal) values('OXXO',      'CORRESPONSAL OXXO',                              'CORRESP', 0, 139, 'N', 'S', 'N', 0, 'N', NULL, 'OXXO',       'D',  'V', 'T',NULL, NULL)

go

