use cob_cartera
go

delete from ca_valor
where va_tipo in ('APERCRED','BALIQCACT','BALIQCPAS','BAPROGRACT','BAPROGRPAS','COMDES','COMFNG','COMIFAG','COMIFGA','COMPER','COMUSAID',
'CXCVAL','DTF','EXEQUIAL','INTCTE','IVA','MICROSEG','SEGDEUANT','SEGDEUEM','SEGDEUVEN','TCERO','TGMF','TIASOFINAC','TIASOFIPAS','TIBA',
'TICALIANZA','TICASORUR','TICCB','TICCC1','TICCC2','TICCDANMPA','TICCESFUN','TICCLCONSO','TICCUBMICR','TICHEXP','TICLECHEM','TICMULRU',
'TICO','TICPBENCOL','TICPLANSEM','TIFIEMPACT','TIFIEMPPA','TIHPBE','TIMBRE','TIOLAINVER','TLU','TLU1','TLU2','TLU3','TLU4','TMM','TMSEGDAN',
'TMSEGDAN1','TMSEGDAN2','TMSEGDAN3','TMSEGDAN4','TMSEGEXE','TMSEGEXE1','TMSEGEXE2','TMSEGEXE3','TMSEGEXE4','TMSEGPRI','TMSEGPRI1','TMSEGPRI2',
'TMSEGPRI3','TMSEGPRI4','TMSEGVID','TMSEGVID1','TMSEGVID2','TMSEGVID3','TMSEGVID4','TFIJA', 'TINT', 'TMORA','TINTGRP','TINTIND','TINTINTER',
'TIVA','TCMORA','TPREPAGO','VCMORA')

--ca_valor
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('APERCRED', 'APERTURA DE CREDITO', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('BALIQCACT', 'INTERES CORRIENTE BANCOLDEX LIQUIDEZ CONTRACICLICO', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('BALIQCPAS', 'INTERES CORRIENTE BANCOLDEX LIQUIDEZ CONTRAC PAS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('BAPROGRACT', 'INTERES CORRIENTE BANCOLDEX A PROGESAR ACTIVAS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('BAPROGRPAS', 'INTERES CORRIENTE BANCOLDEX A PROGESAR PASIVA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('COMDES', 'COMISION DESEMBOLSO', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('COMFNG', 'FACTOR COMISION FNG', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('COMIFAG', 'FACTOR COMISION FAG', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('COMIFGA', 'COMISION FONDO GARANTIA DE ANTIOQUIA FGA', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('COMPER', 'COMISION PERIODICA', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('COMUSAID', 'FACTOR COMISION USAID', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('CXCVAL', 'RANGO CXC AJUSTES', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('DTF', 'TASA PROMEDIO DE CAPTACIONES', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('EXEQUIAL', 'VALOR A APLICAR SEGURO EXEQUIAL', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('INTCTE', 'TASA DE INTERES CORRIENTE', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('IVA', 'TASA IMPUESTO AL VALOR AGREGADO', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('MICROSEG', 'SEGURO DE VIDA TRANQUILIDAD', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('SEGDEUANT', 'SEGURO DEUDORES ANTICIPADO', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('SEGDEUEM', 'SEGURO DEUDORES EMPLEADOS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('SEGDEUVEN', 'SEGURO DEUDORES VENCIDO', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TGMF', 'TASA GRAVAMEN MOVIMIENTO FINANCIERO', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIASOFINAC', 'TASA DE INTERES ASOCIATIVO FINAGRO ACTIVA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIASOFIPAS', 'TASA DE INTERES ASOCIATIVO FINAGRO PASIVA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIBA', 'TASA INTERES CORRIENTE BANCAMIA ACTIVAS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICALIANZA', 'TASA DE INTERES CORRIENTE ALIANZAS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICASORUR', 'TASA INTERES CORRIENTE ASOCIATIVO RURAL', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCB', 'TASA DE INTERES CORRIENTE CORRESPONSAL BANCARIO', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCC1', 'TASA INTERES CORRIENTE CLIENTES CONSOLIDACION 1', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCC2', 'TASA INTERES CORRIENTE CLIENTES CONSOLIDACION 2', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCDANMPA', 'TASA DE INTERES CORRIENTE CLIENTES DANMIFICADOS PA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCESFUN', 'TASA DE INTERES CORRIENTE ESPECIAL FUNCIONARIOS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCLCONSO', 'TASA DE INTERES CORRIENTE CLIENTES CONSOLIDACION', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICCUBMICR', 'TASA DE INTERES CORRIENTE CUPO BANCA MICROEMPRESA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICHEXP', 'TASA DE INTERES CORRIENTE HIPOTECARIA EXEMPLEADOS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICLECHEM', 'TASA DE INTERES CORRIENTE CONVENIO ALQUERIA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICMULRU', 'TASA INTERES CORRIENTE MULTIPROPOSITO RURAL', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICO', 'TASA DE INTERES CORRIENTE CONTRAOFERTAS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICPBENCOL', 'TASA DE INTERES CORRIENTE PLAN DE BENEFICIOS COLABORADORES', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TICPLANSEM', 'TASA DE INTERES CORRIENTE PLAN SEMILLA BANCAMIA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIFIEMPACT', 'TASA INTERES CORRIENTE FINAGRO EMPRESARIAL ACTIVA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIFIEMPPA', 'TASA INTERES CORRIENTE FINAGRO EMPRESARIAL PASIVA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIHPBE', 'TASA DE INTERES HIPOTECARIA PLAN DE BENEFICIOS EMPLEADOS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIMBRE', 'TASA DE IMPUESTO DE TIMBRE', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIOLAINVER', 'TASA DE INTERES CORRIENTE OLA INVERNAL', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TLU', 'TASA LIMITE DE USURA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TLU1', 'TLU1', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TLU2', 'TLU2', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TLU3', 'TLU3', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TLU4', 'TLU4', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMM', 'TASA MAXIMA MORATORIA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGDAN', 'TASA INTERES MORA SEGURO DAÑOS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGDAN1', 'TASA MORA DAÑOS1', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGDAN2', 'TASA MORA DAÑOS2', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGDAN3', 'TASA MORA DAÑOS3', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGDAN4', 'TASA MORA DAÑOS4', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGEXE', 'TASA INTERES MORA SEGURO EXEQUIAS', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGEXE1', 'TASA MORA EXEQUIAL1', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGEXE2', 'TASA MORA EXEQUIAL2', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGEXE3', 'TASA MORA EXEQUIAL3', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGEXE4', 'TASA MORA EXEQUIAL4', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGPRI', 'TASA INTERES MORA SEGURO PRIMERA PERDIDA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGPRI1', 'TASA MORA PRIMERA PERDIDA1', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGPRI2', 'TASA MORA PRIMERA PERDIDA2', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGPRI3', 'TASA MORA PRIMERA PERDIDA3', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGPRI4', 'TASA MORA PRIMERA PERDIDA4', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGVID', 'TASA INTERES MORA SEGURO VIDA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGVID1', 'TASA MORA SEGURO DE VIDA1', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGVID2', 'TASA MORA SEGURO DE VIDA2', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGVID3', 'TASA MORA SEGURO DE VIDA3', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMSEGVID4', 'TASA MORA SEGURO DE VIDA4', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TFIJA', 'TASA FIJA CORRIENTE O DE MORA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TINT', 'TASA DE INTERES', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TMORA', 'TASA DE MORA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TCERO', 'TASA FIJA CORRIENTE O DE MORA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TINTGRP', 'TASA APLICAR INT GRUPAL', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TINTIND', 'TASA APLICAR INT INDIVIDUAL', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TINTINTER', 'TASA APLICAR INT INTERCICLO', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TIVA', 'TASA IVA', 'V', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TCMORA', 'TASA COMISION MORA', 'F', 'N')
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('TPREPAGO', 'TASA PREPAGO', 'V', 'N')
---------------------------------------------
insert into ca_valor (va_tipo, va_descripcion, va_clase, va_pit) values ('VCMORA', 'VALOR COMISION MORA', 'V', 'N')
---------------------------------------------

delete from ca_valor_det
where vd_tipo in ('APERCRED','BALIQCACT','BALIQCPAS','BAPROGRACT','BAPROGRPAS','COMDES','COMFNG','COMIFAG','COMIFGA','COMPER','COMUSAID',
'CXCVAL','DTF','EXEQUIAL','INTCTE','IVA','MICROSEG','SEGDEUANT','SEGDEUEM','SEGDEUVEN','TCERO','TGMF','TIASOFINAC','TIASOFIPAS','TIBA',
'TICALIANZA','TICASORUR','TICCB','TICCC1','TICCC2','TICCDANMPA','TICCESFUN','TICCLCONSO','TICCUBMICR','TICHEXP','TICLECHEM','TICMULRU',
'TICO','TICPBENCOL','TICPLANSEM','TIFIEMPACT','TIFIEMPPA','TIHPBE','TIMBRE','TIOLAINVER','TLU','TLU1','TLU2','TLU3','TLU4','TMM','TMSEGDAN',
'TMSEGDAN1','TMSEGDAN2','TMSEGDAN3','TMSEGDAN4','TMSEGEXE','TMSEGEXE1','TMSEGEXE2','TMSEGEXE3','TMSEGEXE4','TMSEGPRI','TMSEGPRI1','TMSEGPRI2',
'TMSEGPRI3','TMSEGPRI4','TMSEGVID','TMSEGVID1','TMSEGVID2','TMSEGVID3','TMSEGVID4','TFIJA', 'TINT', 'TMORA','TINTGRP','TINTIND','TINTINTER',
'TIVA','TCMORA','TPREPAGO','VCMORA')

--ca_valor_det
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('APERCRED', '1', NULL, 10172, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('APERCRED', '4', NULL, 10172, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('BALIQCACT', '1', '+', 18, '+', 18, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('BALIQCPAS', '1', '+', 2.5, '+', 2.5, '+', 0, 'DTF', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('BAPROGRACT', '1', '+', 18, '+', 18, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('BAPROGRPAS', '1', '+', 3.2000000000000002, '+', 3.2000000000000002, '+', 0, 'DTF', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMDES', '1', NULL, 1.55, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMDES', '4', NULL, 1.55, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMFNG', '1', NULL, 1.55, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMFNG', '4', NULL, 1.55, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMIFAG', '1', NULL, 1.5, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMIFAG', '4', NULL, 1.5, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMIFGA', '1', NULL, 1.55, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMIFGA', '4', NULL, 1.55, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMPER', '1', NULL, 1.55, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMPER', '4', NULL, 1.55, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMUSAID', '1', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('COMUSAID', '4', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('CXCVAL', '1', '+', 1, '+', 4000000, '+', 1, 'TCERO', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('CXCVAL', '2', '+', 1, '+', 4000000, '+', 1, 'TCERO', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('CXCVAL', '3', '+', 1, '+', 4000000, '+', 1, 'TCERO', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('CXCVAL', '4', '+', 1, '+', 4000000, '+', 1, 'TCERO', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('DTF', '1', '+', 0, '+', 0, '+', 0, 'DTF', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('DTF', '4', '+', 0, '+', 0, '+', 0, 'DTF', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('EXEQUIAL', '1', '+', 1, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('EXEQUIAL', '4', '+', 1, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('INTCTE', '1', '+', 0, '+', 0, '+', 0, 'TLU1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('INTCTE', '4', '+', 0, '+', 0, '+', 0, 'TLU4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('IVA', '1', NULL, 16, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('IVA', '2', NULL, 16, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('IVA', '3', NULL, 16, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('IVA', '4', NULL, 16, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('MICROSEG', '1', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('MICROSEG', '4', NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUANT', '1', '+', 0, '+', 0, '+', 0, 'TSEGANT', 'B', 6)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUANT', '4', '+', 0, '+', 0, '+', 0, 'TSEGANT', 'B', 6)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUEM', '1', '+', 0, '+', 0, '+', 0, 'TSEGEM', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUEM', '2', '+', 0, '+', 0, '+', 0, 'TSEGEM', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUEM', '3', '+', 0, '+', 0, '+', 0, 'TSEGEM', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUEM', '4', '+', 0, '+', 0, '+', 0, 'TSEGEM', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUVEN', '1', '+', 0, '+', 0, '+', 0, 'TSEGVEN', 'B', 6)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUVEN', '2', '+', 0, '+', 0, '+', 0, 'TSEGVEN', 'B', 6)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUVEN', '3', '+', 0, '+', 0, '+', 0, 'TSEGVEN', 'B', 6)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('SEGDEUVEN', '4', '+', 0, '+', 0, '+', 0, 'TSEGVEN', 'B', 6)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TGMF', '1', '+', 0, '+', 0, '+', 0, 'TGMF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TGMF', '2', '+', 0, '+', 0, '+', 0, 'TGMF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TGMF', '3', '+', 0, '+', 0, '+', 0, 'TGMF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TGMF', '4', '+', 0, '+', 0, '+', 0, 'TGMF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIASOFINAC', '1', '+', 10, '+', 10, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIASOFINAC', '4', '+', 10, '+', 10, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIASOFIPAS', '1', '-', 3.5, '-', 0, '-', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIASOFIPAS', '4', '-', 3.5, '-', 0, '-', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIBA', '1', '+', 0, '+', 0, '+', 0, 'TIBA1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIBA', '4', '+', 0, '+', 0, '+', 0, 'TIBA4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICALIANZA', '1', '+', 0, '+', 0, '+', 0, 'TICALIANZ', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICALIANZA', '4', '+', 0, '+', 0, '+', 0, 'TICALIANZ4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICASORUR', '1', '+', 0, '+', 0, '+', 0, 'TICASORUR', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICASORUR', '4', '+', 0, '+', 0, '+', 0, 'TICASORUR', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCB', '1', '+', 0, '+', 0, '+', 0, 'TICCB1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCB', '4', '+', 0, '+', 0, '+', 0, 'TICCB4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCC1', '1', '+', 0, '+', 0, '+', 0, 'TICCC2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCC1', '4', '+', 0, '+', 0, '+', 0, 'TICCC2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCC2', '1', '+', 0, '+', 0, '+', 0, 'TICCC3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCC2', '4', '+', 0, '+', 0, '+', 0, 'TICCC3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCDANMPA', '1', '+', 0, '+', 0, '+', 0, 'TICCCPAGR1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCDANMPA', '4', '+', 0, '+', 0, '+', 0, 'TICMCPAGR4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCESFUN', '2', '+', 0, '+', 0, '+', 0, 'TICCESFUN', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCLCONSO', '1', '+', 0, '+', 0, '+', 0, 'TICCC1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCLCONSO', '4', '+', 0, '+', 0, '+', 0, 'TICCC1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCUBMICR', '1', '+', 0, '+', 0, '+', 0, 'TIBA1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICCUBMICR', '4', '+', 0, '+', 0, '+', 0, 'TICCUBMICR', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICHEXP', '3', '+', 0, '+', 0, '+', 0, 'TICHEXP', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICLECHEM', '1', '+', 0, '+', 0, '+', 0, 'TCLECH1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICLECHEM', '4', '+', 0, '+', 0, '+', 0, 'TCLECH4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICMULRU', '1', '+', 0, '+', 0, '+', 0, 'TICMULRU', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICMULRU', '4', '+', 0, '+', 0, '+', 0, 'TICMULRU', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICO', '4', '+', 0, '+', 0, '+', 0, 'TICO', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICPBENCOL', '2', '+', 0, '+', 0, '+', 0, 'TICPBENCOL', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICPLANSEM', '1', '+', 0, '+', 0, '+', 0, 'TICPLANSEM', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TICPLANSEM', '4', '+', 0, '+', 0, '+', 0, 'TICPLANSEM', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIFIEMPACT', '1', '+', 10, '+', 10, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIFIEMPACT', '4', '+', 10, '+', 10, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIFIEMPPA', '1', '-', 3.5, '-', 0, '-', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIFIEMPPA', '4', '-', 3.5, '-', 0, '-', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIHPBE', '3', '+', 0, '+', 0, '+', 0, 'TIHPBE', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIMBRE', '1', '+', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIMBRE', '4', '+', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIOLAINVER', '1', '+', 0, '+', 0, '+', 0, 'TIOLAINV1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TIOLAINVER', '4', '+', 0, '+', 0, '+', 0, 'TIOLAINV4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU', '1', '+', 0, '+', 0, '+', 0, 'TLU1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU', '2', '+', 0, '+', 0, '+', 0, 'TLU2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU', '3', '+', 0, '+', 0, '+', 0, 'TLU3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU1', '1', '+', 0, '+', 0, '+', 0, 'TLU1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU1', '2', '+', 0, '+', 0, '+', 0, 'TLU1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU1', '3', '+', 0, '+', 0, '+', 0, 'TLU1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU2', '1', '+', 0, '+', 0, '+', 0, 'TLU2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU2', '2', '+', 0, '+', 0, '+', 0, 'TLU2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU2', '3', '+', 0, '+', 0, '+', 0, 'TLU2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU3', '1', '+', 0, '+', 0, '+', 0, 'TLU3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU3', '2', '+', 0, '+', 0, '+', 0, 'TLU3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU3', '3', '+', 0, '+', 0, '+', 0, 'TLU3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU4', '1', '+', 0, '+', 0, '+', 0, 'TLU4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU4', '2', '+', 0, '+', 0, '+', 0, 'TLU4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TLU4', '3', '+', 0, '+', 0, '+', 0, 'TLU4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMM', '1', '+', 0, '+', 0, '+', 0, 'TMM1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMM', '2', '+', 0, '+', 0, '+', 0, 'TMM2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMM', '3', '+', 0, '+', 0, '+', 0, 'TMM3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMM', '4', '+', 0, '+', 0, '+', 0, 'TMM4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN', '1', '+', 0, '+', 0, '+', 0, 'TMSEGDAN1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN', '2', '+', 0, '+', 0, '+', 0, 'TMSEGDAN2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN', '3', '+', 0, '+', 0, '+', 0, 'TMSEGDAN3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN', '4', '+', 0, '+', 0, '+', 0, 'TMSEGDAN4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN1', '1', '+', 0, '+', 0, '+', 0, 'TMSEGDAN1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN1', '2', '+', 0, '+', 0, '+', 0, 'TMSEGDAN1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN1', '3', '+', 0, '-', 0, '+', 0, 'TMSEGDAN1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN1', '4', '+', 0, '+', 0, '+', 0, 'TMSEGDAN1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN2', '1', '+', 0, '+', 0, '+', 0, 'TMSEGDAN2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN2', '2', '+', 0, '+', 0, '+', 0, 'TMSEGDAN2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN2', '3', '+', 0, '+', 0, '+', 0, 'TMSEGDAN2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN2', '4', '+', 0, '+', 0, '+', 0, 'TMSEGDAN2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN3', '1', '+', 0, '+', 0, '+', 0, 'TMSEGDAN3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN3', '2', '+', 0, '+', 0, '+', 0, 'TMSEGDAN3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN3', '3', '+', 0, '+', 0, '+', 0, 'TMSEGDAN3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN3', '4', '+', 0, '+', 0, '+', 0, 'TMSEGDAN3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN4', '1', '+', 0, '+', 0, '+', 0, 'TMSEGDAN4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN4', '2', '+', 0, '+', 0, '+', 0, 'TMSEGDAN4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN4', '3', '+', 0, '+', 0, '+', 0, 'TMSEGDAN4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGDAN4', '4', '+', 0, '+', 0, '+', 0, 'TMSEGDAN4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE', '1', '+', 0, '+', 0, '+', 0, 'TMSEGEXE1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE', '2', '+', 0, '+', 0, '+', 0, 'TMSEGEXE2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE', '3', '+', 0, '+', 0, '+', 0, 'TMSEGEXE3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE', '4', '+', 0, '+', 0, '+', 0, 'TMSEGEXE4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE1', '1', '+', 0, '+', 0, '+', 0, 'TMSEGEXE1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE1', '2', '+', 0, '+', 0, '+', 0, 'TMSEGEXE1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE1', '3', '+', 0, '+', 0, '+', 0, 'TMSEGEXE1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE1', '4', '+', 0, '+', 0, '+', 0, 'TMSEGEXE1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE2', '1', '+', 0, '+', 0, '+', 0, 'TMSEGEXE2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE2', '2', '+', 0, '+', 0, '+', 0, 'TMSEGEXE2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE2', '3', '+', 0, '+', 0, '+', 0, 'TMSEGEXE2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE2', '4', '+', 0, '+', 0, '+', 0, 'TMSEGEXE2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE3', '1', '+', 0, '+', 0, '+', 0, 'TMSEGEXE3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE3', '2', '+', 0, '+', 0, '+', 0, 'TMSEGEXE3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE3', '3', '+', 0, '+', 0, '+', 0, 'TMSEGEXE3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE3', '4', '+', 0, '+', 0, '+', 0, 'TMSEGEXE3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE4', '1', '+', 0, '+', 0, '+', 0, 'TMSEGEXE4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE4', '2', '+', 0, '+', 0, '+', 0, 'TMSEGEXE4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE4', '3', '+', 0, '+', 0, '+', 0, 'TMSEGEXE4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGEXE4', '4', '+', 0, '+', 0, '+', 0, 'TMSEGEXE4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI', '1', '+', 0, '+', 0, '+', 0, 'TMSEGPRI1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI', '2', '+', 0, '+', 0, '+', 0, 'TMSEGPRI2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI', '3', '+', 0, '+', 0, '+', 0, 'TMSEGPRI3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI', '4', '+', 0, '+', 0, '+', 0, 'TMSEGPRI4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI1', '1', '+', 0, '+', 0, '+', 0, 'TMSEGPRI1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI1', '2', '+', 0, '+', 0, '+', 0, 'TMSEGPRI1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI1', '3', '+', 0, '+', 0, '+', 0, 'TMSEGPRI1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI1', '4', '+', 0, '+', 0, '+', 0, 'TMSEGPRI1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI2', '1', '+', 0, '+', 0, '+', 0, 'TMSEGPRI2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI2', '2', '+', 0, '+', 0, '+', 0, 'TMSEGPRI2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI2', '3', '+', 0, '+', 0, '+', 0, 'TMSEGPRI2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI2', '4', '+', 0, '+', 0, '+', 0, 'TMSEGPRI2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI3', '1', '+', 0, '+', 0, '+', 0, 'TMSEGPRI3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI3', '2', '+', 0, '+', 0, '+', 0, 'TMSEGPRI3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI3', '3', '+', 0, '+', 0, '+', 0, 'TMSEGPRI3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI3', '4', '+', 0, '+', 0, '+', 0, 'TMSEGPRI3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI4', '1', '+', 0, '+', 0, '+', 0, 'TMSEGPRI4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI4', '2', '+', 0, '+', 0, '+', 0, 'TMSEGPRI4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI4', '3', '+', 0, '+', 0, '+', 0, 'TMSEGPRI4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGPRI4', '4', '+', 0, '+', 0, '+', 0, 'TMSEGPRI4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID', '1', '+', 0, '+', 0, '+', 0, 'TMSEGVID1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID', '2', '+', 0, '+', 0, '+', 0, 'TMSEGVID2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID', '3', '+', 0, '+', 0, '+', 0, 'TMSEGVID3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID', '4', '+', 0, '+', 0, '+', 0, 'TMSEGVID4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID1', '1', '+', 0, '+', 0, '+', 0, 'TMSEGVID1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID1', '2', '+', 0, '+', 0, '+', 0, 'TMSEGVID1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID1', '3', '+', 0, '+', 0, '+', 0, 'TMSEGVID1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID1', '4', '+', 0, '+', 0, '+', 0, 'TMSEGVID1', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID2', '1', '+', 0, '+', 0, '+', 0, 'TMSEGVID2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID2', '2', '+', 0, '+', 0, '+', 0, 'TMSEGVID2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID2', '3', '+', 0, '+', 0, '+', 0, 'TMSEGVID2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID2', '4', '+', 0, '+', 0, '+', 0, 'TMSEGVID2', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID3', '1', '+', 0, '+', 0, '+', 0, 'TMSEGVID3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID3', '2', '+', 0, '+', 0, '+', 0, 'TMSEGVID3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID3', '3', '+', 0, '+', 0, '+', 0, 'TMSEGVID3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID3', '4', '+', 0, '+', 0, '+', 0, 'TMSEGVID3', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID4', '1', '+', 0, '+', 0, '+', 0, 'TMSEGVID4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID4', '2', '+', 0, '+', 0, '+', 0, 'TMSEGVID4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID4', '3', '+', 0, '+', 0, '+', 0, 'TMSEGVID4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMSEGVID4', '4', '+', 0, '+', 0, '+', 0, 'TMSEGVID4', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TFIJA', '1', '+', 34, '+', 36, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TFIJA', '2', '+', 34, '+', 36, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TFIJA', '3', '+', 34, '+', 36, '+', 0, 'DTF', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TINT', '1', '+', 10.38, '+', 10.38, '+', 0, 'TCERO', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TINT', '2', '+', 10, '+', 10, '+', 0, 'TCERO', 'B', 2)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMORA', '1', '+', 124.56, '+', 124.56, '+', 0, 'TCERO', 'B', 4 )
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TMORA', '2', '+', 10, '+', 15, '+', 10, 'TCERO', 'B', 2 )
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TCERO', '1', '+', 0, '+', 0, '+', 0, 'TCERO', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TCERO', '2', '+', 0, '+', 0, '+', 0, 'TCERO', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values ('TCERO', '3', '+', 0, '+', 0, '+', 0, 'TCERO', 'B', 4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTGRP','1','+',0,'+',0,'-',18,'TRGRP','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTGRP','2','+',0,'+',0,'-',18,'TRGRP','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTGRP','3','+',0,'+',0,'-',18,'TRGRP','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTIND','1','+',0,'+',0,'+',0,'TRIND','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTIND','2','+',0,'+',0,'+',0,'TRIND','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTIND','3','+',0,'+',0,'+',0,'TRIND','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTINTER','1','+',0,'+',0,'+',0,'TRINTER','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTINTER','2','+',0,'+',0,'+',0,'TRINTER','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TINTINTER','3','+',0,'+',0,'+',0,'TRINTER','B',4)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TIVA','1','+',16,'+',0,'+',0,NULL,NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TIVA','2','+',16,'+',0,'+',0,NULL,NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TIVA','3','+',16,'+',0,'+',0,NULL,NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TCMORA','1','+',6,'+',999999,'+',0,'TCERO',NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TCMORA','2','+',6,'+',999999,'+',0,'TCERO',NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TCMORA','3','+',6,'+',999999,'+',0,'TCERO',NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TPREPAGO','1','+',0,'+',999999,'+',0,'TCERO',NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TPREPAGO','2','+',0,'+',999999,'+',0,'TCERO',NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('TPREPAGO','3','+',0,'+',999999,'+',0,'TCERO',NULL,NULL)
---------------------------------------------
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('VCMORA','1','+',200.00,'+',0,'+',0,NULL,NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('VCMORA','2','+',200.00,'+',0,'+',0,NULL,NULL,NULL)
insert into ca_valor_det (vd_tipo, vd_sector, vd_signo_default, vd_valor_default, vd_signo_maximo, vd_valor_maximo, vd_signo_minimo, vd_valor_minimo, vd_referencia, vd_tipo_puntos, vd_num_dec) values('VCMORA','3','+',200.00,'+',0,'+',0,NULL,NULL,NULL)
---------------------------------------------
go



/* TASAS REFERENCIALES */
delete from cobis..te_tpizarra
where pi_referencia in ('TRGRP','TRINTER', 'TRIND','TLU1', 'TLU2', 'TLU3', 'TLU4','TCERO','TMM1','TMM2','TMM3','TMM4')
go

declare @w_secuencial int

SELECT @w_secuencial = isnull(max(pi_cod_pizarra), 0) + 1 FROM cobis..te_tpizarra

insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 60, '2027-01-01', '2017-01-01', 'TRGRP', 1, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 72, '2027-01-01', '2017-01-01', 'TRINTER', 1, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 96, '2027-01-01', '2017-01-01', 'TRIND', 1, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TLU1', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TLU2', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TLU3', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TLU4', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 0, '2027-01-01', '2017-01-01', 'TCERO', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TMM1', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TMM2', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TMM3', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
SELECT @w_secuencial = @w_secuencial +1
insert into cobis..te_tpizarra (pi_cod_pizarra, pi_moneda, pi_valor, pi_fecha_fin, pi_fecha_inicio, pi_referencia, pi_periodo, pi_modalidad, pi_tipo_valor, pi_tipo_tasa, pi_rango_desde, pi_rango_hasta, pi_caracteristica, pi_autoriza, pi_login) values (@w_secuencial, 0, 200, '2027-01-01', '2010-01-01', 'TMM4', 4, 'V', 'T', 'A', NULL, NULL, 'E', 'S', 'admuser')
go

delete from cobis..te_tasas_referenciales
where tr_tasa in ('TRGRP','TRINTER', 'TRIND', 'TLU1', 'TLU2', 'TLU3', 'TLU4', 'TCERO','TMM1','TMM2','TMM3','TMM4')
go

insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TRGRP', 'Tasa referencial grupal', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TRINTER', 'Tasa referencial Interciclo', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TRIND', 'Tasa referencial individual', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TLU1', 'TASA LIMITE DE USURA COMERCIAL', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TLU2', 'TASA LIMITE DE USURA CONSUMO', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TLU3', 'TASA LIMITE DE USURA VIVIENDA', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TLU4', 'TASA LIMITE DE USURA MICROCREDITO', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TCERO', 'TASA CERO SIN VALOR', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TMM1', 'TASA MAXIMA DE MORA COMERCIAL', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TMM2', 'TASA MAXIMA DE MORA CONSUMO', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TMM3', 'TASA MAXIMA DE MORA VIVIENDA', 'V')
insert into cobis..te_tasas_referenciales (tr_tasa, tr_descripcion, tr_estado) values ('TMM4', 'TASA MAXIMA DE MORA MICROCREDITO', 'V')


