use cob_cartera
go

delete ca_concepto_bancamia
 where co_codigo in (116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,
                     137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,
                     158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,
                     179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,
                     200,201,202,203,204,205,206,207,208,209)
go

insert into ca_concepto_bancamia values ('CO_ERR',      'CONCEPTO RUBRO NO EXISTENTE (INGRESO)',116,'R')
insert into ca_concepto_bancamia values ('DR',          'Diferencias en recaudos (INGRESO)',117,'R')
insert into ca_concepto_bancamia values ('REC_IVA',     'RECAUDO DE IVA',118,'R')
insert into ca_concepto_bancamia values ('PAGONOM',     'PAGOS NOMINA',119,'R')
insert into ca_concepto_bancamia values ('INGRECARA',   'PAGO OFICINA CARACAS',120,'R')
insert into ca_concepto_bancamia values ('INGREVEN',    'PAGOS OFICINA VENECIA',121,'R')
insert into ca_concepto_bancamia values ('INGREENGA',   'PAGOS OFICINA ENGATIVA',122,'R')
insert into ca_concepto_bancamia values ('INGREMES',    'PAGO OFICINAS MESITAS',123,'R')
insert into ca_concepto_bancamia values ('DREG',        'DIFERENCIAS EN RECAUDO (EGRESOS)',124,'R')
insert into ca_concepto_bancamia values ('INGREMAY',    'PAGO OF. 1RO DE MAYO',125,'R')
insert into ca_concepto_bancamia values ('INGREABA',    'PAGOS O. PATIO BONITO',126,'R')
insert into ca_concepto_bancamia values ('INGRESUB',    'PAGO OFICINA SUBA',127,'R')
insert into ca_concepto_bancamia values ('INGREKEN',    'PAGOS OFICINA KENEDY',128,'R')
insert into ca_concepto_bancamia values ('PGCOMP',      'PAGOS ADMNISTRATIVOS COMPRAS',129,'R')
insert into ca_concepto_bancamia values ('HONOAB',      'HONORARIOS ABOGADOS',130,'R')
insert into ca_concepto_bancamia values ('INGREVIC',    'PAGOS OFICINA LA VICTORIA',131,'R')
insert into ca_concepto_bancamia values ('INGRERIN',    'PAGOS OFICINA SUBA RINCON',132,'R')
insert into ca_concepto_bancamia values ('INGRESTA',    'PAGOS OFICINA SANTA HELENITA',133,'R')
insert into ca_concepto_bancamia values ('INGREQUI',    'PAGOS OFICINA QUIRIGUA',134,'R')
insert into ca_concepto_bancamia values ('INGRELIB',    'PAGOS OF. LA LIBERTAD',135,'R')
insert into ca_concepto_bancamia values ('RCC',         'RECUPERACION DE CARTERA CASTIGADA',136,'R')
insert into ca_concepto_bancamia values ('PGCJME',      'PAGOS ADMNISTRATIVOS CAJA MENOR',137,'R')
insert into ca_concepto_bancamia values ('PGSERV',      'PAGOS ADM SERVICIOS',138,'R')
insert into ca_concepto_bancamia values ('RA',          'REINTEGRO ANTICIPOS',139,'R')
insert into ca_concepto_bancamia values ('INGRETEJ',    'PAGOS OFICINA EL TEJAR',140,'R')
insert into ca_concepto_bancamia values ('PGHONO',      'PAGOS ADMNSINTRATIVOS HONORARIOS',141,'R')
insert into ca_concepto_bancamia values ('PSMI',        'CANCELACION DE SALDOS MINIMOS EN CARTERA',142,'R')
insert into ca_concepto_bancamia values ('INGREFON',    'PAGOS OFICINA FONTIBON',143,'R')
insert into ca_concepto_bancamia values ('CP',          'COBRO JURIDICO',144,'R')
insert into ca_concepto_bancamia values ('INGRESOA',    'PAGOS OFICINA SOHACHA',145,'R')
insert into ca_concepto_bancamia values ('INGREBOS',    'PAGOS OFICINA BOSA',146,'R')
insert into ca_concepto_bancamia values ('INGREGIR',    'PAGOS OFICINA GIRARDOT',147,'R')
insert into ca_concepto_bancamia values ('PADMOIN',     'PAGOS ADMINSITRATIVOS',148,'R')
insert into ca_concepto_bancamia values ('INGREFUS',    'PAGOS OFICINA FUSAGASUGA',149,'R')
insert into ca_concepto_bancamia values ('INGRESAN',    'PAGOS OFICINA SAN FRANCISCO',150,'R')
insert into ca_concepto_bancamia values ('INGRETOB',    'PAGOS OFICINA TOBERIN',151,'R')
insert into ca_concepto_bancamia values ('INGREYOM',    'PAGOS OFICINA YOMASA',152,'R')
insert into ca_concepto_bancamia values ('SCD',         'SANCION CHEQUE DEVULETO',153,'R')
insert into ca_concepto_bancamia values ('INGRERES',    'PAGOS OFICINA RESTREPO',154,'R')
insert into ca_concepto_bancamia values ('INGREFUN',    'PAGOS OFICINA FUNZA',155,'R')
insert into ca_concepto_bancamia values ('SVSURA',      'SEGURO DE VIDA SURAMERICANA',156,'R')
insert into ca_concepto_bancamia values ('HJ',          'HONORARIOS JURIDICOS',157,'R')
insert into ca_concepto_bancamia values ('INGRETUN',    'PAGO OFICIN TUNJA',158,'R')
insert into ca_concepto_bancamia values ('INGRECHI',    'PAGO OFICINA CHIQUINQUIRA',159,'R')
insert into ca_concepto_bancamia values ('INGREDUI',    'PAGO OFICINA DUITAMA',160,'R')
insert into ca_concepto_bancamia values ('INGREDTB',    'PAGO OFICINA MOLINO',161,'R')
insert into ca_concepto_bancamia values ('INGREMON',    'PAGO OFICINA MONIQUIRA',162,'R')
insert into ca_concepto_bancamia values ('INGREPRI',    'PAGO OFICINA PRINCIPAL',163,'R')
insert into ca_concepto_bancamia values ('INGRESOG',    'PAGO OFICINA SOGAMOSO',164,'R')
insert into ca_concepto_bancamia values ('INGREVIL',    'PAGO OFICINA VILLETA',165,'R')
insert into ca_concepto_bancamia values ('INGREZIP',    'PAGO OFICINA ZIPAQUIRA',166,'R')
insert into ca_concepto_bancamia values ('INGREBAR',    'PAGOS OFICINA BARRANCAS',167,'R')
insert into ca_concepto_bancamia values ('INGRECHIA',   'PAGOS OFICINA CHIA',168,'R')
insert into ca_concepto_bancamia values ('INGREFER',    'PAGOS OFICINA SAN FERNANDO',169,'R')
insert into ca_concepto_bancamia values ('NOT',         'RECUPERACION POR APLICAR',170,'R')
insert into ca_concepto_bancamia values ('CCR',         'CONCUSLTA A LAS CENTRALES DE INFORMACION',171,'R')
insert into ca_concepto_bancamia values ('INGREFAC',    'PAGOS OFICINA FACATATIVA',172,'R')
insert into ca_concepto_bancamia values ('CERTIF',      'CERTIFICACIONES',173,'R')
insert into ca_concepto_bancamia values ('CRF',         'CARTAS DE REFERENCIA',174,'R')
insert into ca_concepto_bancamia values ('PADCA',       'PAGOS ADMNO CAJA MENOR',175,'R')
insert into ca_concepto_bancamia values ('RP',          'RETIRO PROCREDITO',176,'R')
insert into ca_concepto_bancamia values ('SALMIN',      'SALDOS MINIMOS DE CARTERA',177,'R')
insert into ca_concepto_bancamia values ('SEX',         'SEGURO EXEQUIAL',178,'R')
--insert into ca_concepto_bancamia values ('DESC_FLAT_IVA','IVA DE DESCUENTO FLAT',179,'R')
insert into ca_concepto_bancamia values ('PADCO',       'PAGOS ADMON COMPRAS',180,'R')
insert into ca_concepto_bancamia values ('PADSER',      'PAGOS ADMON. SERVICIOS',181,'R')
insert into ca_concepto_bancamia values ('DES',         'PAGOS FALTANTES EN CAJA',182,'R')
insert into ca_concepto_bancamia values ('CXS',         'CUENTA X COBRAR SINIESTROS',183,'R')
insert into ca_concepto_bancamia values ('CXPT',        'CXP TERCEROS',184,'R')
insert into ca_concepto_bancamia values ('CXPE',        'CXP EDATEL',185,'R')
insert into ca_concepto_bancamia values ('DESC_FLAT',   'DESCUENTO FLAT',186,'R')
insert into ca_concepto_bancamia values ('PAG_BALOTO',  'RECAUDO BALOTO',187,'R')
insert into ca_concepto_bancamia values ('TRAEG',       'TRASLADO DE VRLES ENTRE CAJEROS (EGERSOS)',189,'R')
insert into ca_concepto_bancamia values ('CNC',         'COMISION NACIONAL (CONSIGNACION)',190,'R')
insert into ca_concepto_bancamia values ('PTRANS',      'PAGOS DE TRANSPORTE',191,'R')
insert into ca_concepto_bancamia values ('CGEFBCOL',    'CONSIGNACION EFECTIVO BANCOLOMBIA',192,'R')
insert into ca_concepto_bancamia values ('CPE',         'CHEQUE PAGADO EN EFECTIVO',193,'R')
insert into ca_concepto_bancamia values ('CEF',         'CONSIGANCION EFECTIVO',194,'R')
insert into ca_concepto_bancamia values ('CCH32',       'CONSIGNACION CHEQUE CAJA SOCIAL',195,'R')
insert into ca_concepto_bancamia values ('CEF01',       'CONSIGNACION EFECTIVO BANCO DE BOGOTA',196,'R')
insert into ca_concepto_bancamia values ('CCH',         'CONSIGNACION EN CHEQUE',197,'R')
insert into ca_concepto_bancamia values ('CGEFBBOG',    'CONSIGNACION EFECTIVO EFECTIVO BANCO DE BOGOTA',198,'R')
insert into ca_concepto_bancamia values ('CGCHBBOG',    'CONSIGNACION CHEQUE BANCO DE BOGOTA',199,'R')
insert into ca_concepto_bancamia values ('CGCHBCSOC',   'CONSIGNACION CHEQUE CAJA SOCIAL',200,'R')
insert into ca_concepto_bancamia values ('CGCHBCOL',    'CONSIGNACIONES CHEQUE BANCOLOMBIA',201,'R')
insert into ca_concepto_bancamia values ('CAMCHEQUES',  'CAMBIO DE CHEQUES COBRADOS POR LA CMMC',202,'R')
insert into ca_concepto_bancamia values ('CXCC',        'RECUPERACION DE CXC A CLIENTES',203,'R')
insert into ca_concepto_bancamia values ('TDO',         'HABILITACION DE CAJA',204,'R')
insert into ca_concepto_bancamia values ('VAREG',       'VARIOS (EGRESOS)',205,'R')
insert into ca_concepto_bancamia values ('COA',         'CANCELACION OPERACI‡N ANTERIOR',206,'R')
insert into ca_concepto_bancamia values ('VAR',         'VARIOS',207,'R')
insert into ca_concepto_bancamia values ('CJM',         'EGRESOS DE CONTABILIDAD Y EGRESOS DE TESORERIA',208,'R')
insert into ca_concepto_bancamia values ('CONVENIO',    'CONVENIO',209,'R')
go

delete ca_concepto_bancamia
 where co_codigo in (210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,
                     231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,
                     252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,
                     273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,
                     294,295,296,297)
go

insert into ca_concepto_bancamia values ('RECCHCXP','RECAUDO EN CHEQUE POR MAYOR VALOR',210,'R')
insert into ca_concepto_bancamia values ('DEVCHCXP','DEVOLUCI„N EN EFECTIVO REC MAYOR VALOR',211,'R')
insert into ca_concepto_bancamia values ('CSGBOGO903','CONSIGNACION EN CHEQUE',212,'R')
insert into ca_concepto_bancamia values ('CSGBCOL203','CONSIGNACION EN CHEQUE',213,'R')
insert into ca_concepto_bancamia values ('CSGAGRA617','CONSIGNACION EN CHEQUE',214,'R')
insert into ca_concepto_bancamia values ('CSGBBVA067','CONSIGNACION EN CHEQUE',215,'R')
insert into ca_concepto_bancamia values ('DECHCOL136','DESEMBOLSO EN CHEQUE',216,'R')
insert into ca_concepto_bancamia values ('DECHAGR617','DESEMBOLSO EN CHEQUE',217,'R')
insert into ca_concepto_bancamia values ('DECHBVA067','DESEMBOLSO EN CHEQUE',218,'R')
insert into ca_concepto_bancamia values ('DECHBOG272','DESEMBOLSO EN CHEQUE',219,'R')
insert into ca_concepto_bancamia values ('DECHBOG166','DESEMBOLSO EN CHEQUE',220,'R')
insert into ca_concepto_bancamia values ('DECHBOG794','DESEMBOLSO EN CHEQUE',221,'R')
insert into ca_concepto_bancamia values ('DECHBOG116','DESEMBOLSO EN CHEQUE',222,'R')
insert into ca_concepto_bancamia values ('DECHBOG566','DESEMBOLSO EN CHEQUE',223,'R')
insert into ca_concepto_bancamia values ('DECHOCC171','DESEMBOLSO EN CHEQUE',224,'R')
insert into ca_concepto_bancamia values ('DECHBCS546','DESEMBOLSO EN CHEQUE',225,'R')
insert into ca_concepto_bancamia values ('RECEFECTIV','RECOLECCION DE EFECTIVO',226,'R')
insert into ca_concepto_bancamia values ('RECEFCO203','RECOLECCION DE EFECTIVO',227,'R')
insert into ca_concepto_bancamia values ('RECEFAG617','RECOLECCION DE EFECTIVO',228,'R')
insert into ca_concepto_bancamia values ('RECEFBV067','RECOLECCION DE EFECTIVO',229,'R')
insert into ca_concepto_bancamia values ('APROVISEFE','APROVISIONAMIENTO DE EFECTIVO',230,'R')
insert into ca_concepto_bancamia values ('APRVCOL136','APROVISIONAMIENTO DE EFECTIVO',231,'R')
insert into ca_concepto_bancamia values ('APRVAGR617','APROVISIONAMIENTO DE EFECTIVO',232,'R')
insert into ca_concepto_bancamia values ('APRVBVA067','APROVISIONAMIENTO DE EFECTIVO',233,'R')
insert into ca_concepto_bancamia values ('APRVBOG272','APROVISIONAMIENTO DE EFECTIVO',234,'R')
insert into ca_concepto_bancamia values ('APRVBOG166','APROVISIONAMIENTO DE EFECTIVO',235,'R')
insert into ca_concepto_bancamia values ('APRVBOG794','APROVISIONAMIENTO DE EFECTIVO',236,'R')
insert into ca_concepto_bancamia values ('APRVBOG116','APROVISIONAMIENTO DE EFECTIVO',237,'R')
insert into ca_concepto_bancamia values ('APRVBOG566','APROVISIONAMIENTO DE EFECTIVO',238,'R')
insert into ca_concepto_bancamia values ('APRVOCC171','APROVISIONAMIENTO DE EFECTIVO',239,'R')
insert into ca_concepto_bancamia values ('APRVBCS546','APROVISIONAMIENTO DE EFECTIVO',240,'R')
insert into ca_concepto_bancamia values ('FALTANCAJA','FALTANTE EN CAJA',241,'R')
insert into ca_concepto_bancamia values ('PAGFALCAJA','PAGO FALTANTE EN CAJA',242,'R')
insert into ca_concepto_bancamia values ('CHANBCOL36','CHEQUE ANULADO PAGADO EN EFECTIVO',243,'R')
insert into ca_concepto_bancamia values ('CHANAGR17','CHEQUE ANULADO PAGADO EN EFECTIVO',244,'R')
insert into ca_concepto_bancamia values ('CHANBBVA67','CHEQUE ANULADO PAGADO EN EFECTIVO',245,'R')
insert into ca_concepto_bancamia values ('CHANBOG72','CHEQUE ANULADO PAGADO EN EFECTIVO',246,'R')
insert into ca_concepto_bancamia values ('CHANBOG66','CHEQUE ANULADO PAGADO EN EFECTIVO',247,'R')
insert into ca_concepto_bancamia values ('CHANBOG94','CHEQUE ANULADO PAGADO EN EFECTIVO',248,'R')
insert into ca_concepto_bancamia values ('CHANBOG16','CHEQUE ANULADO PAGADO EN EFECTIVO',249,'R')
insert into ca_concepto_bancamia values ('CHANBO566','CHEQUE ANULADO PAGADO EN EFECTIVO',250,'R')
insert into ca_concepto_bancamia values ('CHANOCC71','CHEQUE ANULADO PAGADO EN EFECTIVO',251,'R')
insert into ca_concepto_bancamia values ('CHANCSC46','CHEQUE ANULADO PAGADO EN EFECTIVO',252,'R')
insert into ca_concepto_bancamia values ('COBJURIDIC','COBRO JURﬁDICO',253,'R')
insert into ca_concepto_bancamia values ('REVCOBJURI','REVERSO COBRO JURﬁDICO',254,'R')
insert into ca_concepto_bancamia values ('COBROPREJU','COBRO PREJURIDICO',255,'R')
insert into ca_concepto_bancamia values ('REVCOBPREJ','REVERSO COBRO PREJURIDICO',256,'R')
insert into ca_concepto_bancamia values ('RECCASTIGO','RECUPERACION DE CARTERA CASTIGADA',257,'R')
insert into ca_concepto_bancamia values ('APLRECASTI','APLICACI‡N CARTERA CASTIGADA',258,'R')
insert into ca_concepto_bancamia values ('SALDOSMIN','CANCELACION SALDOS MINIMOS',259,'R')
insert into ca_concepto_bancamia values ('SANCHEDEV','SANCION CHEQUE DEVUELTO',260,'R')
insert into ca_concepto_bancamia values ('COMISI','COMISION ESTUDIO DE CR‘DITO',261,'R')
insert into ca_concepto_bancamia values ('REVCOM','REVERSO COMISION ESTUDIO DE CREDITO',262,'R')
insert into ca_concepto_bancamia values ('PAGFUELINE','PAGO FUERA DE LINEA',263,'R')
insert into ca_concepto_bancamia values ('REVPAGFUEL','REVERSO PAGO FUERA DE LINEA',264,'R')
insert into ca_concepto_bancamia values ('CARREF','CARTAS DE REFERENCIA PARA CLIENTES',265,'R')
insert into ca_concepto_bancamia values ('REVCAR','REVERSION CARTAS DE REFERENCIA PARA CLIENTES',266,'R')
insert into ca_concepto_bancamia values ('PAGRETPROC','PAGO RETIRO PROCREDITO',268,'R')
insert into ca_concepto_bancamia values ('DIFRECAUDO','DIFERENCIA EN RECAUDO',270,'R')
insert into ca_concepto_bancamia values ('SOBRANCAJA','SOBRANTE EN CAJA',271,'R')
insert into ca_concepto_bancamia values ('CANSOBCAJA','CANCELACION SOBRANTE EN CAJA CARTERA',272,'R')
insert into ca_concepto_bancamia values ('DEVSOBCAJA','DEVOLUCION SOBRANTE EN CAJA EN EFECTIVO',273,'R')
insert into ca_concepto_bancamia values ('INTNOCAUS','INTERESES NO CAUSADOS',274,'R')
insert into ca_concepto_bancamia values ('DEVOMICRO','DEVOLUCION VALOR POR VENTA DE MICROSEGUROS',275,'R')
insert into ca_concepto_bancamia values ('DEVOEXEQ','DEVOLUCION VALOR POR VENTA DE EXEQUIAL',276,'R')
insert into ca_concepto_bancamia values ('TRASCAJERO','TRASLADO ENTRE CAJEROS INGRESO',277,'R')
insert into ca_concepto_bancamia values ('TRASCAJEGR','TRASLADO ENTRE CAJEROS EGRESO',278,'R')
insert into ca_concepto_bancamia values ('APLPAGFLIN','APLICACI‡N PAGO FUERA DE LINEA',279,'R')
insert into ca_concepto_bancamia values ('RECEDATEL','RECAUDO EDATEL',280,'R')
insert into ca_concepto_bancamia values ('DEVREDATEL','DEVOLUCION RECAUDO EDATEL',281,'R')
insert into ca_concepto_bancamia values ('RECBALOTO','RECAUDO BALOTO',282,'R')
insert into ca_concepto_bancamia values ('CONCHCO476','CONSIGNACION CLIENTE OTROS BANCOS',283,'R')
insert into ca_concepto_bancamia values ('CONCHBO903','CONSIGNACION CLIENTE OTROS BANCOS',284,'R')
insert into ca_concepto_bancamia values ('CONCHBO566','CONSIGNACION CLIENTE OTROS BANCOS',285,'R')
insert into ca_concepto_bancamia values ('CONCHOC171','CONSIGNACION CLIENTE OTROS BANCOS',286,'R')
insert into ca_concepto_bancamia values ('CONCHCS214','CONSIGNACION CLIENTE OTROS BANCOS',287,'R')
insert into ca_concepto_bancamia values ('CONCHCO203','CONSIGNACION CLIENTE OTROS BANCOS',288,'R')
insert into ca_concepto_bancamia values ('CONCHAG617','CONSIGNACION CLIENTE OTROS BANCOS',289,'R')
insert into ca_concepto_bancamia values ('CONCHBV067','CONSIGNACION CLIENTE OTROS BANCOS',290,'R')
insert into ca_concepto_bancamia values ('CXCSIN','CUENTAS POR COBRAR SINIESTROS',291,'R')
insert into ca_concepto_bancamia values ('APLPAGSVGD','APLICACION PAGOS POR RECLAMACI‡N SEGURO DEUDORES',293,'R')
insert into ca_concepto_bancamia values ('COMISI_IVA','IVA COMISION ESTUDIO DE CR‘DITO',294,'R')
insert into ca_concepto_bancamia values ('REVCOM_IVA','IVA REVERSO COMISION ESTUDIO DE CREDITO',295,'R')
insert into ca_concepto_bancamia values ('CARREF_IVA','IVA CARTAS DE REFERENCIA PARA CLIENTES',296,'R')
insert into ca_concepto_bancamia values ('REVCAR_IVA','IVA REVERSION CARTAS DE REFERENCIA PARA CLIENTES',297,'R')
go

delete ca_concepto_bancamia
 where co_codigo in (298,299,300,301,302,303,304)
go

insert into ca_concepto_bancamia values ('DESMBVTU','DESEMBOLSO VTU',298,'R')
insert into ca_concepto_bancamia values ('REVERSO','REVERSO DE OPERACIONES',299,'R')
insert into ca_concepto_bancamia values ('APLDOCTO','APLICACI„N POR DOCUMENTO DE PAGOS REVERSADOS',300,'R')
insert into ca_concepto_bancamia values ('COPANTERIO','CANCELACI„N OPERACI‡N ANTERIOR',301,'R')
insert into ca_concepto_bancamia values ('DECHBOG895','DESEMBOLSO EN CHEQUE B BOGOTA 895000412',302,'R')
insert into ca_concepto_bancamia values ('CHANBOG895','CHEQUE ANULADO B BOGOTA 895000412',303,'R')
insert into ca_concepto_bancamia values ('DECORONA','DESEMBOLSOS CORONA',304,'R')
go

delete ca_concepto_bancamia
 where co_codigo in (305,306)
go

insert into ca_concepto_bancamia values ('PAGOIMP','PAGO IMPUESTO OFICINA',305,'R')
insert into ca_concepto_bancamia values ('IMTIMBRE','IMPUESTO DE TIMBRE RECAUDADO POR LA OFICINA',306,'R')
go

--Actualiza codigos valores
update ca_concepto_bancamia set
co_codigo = co_codigo + 190
go
